### ISSUE TITLE
Remove "Layout Test" menu entry

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1012]
I think that the upgrade to NUI is mostly complete now. Thus, the "Layout Test" entry in the main menu should no longer be necessary (at least in the develop branch).

Commenting that single line out should fix it, but maybe the code behind can also be removed.

@synopia: what do you think?

**Comment by skaldarnar** [comment]
@immortius - the console is currently available in the main menu, so this can probably be addressed....

**Comment by synopia** [comment]
I like the idea of having a 'debug' menu, maybe only accessible when Terasology is launched with a debug command or something. I personally dont need the layout test anymore, but I now have a new menu item for the behavior tree editor, so I can play around with it without launching an actual game. Huge timesaver.

**Comment by msteiger** [comment]
I thought about moving the code to engine-tests or the `dev` source set, because tests shouldn't be part of the game distribution. 

It is not an unit test and therefore might need some extra care.

**Comment by Cervator** [comment]
Bump - we should probably do this already :-)
