### ISSUE TITLE
Grass can grow on ... water?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1030]
Noticed this by chance - it probably speaks for itself!

![terasology-140322164427-1152x700](https://f.cloud.github.com/assets/1063833/2492376/d655d7ac-b226-11e3-80a9-b07fc74bc344.png)

I imagine that's a simple check that can be added somewhere to prevent .. :-)

Edit: As per correction on IRC the issue is having water pockets generate *below* grass, which may be going away soon anyway! We've needed a new approach for a long time

**Comment by Sk0ut** [comment]
Hi, Cervator, I'm one of the students from Porto and I've taken interest in solving this bug.
If I understand  the problem in here, when the world is generated, it may happen that water pockets are generated below grass because there's no check above the selected position for the water pockets.
Is this right?

**Comment by Cervator** [comment]
Hi @Sk0ut - I'm not actually sure if this issue is valid anymore. I *think* this was the "old" Perlin generator. We then overhauled world generation to use facets, which you can read about in https://github.com/Terasology/TutorialWorldGeneration/

I don't think we actually generate pockets of water like that in the new Perlin. I'll close this as out of date.

If you're interested in world generation the tutorial I linked above for the new system is great and makes working on world gen quite approachable. Try going through it step by step and see how you like it :-)

We have #1193 for restoring some of the old Perlin features, with a linked forum thread: http://forum.terasology.org/threads/core-perlin-world-improvements.1093 - there are also some great world gen features in https://github.com/Terasology/PolyWorld/ and https://github.com/Terasology/Cities/

If you would like you could add something simple back to the Perlin generator. Like for instance small puddles of water, or even lakes. Both PolyWorld and Cities have nice lakes. The forum thread has more ideas :-)

In any case just let us know if you have questions or would like guidance on finding something else!
