### ISSUE TITLE
Default font has no asterisk char

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1046]
Not a super-important issue, but rather a nice-to-have.

According to git blame, the author of the font is @begla. The font face name translates to "selfmade" which makes it difficult to find a character glyph that looks nice with the rest of the font.

**Comment by msteiger** [comment]
Good finds, @skaldarnar ! The PressStart2p even supports Baltic languages.

Maybe @Cervator can ask @begla for the code that generates the `.fnt` description files? I have a rough idea how it could work, but it would take quite some time to get it right.

Current [font description for default_0]
(https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/fonts/default.fnt)

**Comment by Cervator** [comment]
I poked him via email, but haven't heard back for a little while (poked about dev meeting too). Hopefully he'll spot it and remember :-)

If not there must be some existing tools floating around on the web to help generate this stuff.

And yup, good find on the press-start-2p (few months overdue). Gets us a good chunk of languages. I wonder, if we later add something like Japanese and have trouble finding a single font supporting them all, we could just swap font in-game to a different one supporting eastern languages?

**Comment by immortius** [comment]
http://www.angelcode.com/products/bmfont/ is the site that invented the format.

**Comment by Cervator** [comment]
Thanks!

**Comment by msteiger** [comment]
That's good to know! I tried out the PressStart2P font and this is how it looks:

![image](https://cloud.githubusercontent.com/assets/1820007/5707843/53da5b5a-9a8c-11e4-911a-7b1d53fb62f0.png)

**Comment by Cervator** [comment]
I like it! Ship it!

Do we need anything else? Wonder if there would be any resistance to the change, I'd like to think not.

Also, that screenie reminds me the initial console text needs an update, now that we don't need quotes.

**Comment by msteiger** [comment]
This is Arvo - it also has Cyrillic chars:

![arvo](http://i.imgur.com/8W1At86.png)

**Comment by MarcinSc** [comment]
That is a nice font.

**Comment by msteiger** [comment]
This is my favorite so far: bitter-bold
![image](https://cloud.githubusercontent.com/assets/1820007/5710319/6fa081c4-9aa1-11e4-9ec6-79070953f0b4.png)
It could be a little more crisp - but that can surely be tweaked.

**Comment by msteiger** [comment]
This is Zantroke:

![image](https://cloud.githubusercontent.com/assets/1820007/5710424/33e2f9ae-9aa2-11e4-9d9e-d6e9cdd0588c.png)

**Comment by Cervator** [comment]
So I guess there are lots of options after all :-)

The Noto font by Google that @Calinou mentioned seems to support most the world's languages even: https://www.google.com/get/noto

Maybe we should spin up a forum thread with the options instead sometime? Maybe do some comparing and voting. Although in theory I am guessing we could support multiple?

**Comment by emanuele3d** [comment]
Is there a sans-serif option? I feel that serif fonts are great for print
but sans-serif are better for the screen.

Also, T could perhaps support only one font for the Core module, to keep it
simple, but module developers should have the option to override the font
in favor of something that suits their module better, i.e. medieval vs
sci-fi setting.

Finally... i guess we might not want to open the "accessibility" can of
worms just yet?

**Comment by skaldarnar** [comment]
PressStart2P is bit too wide for my taste, Arvo and bitter-bold look great. I think the forum thread with voting is a good option, as well as having **one** font in the core, but supporting others. In general, I'd like to see a menu option to select a specific font, and (library) modules can be used to add various fonts...

**Comment by msteiger** [comment]
Good points. I suggest adding a Sans and a Sans-Serif font and use the Sans one as default (as suggested by @emanuele3d). I'd go with Arvo or Bitter (with serifs) and Noto (without serifs - thanks @Calinou) as it supports many languages and it also looks great:

![image](https://cloud.githubusercontent.com/assets/1820007/5723792/261ea66a-9b47-11e4-9a4e-d6da08d0f2a0.png)

I suggest adding the original font and .bmfc config files to [TeraMisc](https://github.com/MovingBlocks/TeraMath) so we can recreate/tweak it later if needed.

**Comment by Cervator** [comment]
Went ahead and merged with Noto, since the sheer amount of languages it supports makes it a good default font. When #1522 moves forward we can then consider extra fonts :-)

@msteiger - thanks! And agreed on adding to https://github.com/MovingBlocks/TeraMisc - feel free whenever :-)

**Comment by MarcinSc** [comment]
I don't think there is a need for more fonts in Engine/Core. Fonts can be easily added (AFAIK) in mods and used by them, since it can be loaded as an asset.
