### ISSUE TITLE
Display labels for debug graphics modes

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1059]
Currently (with some work) you can manage to switch into various special graphics modes via hot keys (F3 + 'r' for instance is wireframe mode)

It would be nice if we could display a debug label somewhere to describe what a special mode is and how to exit it (or toggle other variants) - beyond the F3 debug text (probably in a different corner)

I don't think we've touched some of the special modes for some time either, might be good to check that they actually still work as intended.

The README has more information on how to get in and out of these modes
##

**Comment by flo** [comment]
r is no longer the hotkey for switching to wireframe mode. Instead it is F9. Although I get only a black screen when I try it.

**Comment by codesavory** [comment]
Is it something like this we are looking for ?
![terasology_debug_mode](https://cloud.githubusercontent.com/assets/5894273/14678854/090bb184-0735-11e6-95ab-3f838de8ac50.png)

**Comment by Cervator** [comment]
Hey @codesavory - yep! That is close, although I had imagined it giving details on each debug mode when it is active. So if you F3 then F9 to get that wireframe mode sure you get a broken black screen as the debug rendering isn't actually working but at least put some debug text on the screen saying what it is :-)

A summary like in the above screenshot would also be very handy, I just don't know where we'd keep it. Bottom right instead? So you could have the regular debug text in the top left and a quick summary in any debug mode of the relevant keys and modes in the bottom right?

**Comment by skaldarnar** [comment]
Shoutout to @tdgunes just in case he happens to resolve this issue alongside the rendering pipeline overhaul :wink:

**Comment by majordwarf** [comment]
I guess the issue should now be considered closed or any changer are needed?

**Comment by Cervator** [comment]
Yep we can consider this sufficiently worked - I'm sure we can think of more improvements if we try hard enough but that can be for another day :-)

Thanks again!
