### ISSUE TITLE
Tile damage effect persists beyond an "Ace" multiblock being broken

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1064]
Not entirely sure if this is a general issue or specific to the way the L&S aces are defined (W&S multiblock objects might work differently)

Found during testing for a stable build, with the standard L&S lineup active

![terasology-140413205956-1152x700](https://cloud.githubusercontent.com/assets/1063833/2691029/93127d8c-c370-11e3-9038-970c90409740.png)
##

**Comment by Cervator** [comment]
Update: Still an issue but got a little quirkier. Maybe impacted by #2177 or something a little earlier, new issues didn't seem present in Omega 371 (Feb 6th)

New quirks:

- [ ] Overlay is not using the L&S specific (went back to cracked rock)
- [ ] When the block is fully damaged it doesn't actually break (nor does the overlay go away)
- [ ] The particle effects are fine for the L&S card but for a door it now looks like .. diamond ore?

Exhibit A:

![terasology-160222230656-1152x720](https://cloud.githubusercontent.com/assets/1063833/13241800/8aff6b78-d9bc-11e5-8d37-3f002275f848.jpg)

Exhibit B:

![terasology-160222233122-1152x720](https://cloud.githubusercontent.com/assets/1063833/13241804/97baab5c-d9bc-11e5-9d3b-85ea75a019df.jpg)

**Comment by skaldarnar** [comment]
I noticed some weird particle effects when breaking blocks in TtA, looked like hitting the companion cube.

**Comment by Cervator** [comment]
Closing this as complete / obsolete. Issues have since been resolved although the original block breaking effect still needs to be reactivated (submitted separate issue in a module repo for that)
