### ISSUE TITLE
Add button to show CrashReporter from main menu

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1120]
To ease the reporting of non-crash issues it would be an idea to put a button in the main menu that'll open the Crash Reporter (which perhaps should be called "Issue Reporter", really) under normal working conditions. 

While the bottom of the log file wouldn't necessarily be useful in that case (unless we make it detect the most recent error logging entries or stacktrace?) it would provide super easy access to the game log file, uploading it, filing an issue, etc

Closing #670 and #713 in favor of this
##

**Comment by Cervator** [comment]
Hey @mtjvankuik sending this one your way since you expressed interest on IRC. Sorry for being AFK without being marked as such :-) Feel free to ask questions here, there (or elsewhere) anyway so long as it is somewhere logged we can catch later.

**Comment by mtjvankuik** [comment]
Hey @Cervator, I have reported an issue that may be worthwhile to review in relation to this issue. [https://github.com/MovingBlocks/CrashReporter/issues/29](url)

**Comment by rzats** [comment]
Closing in favour of https://github.com/MovingBlocks/Terasology/issues/2577.
