### ISSUE TITLE
minimum requirements page

### ISSUE THREAD

**Issue by asl97** [MovingBlocks/Terasology#1123]
need minimum requirements page, i am sure not a lot of people like waiting for a few mins loading only to be told that their GPU is not supporting versions of 'open.lg' or find out that it run so laggy that it is impossible to play at all
https://github.com/MovingBlocks/Terasology/issues/1100
##

**Comment by skaldarnar** [comment]
I'll propose to put something like the following into our README and the download page on the website. Exact entries to be discussed, but I'd go for pessimistic estimations here (under-promise, over-deliver).

Open questions:

- do we have some estimation/gut feeling what CPU is the minimum (reasonable) requirement, and whether more cores or higher clock frequency have a (huge) impact on the performance?
- do we profit from GPUs, and what is the main bottleneck there? flops, video memory, OpenGL version?
- what are required and recommended OpenGL versions?

# System Requirements

<table>
    <tr>
        <td></td>
        <th>Minimum Requirements</th>
        <th>Recommended Requirements</th>
    </tr>
    <tr>
        <td>System (OS)</td>
        <td colspan="2" align="center">Windows, MacOS, Linux (64 bit)</td>
    </tr>
    <tr>
        <td>Processor (CPU)</td>
        <td>???</td>
        <td>???</td>
    </tr>
    <tr>
        <td>Memory (RAM)</td>
        <td>2 GB</td>
        <td>8 GB</td>
    </tr>
    <tr>
        <td>Graphics (GPU)</td>
        <td style="vertical-align:top">
            Intel HD Graphics (Gen 5)<br/>
            GeForce 6xxx series or<br/>
            Radeon HD 2000 series <br/>
            with OpenGL 2.1*
        </td>
        <td  style="vertical-align:top">
            ??? <br/>
            with OpenGL 3.x
        </td>
    </tr>
    <tr>
        <td>Storage (HDD)</td>
        <td colspan="2" align="center">1 GB</td>
    </tr>
</table>

Internet connectivity is required for downloading Terasology via the Launcher, afterwards offline play is possible.

**Comment by keturn** [comment]
I don't have any concrete numbers to offer, but here are some notes from when I was trying to figure out bottlenecks:

Last time I checked, chunk handling (loading, generation, saving) will use a lot of cores. More cores definitely helps in that case.

But if you're working on a build in one place and not running around generating or loading chunks? I'm less clear what the bottleneck will be on framerate there.

Another thing I noticed a while back is that _resolution matters._ More than I expected, given the simple textures and geometry.

**Comment by DarkWeird** [comment]
> Another thing I noticed a while back is that _resolution matters._ More than I expected, given the simple textures and geometry.

Yeah.
It is something with shaders and rendering pipeline. Some rendering stages should process in lower resolution, then now.

(You can receive more fps, if using lower windows size, or lower scale in rendering config)

**Comment by skaldarnar** [comment]
Closed by https://github.com/MovingBlocks/Terasology/pull/4332
