### ISSUE TITLE
ComponentSystemManager initialization, registration and re-registration

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#1125]
As per conversation in PR https://github.com/MovingBlocks/Terasology/pull/1094:

The _ComponentSystemManager_ (CSM) is registered and becomes first available on engine initialization (currently in _TerasologyEngine.initManagers())_. However, it is re-instantiated and re-registered in _StateMainMenu.init(GameEngine)_, every time the application enters this game state. This is perhaps done to ensure a fresh new instance of the CSM that doesn't mantain references to previous game instances.  If this is the case the code should make this strategy explicit.  Furthermore, it needs to be evaluated if it is indeed necessary for the CSM to be instantiated and registered on engine initialization or if it should be done _only_ in the context of game states and their lifecycles.
##

**Comment by Cervator** [comment]
With #1739 merged is this addressed fully?

Pinging @emanuele3d, @flo

**Comment by emanuele3d** [comment]
Whoa. Were Dinosaurs still roaming the earth at the time this issue was opened?

I missed the whole discussion in #1739 . Will check it out tonight I hope.

**Comment by jdrueckert** [comment]
Looks like it was done with #1739
