### ISSUE TITLE
Double water transparency = no water!

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#114]
I ran across a spot where there were two big independent waterfalls and noticed that if I place myself with the closer waterfall overlapping the one in the background the overlapped region displays _no_ water whatsoever.

Example: http://nanoware.org/pix/tera/DoubleWaterNoWater.png

Probably relates to the water transparency calculations getting in a fist-fight when they happen twice over the same spot :-)
##

**Comment by 4Denthusiast** [comment]
The picture in the initial post is no longer accessible, so I can't check the exact situation, but this seems to not be happening now so it might as well get closed. @Cervator?

**Comment by 4Denthusiast** [comment]
The image @Qwertygiy posted shows one layer of water in each location, not none as Cervator described. If that's the issue, it's a duplicate of #3305 .

**Comment by Cervator** [comment]
Oh boy this is an old issue! Saw it by chance having been updated while looking for something else.

I think @Qwertygiy's example is subtle but may be showing staggered water blocks in two different places - hard to see and yeah it is a different issue.

I dug up the old image from my ancient webhost, which I guess must have broken the way its URLs work. Here it is again (look at that old school look!):

![DoubleWaterNoWater](https://user-images.githubusercontent.com/1063833/71550846-98ea7180-29a7-11ea-8948-05f8e5976c3c.png)

In that case the near waterfall is in the foreground and where it covers water in the _background_ it *looks* like neither is being rendered at all, meaning you can see right down to the dirt under the second batch of water. Contrast with the side on the left where the near waterfall ends yet suddenly water in the background renders.

On the other hand off to the right it looks like the water _does_ render, just really poorly, and maybe the foreground water does render even where it looks more like you're just looking at dirt in the background. Might be reaching into the territory #656 covers

As a more clear example of the latest here are two sets of screenies showing it better. Now you see it:

![Terasology-191228191757-1152x720](https://user-images.githubusercontent.com/1063833/71550853-e666de80-29a7-11ea-9852-a115c8ef344a.png)

Now you don't!

![Terasology-191228191803-1152x720](https://user-images.githubusercontent.com/1063833/71550857-f088dd00-29a7-11ea-98df-0a1f4a2c3714.png)

But yeah, that looks like a duplicate of #3305 - so I'll go ahead and close this ancient issue in favor of that one and #656 :-)

(Fun fact: this was the 6th oldest open issue at the time it closed)
