### ISSUE TITLE
Allow player customization of eye (camera) height, maybe collision height

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1145]
Another fairly simple configuration change for more player flexibility!

Currently the player's eye height and character (collision) height is set to 1.4 and 1.6 (in block units) which some player's find a tad low. It would be nice to offer a narrow range on the player configuration screen

This needs a bit of experimentation to see what good values are and if they should just be for eye height (within the collision/character height so it doesn't feel like your eyes are scraping against the ceiling) or for both.

Alternatively if it doesn't break the world maybe wider values would be fun to support. We'll get shrink/growth potions eventually!

**Comment by havanagrawal** [comment]
Hi, I'd like to contribute to this project, and this seems like a nice place to start :grin: . Is this issue still active?

**Comment by Cervator** [comment]
Hi @havanagrawal and yes! It absolutely is :-)

It has been a little while since this issue was submitted. We have a settings menu for the player now and I just submitted #2476 which goes into way deeper detail on a bigger topic (player selection of avatar) but some of those details might be useful to consider for this topic. Or they could be overwhelming. Try out just making sure you can make and validate changes first of all! :D

@xrtariq2594 has been working on the Potions module which could eventually result in grow/shrink potions that would also affect the eye/camera height. I think when this issue was originally submitted it was for a bit more of a debug tool to get a better feel for how the height would make the world appear, but really in some less focused gameplay settings (like a creative mode) personal preference on such things would be very valid.

You might want to check out how the current player options (name, color..) are taken from the menu settings and applied to in-game configuration. That might help figure out how to create the new setting.

Are you up and running from source yet? You could post over in the forum as well to say hello: http://forum.terasology.org/forum/contributor-introductions.7/ 

Welcome! :-)

**Comment by havanagrawal** [comment]
Hi @Cervator , I'm up and running from source :grin: I've just started exploring the source though.. Perhaps you could suggest an issue which might not be too overwhelming for me.. Otherwise, I could try working on this one.. I'm pretty comfortable in Java, but haven't worked on any Game dev of any kind before, so it might take me some time..

**Comment by Cervator** [comment]
@havanagrawal great!

This one shouldn't be *too* bad since you should be able to go look at how the existing player settings apply their config to actual in-game objects (giving the player a name and a color). Should be doable to use the same approach to apply an updated camera height.

Other easy ones that stick out: #2383, #2382, #2321

Other than the [wiki](https://github.com/MovingBlocks/Terasology/wiki) here we have a few [tutorial modules](https://github.com/Terasology?utf8=%E2%9C%93&query=Tutorial) usually with an associated wiki. Finally you can ask on here, in the forum, or on IRC if you have questions :-)

**Comment by Cervator** [comment]
This was completed by @nihal111! With some follow-ups tracked in #2535 :-)
