### ISSUE TITLE
Liquid only flows on broken block, not physics or copy paste

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#116]
I thought I had made an item on this, but maybe I was imagining things / sleep-deprived!

Currently liquid starts flowing if a block underneath it is broken via standard tool. However, if the physics explodey tool is used, or terrain copy pasted that includes water not supported by a block, then the liquid doesn't start flowing.

It probably wouldn't be terribly difficult to improve the handling of either of those scenarios to where liquid does start propagating normally :-)

**Comment by skaldarnar** [comment]
@Cervator I think this issue can be closed. 

With https://github.com/Terasology/SimpleLiquids water propagates again (somewhat funny, but well...). This works just fine for explode/railgun tool. I don't know about blueprints, but haven't seen them in while...

**Comment by Cervator** [comment]
Thanks, closing :)
