### ISSUE TITLE
Further enhancements to bring new faceted perlin up to speed with legacy perlin

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1193]
With #1181 merged we've got all facet-based world generators now, yay! @begla's original and now legacy perlin generator still has a few more features than the replacement, which we need to port into facet-land sometime, somehow :-)

Ideally we can get most the way there by the next stable build as that generator is responsible for some of the truly grand vistas you can find in the game. Would also be a good case study in how to re-implement the features in the new facet structure

Legacy Perlin is available in commit https://github.com/MovingBlocks/Terasology/commit/206a93d1121222a8189d5d055ca0747babd5931f and prior
##

**Comment by Cervator** [comment]
For a quick bit of reference: We might be able to reactivate legacy Perlin if we take out its tree generation. That's not really a fix, but it might be nice to have the old worlds easily accessible when we start applying some of their features to the new generation.

**Comment by msteiger** [comment]
What's still missing in the new implementation? Can we make a list and tick it off one by one?

**Comment by Cervator** [comment]
A list got started over at: http://forum.terasology.org/threads/core-perlin-world-improvements.1093 :-)

I think the most fundamental, impressive, and likely tricky one is the sheer cliffs with overhangs etc.
