### ISSUE TITLE
Line up "back" button in different places

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1198]
Suggestion from IRC - for instance the back button with graphic settings up is in a slightly different position than in the main menu. Easy usability win!

**Comment by codesavory** [comment]
Does this Issue still hold true ? I think the "back" buttons are already correctly placed with ease of use. Is there anything in particular we are looking for here ?

**Comment by msteiger** [comment]
Thanks for checking, @codesavory. I think that this was done a quite while ago. Closing for now.
