### ISSUE TITLE
Client crashes after rejoining a multiplayer game and using the character transfer slot

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#1282]
Steps to reproduce:
- Run headless server
- Join with a client
- Use the transfer slot by picking up an item in a chest with the mouse and drop it someplace
- Log out
- Join same game
- Pick up another item in the chest with the mouse

Client log (yes,  the next todo thing is get rid of all the block access noise): https://gist.github.com/Josharias/c292cfa7f8798ebe618c

**Comment by Cervator** [comment]
Closing as fixed some time ago. Re-validated locally with just Core, we've been playing with a server recently but technically JS doesn't give up access to chests readily so it wasn't quite the case listed :-) Still, things were flying around between assembly stations just fine.
