### ISSUE TITLE
Modify LocalChunkProvider to unschedule generation/loading of no longer needed chunks

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#1309]
At the moment LocalChunkProvider keeps adding chunks to generate/load to TaskMaster. However, if a chunk is no longer needed and is still waiting in the queue, it could be unscheduled, therefore releasing some resources.
##

**Comment by sladyn98** [comment]
Hey, I would like to contribute to this issue and would like to propose the following solution
In the function `makeChunksAvailable()`  we could add a further check to see if the `region.checkIfChunkIsRelevant(chunkInfo)` and if not remove it from the queue thereby removing irrelevant chunks
Am I heading in the right direction ?

**Comment by DarkWeird** [comment]
@sladyn98 Yea, Its looks like right.
Can you check the relevance of this issue?
I think :
run game with debugger
enable "hspeed"
Move far away
Stop game by debugger and check queue is valid

**Comment by sladyn98** [comment]
@DarkWeird thanks for the comment, how do I enable "hspeed" ?

**Comment by DarkWeird** [comment]
@sladyn98  
Open ingame console(~) and type "hspeed"

If you receive some error like "you haven't permission " then install module "CheatsForAll"

Maybe you will need play with  view distance ( more task to world generation)

**Comment by sladyn98** [comment]
@DarkWeird The queue seems to be valid and its continually not increasing though its constant at around 1058 chunks in the queue at any given time.

**Comment by DarkWeird** [comment]
@sladyn98 
What about sortedReadyChunk and readyChunk fields? non relevant chunks removed from it?
Looks like it fixed already. 
See chunkForUnload and unloadChunkInternal methods.

**Comment by sladyn98** [comment]
@DarkWeird yeah the irrelevant chunks are being removed. Looks like this issue can be closed

**Comment by Qwertygiy** [comment]
Good to hear!
