### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by Calinou** [MovingBlocks/Terasology#1343]
There should be language translations somewhen.

**Comment by Cervator** [comment]
Just a note so we have it for later - #1758 tweaked at encoding a bit. We might want to consider the impact / related topics when we get more serious with translations for the engine, which may include doing .json files supporting full UTF-8 rather than ASCII-only .properties files

**Comment by Cervator** [comment]
Closing as complete / superseded by #2433 for the remainder (prefab translation in addition to UI translation)
