### ISSUE TITLE
Intro doc / tutorial on Unit Testing & JavaDoc

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#135]
Thanks to assorted commits on unit testing and Javadoc @rapodaca has outed himself as knowledgeable on the topics!

Commits: https://github.com/MovingBlocks/Terasology/commit/deeb34d79052d4bc6b5e32554226efad0a06f87c

Forum: http://board.movingblocks.net/viewtopic.php?f=4&t=161

So I'm going to ask pretty please with sugar & cherry on top if you could write up a couple quick intro sections in the ContributorGuide on the how and why on unit testing, and some quick hints on how to use JavaDoc well. 

http://wiki.movingblocks.net/Main/UnitTesting
http://wiki.movingblocks.net/Main/JavaDoc

Doesn't have to be very involved, could just be mostly links to other good resources and some brief suggestions / examples on how to use either for Terasology. I don't think we have much direction on either topic so far, so it can be all yours... :-)

Doesn't even have to be in the wiki, alternatively just PM me (here, forum, post there, whichever!) with some initial stuff and I'll put it in the wiki

More actual code to make unit testing easier would of course also be great! But I don't know enough about what we need to really specify anything. I do know that we'll likely need to tinker with overall architecture / entity system before we can really go nuts.

This would fill out a good chunk of what #70 asks for (code formatting is another, I think I can dig up some existing material there from the core wiki sometime) and would be hugely appreciated!

**Comment by rzats** [comment]
AFAICT this has been covered by

- https://github.com/MovingBlocks/Terasology/wiki/Unit-Testing
- https://github.com/MovingBlocks/Terasology/wiki/JavaDoc

for a while now. Do these articles need more improvement or should I close as complete?
