### ISSUE TITLE
Allow world generators to define spawnable locations/areas

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1379]
Currently, the player spawns very close to the world's origin (center of chunk 0/0 I believe). I'd like to have this more customizable. Two examples:

* In PolyWorld, players should start at the island shore rather than 10 miles out in the sea.
* In Cities, player should spawn in a town/settlement to get started quickly.

I guess this could be done with `SpawnableAreaFacet` and/or `SpawnableLocationFacet` and engine picks the closest match with respect to the last-known player location. For worlds without that facets, the default (current) spawning procedure is performed.

Any other suggenstions/ideas/thoughts?

**Comment by msteiger** [comment]
I think that the world generator needs some (facet-based) meta information to find good spawning points. This information is generated per (chunk) region and unfortunately not available after the chunk is rasterized.

I envision spawning point providers that write to a facet that is collected at the end of the chunk generation process. The world gen. would store them in a `Map<Chunk, Collection<Vector3i>>`. Then, this map could be queried by a method

    Vector3i getClosestSpawningPoint(int worldX, int worldZ);

which would iterate in a spiral around the target region until a valid spawning point is found. In a last step, the worldProvider must be checked for air blocks at the spawning location. 

In the simplest case, `getClosestSP()` would just return the queried location (at the correct height).

Maybe one spawning point per chunk is enough? Then, `Optional` could be used instead of Collection.

What do you guys think?

**Comment by Cervator** [comment]
Sounds fine to me but then I'm not picky :-)

I've been wondering how to update the Spawning module to find suitable spawning sites for creatures with various demands, but I suppose that's entirely different (has the luxury of running on a timer after chunks have loaded)

Or alternatively should we consider a pre-spawning game state (think scoreboard in typical FPSes, or even optionally in an artificial lobby if the gameplay warrants that) so chunk gen can run for a while and make it easier to detect good spawning sites for either players or creatures?

Although it seems like there are two topics here

1. Finding good world scope "home" location for certain actions, like spawning the player. PolyWorld could go "Generate partial world map, then find suitable land mass, start game there, generate chunks, place player
1. Determine suitable block locations within generated chunks fitting a particular context. Could be the Spawning module, even for players.

Would that split approach help lay the groundwork for supporting gameplay with custom start settings? Like Polyworld, a large world possibly needing a start spot far from the default world center, or L&S where the player needs to spawn in a suitable village, maybe even with clickable options on what creature to spawn as

With a modifiable world map/scope concept you could also apply special spawn considerations later in the game, such as building a new village with a central portal the player can choose to spawn at.

**Comment by Cervator** [comment]
Just merged in #1706 and I believe that completes this issue. Yay!

The support is there now, and with fancy default interface implementation all worlds get it automatically, and work fine.

Still need to actually vary the spawn requirements if so desired per world. But that's a different effort up to world authors.
