### ISSUE TITLE
Move code configuration files to a shared repository

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1414]
We have quite a few repositories that have their own config folder that contains general code configuration. I suggest moving these files into a new repository that contains files such as:

* IDE configuration
* Code Analytics (CheckStyle, PMD, FindBugs) configs
* Common gradle code such as version definition
* Git configs such as .gitattributes and .gitignore

One way to get the content from this repo into existing ones would be using it as a **submodule**.

Most relevant projects seem to be engine / Launcher / WorldViewer.

**Comment by Cervator** [comment]
Closing this as completed a little while back. Even started using it in Destination Sol as well!
