### ISSUE TITLE
Game crashes every 10-15 minutes

### ISSUE THREAD

**Issue by salzix** [MovingBlocks/Terasology#1418]
Crashes in singleplayer every 10-15 minutes. Changing gfx settings to min doesn't help. Moment before crash game seems to go choppy and sometimes some textures are missing.
I don't know if it's correlated but memory usage of java process is increasing continously to more than 900MB.

Specs:
GAME: version 44
SYSTEM: Windows 7 64bit
GFX: ATI Mobility Radeon HD 4650
MEM: 6GB RAM
SOUND: ATI HDA

stacktrace: http://pastebin.com/pcCT1zFp

**Comment by Cervator** [comment]
Closing this from age / changes made since. We probably can catch some of these issues with a profiler sometime when we do an optimization effort of some sort :-)
