### ISSUE TITLE
Log exactly which modules are enabled on world creation

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1419]
Should be super easy! Somebody go go go please :-)

Probably a good thing to do before then moving some of the rather verbose module logging to debug

Bonus: Also summarize how many blocks were registered per module (optional, can do later)

**Comment by emanuele3d** [comment]
Answering here from your prompt in #1565: 

I basically know nothing about module loading. I know when the world gets created, in GameState StateLoading, but how do I get the list of loaded modules? Once I have that it should be easy to print out the module names and versions.

**Comment by Cervator** [comment]
I have no idea :D You're already closer than me!

Not a rush item though :-)

**Comment by emanuele3d** [comment]
Unless somebody offers a tip I'll let this one simmer then. I don't want to get into modules just yet. Eventually I will though. I'd love for the existing skysphere to be the default from core, while new skyspheres or new skysphere features should be hooked from modules.
