### ISSUE TITLE
"Sticky" thrown objects (especially torches)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1443]
On entering one of the large churches in a City world I realized how handy it would be to be able to throw some sticky torches up high on the walls to get some proper lighting. Not that we'd want the normal torches to work that way, but it seems to be a useful option to support. I know it can work as the arrows in the combat branch worked that way - one type you'd shoot into a wall and they'd stick there.

Nice little separate item that can be done any time, probably without too much difficulty for somebody familiar with game physics a bit.
##

**Comment by portokaliu** [comment]
On to porting the behavior to a module... right after some Rust ^^

**Comment by Cervator** [comment]
We have sticky arrows in CombatSystem now - does that count as this being complete, or do you still have sticky torches hiding somewhere @portokaliu ? :D

**Comment by jdrueckert** [comment]
It's not entirely clear here, whether the requested feature is a way to persistently place objects like torches by throwing them against a surface or a way to temporarily place them by having them stick in the target object using physics before they despawn later-on (like the "sticky" arrows in CombatSystem).
In the org meeting it was agreed-upon, that this neither is a "Good First Issue" for new contributors, nor has enough detail to keep around until gameplay content feature requests can actually be prioritized again.
