### ISSUE TITLE
Multiplayer server crash on client right click action with Java8 + Win8

### ISSUE THREAD

**Issue by fxbisto** [MovingBlocks/Terasology#1445]
As above - When hosting a multiplayer game on any of my Windows 8.1 x64 machines (headless or not) a right click from any client game causes the host to crash. So far only a right click that produces a sound seems to cause the behaviour - using the scissors, placing a block, torch, or using the destructive tools. When left clicking from a client game there is no problem with the server crashing.
I have used 3 different builds as the server (matching build each time for the client games) and receive the same error each time.
I am currently using build 1246, downloaded directly from Jenkins @ http://jenkins.terasology.org/job/Terasology/1246/artifact/build/distributions/Terasology.zip as build 1269 was not connecting on multiplayer (kept freezing firstly on 'downloading core,' then on 'getting missing modules')
The behaviour is not reproduced when a Windows 7 machine is used as the host (on any of the builds that fail on Windows 8.1)
Also both host machines that crash successfully run the game on Linux when using OpenJDK on Linux Mint, so I believe it to  be either Windows 8.1 or it's associated Java version?

The crashing Windows 8.1 machines are using Java v.8 u 25
The successful Windows 7 machine however is using v.7 u.23

here's the crash dump:
http://pastebin.com/6biqirGk

Hope we can get this working on Win8.1! :)

**Comment by Cervator** [comment]
I'm going to tentatively close this as probably resolved - we're officially requiring Java 8 now and recent fixed a few issues that could relate to this one.

@fxbisto - if you're still around feel free to retest with Java8 + Win8 sometime :-)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
