### ISSUE TITLE
display hang on left click (solved - display driver issue)

### ISSUE THREAD

**Issue by Michael-S** [MovingBlocks/Terasology#1448]
I'm guessing I have my configuration wrong, but just in case I thought I would report it.  Ubuntu 14.04 64-bit, 12GB of RAM, six core AMD CPU, AMD HD 5770 video card with radeon driver (I'm pretty sure that's the open source one, I don't remember installing the AMD proprietary one).  Latest code (git pull as of this morning 2014-12-20).  If I start the game with "./gradlew run" and start a new singleplayer game with the default map settings, it starts normally and I can look around and move.  But when I right click to mine, the game hangs and my screen flickers, and it takes 5-10 seconds before my display returns to normal and the game responds to more input.  Full output:

I work with Java at my day job, so hopefully I can follow any suggestions for tracking down the problem.  On the other hand, all I've done is file and web software, so graphics-related stuff that doesn't involve Javascript in a browser window is alien to me.

installPath was null, running from IDE or headless server? Setting to: /home/somebody/workspace/Terasology
Found the natives dir: /home/somebody/workspace/Terasology/natives
09:43:16,862 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
09:43:16,910 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
09:43:16,910 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Naming appender as [FILE]
09:43:17,058 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [logs/Terasology.log]
09:43:17,065 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:43:17,066 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Naming appender as [CONSOLE]
09:43:17,077 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Setting level of logger [ROOT] to DEBUG
09:43:17,088 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Attaching appender named [CONSOLE] to Logger[ROOT]
09:43:17,089 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Attaching appender named [FILE] to Logger[ROOT]
09:43:17,091 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Setting level of logger [org.terasology] to INFO
09:43:17,091 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@34c882c6 - Setting level of logger [org.reflections.Reflections] to WARN
09:43:17.132 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
09:43:17.137 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=, buildId=, buildTag=, buildUrl=, gitBranch=, gitCommit=, dateTime=, displayVersion=, engineVersion=]
09:43:17.137 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: 
09:43:17.138 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: /home/somebody/workspace/Terasology
09:43:17.139 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 1.7.0_65 in /usr/lib/jvm/java-7-openjdk-amd64/jre
09:43:17.139 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: OpenJDK 64-Bit Server VM, version: 24.65-b04
09:43:17.139 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Linux, arch: amd64, version: 3.13.0-43-generic
09:43:17.139 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 2670 MiB
09:43:17.139 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 6
09:43:17.142 [main] INFO  org.terasology.config.Config - Reading config file config.cfg
09:43:17.333 [main] INFO  o.terasology.engine.TerasologyEngine - Video Settings: {"pixelFormat":24,"windowPosX":384,"windowPosY":180,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"viewDistance":"near","flickeringLight":false,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":false,"renderPlacingBox":true,"blurIntensity":0,"reflectiveWater":false,"vignette":false,"motionBlur":false,"ssao":false,"filmGrain":false,"outline":false,"lightShafts":false,"eyeAdaptation":false,"bloom":false,"dynamicShadows":false,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":false,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"cameraSettings":{"cameraSetting":"normal"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
09:43:17.409 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Core-0.45.1
09:43:17.435 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:18.109 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:18.381 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:18.413 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: /home/somebody/workspace/Terasology/modules/Core/build/classes
09:43:18.539 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:19.555 [main] INFO  o.t.rendering.ShaderManagerLwjgl - Loading Terasology shader manager...
09:43:19.555 [main] INFO  o.t.rendering.ShaderManagerLwjgl - LWJGL: 2.9.1 / linux
09:43:19.555 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_VENDOR: X.Org
09:43:19.555 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_RENDERER: Gallium 0.4 on AMD JUNIPER
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_VERSION: 3.0 Mesa 10.1.3
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - SHADING_LANGUAGE VERSION: 1.30
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map
09:43:19.556 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters
09:43:19.557 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object
09:43:19.558 [main] INFO  o.t.rendering.ShaderManagerLwjgl - EXTENSIONS: GL_ARB_invalidate_subdata GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev
09:43:21.770 [main] INFO  o.t.audio.openAL.OpenALManager - Initializing OpenAL audio manager
09:43:23.058 [main] INFO  o.t.audio.openAL.OpenALManager - OpenAL 1.1 ALSOFT 1.15.1 initialized!
09:43:23.058 [main] INFO  o.t.audio.openAL.OpenALManager - Using OpenAL: OpenAL Soft by OpenAL Community
09:43:23.059 [main] INFO  o.t.audio.openAL.OpenALManager - Using device: OpenAL Soft
09:43:23.059 [main] INFO  o.t.audio.openAL.OpenALManager - Available AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
09:43:23.059 [main] INFO  o.t.audio.openAL.OpenALManager - Available ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
09:43:23.059 [main] INFO  o.t.audio.openAL.OpenALManager - Max mono sources: 255
09:43:23.059 [main] INFO  o.t.audio.openAL.OpenALManager - Max stereo sources: 1
09:43:23.060 [main] INFO  o.t.audio.openAL.OpenALManager - Mixer frequency: 44100
09:43:23.080 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:23.116 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: /home/somebody/workspace/Terasology/modules/Core/build/classes
09:43:23.117 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:23.169 [main] INFO  o.terasology.engine.TerasologyEngine - Initialization completed in 6.04sec.
09:43:24.277 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1419086604277), capping to 1000
09:43:55.886 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: /home/somebody/workspace/Terasology/modules/Core/build/classes
09:43:55.886 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:57.037 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: /home/somebody/workspace/Terasology/modules/Core/build/classes
09:43:57.037 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:43:57.188 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1338), capping to 1000
09:44:02.719 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: /home/somebody/workspace/Terasology/modules/Core/build/classes
09:44:02.719 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
09:44:03.875 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1157), capping to 1000
09:44:05.070 [main] INFO  o.t.w.block.loader.BlockSoundsLoader - Loading Block Sounds...
09:44:05.080 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds engine:default
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:gravel
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:wood
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:snow
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:stone
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:sand
09:44:05.081 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Sounds Core:soil
09:44:05.108 [main] INFO  o.t.world.block.loader.BlockLoader - Loading Blocks...
09:44:05.194 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
09:44:05.195 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 0
09:44:05.203 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome MOUNTAINS with short id 0.
09:44:05.204 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome SNOW with short id 1.
09:44:05.204 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome DESERT with short id 2.
09:44:05.204 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome FOREST with short id 3.
09:44:05.204 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome PLAINS with short id 4.
09:44:05.207 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome org.terasology.world.biomes.UnknownBiome@4320644d with short id 0.
09:44:05.208 [main] INFO  o.t.world.biomes.BiomeManager - Registered new biome Core:mountains with id 1 that wasn't present in the save game.
09:44:05.209 [main] INFO  o.t.world.biomes.BiomeManager - Registered new biome Core:desert with id 2 that wasn't present in the save game.
09:44:05.209 [main] INFO  o.t.world.biomes.BiomeManager - Registered new biome Core:plains with id 3 that wasn't present in the save game.
09:44:05.209 [main] INFO  o.t.world.biomes.BiomeManager - Registered new biome Core:snow with id 4 that wasn't present in the save game.
09:44:05.209 [main] INFO  o.t.world.biomes.BiomeManager - Registered new biome Core:forest with id 5 that wasn't present in the save game.
09:44:06.582 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1384), capping to 1000
09:44:07.044 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Breather'
09:44:07.231 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Miniaturizer'
09:44:07.239 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:DoorTop]
09:44:07.239 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.LEFT with id 1
09:44:07.239 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.RIGHT with id 2
09:44:07.239 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.FRONT with id 3
09:44:07.239 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.BACK with id 4
09:44:07.244 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:DoorBottom]
09:44:07.244 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.LEFT with id 5
09:44:07.244 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.RIGHT with id 6
09:44:07.244 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.FRONT with id 7
09:44:07.244 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.BACK with id 8
09:44:07.268 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'UnbreathableBlock'
09:44:07.465 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "NkRAzzYT0nEEeA0rH6fKfTtjIJkNtwlY"
09:44:07.956 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:stone]
09:44:07.956 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:stone with id 9
09:44:07.956 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Water]
09:44:07.956 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Water with id 10
09:44:07.958 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Ice]
09:44:07.958 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Ice with id 11
09:44:07.959 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Sand]
09:44:07.960 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Sand with id 12
09:44:07.960 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Grass]
09:44:07.960 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Grass with id 13
09:44:07.961 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Snow]
09:44:07.961 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Snow with id 14
09:44:07.963 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Dirt]
09:44:07.963 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Dirt with id 15
09:44:07.964 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:TallGrass1]
09:44:07.964 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:TallGrass1 with id 16
09:44:07.969 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:GreenLeaf]
09:44:07.969 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:GreenLeaf with id 17
09:44:07.969 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:OakTrunk]
09:44:07.970 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:OakTrunk with id 18
09:44:07.971 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:DarkLeaf]
09:44:07.971 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:DarkLeaf with id 19
09:44:07.972 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:PineTrunk]
09:44:07.972 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:PineTrunk with id 20
09:44:07.972 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:BirkTrunk]
09:44:07.973 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:BirkTrunk with id 21
09:44:07.974 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:RedLeaf]
09:44:07.975 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:RedLeaf with id 22
09:44:07.976 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Cactus]
09:44:07.977 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Cactus with id 23
09:44:08.128 [main] WARN  o.t.w.internal.WorldProviderCoreImpl - Attempted to access unavailable chunk via block at 0, 41, 0
09:44:08.129 [main] WARN  o.t.w.internal.WorldProviderCoreImpl - Attempted to access unavailable chunk via block at 0, 42, 0
09:44:09.552 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Chest]
09:44:09.553 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Chest.LEFT with id 24
09:44:09.553 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Chest.RIGHT with id 25
09:44:09.553 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Chest.FRONT with id 26
09:44:09.554 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Chest.BACK with id 27
09:44:09.557 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:companion]
09:44:09.567 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:companion with id 28
09:44:09.598 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:brick:engine:stair]
09:44:09.599 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:brick:engine:stair.LEFT with id 29
09:44:09.600 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:brick:engine:stair.RIGHT with id 30
09:44:09.601 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:brick:engine:stair.FRONT with id 31
09:44:09.601 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:brick:engine:stair.BACK with id 32
09:44:09.603 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Tnt]
09:44:09.607 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Tnt with id 33
09:44:09.611 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Brick]
09:44:09.612 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Brick with id 34
09:44:09.615 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Plank]
09:44:09.616 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Plank with id 35
09:44:09.619 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Lava]
09:44:09.635 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Lava with id 36
09:44:09.638 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Iris]
09:44:09.639 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Iris with id 37
09:44:09.640 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Dandelion]
09:44:09.641 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Dandelion with id 38
09:44:09.643 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Tulip]
09:44:09.644 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Tulip with id 39
09:44:09.645 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:YellowFlower]
09:44:09.646 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:YellowFlower with id 40
09:44:09.649 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Torch]
09:44:09.651 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Torch.TOP with id 41
09:44:09.651 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Torch.LEFT with id 42
09:44:09.651 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Torch.RIGHT with id 43
09:44:09.652 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Torch.FRONT with id 44
09:44:09.652 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Torch.BACK with id 45
09:45:01.651 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (21829), capping to 1000
09:45:23.718 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (21999), capping to 1000
09:45:23.720 [main] INFO  o.t.p.i.StorageManagerInternal - Saving - Creating game snapshot
09:45:23.848 [main] INFO  o.t.p.i.StorageManagerInternal - Saving - Snapshot created: Writing phase starts
09:45:24.435 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
09:45:35.298 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (11580), capping to 1000
09:45:40.851 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
09:45:40.862 [main] INFO  o.t.p.i.StorageManagerInternal - Saving - Creating game snapshot
09:45:40.907 [main] INFO  o.t.p.i.StorageManagerInternal - Saving - Snapshot created: Writing phase starts
09:45:40.908 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Player
09:45:40.919 [main] INFO  o.t.l.console.internal.ConsoleImpl - [NOTIFICATION] Player "Player" has left the game
09:45:40.920 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
09:45:41.391 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
09:45:41.392 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration

**Comment by Michael-S** [comment]
As a very late follow up, I'm now running Ubuntu 15.10 alpha and using the 4.1 Linux kernel with the radeon (open source) driver, and this issue appears to be fixed.  I could still reproduce it with the Ubuntu 15.04 default 3.19 kernel and radeon driver yesterday.

**Comment by Cervator** [comment]
Better late than never! Thanks for the update :-)
