### ISSUE TITLE
Requires anotation cant have more than 1 class in faceted world generation

### ISSUE THREAD

**Issue by esapetri** [MovingBlocks/Terasology#1457]
having more classes than 2 in required annotation in facet system causes odd eternal loop and kills game whit out errors. I have no idea how to fix this because I am bad whit annotation codding. Log also gets flooded whit same message so reading it is impossible.

**Comment by esapetri** [comment]
I found out it was odd bug in one required class. I managed to get my system working but I still don't know what causes given problem. It seems  @requires annotation is working right, but there is bug some where else. I think This might be more logging problem. I'll add more info when I have found out what thins error was about exactly. Any cause it is mystical.

**Comment by Cervator** [comment]
Going to go ahead and close this for now then, any other bug would be distinct and deserving of its own issue :-)
