### ISSUE TITLE
Fix dependency version entries in Artifactory pom files

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1463]
Most of the `pom.xml` files that are currently stored in Artifactory are invalid due to wrong version dependency specifiers. An example from [WeatherManager-0.1.0-SNAPSHOT](http://artifactory.terasology.org/artifactory/simple/terasology-snapshot-local/org/terasology/modules/WeatherManager/0.1.0-SNAPSHOT/WeatherManager-0.1.0-20141217.201303-1.pom):

```
<dependency>
  <groupId>org.terasology.modules</groupId>
  <artifactId>MarkovChains</artifactId>
  <version>+</version>                         <----
  <scope>runtime</scope>
</dependency>
```

I first blamed the `build.gradle` [template file from the Core module](https://github.com/MovingBlocks/Terasology/blob/develop/modules/Core/build.gradle#L166), but when I run `gradle install` the pom.xml file in my local .m2 repository is correct:

```
<dependency>
  <groupId>org.terasology.modules</groupId>
  <artifactId>MarkovChains</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <scope>compile</scope>
</dependency>
```

Surprisingly, also the `scope` attribute is different. 

I assume that the metadata is created differently on Jenkins. Ideas, anyone?
##

**Comment by skaldarnar** [comment]
I just checked, and this still seems to be the case, for instance with [Health-2.0.0-20230630.210229-33.pom](http://artifactory.terasology.org/artifactory/simple/terasology-snapshot-local/org/terasology/modules/Health/2.0.0-SNAPSHOT/Health-2.0.0-20230630.210229-33.pom) for the [Health](http://artifactory.terasology.org/artifactory/simple/terasology-snapshot-local/org/terasology/modules/Health) module.

Given that we've been living with this for nearly a decade now I'll close it as "won't fix".
