### ISSUE TITLE
Java crash issue on creating one game then another with different template

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1467]
Ran across this during some general testing. Seems I can replicate it pretty easily

* Start Terasology with lots of modules available
* Create game based on TtA with its world
* Exit to main menu
* Create game based on Cities and its world
* Java crashes, producing a dump file

More combinations than that cause the crash, but so far consistently I have to change to a different set of modules and/or world to trigger the crash (haven't gone through all possible combinations to narrow it down further). I can run with the same template repeatedly without crashing. So I'm thinking it is some disposal / asset overlap issue between sessions.

It may be video card specific as this doesn't appear to be super recent (tried two weeks old code, same crash) yet the replication steps are pretty common - and I changed my video card just recently. I bet if I go back to my old primary it goes away. Might try to test that soon. New video card is a Radeon R7 260.

Some snippets from the dump file:

```
# JRE version: Java(TM) SE Runtime Environment (7.0_55-b13) (build 1.7.0_55-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.55-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0x9453d3]
...
Stack: [0x00000000023c0000,0x00000000024c0000],  sp=0x00000000024be050,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [atio6axx.dll+0x9453d3]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J  org.lwjgl.opengl.GL11.nglDrawElementsBO(IIIJJ)V
J  org.terasology.rendering.primitives.ChunkMesh.renderVbo(I)V
J  org.terasology.rendering.world.WorldRendererLwjgl.renderChunk(Lorg/terasology/world/chunks/RenderableChunk;Lorg/terasology/rendering/primitives/ChunkMesh$RenderPhase;Lorg/terasology/rendering/cameras/Camera;Lorg/terasology/rendering/world/WorldRendererLwjgl$ChunkRenderMode;)V
J  org.terasology.rendering.world.WorldRendererLwjgl.renderWorld(Lorg/terasology/rendering/cameras/Camera;)V
J  org.terasology.rendering.world.WorldRendererLwjgl.render(Lorg/terasology/rendering/opengl/DefaultRenderingProcess$StereoRenderState;)V
j  org.terasology.engine.modes.StateIngame.render()V+48
j  org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(Lorg/terasology/engine/modes/GameState;F)V+28
J  org.terasology.engine.TerasologyEngine.mainLoop()V
j  org.terasology.engine.TerasologyEngine.run(Lorg/terasology/engine/modes/GameState;)V+29
j  org.terasology.engine.Terasology.main([Ljava/lang/String;)V+80
v  ~StubRoutines::call_stub
```

I can add more details later but am curious if anybody else can replicate it first? Can use the omega zip to trigger it, don't need to run from source, they crash equally.

http://jenkins.terasology.org/job/DistroOmega/

**Comment by Cervator** [comment]
Tinkered around with video cards some. After making my old one solo I could still produce the crash (odd). But after putting in both new ones, and spending a couple hours crashing and rebooting till I stabilized, I no longer get the crash.

I'm going to call it obscure enough due to GPU config that we'll likely never see it again, maybe we'll shake something lose and fix it by chance anyway. Closing.

**Comment by msteiger** [comment]
I'm having the same problem on my (single) ATI card. I guess it's related to the driver, but we're somehow triggering it ...

**Comment by Cervator** [comment]
Doh! Finally after I give up on it somebody else reproduces, haha.

While performing software surgery during my final upgrade I did a full ATI driver reset using one of their tools. Took a couple attempts before I stabilized and then I couldn't reproduce anymore.

Should we hunt this down some more then? Trouble is now you're the only confirmed one with the issue :-)

**Comment by msteiger** [comment]
I was just looking for this issue and Github's search engine listed #1268 first. Surprisingly, it seems to point to the same problem. I'm leaving this closed as it is mostly a duplicate.
