### ISSUE TITLE
Likely off-by-one issue on flora seeding in Perlin (or more?)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1478]
Noticed a pretty clear bug where a single block layer right at the border between two vertical chunks is entirely clear of vegetation, with everything above and below entirely overgrown (itself a bit of a quirk for new world gen config defaults I think)

Low priority and likely easy fix. Might be good to clean up a little and make the generation a bit more tidy (like no normal grass on snow blocks or sand)

Screenie: 

![terasology _ pre alpha_2015-01-01_01-07-27](https://cloud.githubusercontent.com/assets/1063833/5591746/d745c90e-9152-11e4-9400-4e6cf8f3392c.png)

**Comment by msteiger** [comment]
The same issue also exists for trees. I'm working on that as part of a larger refactoring for tree generation.
