### ISSUE TITLE
Crash on starting a TtA world - NPE

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1483]
Since the last stable we seem to have broken TtA once more. I verified the master branch is fine. It might be all the refactoring for commands, maybe something permission related, I saw some more detailed errors at once point but now get a very vague one:

```
23:07:47.556 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.BACK with id 16
23:07:47.565 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Miniaturizer'
23:07:47.623 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'UnbreathableBlock'
23:07:49.482 [main] ERROR o.t.e.event.internal.EventSystemImpl - Invalid event handler method: componentActivated
23:07:49.489 [main] ERROR o.t.e.event.internal.EventSystemImpl - Invalid event handler method: componentActivated
23:07:50.440 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.world.sun.OnMidnightEvent
23:07:51.297 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (3613), capping to 1000
23:07:52.585 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "3h3XSDUGZxwVEM9V6UNjkk9DH3l1RGCh"
23:07:53.301 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:144) ~[classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:235) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:440) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:371) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:137) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
23:07:53.301 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

However it is possible the earlier error was just some sort of dirty workspace issue.

The `org.terasology.world.sun.OnMidnightEvent` permission error is *not* new - TtA has worked with that in place before, although it certainly seems like something we need to fix.

The `componentActivated` errors on the other hand I haven't noticed before. That method appears to only be in use in two classes from the ClimateConditions module, which is part of TtA, so maybe that's the culprit. Not sure why they are getting flagged as invalid event handlers.

**Comment by Cervator** [comment]
Linking to #1375 since it is similar functionality, might be worth looking at together with this (no direct relation that I know of though)

**Comment by Cervator** [comment]
The `org.terasology.world.sun.OnMidnightEvent` was fixed by #1485 but that indeed didn't fix this crash for me :-(

**Comment by Cervator** [comment]
The mystery thickens. 

TTA works as-is for @Limeth on Win7 from source with just the main TTA module present in source form.

It fails for me set up like that, in my mega-integration workspace with everything in source, in the latest Omega zip, and even on my tablet with the very latest Omega zip, or on my wife's PC.

Maybe it is machine specific. Tagging as support in that case.

**Comment by msteiger** [comment]
I get a different NPE - `PluggableWorldGenerator` initializes the world differently from the other world gens. The world gen is not yet initialized in InitialiseWorld which tries to get the sea level height from it. Will look into that (on Wednesday probably)
