### ISSUE TITLE
Remove test classes from module jar files

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1498]
For some reason, test classes are packaged into module jar files. I figure that this should not be the case.

**Comment by Cervator** [comment]
This is probably in part coming from how test classes in the engine can be extended from modules. I don't recall if any of those classes were in the Core module at some point.

Doesn't look like they are right now, so yeah, we could probably toss those. Unless there is a use case for making modules with test template classes at some point, maybe? Although perhaps in that case we can add some tweak to only include those if needed.

**Comment by msteiger** [comment]
It seems as if this issue was caused by outdated `build.gradle` files in the module folders. I copied the latest version from Core and that fixed it.
