### ISSUE TITLE
Fix broken unit test: Mathy stuff

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1502]
Just one, at least!

http://jenkins.terasology.org/job/Terasology/1303/testReport/org.terasology.logic.location/LocationComponentTest/worldRotationCombinedWithParent/

Came from the Great TeraMath Migration :-)

**Comment by Cervator** [comment]
This ... fixed itself? Weird

http://jenkins.terasology.org/job/Terasology/1304/testReport/org.terasology.logic.location/LocationComponentTest/worldRotationCombinedWithParent/

Saw something similar earlier when a certificate test failed once, then worked next execution.

Oh well.

**Comment by msteiger** [comment]
I changed the constructor of Quat4f in TeraMath so it would have the same (low) resolution as VecMath. I triggered a rebuild twice, but both failed with "Internal Server Error". It worked the third time :open_mouth:

**Comment by Cervator** [comment]
Ahh. Third time was me, after fixing Artifactory (out of space) :D
