### ISSUE TITLE
Font improvement: Russian language support in chat?

### ISSUE THREAD

**Issue by getsmp** [MovingBlocks/Terasology#1508]
Searched through the repository, everything seems to be in UTF-8. However, I cannot chat in Russian. Thanks for your reply.

**Comment by msteiger** [comment]
Hi, the infrastructure should work fine with Russian charsets. However, [the font we use](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/fonts/default_0.png) supports only English, German and French characters. 

It would be great to have a free font that supports more than that.

**Comment by getsmp** [comment]
How can I modify that file to make it support Russian (How does infrastructure know which character to take from that file?) ? Thanks.

**Comment by Cervator** [comment]
Yeah we definitely need a new font - existing also lacks other stuff like `*` - #1046 :-)

We probably should find a new free font that covers more languages rather than try to edit the existing font. I am not sure what that involves though.

**Comment by getsmp** [comment]
Okay, thank you. I'll keep it opened just not to make the task forgotten :)

**Comment by Cervator** [comment]
Yep, I tweaked the name real quick, this is something we need to do :-)

**Comment by immortius** [comment]
In brief: we use the bmfont ascii + bitmap, as described here: http://www.angelcode.com/products/bmfont/
That site also has an app for generating bitmap fonts from normal fonts.

So a font is composed of one or more images which contain the characters, and a text file that describes the position of each character, how to render it, and the character code it maps to.

**Comment by Cervator** [comment]
@getsmp - this should be supported now! Try it out :-)

**Comment by getsmp** [comment]
Great job! I really love to communicate with you, guys. You are very friendly :)

**Comment by Cervator** [comment]
Happy to have happy users! So did it work? :-)

You'll need to use the latest develop build from the launcher or our Jenkins server. Or the develop branch if running from source

**Comment by getsmp** [comment]
Yes, it did! I've tested cyrillic and special chars, worked perfectly.

**Comment by Cervator** [comment]
Awesome! :)
