### ISSUE TITLE
Terasology crashes

### ISSUE THREAD

**Issue by getsmp** [MovingBlocks/Terasology#1509]
Hello! I have Terasology (stable) crashing when creating new world. Here's the log: http://pastebin.com/8bSa4cdU
The game even crashes when no modules are enabled (but they're still in modules folder). Thank you for your help!

Sincerely yours, getsmp.

**Comment by Cervator** [comment]
Huh, the log just seems to end, without an error. Startup logging looks fine, your system looks fine.

Does the game window just disappear while creating a new world? Or does the CrashReporter pop up?

Could you try with the latest dev build? It has no extra modules, in case that matters: http://jenkins.terasology.org/job/Terasology/lastSuccessfulBuild/artifact/build/distributions/Terasology.zip

**Comment by getsmp** [comment]
The game just closes on "Caching world" or like that. Without modules on ".. prefabs". I'm installing dev build now, thanks.

**Comment by getsmp** [comment]
With latest 1311 build it still crashes on "Caching textures". Log: http://pastebin.com/xNBc2f1p
Maybe I am to turn debug mode somehow?

**Comment by getsmp** [comment]
Oh, I found a duplicate Core module... The error in one of modules than, sorry. I'll work on that.

**Comment by getsmp** [comment]
Yes, I've found that the Fence module is troublemaker. I'll close this and make the corresponding issue.
