### ISSUE TITLE
Add beach and water biomes to CoreBiome

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1512]
Currently, there is no biome definition for neither water bodies nor beaches. The legacy world generator performed simple checks for sand blocks and sealevel height to prevent trees from growing there.

In the current setup this doesn't exist anymore. Thus, a beach could actually be in the forest biome and be overgrown with trees.

I am currently refactoring the tree generation process to enhance flexibility, but also to bring back the functionality of the legacy generator. If there was a biome for sand beach, it could have growing probabilities assigned like the others.

Same goes for water bodies. This would even allow for underwater plants.

I therefore suggest to add the following two biome types:

* `BEACH` or maybe shore/beach front/coast
* `WATER-BODY` or water/underwater/sea

Maybe a native-speaker can pick the best expression?

**Comment by Cervator** [comment]
Beach makes sense to me as long as it involves sand. You can have coast without sand.

Water - how about we use biome to differentiate the different types of water? We have so much biome space now. In Perlin only sea water and rivers exist, so we could probably apply an ocean biome pretty easily, and overwrite with river where the process to make rivers ends up depositing water.

Or we could just stick with ocean for now and let rivers stick with the surrounding biome. I'm not sure what's better. A lake generator could flag that water as lake instead and you could treat the different types differently. But I'm not sure what the impact of making smaller water related biomes within land biome areas.

Whether this should be in the Core biomes I dunno. I'm not sure what our design goal is there - keep it minimal and let modules build on top? Eventually make an expanded biome module? Or define as many biomes we can but let modules reuse/tweak them?

Curiously, how would this allow underwater plants, if not displacing the water block to place the plant block? :-)

**Comment by MarcinSc** [comment]
If I may suggest an improvement in Biome interface, I'd suggest adding "Biome getParent()" or similar to the interface, as I did in AnotherWorld. This is to allow extensibility in biomes and inter-mod compatibility.

For example, if a mod adds wild animals that spawn in the world, and it only knows about core biomes, so for example - in "Forest" spawn rabbits, foxes and bears. Some other mod adds a new biome - "WarmForest" - normally no animals would spawn in it, until someone actually added a new spawn definitions for this specific biome.

However, if you added that method and there was no definition for what to spawn, the first mod can check the "getParent()" method and figure out if it has the definition for that "parent" (what is the super-type of this new biome - closest known relative) biome, and travel up the chain if needed, up to a biome that is defined in Core (we could define that this method can return "null" only for core Biomes, or a completely new biome) to find what it should spawn there. So, without any extra configuration that "WarmForest" would return Forest from getParent() method, and therefore it will be spawning rabbits, foxes and bears.

**Comment by Cervator** [comment]
Sounds good to me :-)

Would it be over-complication if we make it more component system-y by assigning some traits to biomes so spawning can choose to base on traits rather than biome? Possibly direct parentage could run into the sort of scenarios making us go with components rather than inheritance

Typical example would be maybe a rabbit needs "forest" + "good" or "neutral" which would spawn it in the normal Core forest biome (forest/neutral) and lollipop woods (forest/good) but not haunted woods (forest/evil)

Probably more of a forum topic than for discussion in a merged PR :-) We have several world related threads to go over and organize
