### ISSUE TITLE
"Search" command

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1525]
We are getting quite a few commands, blocks, items, etc. I think a "search" command would be a great utility if you're curious about all commands that relate to "health" (in the command name or description), blocks or items that relate to "wood" (in name or description), even cross-category for something like "hunger" (all related commands and all items that have hunger in name/description/attribute)

Maybe something for @Limeth if curious, or anybody else looking for something interesting to do :-)

**Comment by immortius** [comment]
I think this is overdoing it. Commands are for debugging primarily, people can search the source for that information. I don't think we need a search engine for them.

**Comment by Cervator** [comment]
Certainly not high priority, but IMHO it would be a whole lot easier to run a search in-game for commands/blocks when you're trying to test than first fashioning a search in an IDE for a more common term without too many junk hits :-)

Could have some potential for users and admins too, maybe hitch a ride on the BlockPicker's searchability. listBlocks can get too big. Maybe pass a an optional filter to it as a second parameter as an alternative?

I get the impression this would be relatively easy to do - if it is more of a hassle then surely I'll concede the point :-)

**Comment by Cervator** [comment]
Completed by #1878
