### ISSUE TITLE
Remove more javax.vecmath uses

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1539]
We still have some usages of old school vecmath in engine, and some uses might be getting mixed with TeraMath, although it seems tricky to reproduce at times. For instance:

http://forum.terasology.org/threads/game-crashes-when-creating-world-with-stable-47.1202/#post-11159

I cannot reproduce that with current develop + latest of all relevant modules though, nor can I find any actual usages for Tuple3i

Digging around in the code I noted some places like our "VecMath" class, which inlines `javax.vecmath.Vector3f` - I guess it is a converter of some sort?

It is used in AABB.java which is also using old school `javax.vecmath.Matrix4f`

Can we replace these entirely with new TeraMath yet, just in case there are execution paths that can leave you with Java vecmath when the game expects TeraMath?

**Comment by Cervator** [comment]
Never mind on the crashes, I *think* those were because some modules hadn't been rebuilt after the TeraMath merge. Rebuilt everything now and I suspect some of the weird crashes will go away.

I figure we still need to do this anyway :-)

**Comment by msteiger** [comment]
Wherever possible, the vecmath version of Vector3f should have been replaced with TeraMath by now. The remaining uses are linked to TeraBullet, which still actively uses vecmath. The VecMath class contains a few wrapper methods.

As stated in the forums, we could switch from JBullet to libgdx in the long run - this would also make vecmath obsolete.

Still, there are still two versions of Vector3i and a few related classes. I'm working on that atm.

**Comment by Cervator** [comment]
@msteiger - I'm thinking this is now complete?
