### ISSUE TITLE
Instant crash after starting Terastology

### ISSUE THREAD

**Issue by Brigas1** [MovingBlocks/Terasology#1540]
Hello. I just installed Terastology and have my java updated, but when I start it via launcher, it instantly crashes and gives me this log 

http://pastebin.com/7cpDsipn

Can anyone please help me?

Thanks in advance.

**Comment by skaldarnar** [comment]
I'm not sure if #1310 is related. At least you have non-ascii character in your patch `C:\Users\Barragão\Saved Games\Terasology` - the `ã`. 

Can you try running the game from another location (e.g., `D:\Games\Terasology`) with the `-homedir` option (this will use the installation folder for save games, etc.)?

**Comment by immortius** [comment]
Ack, I'd forgotten about that. Let me write a note to myself to look into
the non-ascii character bug this weekend.

**Comment by Cervator** [comment]
@Brigas1 - try the latest develop build now, this should be fixed!

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
