### ISSUE TITLE
Console tab-suggestions can crash with IOOBE

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#1541]
The suggestions triggered when hitting tab in the console can crash the game when used on parameters instead of the command itself. It will fail with an `IndexOutOfBoundException` on [this line](https://github.com/MovingBlocks/Terasology/blob/7c526227ce0a39d876f83ed450ee1cc71d53ad92/engine/src/main/java/org/terasology/logic/console/commandSystem/AbstractCommand.java#L269).

I think the problem is that [`processedParametersWithoutSender`](https://github.com/MovingBlocks/Terasology/blob/7c526227ce0a39d876f83ed450ee1cc71d53ad92/engine/src/main/java/org/terasology/logic/console/commandSystem/AbstractCommand.java#L252) actually contains the sender as first entry, whereas the `commandParameters` do not contain the sender.

A quick fix is to decrease `i` by one when accessing `commandParameters`, although this does assume that the sender is always the first entry... 

Another option is to have [`processParametersMethod()`](https://github.com/MovingBlocks/Terasology/blob/7c526227ce0a39d876f83ed450ee1cc71d53ad92/engine/src/main/java/org/terasology/logic/console/commandSystem/AbstractCommand.java#L191-L218) actually filter out the sender.

@immortius @Limeth any comment on this?

**Comment by immortius** [comment]
My comment: there should be no assumptions made on the existence, position or even number of sender parameters now. I guess this should be walking through the available params, skipping the sender ones?
