### ISSUE TITLE
Remove duplicate class CoreCommands

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1552]
There are two classes `CoreCommands`, which are mostly identical. 

internal/CoreCommands has more methods:
* kill
* teleport
* debugTarget
* setWorldTime

commands/CoreCommands has
* help

It looks like the one in "commands" is the newer one. Were all of the methods removed on purpose? setWorldTime and teleport could be quite useful ..

**Comment by Cervator** [comment]
Closing as fixed by #1599

**Comment by msteiger** [comment]
The commands have been moved to `PlayerSystem` and `ClientCommands`. I think that they could and probably should be removed from `CoreCommands`.
