### ISSUE TITLE
plz help i have this error when i put the game on my computer.What i need to do??

### ISSUE THREAD

**Issue by terasologyfan** [MovingBlocks/Terasology#1563]
java.lang.RuntimeException: Can not initialize graphics device.
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:182)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:100)
	at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:255)
	at org.terasology.engine.TerasologyEngine.<init>(TerasologyEngine.java:160)
	at org.terasology.engine.Terasology.main(Terasology.java:100)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:177)
	... 4 more

**Comment by Cervator** [comment]
Hi there - unfortunately it sounds like your video card is not fully working or new enough to support Terasology :-(

What computer do you have and do you know if you have the latest graphics drivers for your system?

**Comment by emanuele3d** [comment]
Cervator, can we be sure that what we write here will reach back to the user who reported the issue?

Good to know there is this other failure mode. In this case it's much harder to get information about the hardware/software configuration, but maybe there is a way.

**Comment by Cervator** [comment]
@terasologyfan should be getting email notifications from GitHub for updates to this issue. Whether he or she gets and notices the email I can't say, and we don't have any other options so I hope so :-)

I was wondering exactly what build this is from (the game log file would be great) as it is hard to know if your newer logging is actually in place. Unless you can tell from that snippet anyway.

**Comment by emanuele3d** [comment]
No, unfortunately this failure is earlier than the new logging: by my understanding in this case the opengl context failed to be created. Even in the latest build the glGetString() commands wouldn't have been able to execute.

By the way. At least TerasologyEngine has a logEnvironment() method that provides some limited information that could be useful in these circumstances. But it'd be good to have something like [oshi](http://oshi.codeplex.com/) or similar, to obtain as much hardware/software specific information as possible.

**Comment by emanuele3d** [comment]
Also, how come we don't get the full log?

**Comment by Cervator** [comment]
Most likely because the CrashReporter caught it and by default only displays the final stacktrace, often users just copy paste that here rather than realize there's a "full log" tab available too :-)

I put in an issue to change the default some time ago: https://github.com/MovingBlocks/CrashReporter/issues/12 - it is probably fairly straight forward to change sometime

**Comment by emanuele3d** [comment]
Do they have to create a github account to create an issue? Does the account by default forward this conversations to them via email or is this something the user needs to configure? I'm asking because paulanne failed to respond in issue #1548 and I wonder if he saw our conversation at all.

**Comment by Cervator** [comment]
Yep, have to create an account to create an issue, so they would've had to put in an email. I'm not sure if you have to confirm said email though, so if somebody made an account with a gibberish email we'd be relying on them to remember visiting the issue again later.

Unfortunately some users find the game, run it, crash, report something, then never seem to return. Many more probably stall even earlier in the process.

**Comment by immortius** [comment]
I think we have to have faith that if a user goes to the trouble or reporting an issue then they will check and follow up on it. There's not much else we can do.

Although I would prefer people took this sort of issue to the forums in the first instance. Github issues are intended for bugs to be fixed, not tech support style issues (at least until it becomes apparent there is something deeper to be fixed).

**Comment by msteiger** [comment]
I agree with that. I'm going to add an option to CrashReporter that directs users to the support forum and make it the default. 

Maybe it should be more like a wizard though:
1. Upload crash log
2. Describe it in a forum post (register first)
3. Check back later

This would also help with the issue that people just c&p their stacktrace instead of the full log.

**Comment by terasologyfan** [comment]
I have a Samsung computer and my graphic cards are up to date if you can
fix this error i will be greatfull minecraft and teraology are my life plz
if you van fix this send me an email
 Em 28/01/2015 20:22, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by Cervator** [comment]
Hi again @terasologyfan - we need more than "Samsung" like a model name or number :-)

Also would help with the game log, probably at something like C:\Users\[username]\Saved Games\Terasology\log if you're on Windows

@immortius / @msteiger - agreed on forum etc. Would be good to highlight easier defaults, https://github.com/MovingBlocks/CrashReporter/issues/12 has been floating around a while for that :-)

**Comment by terasologyfan** [comment]
Hi again too im AM just a boy so i dont know what i need to do my computer
is from Portugal its from the samsung enterprize what do i need to do????
Em 29/01/2015 15:05, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by Cervator** [comment]
Look at the case of the computer, do you see a name or some numbers anywhere? Is it a laptop or a desktop PC? Is it old?

**Comment by terasologyfan** [comment]
Is it the model code.or just the model???
 Em 29/01/2015 15:13, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by Cervator** [comment]
As many names and numbers as you can find please :-)

Is it a laptop? How long have you had it?

**Comment by terasologyfan** [comment]
I had this laptop like one year ago the model is:NP-N145 and the modelo
code is:NP-N145-JP03PT
 Em 29/01/2015 16:21, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by terasologyfan** [comment]
I will put new graphic Cards on my laptop ok
Em 29/01/2015 16:21, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by Cervator** [comment]
Thanks for the model info, that helped - looks like this? http://www.tecnikk.co.uk/index.php/laptops/samsung/np-n145-jp03-black.html

But yeah, unfortunately that is likely too weak to play Terasology :-(

Can you play on another computer? You typically cannot change the video card in a laptop, especially not on netbooks. 

Sorry about that. It might be that we'll make Terasology compatible with weaker/older systems one day, but I can't say when, if ever.

**Comment by terasologyfan** [comment]
Thx for all im sorry for you because i cant play Terasology.
Em 29/01/2015 16:37, "Rasmus Praestholm" <notifications@github.com>
escreveu:

**Comment by Cervator** [comment]
One day in the future you'll be able to! Hopefully we'll see you back then. Good luck and have fun :-)

**Comment by emanuele3d** [comment]
I found the specs for his GPU:

http://www.notebookcheck.net/Intel-Graphics-Media-Accelerator-3150.23264.0.html

Interestingly, it supports OpenGL 1.5. So, now I'm wondering if the context
creation process attempts to generate a 2.0 context and why.

**Comment by Cervator** [comment]
![goodluckcountingonyou](https://cloud.githubusercontent.com/assets/1063833/5964849/74be9f70-a7c5-11e4-98c7-42c2b8d1e89d.jpg)

**Comment by emanuele3d** [comment]
LOL =D

**Comment by terasologyfan** [comment]
OK i will ser thx
 Em 29/01/2015 19:43, "manu3d" <notifications@github.com> escreveu:

**Comment by terasologyfan** [comment]
I will see if it works i mail you again.
Em 29/01/2015 19:43, "manu3d" <notifications@github.com> escreveu:
