### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by sergey200800** [MovingBlocks/Terasology#1566]
please tell me what to do:java.lang.NullPointerException

**Comment by msteiger** [comment]
More information would be helpful. Can you upload the log file (to Pastebin) and post the link here, please?

Maybe you can find [help in the forum](http://forum.terasology.org/forum/support.20/),too.

**Comment by Cervator** [comment]
Also helps to know what computer you're playing on. If it is really old it probably won't run Terasology :(

If you got the CrashReporter window then there is more information on there. Even if that's gone now if you're on Windows you should be able to find the log again at C:\Users\[username]\Saved Games\Terasology\logs

**Comment by Cervator** [comment]
Closing from lack of user feedback
