### ISSUE TITLE
"say" command shouldn't require "op" permission

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1577]
I think this might have been mentioned elsewhere already, but I didn't see it listed officially. Probably an easy fix.

Can host a game locally and have a separate client connect. Hoster will be able to chat, joiner will not, with errors listed in the console.

**Comment by MarcinSc** [comment]
I think the problem with it is, that you shouldn't be using commands to talk to people. There should be a chat box for that. I can imagine, that for the time being, this command as the only way to chat, should not require any permissions.

**Comment by Cervator** [comment]
Well, there *is* a chat box, you can pop it up with `t` - but behind the scenes it uses the "say" command :-)
