### ISSUE TITLE
he following OpenGL versions/extensions are required but are not supported by your GPU driver:

### ISSUE THREAD

**Issue by endergamer123** [MovingBlocks/Terasology#1580]
- OpenGL15
    - OpenGL20
    - GL_ARB_framebuffer_object
    - GL_ARB_texture_float
    - GL_ARB_half_float_pixel

**Comment by Cervator** [comment]
Hi @endergamer123. This is not suitable for a bug report. I am sorry but the error is telling you that your video card isn't good enough to run Terasology.

It is possible we can make it easier to run Terasology one day, but not likely any time soon. In the meantime maybe you'll end up with access to a newer computer sometime and can play on there. Good luck!
