### ISSUE TITLE
Refactor how the Breathing modules activates

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1587]
Currently we have hooks in engine/core for the Breathing module to function, when active - see #1582 which would've removed them. Rather than apply that in engine/core we should have Breathing register/activate it when it is enabled instead. Some way of using delta/override options?

In short it applies a Breather to the player and makes water unbreathable. We must be able to do that differently, although how to enhance breathing beyond water is outside the scope of this issue (such as letting fish breathe in water but not in air)
##

**Comment by skaldarnar** [comment]
I think this done ... https://github.com/Terasology/Breathing/tree/master/deltas
