### ISSUE TITLE
Use glCullFace(GL_FRONT) when rendering water surface from underwater.

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#1590]
This is probably a minor performance issue.

Currently the renderer checks if the head of the player is underwater and disables face culling entirely when rendering the water surface, using glDisable(GL_CULL_FACE). This has the desired effect of making the water surface visible even if the player is underwater and looking to the back face of the polygons making up the water surface. However, by my understanding it effectively renders the polygons twice as it renders each polygon's back AND front rather than just the face facing the camera.

Ideally this would be handled instead by using glCullFace(GL_FRONT). This culls the front face of the polygons (the face visible when above water) and renders only the back face. A quick test revealed that this works, but introduces a problem when transitioning from above to underwater and viceversa: the water surface briefly (0.5 secs?) but noticeably disappears, for unknown reasons.

As solving the problem is not my current focus I'm opening this issue as a memo for myself or anybody who'd like to look into it.

The class affected at the time of the writing is WorldRendererLwjgl, but I'm moving its opengl commands, including those mentioned, to DefaultRenderProcess, which itself will eventually undergo at least some round of refactoring.

**Comment by immortius** [comment]
Disabling culling doesn't cause double rendering. The way culling works when enabled in either direction is if a triangle is facing the wrong way, it is discarded.

If water is a flat sheet, then every triangle is facing the same way so it makes no difference whether culling is enabled or if we want them to always be rendered. It is likely to provide a slight improvement for waving water though.

**Comment by Cervator** [comment]
Linking some maybe related issues :-)

#114 (mostly that one), #405, #656, #717

(more so from being about underwater stuff in case somebody plays around in that area and want to fix multiple things)

**Comment by emanuele3d** [comment]
No, you are right Immortius, I misunderstood the way culling works. I was misguided by articles on the net mentioning halving the number of rendered triangles. But that is only in the case of convex meshes. A flat(ish) sheet such as the water surface in this case, indeed has very little benefit. And indeed NOT culling at all is the appropriate thing to do as waves might allow for a front-facing triangle to be seen through a back-facing triangle and viceversa. So, I'm closing this one. It's a non-issue.
