### ISSUE TITLE
Headless server leaving clients requesting the "engine" module in some cases?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1601]
Not quite sure what's going on here. Works fine for me and works fine with stable 48. Changes: http://jenkins.terasology.org/job/TerasologyStable/49/

When minnesotags on IRC starts up his 24/7 headless server with stable build 49 (Omega, not that it should matter as no modules or anything are enabled) the server launches fine and sits there, but any client that connects gets stuck on "Requesting missing modules"

On running through debug mode `org.terasology.network.internal.ClientConnectionHandler` gets to the "Requesting missing modules" log statement at which point `missingModules` contains one element: "engine" - @immortius is that expected? Seems odd.

The client stalls at this point and there is nothing of interest at the bottom of either server or client log. I took a thread dump and included a full client log at https://gist.github.com/Cervator/bdb5f43bf2843920a19f

On trying to replicate, even hosted on a droplet server with me connecting from my local PC it works fine with the same build + same launch command:

`java -Xms256m -Xmx1536m -jar /opt/terasology/TerasologyOmega/Terasology.jar -headless -homedir=server`

We both executed that from `/opt/terasology/TerasologyOmega`

I ran from a CentOS 6.5 64-bit server with the latest Java 8 SDK installed, nothing else done from the extremely basic state of the server. Asking minnesotags to add what info he has there :-)

We did a bandwidth monitor test to see if the game client is in fact somehow trying to download the whole engine somehow but after the initial connection spike bandwidth drops back down to background levels

**Comment by minnesotags** [comment]
Server is located at terasology.tuffkidtek.com if you would like to test for yourself. 64-bit Debian wheezy virtual machine set up as a minimal gaming appliance with latest Java 8 SDK.

**Comment by minnesotags** [comment]
A pastebin of the startup log: http://pastebin.com/XCNa6NjS

**Comment by Cervator** [comment]
Closing this in favor of  #1626 which is easy to replicate and might somewhat relate to this. But it is likely this was a quirky situation we've since made it past via server setup rather than code change.
