### ISSUE TITLE
Broken commands: kill + teleport

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1602]
Both hit an NPE currently when executed in single player

Teleport has broken been broken longer but may be trickier to fix considering the suddenly moving player might trigger systems watching for weird behavior

Kill used to work - maybe it got shook up by recent changes (maybe the EntityRef client parameter?). Not too recent though, also broken in stable 49

**Comment by msteiger** [comment]
Both commands exist *twice*: In CoreCommands and in PlayerSystem. 

Similarly, `debugTarget` and `setWorldTime` have been moved to `ClientCommand` and also exist twice now.

**Comment by Cervator** [comment]
Oho, so we had more duplication.

So really we need to remove those four from CoreCommands again then fix the two broken ones in PlayerSystem
