### ISSUE TITLE
Command line argument for server port

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1603]
You can pick the port in the menu when joining a server, but I don't figure there's a way yet to set the server port, at least outside editing config.cfg directly (network.serverPort)

We should probably have a port argument on the PC facade to allow easy port selection for headless servers in particular

Wouldn't hurt to have something similar when hosting a game via the normal client, but that seems like less of a priority :-)

**Comment by unpause** [comment]
Working on that! :D
