### ISSUE TITLE
Multiplayer too version sensitive - Core module download fails

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1626]
This may not have much to do with the game not actually handling a version difference between server and client well, but in short if you connect to a server with a version mismatch you'll get "Downloading Core 0.##.#" and stall at that step.

It makes sense that the server offers the correct version for the client that's out of whack, and in many cases this would work fine. But something causes the process to outright stall and just sit there forever.

I'm not sure how we'd actually handle version conflicts that are "bad" in some sense. Most the time these days the minor version diffs don't seem bad enough to cause much trouble.

**Comment by immortius** [comment]
Hmm, there's no particular reason why a client should be unable to use a
different version of core as required.

**Comment by Cervator** [comment]
I imagine it could more point to a bug in the download process? Since that's where the stall happens. It is just only provoked when the two are at different levels, I figure.

**Comment by msteiger** [comment]
Is this related to or even fixed by #1670 ?

**Comment by Cervator** [comment]
I don't think so, that's just a simple dependency issue due to versioning. I know the fix to that one but not this one :-)

**Comment by Cervator** [comment]
Interestingly while testing with a new fellow on IRC I did not stall while downloading, and in fact got a bunch of modules from his server (set to run TTA) downloaded before the server crashed from some save issue.

Maybe this was resolved recently? We need to retest :-)

**Comment by Cervator** [comment]
Testing today with http://jenkins.terasology.org/job/DistroOmega/408/artifact/distros/omega/build/distributions/TerasologyOmega.zip against a partially updated server (wiped install dir, but intact game data dir?) again resulted in the stall on downloading missing modules.

Maybe it works if the module isn't present, but fails if it of the wrong version / older on the server?

In any case we should at least be adding a timeout or some other option to cancel (a button maybe?)

**Comment by Cervator** [comment]
Closed as fixed by #2379
