### ISSUE TITLE
UI Improvements for vertically squeezed resolutions

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1627]
Currently the game UI doesn't rearrange very well if challenged at the vertical dimension. A simple example:

![verticalsqueeze](https://cloud.githubusercontent.com/assets/1063833/6543097/960b3d58-c4dc-11e4-8c1b-9213d774f2fb.png)

Some potential improvements:
- [ ] Let the open space around the game logo shrink rather than the box with all the UI elements in it
- [ ] Let some elements move to the side if needed (might be trickier - but stacked Play/Back buttons would fit easily on either side)
- [ ] Squeeze away some of the margins inside the box rather than let the bottom of the box go out of view
- [ ] Add [tab] order on the buttons so even if you can't see an element you could at least have a chance to tab to it for interaction (that's a stretch in this situation but a good usability item in general) - #483
- [ ] Improve dropdowns or make other types available that open their list upwards or have other options. See #844
- [ ] Allow the user to scroll if any UI elements fall off the visible part of the window

Any other options?

Maybe related: #1223, #1198
##

**Comment by skaldarnar** [comment]
Closing in favor of #2585.
