### ISSUE TITLE
Swimming mode doesn't end if you exit by entering freshly broken blocks underwater

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1633]
Hop in a body of water, start digging into the ground and exit out of the water into the freshly dug open area. You keep swimming.

I did it into the side of an underwater wall, unsure if it gets more specific (have to dig sideways rather than dig down, etc)

Edit: Tangentially related to #1513

**Comment by skaldarnar** [comment]
Most likely the spot to look at: https://github.com/MovingBlocks/Terasology/blob/f06491acb06ab1c226e5333e2f3bf2b449508760/engine/src/main/java/org/terasology/logic/characters/KinematicCharacterMover.java#L167-L258
