### ISSUE TITLE
Blockdrops don't have a texture.

### ISSUE THREAD

**Issue by unpause** [MovingBlocks/Terasology#1638]
The Blockdrops in the game don't have a texture. Tested with most of the graphics settings.

![terasology-150315112305-1152x616](https://cloud.githubusercontent.com/assets/9016634/6655623/111944c0-cb06-11e4-9326-18af99def5e0.PNG)

EDIT: This happens after changing the video settings in-game.

**Comment by Cervator** [comment]
Did this happen after changing video settings while in-game? There is #966 for that known issue, if that's the case :-)

**Comment by unpause** [comment]
That's the case.

**Comment by Cervator** [comment]
Okies, thanks! Closing as a duplicate then :-)

Still no clue what actually causes it. Fairly low priority since you can fix by exiting to main menu and reloading the world.
