### ISSUE TITLE
Update basic display of health [$10]

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1639]
Currently the health bar and possibly the breath bar are among the oldest bits of placeholder stuff we have, we might even be using unoriginal artwork (can't remember)

On large resolutions it can be hard to see details and it just isn't very original or interesting.

We have the anatomy system suggestion (#465) to instead do a more sophisticated damage model a la Dwarf Fortress, but that's probably still a long ways off, and really is a different concept that might only be interesting to some gameplay styles.

Instead in the meanwhile it would be nice to do some updates to the basic system
- [ ] Update artwork to something original designed by us
- [ ] Add nice animations / indicators of damage gained/lost, especially when lower health (blink?)
- [ ] Allow status modifications to change color of the health indicators (this used to be a thing when Potions worked - #737)
- [ ] Maybe add an (optional?) text display
- [ ] Make it scale / display better on larger resolutions.
- [ ] Maybe even make it movable, like the suggestion at http://forum.terasology.org/threads/editable-gui-layer.1174/#post-11573 - this could be a nice first element to try that out with

Also, should player health / health display perhaps even be moved to a module, like the breath bar (Breathing module) was? Then if it isn't enabled == immortal creative style.

Breathing bar itself might be a good thing to update along with this, especially if the artwork there is unoriginal (still can't remember)
##

**Comment by Cervator** [comment]
Little mockup by @Calinou of a basic bar-only system (akin to TTA)

![simplehealthbars](https://cloud.githubusercontent.com/assets/1063833/6657031/9c3e2d50-cb14-11e4-9985-10b172e41108.png)

**Comment by skaldarnar** [comment]
I'd stick with the very basic layout (as in the mockup) and either use a texture (as is used in TtA if I remember correctly) or some gradient color. 

I'd also suggest to introduce as (composed) `UIBar` which can be parameterized to specific needs, e.g., change the background color/texture, position of display text, ... I'm not 100% sure, but I think we have binding mechanisms for UI elements, which could be used to directly bind the displayed value of the bar to some component...

**Comment by Calinou** [comment]
To reduce clutter, the health/breath bars could be hidden or made semi-transparent when full (à la The Dark Mod).

**Comment by Cervator** [comment]
Bump. On reviewing the recent changes in #2171 I noticed the health bar now ended up in the middle where before it was sort of off to the left so the breath bar could go to the right. Now they sort of overlap but then the breath bar is broken anyway (https://github.com/Terasology/Breathing/issues/4) and we really need to go away from that placeholder stuff as well.

@Josharias dunno if the move was a random side effect of recent changes or a stylistic choice but it hardly causes any real trouble as it is now. 

To celebrate trying to do something more than just move it back to the left a little I threw a little bounty on here for the fun of it :-)

**Comment by VincentWells** [comment]
Hey, Cervator; since I finished up exams last week, I've finally had time to look into some issues to get to know the codebase, and this one looked like a good starting point.  So far, I've managed to move the bar to far left, and edited the bar from hearts to a plain green bar for now.  A couple questions, though: first, is it just the graphics that's broken about the breath bar?  It didn't seem like I ever took damage while being underwater when I was playing around.  Next, my current method is sort of hackish; just replacing the heart icons in the icons.png file, so the bar is still bound the same increments of 1/2 icon as before; is that what you had in mind, or should I try to find a way to make the bar more continuous?

**Comment by Cervator** [comment]
Hey @VincentWells :-)

I just tried out enabling Breathing and hopping in the nearest body of water deep enough to trigger the breath bar. When I ran out my health started dropping normally.

Simply replacing the icons would satisfy item 1 in this issue, so that's one small good step forward. Continuous would be another nice extra but not mandatory.

Progress is progress. Keep it up :+1:

**Comment by VincentWells** [comment]
Ah, so you have to enable Breathing? I didn't realize that; my bad.

**Comment by skaldarnar** [comment]
A lot has happened in https://github.com/Terasology/Health, I think we're good for now.
