### ISSUE TITLE
Javadoc improvements needed for Java 8

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1641]
I tried building the engine in Jenkins with Java8 including the standard lineup (so javadoc etc too). It went poorly :-)

http://jenkins.terasology.org/view/Nanoware/job/NanoTerasology/42/console (used JDK 8u40)

It looks like Java 8 javadoc generation got a whole lot pickier, or maybe the default leniency changed. In any case it isn't really a bad idea to tighten up our Javadoc, and it is pretty easy for a new contributor too.

Probably run javadoc locally to catch everything, the Jenkins log above has the first 100. 

*NOTE:* This should be done AFTER the big pending PR by @Josharias lest the conflicts reach epic proportions. This is a requirement before we can switch to Java 8 (or if too much hassle figuring out how to make javadoc more lenient again)

Sample snippet:

```java
:engine:javadoc/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeDeactivateComponent.java:24: error: self-closing element not allowed
 * <p/>
   ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeDeactivateComponent.java:28: error: malformed HTML
 * @author Immortius <immortius@gmail.com>
                     ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeDeactivateComponent.java:28: error: bad use of '>'
 * @author Immortius <immortius@gmail.com>
                                         ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeEntityCreated.java:30: error: malformed HTML
 * @author Marcin Sciesinski <marcins78@gmail.com>
                             ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeEntityCreated.java:30: error: bad use of '>'
 * @author Marcin Sciesinski <marcins78@gmail.com>
                                                 ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/BeforeRemoveComponent.java:23: error: self-closing element not allowed
 * <p/>
   ^
/var/lib/jenkins/jobs/NanoTerasology/workspace/engine/src/main/java/org/terasology/entitySystem/entity/lifecycleEvents/OnActivatedComponent.java:24: error: self-closing element not allowed
 * <p/>
```

**Comment by skaldarnar** [comment]
How would we go about the `@author` + mail lines in general? Would you go and just enclose the mail address in normal parentheses `(my.name@mail.com)` or remove the line altogether since version control holds the more reliable information about the author and/or current/maintainer.

**Comment by msteiger** [comment]
Maybe this stackoverflow post is helpful?

http://stackoverflow.com/questions/22528767/jdk8-and-javadoc-has-become-very-strict

The guys suggest turning the strict mode off, but I'm not a big fan of that. Maybe we should try to fix/remove them? Not sure about removing the authors - I think they can be useful sometime (but then, often they are not). Maybe just remove the mail address?

**Comment by Cervator** [comment]
Thanks for the link, there was a nice quick blog entry in there too: http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html

What I think we should do is get serious about javadoc already, pick our conventions, code them into our checkstyle rules (or the nagging at least), then start fixing them. Somebody needs to run point on a convention proposal real quick and pleasegodnotmeihavetoomuchalready :pray: :D

Fix the warnings when we know exactly how we want to do so then hop on Java 8 already :-)

I'm sure there's a decent author tag that still includes email in a nice optional format. If the author wants to put it there go for it. We can probably code in a javadoc header template with the right format in the IDE customization scripts in Gradle too.

**Comment by Cervator** [comment]
Closing as complete, next round of work is in #1664 (although weirdly I'm seeing some remaining hits in Core)
