### ISSUE TITLE
Logs no longer capturing fatal exceptions

### ISSUE THREAD

**Issue by immortius** [MovingBlocks/Terasology#1645]
I've been seeing a number of reports recently where people say they crashed, but the log does not contain an exception. Without having investigated I suspect the recent changes to crash logging may have resulted in the exception causing a crash not being logged.

**Comment by Cervator** [comment]
I know the multiple log files could cause some confusion, like a player uploading the menu / init log while the crash was in the world log. I dunno if that could explain all situations though.

Sending @msteiger's way :-)

**Comment by msteiger** [comment]
Is there a way to reproduce the issue?

In any case we could consider having separate logging configurations for regular players and (headless) server instances. I will look into that.

**Comment by Cervator** [comment]
Linking this to https://github.com/MovingBlocks/CrashReporter/issues/23 as possibly related

**Comment by Cervator** [comment]
Closing as fixed by #2073 - yay!
