### ISSUE TITLE
Improve shader error popups

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1649]
Currently I believe multiple shader compilation errors result in one popup per error, which can be somewhat obnoxious if there's a bunch. We can probably instead sum them up temporarily and present them all in a single popup the first time they're relevant, then not do it again for that game session / config session if the errors are specific to some video option?

Additionally it is possible the popups do not behave well when the user is running in full screen.

Reference: http://forum.terasology.org/threads/multiple-pre-alpha-bugs.1268/

**Comment by msteiger** [comment]
I'll have a look at this in the frame of logging / error reporting improvements. I guess it should rather propagate the failure up the hierarchy and let the root level take care of it.
