### ISSUE TITLE
stable-50 Release has no modules except core/csg, but stated otherwise in readme

### ISSUE THREAD

**Issue by qwc** [MovingBlocks/Terasology#1655]
Hi,

just wanted to mention that in the readme is written that a bunch of modules are bundled with the game.

That's just not the case, I downloaded terasology as ZIP from your jenkins and also installed it with my distribution repository and there are no modules except core and coresamplegameplay.

Just please, give the correct information in the readme or really supply all mentioned modules in the zip, because i searched quite a while where this modules could be for my little docker image at my server.

Thanks!
Best Regards,
qwc

**Comment by msteiger** [comment]
Hey there,

Terasology comes in different flavors. The one you're looking for is probably "Omega". It contains the modules that are mentioned in the Readme file:

http://jenkins.terasology.org/job/DistroOmega/118/console

You can download it from the github release page or from Jenkins just as you did for the "Iota" build, which is smallest flavor. Does that help?

**Comment by qwc** [comment]
Of course this does help! Maybe the information about flavours should be more eye-catching? :)

**Comment by skaldarnar** [comment]
Hey @qwc, one single question from my side: Which distribution are you using? We should probably contact the package maintainer and ask to use the Omega-bundle as default.

**Comment by qwc** [comment]
:P :)

**Comment by qwc** [comment]
In the arch linux user repository is now the Omega Build available.

-> aur/terasology
