### ISSUE TITLE
Crash when i want to preview a seed for a map generator

### ISSUE THREAD

**Issue by qwc** [MovingBlocks/Terasology#1656]
See: http://pastebin.com/nhz3R60b

Argh, sry, made this issue just after the crash, and did not search for similars. Sorry for the doublepost!
Already reported in: #1524

**Comment by Cervator** [comment]
No worries! Yep one more thing we need to fix :D I'd rather have a dupe than an issue that goes unreported.

Closing as duplicate :-)
