### ISSUE TITLE
Entity/Memory leak due to item movement prediction

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#1659]
When you split a item stack on a client then it predicts the item split by creating a local copy of the item.
When the server then informs the client about the new inventory content with the real new item stack then the client only item stack remains unconnect to a inventory.

**Comment by Cervator** [comment]
Is this still an issue? Helped any by having #1699 merged?

**Comment by flo** [comment]
#1699 is unrelated. It is not fixed yet.

**Comment by Cervator** [comment]
Closing as fixed by #1704 :-)
