### ISSUE TITLE
Retire all Javadoc author tags

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1664]
As discussed in the forum: http://forum.terasology.org/threads/removal-of-all-javadoc-author-tags-any-objections.1273/

No objections so far, so if anybody wants to get it over with doooo eeeet :-)

We probably should also look at Javadoc in modules, lest we forget and have them break when updated to Java 8.

**Comment by msteiger** [comment]
I'll have a look at it in the frame of an update of code style checkers and also add the @author tag to the set of checkstyle rules.

Gradle 2.4 should bring a few niceties for improved integration and I might want to wait for it to be released. This should be the next 1-2 weeks, I hope.

**Comment by Cervator** [comment]
Sounds good, no rush :)

**Comment by Cervator** [comment]
Started looking at module javadoc some thinking maybe I could fix up a few modules real quick, switch them to Java 8 in Jenkins, then run good builds so we can have working binary releases again ... but I may be underestimating the amount of errors :D

I just started with a search for @author in *.java under modules in my mega-workspace and fixed 136 hits across AnotherWorld, BlockNetwork, Breathing, and Cities. But that didn't count other javadoc errors ;-)

It is a bit of a hassle to detect them too, takes forever if using gradlew javadoc on a particular module. Wonder if Checkstyle could catch it all specifically to make it easier to fix. I'm probably missing other easy options.

Just to get a list anywhere here are the modules in the lineup with author tags (about 500 file hits, not counting what I've got fixed locally):

- [ ] AnotherWorld
- [ ] Breathing
- [ ] Cities
- [ ] CommonWorld
- [ ] CopperAndBronze
- [ ] Core (wut? I thought that was covered and would break things if not)
- [ ] Fences
- [ ] Fluid
- [ ] Genome
- [ ] GrowingFlora
- [ ] Hunger
- [ ] Journal
- [ ] LightAndShadow
- [ ] Malicious
- [ ] MarkovChains
- [ ] MasterOfOreon
- [ ] Maze
- [ ] Miniion
- [ ] Minimap
- [ ] MultiBlock
- [ ] MusicDirector
- [ ] NameGenerator
- [ ] OreGeneration
- [ ] Pathfinding
- [ ] PlantPack
- [ ] PolyWorld
- [ ] Portals
- [ ] Sample
- [ ] Seasons
- [ ] Signalling
- [ ] Spawning
- [ ] WeatherManager (okay, may not be in the lineup yet, but I have it in my workspace)
- [ ] WoodAndStone
- [ ] Workstation

**Comment by Cervator** [comment]
I just noticed Gradle 2.4 adds an ability to replace external dependencies with project dependencies, woo! That's what I've hacked in presently. That'll be nice to clean up - that release could indeed be sweet :-)

**Comment by Cervator** [comment]
Temp hack in place to let the module builds work: https://github.com/MovingBlocks/Terasology/commit/e328c4ac69d73eaca8f3b80ac06c590658ab3f00

Includes a TODO to remove it again later, since you know that always ensures that it does in fact get removed later ...

Jenkins should log the warnings + errors so at least they'll be easy to spot, although I'm sure there's a better way in IDEs

**Comment by msteiger** [comment]
I tried to configure CheckStyle to flag `@author` tags, but it just wouldn't do it. I suspect that it's a bug in CheckStyle ([related issue](https://github.com/checkstyle/checkstyle/issues/952)).

**Comment by msteiger** [comment]
Unfortunately, my assumption was confirmed and we need to find a workaround such as plain RegEx to make CheckStyle flag the remaining `@author`  tags.

**Comment by msteiger** [comment]
I think that we can close this issue, since all *MovingBlocks* repositories have been updated.

**Comment by Cervator** [comment]
Agreed! And we have warnings being issued for them now too, thanks for that :-)
