### ISSUE TITLE
Cache Files

### ISSUE THREAD

**Issue by Skintillion** [MovingBlocks/Terasology#1667]
How does Terasology determine where to install the cache files? It installed on a network drive without asking. It was a mapped drive if that helps.

**Comment by Cervator** [comment]
Hi @Skintillion 

Terasology looks for your defined user home directory, which varies by OS. Likely your user home dir is what's mapped to the network drive?

You can run the game with "-homedir" to make it save data to the local directory you're running from (or "-homedir=/some/other/dir"

Does that help? :-)

**Comment by Skintillion** [comment]
It was just a mapped folder, no user files are stored there. It was "Z:\".
I ran %USERPROFILE% and it does not take me there at all.

On Tue, Apr 14, 2015 at 2:22 PM, Rasmus Praestholm <notifications@github.com
> wrote:

> Hi @Skintillion <https://github.com/Skintillion>
>
> Terasology looks for your defined user home directory, which varies by OS.
> Likely your user home dir is what's mapped to the network drive?
>
> You can run the game with "-homedir" to make it save data to the local
> directory you're running from (or "-homedir=/some/other/dir"
>
> Does that help? :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MovingBlocks/Terasology/issues/1667#issuecomment-93067248>
> .
>



-- 
Jeremy Jackson

**Comment by Cervator** [comment]
Interesting!

Could you upload the game log files somewhere please? There should be some details logged on it figuring out the relevant directories

**Comment by immortius** [comment]
Which OS are we talking. The mechanism differs slightly by OS, although in
each case it tries for a "standard" user location.

**Comment by Skintillion** [comment]
Win 7 64bit in a domain. Fairly standard setup

**Comment by Cervator** [comment]
In a domain? Hmm. Standard Win7 should put saved files in C:\Users\[user]\Saved Games\Terasology but I am not sure how commonly we've had testing done on domain-attached PCs. I wonder if there are any scenarios where group policy or other Domain-y things can interfere with our path lookup.

I had the game on my old work laptop, where we had a network-based user home directory, although it was primarily for My Documents so Terasology stayed local. Other things didn't - I ran across a bunch of Civilization saves in my corp network home once, whoops.

**Comment by Skintillion** [comment]
Yea thats kind of what happened in this case. So i can run a test for you
if you like would hate for it to happen to someone else.

**Comment by Cervator** [comment]
Yes please! We absolutely want to make sure these kinds of edge cases will behave along with more typical setups.

Do you have any ideas of the exact config that is involved? If so we might be able to prepare some debug logging to get more info. Unless you by chance feel comfortable with running Java from source and can sort through OS related path issues ... :-)

**Comment by immortius** [comment]
Under windows, we use the windows api to request the location of the Saved
Games folder, falling back on the Documents folder. We do not use the
registry directly although there are registry keys corresponding to these
as well.

I will do some research and see if these failing is a known issue for
domain setups.

**Comment by immortius** [comment]
Hmm, dunno. There doesn't appear to be any known issues. If you could provide any further information it would be appreciated.

**Comment by Skintillion** [comment]
It was a strange user configuration. They had the saved games folder mapped to the server. Sorry for the trouble.

**Comment by Cervator** [comment]
Thanks for following up - appreciated :-)
