### ISSUE TITLE
Fatal issues in latest stable + separate in latest develop

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1669]
More or less leaving this as notes for myself as I think they relate to recent build fun or similar changes like Java 8 fun.

Latest stable binary fails in TTA:

![crash reporter_2015-04-14_22-49-16](https://cloud.githubusercontent.com/assets/1063833/7152529/85d484f6-e30b-11e4-8a35-d0a0257106a9.png)

That crash also leaves an orphaned process hanging in the background as the game fails to dispose correctly (pinging @msteiger when he gets back, or maybe @flo or @shartte)

Latest develop build & Omega in Jenkins leaves you stranded with dependency issues (probably related to Core and some versioning quirk?) - http://forum.terasology.org/threads/cannot-select-core-gameplay-module.1281/

**Comment by immortius** [comment]
This looks less to do with Java 8 and more because AssetManager was changed
from a class to an interface. This requires a recompile of users of
AssetManager.

Not as bad as the upcoming large scale breaking change as the asset
framework get upgraded. If I can get my internet working again.

**Comment by Cervator** [comment]
Yeah that sounds about right. Late night and throwing some last minute notes together :D

Good luck with internet!

**Comment by msteiger** [comment]
Does this problem still persist?

**Comment by Cervator** [comment]
Almost fixed. I think we got the Core version tweaks done and may have rebuilt enough to fix TTA, although the last stable release binary will still be broken. If I can get the remaining modules built today and a binary confirmed as good I can do a quick checkpoint stable then close this :-)

**Comment by Cervator** [comment]
Okay, rebuilt a few modules that used AssetManager + any remaining modules with dependency numbers off.

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip is showing 100% module readiness and TTA is working again.

Next stable release should function as well, in the meantime latest dev build is more stable :-)
