### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by accyasry** [MovingBlocks/Terasology#1678]
Log: https://docs.google.com/uc?id=0B5l2RT_UOCXRWk5la2F4WlVmU28&export=download

**Comment by Cervator** [comment]
Hello @accyasry - I'm afraid you appear to be running Terasology on unsupported graphics hardware, probably on an older computer? :-(

You can try to update your graphics drivers but the odds are low you'll be able to play the game well on that computer.
