### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Wayward1** [MovingBlocks/Terasology#1687]
I was trying to join a server when Terasology crashed without warning, followed shortly after by the error report window. I'm not sure where to find the logs, as the folder this particular copy of Terasology is in has only the libs, modules, and natives folders, but this is the error output I recieved: http://pastebin.com/XLGcDi4j

**Comment by Cervator** [comment]
Thanks for the report :-)

The full log files should be in your use home directory. On newer versions of Windows for instance they'll be at C:\Users\[user]\Saved Games\Terasology\logs

**Comment by Wayward1** [comment]
You're welcome :)

I still can't seem to find the logs, even after a system-wide search. I'm running a Linux Mint 17 live USB with persistent storage, by the way.

**Comment by Cervator** [comment]
Oh, huh, maybe that's an unusual setup.

Try this - when you crash the game the CrashReporter should show all the associated log files. There should be multiple tabs open. In the Init one at the top the location the logs are being saved to should be listed (the game home dir)

If you can't easily replicate this crash just start a local game with the "Sample" module enabled and do `giveBlock crashgameblock` from the console. Place one of the blocks and press `e` while pointing at it. Boom.

**Comment by msteiger** [comment]
One of the first lines in your log should be:

    o.terasology.engine.TerasologyEngine - Home path: <>

This is where your log files should be.
Are you using Oracle's JDK or OpenJDK?

In any case, I don't see why the thread pool in `ServerInfoService` would reject the task. Maybe there's a nested error?

Also, I cannot reproduce the error. The server list looks fine on my Win7 machine :confused:

**Comment by skaldarnar** [comment]
Make sure you search for invisible directories as well! I've got a `/home/<user>/.terasology` folder which holds the save games (note the leading dot).

**Comment by msteiger** [comment]
I was able to reproduce the bug. Will have a look ..

**Comment by Cervator** [comment]
@Wayward1 feel free to retest sometime (well, in 10+ minutes when the build is done). This should be fixed in the latest develop build (hopefully in a next release within a couple days)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

**Comment by Wayward1** [comment]
Ok, sounds good. (I apologize for the late response, I've been quite busy recently)

**Comment by Cervator** [comment]
Oh we're all familiar with busy! No worries and thanks for following up :-)

**Comment by Wayward1** [comment]
No problem :)
