### ISSUE TITLE
More powerful API for serverside plugins?

### ISSUE THREAD

**Issue by getsmp** [MovingBlocks/Terasology#1696]
Hello. Can I write any other plugins for server in addition to defining new commands?

**Comment by MarcinSc** [comment]
Yes, modability of the engine is the main goal of Terasology.

If you wish to find out how other mods are working, and how to start - I recommend the following post with a list of couple of mods ordered by difficulty:
http://forum.terasology.org/threads/systems-and-components-to-learn-from.1016/#post-10070

This question however does not belong in issue tracker, it belongs in the forums, hence I will close it.

**Comment by getsmp** [comment]
Thanks for pointing that out.
