### ISSUE TITLE
When I do "Return to main" or "Exit Terasology" the BeforeChunkUnload is not called

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#1698]
##

**Comment by MarcinSc** [comment]
Maybe the following code in StateIngame should replace the calling of storeManager:
        ChunkProvider chunkProvider = CoreRegistry.get(ChunkProvider.class);
        chunkProvider.dispose();

**Comment by Cervator** [comment]
https://github.com/MarcinSc/Terasology/commit/bf94cca17c85eff9931f6c3729f669da317c80f9 got merged and seems to relate to this. Unsure how to easily test if it made a difference though.

**Comment by Cervator** [comment]
@MarcinSc - is this complete?

**Comment by MarcinSc** [comment]
I put a workaround in place, but it would be nice if someone more knowledgable made sure it is correct. Also, it probably needs to be refactored, as those spaghetti calls seem a bit random - definitely could be done nicer.

**Comment by jdrueckert** [comment]
Closing as StateInGame is not particularly better or worse than other parts when it comes to need for refactoring.
