### ISSUE TITLE
Support for clipboard access (read and/or write) for modules

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#1702]
Modules should be able to access the clipboard via an @API code in the engine that works around the security limitations. It should only support text flavors.

**Comment by Cervator** [comment]
Is this technically complete now or would it be an outstanding bug that the OS clipboard contents still do not appear available? Only content that has been copied from an in-game source can be pasted.

At least that's what I *think* is going on, more testing would be good. Not super sure if OS-origin stuff should be available anyway (modules reading sensitive stuff - although what could they do with it?). 

On the other hand having to first copy paste stuff from the OS level into the game console then copy pasting it from there into a module UI that can take pasted input ... that would be an awkward workaround :D

**Comment by MarcinSc** [comment]
It worked fine for me, copying from IntelliJ into the computer terminal. Could you please retest it, and see which part has failed? It's possible that if you copy from some fancy editor (Word, or whatever), it might not support the String flavor?

**Comment by Cervator** [comment]
Oh I see - it is actually the other issue where the computer terminal UI loses focus. Which it can do if you don't carefully copy paste from an outside window.

If you exit out of the terminal then reopen so it has focus the copy paste works fine :-)

My mistake, closing as complete, yay!
