### ISSUE TITLE
You can replace water blocks with water blocks forever

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1713]
This is probably a fairly simple case of "abusing" the system where you can place blocks in water to make the water go away. If you do so with actual water - you can place "new" water blocks over and over and over until you run out of blocks ;-)

If a block is replaceable like that it probably shouldn't be replaceable by its own kin (exact block, block family, or what not)

**Comment by MarcinSc** [comment]
You probably should NOT be able to obtain water in block form, so I would ignore this problem.

**Comment by Cervator** [comment]
Eh, that's sort of aside the point :-)

Some mode will end up allowing it, and it probably affects similar situations (lava maybe?)

I have a vague recollection that you used to be able to replace billboard plants with blocks without first breaking the plant, but that doesn't seem to work anymore. Had wondered if you'd be able to replace tall grass with tall grass forever too

**Comment by skaldarnar** [comment]
I would suggest to close this and have an note in a related issue on water/fluid overhaul. Water replacement is just special because water blocks are special, but it is not really tailored towards liquids in general.

**Comment by Cervator** [comment]
That's fair. But interestingly ... we don't have an issue for an entire overhaul, looks like :D

We just collectively know of it, more or less, along with various forum mentions of turning liquids into "something else" that yeah would probably obsolete this issue.

If we go that route one day I imagine actual liquid "blocks" being acquirable would probably also truly go away. Thought I'm not sure (creative mode)

@skaldarnar whenever you post a fresh liquid module thread in the forum (no rush!) feel free to just include a bullet point for this then close it :-)

**Comment by Cervator** [comment]
Closing as fixed by #2225!
