### ISSUE TITLE
I CANNOT ENTER GAME

### ISSUE THREAD

**Issue by terology** [MovingBlocks/Terasology#1716]
Vendor: Intel
Model: intel 965/963 Grafics Media Accelerator
Driver: 2.0.0 - Build 8.14.10.1930

**Comment by Cervator** [comment]
Hi there. Normally we'd ask for a lot more detail than that, but chances are your video card is too old. I'm seeing hits on Google around 2007-2008.

Probably the log / crash reporter suggests as much too. Unsupported graphics format or so.

If you can get more details we can try to look at it more but you are probably out of luck, sorry :(

**Comment by msteiger** [comment]
Closing this due to lack of feedback.
