### ISSUE TITLE
Crash to Desktop by using seeds on hoed ground

### ISSUE THREAD

**Issue by thyrax** [MovingBlocks/Terasology#1725]
I cultivate the ground with the hoe and after that i used the seeds of the red flower on it. 
Then it chrashed.

**Comment by Cervator** [comment]
I figure this is in Throughout The Ages? It sounds like https://github.com/Terasology/WoodAndStone/issues/33

**Comment by thyrax** [comment]
Yes its Through the Ages.
Its like the problem you have linked. Ony different that i used seeds and not a sapling.

**Comment by Cervator** [comment]
Fixed by  #1863 - woohoo!

@thyrax ping!
