### ISSUE TITLE
Crash after using herb bag

### ISSUE THREAD

**Issue by darklynyxx** [MovingBlocks/Terasology#1734]
Log file:

https://docs.google.com/uc?id=0B5l2RT_UOCXRN2hDWmFxY3BYQlE&export=download

**Comment by Cervator** [comment]
Hi @darklynyxx and thanks for the report :)

Could you please list the exact steps you use to trigger this error? You're in the Throughout The Ages world, get a herb bag, then use it - how? Helps to replicate it more easily.

There are multiple log files, the crash is in a different file, probably in a world log. If the CrashReporter is popping up it is likely just showing you one of the available files of several.

**Comment by Cervator** [comment]
Fixed by  #1863!

@darklynyxx ping :-)
