### ISSUE TITLE
Resolve and download modules at runtime

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1754]
I think that it would be great if Terasology could resolve and download wanted or required artifacts (from Artifactory?) automatically.

- [x] **TODO:** Make Artifactory list all module jars

* The GAVC (group, artifact, version, classifier) search returns all file types (pom, jar, asc)
* The GAVC search without classifier finds all classifiers instead of none (javadoc, sources)
* By default, [Artifactory lists only 500 search results](http://artifactory.terasology.org/artifactory/api/search/gavc?g=org.terasology.modules&repos=terasology-release-local,terasology-snapshot-local), but this can be increased.

- [x] **TODO:** Retrieve module information for each entry
* One way would be extracting the module.txt from each jar file
* Another would be encoding the important data in the `pom.xml` file: minVersion, maxVersion (maybe name, description and authors)

- [x] **TODO:** Create a ModuleRegistry based on the entry data
* Maybe [master-server](https://github.com/MovingBlocks/master-server) could provide a cached and JSON-ized list of `ModuleMetaInfo`.

- [x] **TODO:** Resolve deps. and download artifacts
* Maybe using a Maven plugin
* Probably easier through gestalt-module
* Downloading must be done into a folder with write-access

- [ ] **TODO:** Search the target download folder for modules on startup and after downloads

**Comment by Cervator** [comment]
This is the sort of thing I was hoping https://github.com/MovingBlocks/ModuleManager could be made to do so it could be used in different contexts :-)

I think being able to cache into the Index on GitHub will be important in case of usage spikes. Any of our servers will melt like butter in the sun if another big Lets Play comes out and we have module management hitting Jenkins, Artifactory, or even the master server list. With MM running locally and fetching indexed data off GitHub we should be fine.

If the master server just redirects to the index that could probably work too, but would still suck if it became unavailable for some reason (same reason I really want to start mirroring some of the stuff in Artifactory so local dev doesn't break if it isn't available)

I'm not sure what ideally would update the index, when. We do have the current job in Jenkins that does something similar. That could do a sort of full refresh out of Artifactory data if it is only needed once daily. Or we could batch changes building up in Jenkins then push to the Index on a regular basis.

**Comment by msteiger** [comment]
Sneak preview:

![image](https://cloud.githubusercontent.com/assets/1820007/8397779/951ef91c-1dd7-11e5-939f-506bb92b59f6.png)

**Comment by Cervator** [comment]
Very nice! Did not expect to see that so fast :-)
