### ISSUE TITLE
Terasology no longer compiles on eclipse

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1771]
With #1740 merged, Terasology does no longer compile on eclipse. The following line fails:

```java
assetTypeManager.registerCoreAssetType(BlockTile.class, BlockTile::new, "sounds");
```
*The target type of this expression is not a well formed parameterized type due to bound(s) mismatch*

I first thought that this was a bug in the eclipse compiler: [Eclipse Bug 425278](https://bugs.eclipse.org/bugs/show_bug.cgi?id=425278), but if I understood it correctly this is supposed to happen.

One of the compiler developers [reported a bug for OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8033810) that `javac` compiles the code fine, but it shouldn't.

**Comment by Cervator** [comment]
Huh! Now that's interesting.

I do find the :: a bit scary still, haven't taken the time to get used to it yet :D Java is getting complicated.

**Comment by Cervator** [comment]
Three merged PRs later is this one resolved?

**Comment by msteiger** [comment]
Yup - thanks!
