### ISSUE TITLE
Incomplete reflection cache files for 0.54 engine/Core jars

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1777]
After upgrading to engine 0.54.0, some of the `FacetLayers` were no longer discovered in WorldViewer. I noticed that the `reflections.cache` file in the snapshot jars specified only some implementations.

Example: [engine-0.54.0-6](http://artifactory.terasology.org/artifactory/terasology-snapshot-local/org/terasology/engine/engine/0.54.0-SNAPSHOT/engine-0.54.0-20150617.090056-6.jar) reflections:

According to the cache file, the only subtypes of `AbstractFacetLayer` are `NominalFacetLayer` and `SeaLevelFacetLayer`, but in fact there are more - even in the same package (e.g. `FieldFacetLayer`).

How is that possible?

**Comment by immortius** [comment]
This is the issue I've been struggling with. It only happens in a gradle
context - the same code for gathering reflections works fine external to
gradle. Some of the symptoms are really odd, like it discovering inner
classes but not the outer class for GLSLShaderFormat.

Perhaps reflections caching needs to be in a gradle plugin, or run in a
separate jvm?

**Comment by msteiger** [comment]
Just a wild guess: Could it be related to gradle now compiling projects in parallel? I don't see a direct link, but maybe that's still buggy. Commit https://github.com/MovingBlocks/Terasology/commit/6c1fe4b5522b618458b1c9442797c49f3e0a1fe7 enabled it. The [Gradle docs](https://docs.gradle.org/current/userguide/multi_project_builds.html) "56.8 Parallel project execution" gives some background info.

**Comment by immortius** [comment]
It doesn't look like it, but if the reflections caching is happening concurrently with compilation that could explain it. Although I think it is too consistent on what classes are and aren't included.

**Comment by Cervator** [comment]
Actually that commit is to a template file, it isn't being used. I manually copy it to my local workspace to enable that kind of stuff and override destinations if I'm testing Artifactory type stuff.

Jenkins should still be compiling old school. We probably *should* actually consider changing that around a little sometime to optimize Gradle.

Would it be something to try running the build and the caching in separate Gradle executions? Like first compile the code, finish that Gradle execution, then start another to cache, then dist?

**Comment by immortius** [comment]
Any caching in gradle, even if you do nothing but caching after previously
compiling, fails to find all the classes. Would need to debug in to work
out why.
