### ISSUE TITLE
Rename "Online" to "Listed" on the server join screen?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1786]
After merging #1784 I got to thinking - if the tab says "Online" yet I'm looking through servers that are mostly offline that could be read kinda funny.

Maybe a better option would be to name the tab "Listed" - as in, servers officially listed by us via the listing service. They may be running or not at any given time (online/offline)

@msteiger what do you think?

**Comment by msteiger** [comment]
I see your point. How about "official" to contrast the "custom" tab?

**Comment by Cervator** [comment]
I was considering "official" but that gets ambiguous in a different way: it implies we might have an official relationship / monitoring over said servers, rather than just having listed them as a convenience for players:-)

In other words there could be an *actual* official server one day we host ourselves and play test on. Which could be one of the existing ones, for a period of time at least.
