### ISSUE TITLE
crash when "back into menu" in a video settings (game off, only menu)

### ISSUE THREAD

**Issue by XAOc57** [MovingBlocks/Terasology#1792]
http://pastebin.com/FKYizwQ9
All logs generated: https://yadi.sk/d/iVNKkzJphTKC6

Change before crash: View distanse: Near > Moderate

P.S. I am sorry for my mistakes in registration crash report, i'm no developer.
I think this is a continuation of the problem: https://github.com/MovingBlocks/Terasology/issues/1791

**Comment by Cervator** [comment]
Going to close this in favor of #1791 since any changes there will probably fix or invalidate this one
