### ISSUE TITLE
Latest development version of game error

### ISSUE THREAD

**Issue by mahmutelmas06** [MovingBlocks/Terasology#1794]
details are here

http://pastebin.com/QX3EFF9T

**Comment by Cervator** [comment]
Hi @mahmutelmas06 - latest develop version of the game is very unstable. Please use the stable release instead :-)

We should have it fixed up soon.

**Comment by immortius** [comment]
Duplicates #1777

**Comment by Cervator** [comment]
@mahmutelmas06 this should be fixed in http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
