### ISSUE TITLE
NullPointerException near Companion

### ISSUE THREAD

**Issue by DonkeyCore** [MovingBlocks/Terasology#1806]
When trying to interact with a Companion I placed down, my game crashed with a NullPointerException as shown [here](http://pastebin.com/5tmWhpAY). Worth mentioning I've been playing with the latest build as of today (7/2/15), 1454.

**Comment by Cervator** [comment]
Thanks for the report :-)

There are some interesting bits in the log we can look at. You mean you placed a companion cube? Did you attempt to hit it or any other blocks in the area?

Did you have the video settings up while in-game? There's a known issue there, although I'm not sure that relates if this happened later in immediate response to interacting with a block.

Or do you mean something else with "Companion" ?

**Comment by DonkeyCore** [comment]
I used the Companion block found in the Chest. I placed it down
successfully, but when I clicked on it (I can't remember if it was left or
right), my game crashed. It happened as soon as I clicked (instantly).

**Comment by Cervator** [comment]
Much appreciated. It looks like left-click, on damaging the block something broke. We should be able to look into that :-)

**Comment by Cervator** [comment]
Been able to confirm this and narrow it down to an issue with "auto" blocks (generated from plain .png files with no block definition). The plain Brick in the starting chest (which has a block definition) is fine.

@immortius is on the case, probably an easy fix sometime soon :-)

**Comment by DonkeyCore** [comment]
Awesome, thanks for taking a look!

**Comment by Cervator** [comment]
Closing as fixed :-)

@DonkeyCore the latest develop build should no longer have this issue
