### ISSUE TITLE
Underline support for drawing Fonts

### ISSUE THREAD

**Issue by immortius** [MovingBlocks/Terasology#1813]
Add support for drawing fonts with an underline with NUI.

**Comment by immortius** [comment]
Making some progress:

![Some underlines](https://dl.dropboxusercontent.com/u/5057882/underline.png)

Added the 'base' attribute to Font, and using it to add a 1px underline to all text.

Still to do:
[ ] Color support
[ ] Underline toggle unicode character (similar to color codes characters)
[ ] Clean up support for shadow w/ underline
[ ] Underline thickness parameter

**Comment by Cervator** [comment]
I'm thinking this is complete and can be closed? Or do we still need the last checkbox there about underline thickness being a parameter?
