### ISSUE TITLE
Delta Prefabs do not resolve other module's components

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#1815]
When using delta prefabs in an extra module (in this case, JoshariasSurvival) it does not seem to resolve any of the components from non-engine modules (like ManualLabor, Machines, Durability, Hunger, etc).  It ends up giving a bunch of these errors:
```
Prefab contains unknown component '<NameOfTheComponentFromThePrefab>'
```

In particular ```PrefabSerializer.componentLibrary.uriLookup``` did not have any components from any of the activated modules.

**Comment by Josharias** [comment]
Help me @flo Kinobe, you are my only hope! ;)

**Comment by MarcinSc** [comment]
Just a sanity check: is the delta defined in a module that contains the new component (or its dependencies contain it)?

**Comment by Josharias** [comment]
Both cases exist,  where the module with the delta also has the component java code.  And where the dependency has the java code.  (is that what you are asking?)

**Comment by MarcinSc** [comment]
Yes, could you try explicitly specifying the module in component name, so for example:
"ModuleName:ComponentName": { ... }

**Comment by flo** [comment]
I am currently investigating if 2a37237f6e20ce77c57f697f2e48aab5fcfc9704 caused it. Apparently the ComponentLibrary gets replaced after the PrefabFormat got registered. Maybe the second ComponentLibrary isn't containing components added by modules?

**Comment by flo** [comment]
Ok, there were 2 PrefabDeltaFormats registered for the same time. What I didn't realize first is that it isn't a map but a multi map that stores the asset type to prefab relationship.

So the issue is that the old PrefabDeltaFormat gets neither cleaned up nor overriden by the newer version.

There is a method for unregistring delta formats but it requires the exact delta format instance that got registered before. So it is not possible to simply clean up the old prefab delta formats when a new one gets registered.

@immortius Which solution to the issue do you prefer? Do you want to add some kind of automatic reset at each environment switch? Or do you have a better solution?

**Comment by Cervator** [comment]
Is this specific to deltas? I'm seeing a bunch of new errors in Spawning/Portals and nothing is getting spawned. Again references to other modules are coming up broken.

```
23:06:35.264 [main] ERROR o.t.p.t.e.TextureRegionTypeHandler - Failed to resolve texture region 'Oreons:icons32.oreonguard'
23:06:35.343 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Animation'
23:06:35.399 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawnable'
23:06:35.402 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'UnbreathableBlock'
23:06:35.458 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type BlockFamily: not a supported type or MappedContainer
23:06:35.458 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:BlockItem.blockFamily'
23:06:35.600 [main] ERROR o.t.p.t.e.TextureRegionTypeHandler - Failed to resolve texture region 'Oreons:icons32.oreonbuilder'
23:06:35.625 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Animation'
23:06:35.626 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawnable'
23:06:35.634 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Portal'
23:06:35.634 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Holding'
23:06:35.634 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawner'
23:06:35.657 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type Block: not a supported type or MappedContainer
23:06:35.657 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:BlockType.block'
23:06:35.661 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type BlockFamily: not a supported type or MappedContainer
23:06:35.661 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:BlockParticleEffect.blockType'
23:06:35.672 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
23:06:35.672 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'maxGroundSpeed' onto 'engine:CharacterMovement'
23:06:35.672 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
23:06:35.835 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Breather'
23:06:35.842 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Portal'
23:06:35.842 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawner'
23:06:35.878 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'AccessInventoryAction'
23:06:35.878 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawner'
23:06:35.888 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Door'
23:06:35.888 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'BlockDropGrammar'
23:06:35.888 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type BlockFamily: not a supported type or MappedContainer
23:06:35.888 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:ActAsBlock.block'
23:06:35.888 [main] ERROR o.t.p.typeHandling.Serializer - No type handler for type interface org.terasology.world.block.family.BlockFamily used by class org.terasology.world.block.regions.ActAsBlockComponent::block
23:06:35.929 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Animation'
23:06:35.930 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Spawnable'
23:06:36.307 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "aws888Qr0JUpTPfvDbuVin8jZmIZakzI"
23:06:36.768 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:air]
23:06:36.768 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:air with id 1
23:06:37.389 [main] INFO  o.terasology.spawning.SpawnerSystem - Grabbed all Spawnable entities - got: []
23:06:37.389 [main] INFO  o.terasology.spawning.SpawnerSystem - Full typeLists: {}
```

Or is it likely something else / am I doing something wrong? Some of the related code is getting kind of old.

**Comment by immortius** [comment]
@flo

Explicitly registered formats are expected to be eternal unless explicitly unregistered. Formats registered via the annotation are automatically cleaned up and recreated.

Based on that, unless a reference to the old format can be obtained/retained it would probably be easier to use the annotation and set context up to be injected.

**Comment by flo** [comment]
@immortius 
The only time when you can specify a ClassFactory for the ModuleAwareAssetTypeManager is when it gets constructed. So the only Context I can pass at that time would be the engine Context which does not contains the ComponentLibrary of the loaded game.

**Comment by flo** [comment]
#1819 may fix it, I haven't tested it yet as I am unsure how.

**Comment by Josharias** [comment]
I checked out Portals/Spawning.  Those issues had to do with other json problems and have since been fixed and pushed.

**Comment by Cervator** [comment]
Much appreciated :-)
