### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Lynwood** [MovingBlocks/Terasology#1830]
I'm using the latest download of Omega, dated July 10, 2015.  It was crashing in the x64 bit version, so I tried the x86 version, it too crashed.  I'm new to this, I told the crash reporter to upload the crash logs to google drive...not sure if I have to cut and paste here..or if the reporter tells you where they are..?

Just trying to help, if there is anything you need to be of more assistance, let me know and I will try to provide it for you...

Thanks for a beautiful program.

Lynny

**Comment by Cervator** [comment]
Hi @Lynwood - yep we still need the link. Or at least it would be easier with the link, we might be able to dig through and find the exact one. Also be sure you're uploading all relevant logs, the crash reporter should be showing you several, the error could be in any one :-)

It also would help to have you describe what you were doing when the crash occurred.

Latest omega develop build has some broken modules in it, so it isn't super suitable for play. Stable release 55 is better, even if it is lacking a fair bit of recent effort: https://github.com/MovingBlocks/Terasology/releases/tag/stable55

And thank you for the kind words!

**Comment by Cervator** [comment]
Hey @Lynwood if you're still around give the new release a try: https://github.com/MovingBlocks/Terasology/releases/tag/v0.54.0

That should both be more stable and better updated than the last build you tried :-)

I'm going to close this as either potentially resolved or too vague without further detail, but feel free to re-open or submit a new issue if you can find problems in the latest release
