### ISSUE TITLE
Various issues in Josharias Survival

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1854]
Tested around for a while and found some issues to document - some may relate to recent changes, unsure. Ping @Josharias :-)

- [x] Picking blueberries gets no blueberries :-(
- [ ] Trees look a little ... odd (1)
- [ ] Some issue gets logged every time you open the inventory / assembly table / click 'i' again with it already up. Seems benign though (2)
- [x] With the inventory (and all the text) visible some sort of entity creation loop kicks in. I was stable at 200 without, then opening it made hundreds of entities generate and then get garbage collected a la memory stats (which were also impacted). Closing the inventory makes the entity count go back to normal (after a moment)
- [x] One time a severe performance issue triggered while auto-saving. Unsure if it relates to the entity count (both screenshots I got only show 200-300 entities, but the lag was causing UI updates to be rare). During saving the game would slow to a crawl, with the save process taking longer than normal (30 seconds?). After completion game went back to normal. Had the inventory screen up. (3)

(1)

![terasology-150726174624-1152x720](https://cloud.githubusercontent.com/assets/1063833/8896078/59bec54e-33be-11e5-820f-19e49134eb46.jpg)

(2)

```
17:27:36.871 [main] ERROR o.t.w.b.internal.BlockManagerImpl - Family not available: ManualLabor:Sifter
17:27:36.871 [main] ERROR o.t.w.p.i.InventoryOutputComponent - EntityRef{id=0} DisplayNameComponent not found
```
(3)

![terasology _ pre alpha_2015-07-26_17-04-00](https://cloud.githubusercontent.com/assets/1063833/8896097/2b755620-33bf-11e5-9d40-45783dbdaae0.png)

**Comment by Josharias** [comment]
I hope to resolve some of these soon.  Day job has us on crunch mode.

The trees are indeed odd.  I already had one usuccessful hunt for the cause of the always-inside-out tree trunks. :(

**Comment by Cervator** [comment]
Ouch, sorry to hear! But hang on there, RL as usual comes first. Thanks for the updates :-)

**Comment by Josharias** [comment]
- Picking blueberries gets no blueberries :-(
Fixed in https://github.com/Terasology/SimpleFarming/commit/a0642a8a9bd15d26ac3063864ff5a0ada07cf83d

**Comment by Josharias** [comment]
- One time a severe performance issue triggered while auto-saving

Possibly fixed by using non-persistent entities in https://github.com/Terasology/Workstation/commit/a78e4c9c7342b63bfcb916957ac801c9967d9dad

- With the inventory (and all the text) visible some sort of entity creation loop kicks in.

Should be an ok level of entity creation by only checking valid inputs every 200ms in https://github.com/Terasology/Machines/commit/728c915a41bb000766bd3e1316e307c0da9f412c

**Comment by Cervator** [comment]
Thanks for the attention and tweaks, none were crazy bad and good enough for the rest to know you're aware. Going to close this as fixed enough and try to release this weekend :-)
