### ISSUE TITLE
Input settings went wonky size-wise again

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1858]
We've hit this before - something causes the input settings screen to have some of the buttons max their fill or something so they become huge:

![terasology _ pre alpha_2015-07-26_18-16-03](https://cloud.githubusercontent.com/assets/1063833/8896201/acfe0f54-33c2-11e5-9df9-714a3fa8d37c.png)

Probably an easy fix (and we've fixed it before)

**Comment by immortius** [comment]
Dupe of #1759

**Comment by Cervator** [comment]
Yep, I even have them both in the milestone. Doh. Shows about how long my memory lasts and puts a dent in the organic search engine bit :-)

**Comment by Cervator** [comment]
Fixed!
