### ISSUE TITLE
Headless server + solo legally blind client = no visible chunks

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1859]
Pretty sure this has been noted before with @minnesotags' server, but on there with pre-alpha release 55 chunks did eventually become visible by a client. Testing just now I waited a minute or two without having any visible blocks in the world. Yet the world *has* generated fine, I can walk around, place things, throw torches, etc.

A hosting player + client player doesn't have the same problem, world is visible immediately.

**Comment by Cervator** [comment]
Bump - @immortius or @flo could either of you check if this happens for you and if so theorize on what's wrong? Would be good to get fixed for the next release.

**Comment by flo** [comment]
I only see nothing as a headless server client if I change the viewing distance to the smallest value.

Then the server sends only 3x3x3 chunks and the client needs 5x5x5 chunks to make the first visible.
See #1886 for details about the absurd high numbers of chunks needed to show the first chunk.

**Comment by Cervator** [comment]
Going to mark this as a "Known issue" (I know, weird label) in general and close it as a near non-issue. After additional clarity and testing it is a very minor impact with a workaround available with adjustments/fix coming eventually via #1886.

Workaround: Amusingly if you join a headless server with a non-legally blind client it forces enough chunk loading for the legally blind player to see stuff :-)

At that point said legally blind player can move around normally since enough chunks have been "primed" around the player to keep going.

Caveat: Second player should be within distance to have their chunk coverage affect the legally blind player (at least once)

**Comment by flo** [comment]
Reopening as it wasn't fixed.
