### ISSUE TITLE
Overriding loading screen does not work with new asset system

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1865]
Before new assert system was in place, it was possible to override the loading screen by adding a file  `\overrides\engine\textures\loadingBackground.png` in a module. This doesn't work anymore - see https://github.com/Terasology/PolyWorld/issues/8

I think that this issue is actually about two different things:
* Fix the broken block texture discovery process. The exception seems to be triggered by `AssetType.getAvailableAssetUrns()` that lists `engine:loadingBackground` as a *BlockTile* resource, which it isn't.

* Re-implement the custom loading screen functionality - maybe through a module extension or a default image file that is searched for? Maybe restricted to gameplay modules?

**Comment by immortius** [comment]
Discovered two issues from this:
1. Overrides were not correctly being filtered by type, so any png in any override subdirectory was being applied as a blocktile (for example).
2. There trick used to default font textures to have nearest filtering and other textures to linear was blocking support for overrides for those formats.

I'll push out fixes for these.

**Comment by immortius** [comment]
Fixed by #1867
