### ISSUE TITLE
Remove executable file permission for Java files

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1899]
Surprisingly, many source code files have the `+x` permission set in git. A full list can be obtained by running:

    git ls-tree -r HEAD | grep 100755

Assuming that this is not intended, I suggest resetting the file permissions to 644.

**Comment by Cervator** [comment]
Not intended, but probably also never really thought about. Outside of having the executables executable on Linux I haven't considered any special file-level anything .. ever, really :-)

Oh, maybe whether a few tricky file extensions are binary or text for a .gitattributes.

Expecting this would cause a mega-commit touching a ton of files currently with pending work do we even want to worry about it? Can anything bad really happen if a .java is executable in some developer's Linux workspace?

Maybe if we run into a different need to touch a very large amount of files we could do this at the same time? Speaking of we should probably have a milestone to assign that kind of stuff to for future reference.
