### ISSUE TITLE
Various Translation Issues

### ISSUE THREAD

**Issue by immortius** [MovingBlocks/Terasology#1910]
Missing translations
- [x] Title of Player Settings screen
- [x] Title of Video Settings screen
- [x] Title of Audio Settings screen
- [x] The tabs at the top of the Join Server screen seem to appear in german rather than english

Suggestion:
- [ ] Highlight text missing translation in red?

**Comment by msteiger** [comment]
Maybe also interesting to @Halamix2

**Comment by Halamix2** [comment]
Everything should be fixed now

**Comment by Cervator** [comment]
I've already forgotten what the plan was to merge in translations. Local develop on the Weblate server --> develop here or merge in the weblate branch akin to a PR? :-)

**Comment by Cervator** [comment]
Fixed by #1915 - closing as complete

@msteiger / @Halamix2 - either of you interested in trying something out to highlight missing translations? Maybe red for missing entirely (problem in a translation file - missing line) and yellow for missing translation (key present in translation file but no value added yet)

**Comment by msteiger** [comment]
I first thought that using `develop` might be preferable, because translation commits would always be on top of latest code changes.

However, this makes it difficult to review. Maybe we should file a feature request for different fetch/push branches!?

**Comment by Cervator** [comment]
I'd just maintain a weblate branch like with the launcher, honestly. Then merge translations occasionally and at the same time refresh the weblate branch. Could be fancier but it is nice and easy :-)

**Comment by msteiger** [comment]
Alright - Weblate is using the `weblate` branch here on MovingBlocks for new translation commits.
