### ISSUE TITLE
Copying Components fails for some class names

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1924]
The Cities module has several facet providers, which all have a
```java
private static class Configuration implements Component
```
Starting the game with Cities currently fails because those config components cannot be copied. Renaming them to unique names seems to resolve the issue. Some debugging revealed:

* In CreateWorldEntity the world gen. components are added to the world entity
* The ReadWriteStorageManager is notified and delegates to EntitySetDeltaRecorder
* In ESDR.onEntityComponentChange() the entity mgrs. ComponentLibrary is used to copy components
* The AbstractClassLibrary.classLookup map does not contains an entry for the class

I think that it's caused by the fact that their `ComponentMetadata` share the same URI. The AbstractClassLibrary uses this URI in a lookup table. 

This could be fixed if the URI  also reflected the outer class if present. I *believe* that all(?) component class names are generated through MetadataUtil.getComponentClassName().

So maybe add a check for `componentClass.getEnclosingClass()` and concatenate if it exists? Unsure if the  default `$` should be put in between then.

**Comment by immortius** [comment]
Component class names are expected to be unique within a module. This is
required by the persistence and prefab systems.

I guess I would mark this as documentation that needs to be included. I
don't think it needs to be fixed - static inner components is a strange use
of the entity framework in the first instance.
