### ISSUE TITLE
Support complex components

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1945]
I'm currently re-writing the Quests module and designed the following format to define player quests:
```json
"Quest" : {
    "shortName" : "TestQuest",
    "tasks" : [
        {
            "id" : "collectDirt",
            "type" : "CollectBlocksTask",
            "data" : { "amount" : 3 }
        },
        {
            "id" : "returnHome",
            "type" : "GoToBeaconTask",
            "dependsOn" : ["collectDirt"],
            "data" : {  }
        }
    ]
}
```
The different parts of a quests (=tasks) are nested inside a single quest component, because different instances of a class can exist. For example: collect 3 dirt blocks and 2 wood blocks.

This is not yet  working,  because the `tasks` element are not parsed (no entry in type serialization library?) even though a default Gson instance can read it just fine.

Also, the factories to convert `type` and `data` json into actual `Task` implementations need to be manually added the because ModuleEnvironment.getSubtypesOf() method is not available for modules.

Ideas? Feedback? Sending a ping to @nh-99 @MarcinSc @Josharias  and @immortius.

**Comment by nh-99** [comment]
That looks much better than when I did it. My original code was basically something I threw together that worked. I like the formatting of that and think that the hierarchy of dependence is great.

**Comment by immortius** [comment]
You probably just need to put a ```@MappedContainer``` annotation on whatever class you use to hold task.
