### ISSUE TITLE
A fatal error occured while the game was booting up

### ISSUE THREAD

**Issue by flashmanX** [MovingBlocks/Terasology#1949]
Terasology -init.log 
Fatal error occured message 
Run-time exception: Cannot initialize graphics device. 
(I am a noob at computers)

**Comment by Cervator** [comment]
Hi there - unfortunately that error suggests you may be out of luck

`Cannot initialize graphics device`

That means your video card likely isn't good enough :-(

There's a small chance a driver update may help, or if you have a relatively new and powerful video card there could be a more specific error hiding deeper in the log. Posting all available logs (via https://gist.github.com, pastebin, or some other service) is ideal, just in case.

**Comment by flashmanX** [comment]
It was that my graphics card needed updating. Thanks for responding! :) 
Terasology is awsome!

**Comment by Cervator** [comment]
So a new driver worked? Awesome! You're in luck then, that rarely works, but good to know it does occasionally :-)

And thanks!
