### ISSUE TITLE
java.lang.IllegalStateException: Data is not an array

### ISSUE THREAD

**Issue by ariasemis** [MovingBlocks/Terasology#1960]
https://docs.google.com/uc?id=0B5l2RT_UOCXRdEt4bmU4ZVIzczQ&export=download

**Comment by Cervator** [comment]
Hi @ariasemis - there are probably more log files than just that one, which doesn't have any useful crash info in it. Also, what were you doing when it happened? The more detail you can supply the better :-)

**Comment by ariasemis** [comment]
Hi!
Sorry for the lack of info, the crash happened right after creating a new
map, in loading screen.
I uploaded the log files from game's report tool, so i thought all files
were there. Sadly I didn't save them.

If it happen again i'll make sure to supply as much info as i can.

Thanks for replying

2015-10-04 15:25 GMT-03:00 Rasmus Praestholm <notifications@github.com>:

**Comment by Cervator** [comment]
Yup please let us know :-)

By chance did you enable *all* the modules or anything like that? That often leads to problems.

**Comment by emanuele3d** [comment]
This issue keeps cropping up. Not the crash, but people sending only one
log.

Question 1: is this because they are not using the crash reporter?
Question 2: can we add the anonymised location of the other logs at the end
of this log with a small sentence "In case of problems please send us these
other logs too!"

Manu

**Comment by emanuele3d** [comment]
Also this seems to keep cropping up. Is there an "Enable All" button that
perhaps we should remove? Or should perhaps an alert popup if all modules
have been selected warning the user: "Be aware that not all modules might
be compatible with each other. Enabling all modules indiscriminately might
increase the risk of crashes."

**Comment by Cervator** [comment]
We removed the "Enable All" button a little while ago for this very reason, heh :-)

Module selection / compatibility could be hardened further, as could how well the CrashReporter handles the individual log files

**Comment by Cervator** [comment]
I was looking at the exact places this text ("Data is not an array") shows up, thinking about adding more details to it, but while that might be more helpful when we get a partial report like this it would probably still be useless without the exact stacktrace. And if we have the stacktrace we don't need the additional details in the text.

I'm going to close this as too incomplete to to troubleshoot but @ariasemis feel free to re-open or submit a new issue if it happens again.

I submitted https://github.com/MovingBlocks/CrashReporter/issues/22 as a reminder to make the CrashReporter more user friendly still.
