### ISSUE TITLE
Apply improved spawning algorithm to Perlin (and others?)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1973]
PolyWorld's island map and Cities both now spawn the player intelligently in a suitable spot. Perlin still has a bad tendency to leave the player facing a wall in a ditch and still occasionally under water.

We can probably improve this in some similar fashion to improve initial presentation of the game

https://github.com/MovingBlocks/TeraMath/blob/develop/src/main/java/org/terasology/math/geom/SpiralIterable.java is available to provide positions to check one by one in an intelligent fashion until a suitable spot is found (flat or mostly flat ground, no cliffs, water, or tree tops)

**Comment by msteiger** [comment]
This one is on my list already - be it through a different approach. I'd like to enhance the `EnsureSpawnableChunkZero` surface modifier to flatten the area around 0/0, not just a single block.

**Comment by Cervator** [comment]
Sounds good to me, although some of the ravines you can start in might flatten sort of weird :-)

Thanks!

**Comment by Josharias** [comment]
Please do revamp the EnsureSpawnableChunkZero, it was a knee jerk reaction from when one had to spawn in 0,0,0.  I don't think technically it is needed anymore as WaS made it possible to spawn in any chunk.

**Comment by Cervator** [comment]
Oh just realized this is done now. We could re-whack the old class on this issue (I brought it back so Cities would compile, that's no longer a problem) and close it as complete.

LandsOfTerra may still use the old class but isn't in the lineup and I'm not sure if it will be coming back. @esapetri you out there?
