### ISSUE TITLE
Crash upon Windows 10 networking security prompt completion

### ISSUE THREAD

**Issue by reilly3000** [MovingBlocks/Terasology#1987]
I got a popup from Windows Defender asking about network access for Teresology. I approved it and the game crashed after the dialog closed.

**Comment by reilly3000** [comment]
I got another crash after that : ( here is the log from the second one: http://pastebin.com/m7D55bSk

**Comment by reilly3000** [comment]
I tried disabling all plugins and got the same issue: http://pastebin.com/9Mn7HEph

**Comment by reilly3000** [comment]
It seems to be related to the city generation module. I was able to start a game effectively by selecting a different generator.

**Comment by msteiger** [comment]
Thanks for the report. It looks like one of the files was still in use - maybe from the previous launch? If you disable all modules, the City World Generator should no longer show up.

You closed the issue - does it work for you now?
