### ISSUE TITLE
"auto" blocks unavailable via in-game console, blocks also missing from listBlocks [$5]

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1988]
I'm not sure if this is an asset or console bug. Maybe console as auto blocks *do* work if used from `PlayerStartingInventorySystem` to grant said auto blocks to a player. You start with a stack of companion cubes (in a chest), which is an auto block, but you can't do `giveBlock companion` in the console

Console command "listBlocks" also doesn't seem to be catching all blocks, auto or not. For instance with Minerals enabled (which has a large amount of regular blocks + auto blocks) not a single one gets listed by listBlocks. While that might be because none have been assigned a block id yet (lazy assigning?) we should probably still list their generic name.

Pinging @Limeth if around and interested :-)

**Comment by Waterpicker** [comment]
I did some tests with the giveBlocks command. When I type out companion's fully name 'core:companion' it works. Continuing investigation on why this works and not just 'companion'.

**Comment by Waterpicker** [comment]
Well I discovered a few things about the bug. When you just type companion, It spats back 'Companion:companion' instead of 'core:companion'. If you use core:companion it work perfectly fine. Also the listblocks command worked for me. It showed core:companion.

**Comment by Cervator** [comment]
Here's a bit of a copy paste from earlier additional thoughts on IRC:

> the asset system essentially boils down to giving you a way to refer to resources in a module:asset format
> the asset's location matters, so stuff defined in /blockTiles is a block tile, and so on. There is an extra hook for considering block tiles in an "auto" dir - they get a generic block definition magicked up so you don't have to write a separate .block file for it
> at the same time there are ways to refer to assets in a short format, so if you have a `VerySpecificDirtBlock` in some module `X` you can `giveItem VerySpecificDirtBlock` without calling it `x:VerySpecificDirtBlock`
> i think there is something wrong with auto blocks in that area
> maybe somehow auto blocks get registered with the wrong prefix `blockName:blockName` instead of `module:blockName`
> it might in the end be a single variable name change somewhere - super easy - but i can't theorize deeper without starting to dig through it myself :-)
