### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by IPv6** [MovingBlocks/Terasology#1990]
Game constanlty crashing on single player mode start.
I didn`t change anything - just download with launcher (stable and release tsted - same error in both), hit play ->singleplayer->create->create.
Crahes after "Waiting for player to spawn"
Log: http://pastebin.com/3aMkuf2P

**Comment by msteiger** [comment]
Thanks for your report. This is probably a duplicate of #1986.

The other world generators / gameplays should work fine.

**Comment by Cervator** [comment]
Hi @IPv6 - this should be fixed in the latest develop build now :-)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
