### ISSUE TITLE
Terasology crashes on startup

### ISSUE THREAD

**Issue by OCmylife** [MovingBlocks/Terasology#2013]
http://pastebin.com/QEfZbz4y

Packages:

Java: Oracle-jdk-1.8.0.66

Portage 2.2.20.1 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/gnome/systemd, gcc-4.9.3, glibc-2.21-r1, 4.3.0 x86_64)
=================================================================
System uname: Linux-4.3.0-x86_64-Intel-R-_Core-TM-_i5-2500K_CPU_@_3.30GHz-with-gentoo-2.2
KiB Mem:     8133256 total,   1200700 free
KiB Swap:    4194300 total,   4194300 free
Timestamp of repository gentoo: Thu, 19 Nov 2015 11:00:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p39::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.17::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo

I don`t see an error message though, which could be related, that the game would not start.

**Comment by OCmylife** [comment]
I fixed this through installing openjdk. Maybe my Oracle-jdk-1.8 installation wasn`t compatible with Terasology

**Comment by Cervator** [comment]
Thanks for the detailed report! Glad you could resolve it :-)

Odd issue too.

**Comment by OCmylife** [comment]
Unfortunately Java wasn't the issue. Xrandr wasn't installed. Maybe it's
possible to edit the script to check for dependencies?
Am 19.11.2015 4:52 PM schrieb "Rasmus Praestholm" <notifications@github.com

**Comment by Cervator** [comment]
Interesting, good to know. At least we could probably add a note about Xrandr somewhere as a common issue. I imagine it is more of an LWJGL topic though than anything Terasology specific. It might be possible to script *something* but I'm unsure what (in a portable fashion) or who might have the time, skill, and OS availability to do it.

Unless maybe you're up for trying something out ... :-)

**Comment by skaldarnar** [comment]
What do you need xrandr for? I didnot havea look at the full log, but I don't get the connection between TS and xrandr. ..
