### ISSUE TITLE
Add dimensions to view distance naming and enhance further

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2028]
~~This has come up now and then but we don't have an explicit issue for it.~~

~~We should clarify the naming for our view distance levels, both to make them clearer to understand and easier to translate. Additionally we need to put a warning on the top two settings or so.~~

~~Probably there's an Enum or something somewhere, I forget how it works, but it should be contributor friendly in any case~~ Done :-)

Add chunk dimensions to the UI label: Switch "Minimal" to "Minimal (5x5x5)" - loading the dimensions from whatever the view distance actually is configured with, so the text will remain accurate if we change the stats.

Optional: Leave an option to mark a setting as "demanding" indicating it'll only work for high-end computers or even only for testing (not realistic for typical play). If a setting is marked as demanding put an asterisk by the name, make it bold, color it red, or all of those together. If the player selects such a setting expose a label in the menu UI somewhere to warn the player with something like: "Warning: You have selected a very high view distance. This may cause severe lag or even crash the game"

Optional: Find a way to include a "Custom" view distance naming that when selected will expose three text fields accepting numbers so the user can specify exactly how many chunks to view for every axis.

Mildly related to #1144
##

**Comment by MottaTheHutt** [comment]
I started looking into this, and getting the values to display is pretty straightforward. The way I have it set up right now causes the dropdown to be blank when you first load the screen though.

![untitled](https://cloud.githubusercontent.com/assets/6486092/14374441/798b6e50-fd1b-11e5-9097-26b04bd81472.png)

After that's solved, thinking up a new name scheme shouldn't be hard. Something like:

- Minimal
- Low
- High
- Medium
- Higher
- Highest (Ultra?)
- Extreme

**Comment by Cervator** [comment]
Huh, I could've sworn I replied to this, I remember writing up a comment. Maybe never submitted and closed my browser? Or I did it elsewhere. Weird.

Real quick: Have you tried deleting config.cfg to see what happens? Sometimes having an old config.cfg when making config-related changes can hit unexpected

On the naming I wrote up a little suggestion essentially going with 5 levels (minimal, low, moderate, high, ultra or what not) + a custom option that would expand 3 labels + text fields to let the user enter a number for each dimension. Mega and Extreme are more for testing than playing, but a custom option would cover that + make nutty players happy.

That may be a little trickier since we couldn't cover that purely with an enum. Probably should also come with a warning of some sort (maybe an on-hover or something that only pops up when total chunks > some high number)

**Comment by MottaTheHutt** [comment]
You're right, you did reply in #2058. I sort of did a double post, as these issues overlap. My bad.

**Comment by Cervator** [comment]
Aha so I'm not insane! Or at least not for that reason. Phiew :D

**Comment by Cervator** [comment]
Bump - clarified the updated purpose of this issue to be just the chunk dimensions (naming has been changed) with a couple optional items.

@MottaTheHutt - poke! You already got that working but then we drifted away from the topic. Still got the code handy or want to redo it real quick? :-)

**Comment by rzats** [comment]
Closing as implemented by #2631.
