### ISSUE TITLE
Main menu fails to display special characters (Polish example)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2029]
Noted by @Halamix2 with #2027 

Example snippet from the Polish menu .lang file:

`"create-game-title": "Utwórz grę",`

From https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/i18n/menu_pl.lang#L41

Yet in display in-game the special character `ę` is missing

![polishspecialcharmissing](https://cloud.githubusercontent.com/assets/1063833/11448712/2d42e32c-952c-11e5-8dde-4f1bb0cb6812.png)

The character shows fine in the .lang file in IntelliJ (and in a Jenkins workspace too for that sake)

**Comment by msteiger** [comment]
If I remember correctly, the screen titles are still using the obsolete `title` font, which does not support these characters. We should replace it with the new Noto font.
