### ISSUE TITLE
Terasology crashes

### ISSUE THREAD

**Issue by chrisw138** [MovingBlocks/Terasology#2032]
I cannot get Terasology to initialize.  I add modules and create the world, but it won't go into the world.
[Terasology-init.txt](https://github.com/MovingBlocks/Terasology/files/49975/Terasology-init.txt)

**Comment by msteiger** [comment]
Do you have any other log files? Which world generator did you use?

**Comment by Cervator** [comment]
My guess: memory issue

`Max. Memory: 247 MiB`

The game isn't being launched with enough available memory. The launcher should allow you to configure a higher amount of memory to make available. Alternatively you can launch straight from the game .exe which should default to 1 GB of memory IIRC.

**Comment by Cervator** [comment]
Closing from lack of follow-up.
