### ISSUE TITLE
Final bit of font tweaking

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2042]
Follow-up to  #2036 - we should delete the outdated `default` and `title` fonts and verify that they're not in use anywhere else like in modules (I saw hits in InGameHelp, JoshariasSurvival, and ManualLabor but am unsure if they're legit)

We also need either a medium size Noto for sub-headings or the ability to scale fonts dynamically.

**Comment by msteiger** [comment]
The default text font size is 20, the font size for captions is 52.
I went for the average (36) for the medium-sized one:

![image](https://cloud.githubusercontent.com/assets/1820007/11634644/1103984e-9d12-11e5-8c5b-fb21ae55550e.png)

What do you guys think?

**Comment by Cervator** [comment]
Wow, normal is 20? I thought it would be smaller than that.

Looks fine to me at 36, although yeah long-term it probably would be nice to have options to scale things more exactly.
