### ISSUE TITLE
Clear out remaining (old) deprecations

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2043]
_Edit: Moved to v2.0.0 as v1.0.0 was released. The engine and Core entries may not be doable early_

Before we go v1.0.0 with engine we should clean out the remaining spots where code uses deprecated methods from elsewhere in engine, and finally delete those methods. That way we have a clean slate to start the major release with where any future deprecations will stand out better.

_Deprecation warnings in engine + standard module lineup_
- [ ] engine: 17
- [ ] Core: 1
- [ ] SimpleFarming: 1
- [ ] Maze: 3
- [ ] MarkovChains: 1
- [ ] WeatherManager: 3 (okay, technically not in the lineup but I have it in my workspace)
- [ ] ItemRendering: 1
- [ ] CustomOreGen: 2
- [ ] Pathfinding: 5
- [ ] JoshariasSurvival: 1
- [ ] ClimateConditions: 2
- [ ] LightAndShadow: 10
- [ ] Miniion: 4 (but we might as well retire that one entirely already)
- [ ] BlockPicker: 1
- [ ] AnotherWorld: 14
- [ ] GrowingFlora: 12
- [ ] WoodAndStone: 3

Pinging @msteiger @Josharias @MarcinSc @synopia 
##

**Comment by Cervator** [comment]
Engine cleared up some by #2062

**Comment by skaldarnar** [comment]
Clearing out deprecations is something we should do with an upcoming revive, but the information in this ticket is likely outdated, thus, closing it.
