### ISSUE TITLE
Easier way to run game at minimal settings / visual guide 

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2058]
Had a user request on Youtube for a more visual guide on lowering graphic settings (due to language barrier - we don't have Arabic translated yet). So I thought I'd put some screenshots here for now.

Maybe at least we can put this in a wiki guide instead of in an issue, and at most find a way to run with minimal settings - maybe a single button in settings / video settings that'll set everything at minimums, and/or a command line flag to load at all minimums?
- [ ] Throw updated screenshots on a wiki page
- [x] Clarify the preset names
- [x] Make the preset dropdown more prominent
- [x] Disclaimer that the present doesn't change view distance
- [ ] View distance needs name review / #x#x# style stats listed for number of chunks loaded

![step1](https://cloud.githubusercontent.com/assets/1063833/11768952/869d96e4-a1aa-11e5-8a8f-2344efc46de6.png)

![step2](https://cloud.githubusercontent.com/assets/1063833/11768953/8941ff16-a1aa-11e5-95e7-689140ee0fe1.png)

![step3](https://cloud.githubusercontent.com/assets/1063833/11768954/8b542bf8-a1aa-11e5-94c9-31e80ba96aaf.png)

![step4](https://cloud.githubusercontent.com/assets/1063833/11768956/8da22338-a1aa-11e5-9e4b-4601a04174ab.png)
##

**Comment by skaldarnar** [comment]
Ideally the _minimal_ preset should just be the set of settings for lowest settings. Maybe we can make the preset selection more prominent, placing on top and across both columns? 
And of course, find more people for translations to all the languages!

**Comment by MottaTheHutt** [comment]
Like so? I moved preset out of "Window/Graphic Settings" because it modifies fields outside of that category.

A checkbox requiring you to explicitly enable custom settings could also help clarify.

![untitled](https://cloud.githubusercontent.com/assets/6486092/14306066/e9c6e468-fb88-11e5-80a8-3048117e5044.png)

**Comment by Cervator** [comment]
@MottaTheHutt definitely more prominent! :D 

Feel free to change the preset names while you're in there. The base preset name should be easy to translate.

View distance similar + need #x#x# style stats listed. 

Maybe the preset label should indicate it doesn't change the view distance?

There are a few related tweaks needed in the area :-)

**Comment by Cervator** [comment]
Added a todo checklist with 3 items now covered after @MottaTheHutt's PR #2279 :-)

**Comment by MottaTheHutt** [comment]
I have it so the chunk values are displayed. There's one issue where the view distance field is blank the first time you load the game. Not sure if this is an issue, or just a side effect of the values being updated.

![untitled](https://cloud.githubusercontent.com/assets/6486092/14374441/798b6e50-fd1b-11e5-9097-26b04bd81472.png)

After that's solved, thinking up a new name scheme shouldn't be hard. Something like:

- Minimal
- Low
- High
- Medium
- Higher
- Highest (Ultra?)
- Extreme

**Comment by Cervator** [comment]
@MottaTheHutt try deleting `config.cfg` then reloading the game? When you change config related stuff sometimes having an old version of the file can make stuff messy.

Maybe rather than having a full 7 ranges we should stick with, say, 5 (minimal, low, regular, high, ultra) and leave a "Custom" entry that when selected expose 3 small text fields with labels for setting your own x y z dimensions? Really the Mega and Extreme ranges are more for testing chunk-related changes than for serious gameplay (they'll choke out just about any system)

Custom would make sense for both testing and to let crazy users go nuts, although it might be trickier to work with (can't set as an enum)

**Comment by MottaTheHutt** [comment]
That didn't do the trick. I'm not even sure it's an issue, as it only happens the first time the game is loaded after the change. Even if you close the game without setting a value, it will be populated the second time you load the game.

It looks like `setViewDistance` in `RenderingConfig.java` might be where this is happening.
`ViewDistance oldValue = this.viewDistance;` is resulting in oldValue being set to null, if my thinking is correct.

Replacing the highest two settings with a custom setting would also help simplify a bit.

As for implementing a custom view distance without using an enum, that's something I can try and figure out. I notice the video presets use enum, even though there's a custom option. Not sure if a similar approach would be possible/desirable with view distance or not.

**Comment by jdrueckert** [comment]
Preset setting has been made more visible (although the presets don't yet change all the underlying settings to a sensible value yet - tracked in #3762 ). Also, we do have an arabic translation now (although not all of the entries have been translated yet). Furthermore, this issue was last updated in 2016.
