### ISSUE TITLE
Stone dust

### ISSUE THREAD

**Issue by t3hk0d3** [MovingBlocks/Terasology#206]
They basic idea what stone should leave something after it has been broken.

After breaking rock block there is 1/7 of stone dust created, which have very high viscosity liquid dynamics.

Rock dust is penetrable unti 4/7, but reduce player movement speed slightly.

Player could collect stone dust using shovel and bag, and unload it into minecart.

**Comment by Cervator** [comment]
Closing in favor of a bullet point in the backlog thread: http://forum.terasology.org/threads/backlog.1101/
