### ISSUE TITLE
Follow-up tweaks for input mappings (PR #2060)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2064]
I noticed some items during testing and wanted to highlight them for later work :-)

- [x] Layout on the new screen is a little funky (buttons not limited to the usual size - seems more like they're expanding to take up max space). Already mentioned as known in the PR
- [x] If you open the secondary mapping for a key the label for the key name is empty (primary mapping displays the label just fine)
- [x] Doesn't appear like any fields under input settings or the new input binding screen are being translated if a different language is selected (probably pre-existing issue?)
- [x] If the primary mapping for a key is removed the value from the secondary mapping moves into the primary mapping's spot. That's probably not desirable as you might well want to group primary/secondary keysets and this would mix them up
- [x] Reset to defaults sets mouse sensitivity to 0. Which means you can no longer look around in-game :-) (probably also pre-existing?)

**Comment by msteiger** [comment]
I'm working on the remaining issues now.

**Comment by msteiger** [comment]
What do you guys think of this layout?
![image](https://cloud.githubusercontent.com/assets/1820007/12257049/33e4c1fa-b903-11e5-9561-598561204f72.png)

**Comment by MaloJaffre** [comment]
I think you can add a cancel button but this layout is good for me.

**Comment by Cervator** [comment]
Yeah cancel button makes sense :-)
