### ISSUE TITLE
Support letter-jumping in the module list

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2077]
We have super neat auto-completion in the console, but still have to manually scroll around in the growing module list like some sort of internet barbarian :-)

We should support the use of module starting letter(s) jumping the scroll to the first valid matching module.

Bonus: Search or filter box to limit the displayed modules.

**Comment by msteiger** [comment]
I suggest adding a small text box that takes a (camel-case) search string instead. As the user types into the text box, the list of modules is filtered down to those that match the search string.

**Comment by Cervator** [comment]
Sounds good. Anything that makes the growing list more navigable :+1:

**Comment by MaloJaffre** [comment]
I've wrote a (temporary) substring matcher which can be used to filter modules names or anything else.
See https://gist.github.com/MaloJaffre/ef05ae25f631c7eb3a12

**Comment by msteiger** [comment]
Good start! There's already [org.terasology.utilities.CamelCaseMatcher](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/utilities/CamelCaseMatcher.java), which is used to complete  commands in the console. Press `F1` to open the console, e.g. type `setH`, press `TAB` and it will auto-complete or suggest matching commands.

**Comment by MaloJaffre** [comment]
Oops, I hadn't seen that, but I think my implementation can be more efficient with a case-insensitive-sorted list, because it returns a contiguous sublist and doesn't use an inefficient regex.
However, the camel-case completion is very cool.
I think we can add my method in this class for perfomance-sensitive usages or for large lists.

**Comment by Cervator** [comment]
Closing as fixed by #2222! The filtering works great and is much better than letter jumping.
