### ISSUE TITLE
Crashed...

### ISSUE THREAD

**Issue by Trinob** [MovingBlocks/Terasology#2081]
I selected all of the mods, and it loaded but then it crashed.

**Comment by Cervator** [comment]
Hi @Trinob - you can't run with all modules together. That's way too much stuff and some will clash with others.

Use the gameplay template drop-down to pick a set of matched modules that'll work together for sure. Picking individual modules is more for when you've examined what they do (looked at documentation or code) and want to experiment to see if something works.

Try JoshariasSurvival for instance, it has an in-game help system :-)
