### ISSUE TITLE
Extra entity events when loading game

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#2087]
Here is a sample output from my test game (with extra info added by system to expose the issue):
```
22:31:20.685 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "hkNG4i9RrZnxArmtteZvybL2IDEOoHsD"
22:31:21.650 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (3, 41, 0)
22:31:21.679 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:31:21.768 [main] WARN  o.t.l.nameTags.NameTagClientSystem - Can't create player based name tag for character as owner has no client component
22:31:21.770 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Moderate
22:31:21.777 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (3, 41, 0)
22:31:21.799 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (3, 41, 0)
22:31:21.801 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (4, 41, 0)
22:31:21.802 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
```

The first two events are correct, however the remaining two are just waste of CPU.

Sometimes however it gets even worse. After the initial correct series of "activate", the additional deactivate+activate are issued in incorrect order (activate then deactivate), like here:
```
22:49:52.312 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:49:52.399 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (5, 41, 0)
22:49:52.452 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (4, 41, 0)
22:49:52.464 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (4, 41, 0)
22:49:58.432 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Activated component for block: (5, 41, 0)
22:49:58.435 [main] ERROR o.t.n.e.s.EntityTransportAuthoritySystem - Deactivated component for block: (5, 41, 0)
```

**Comment by Cervator** [comment]
Heya @MarcinSc good to see you :-)

I'm using the Blocker label as things to review before v1.0.0 in case it would result in a backwards-incompatible change, so we should complete that before releasing. Do you think this qualifies or is it just poor performance that wouldn't impact game functionality (or API) to fix at some point?

Pinging @immortius and @flo

**Comment by MarcinSc** [comment]
Due to the second case happening sometimes, this is definitely a blocker.

**Comment by Cervator** [comment]
Sure, it is a serious bug, I get that :-) But does the likely fix require resulting fixes in modules or stuff wouldn't compile? In any case I hope Immortius and/or Florian have ideas or comments, and I'm happy to have you poking at the holes again! We need to fix em.

I'm on vacation in  NYC and heading off for today, but I'll be around from time to time.

**Comment by MarcinSc** [comment]
No, it's just that for every test I have to recreate the world, because the existing blocks might be incorrectly initialized. Quite annoying.

The result for the player is, that stuff might not work after loading game.

**Comment by Josharias** [comment]
By chance is this in a multiplayer game and it you are seeing the events for the temp client entity and then the server sent entity afterwards?
