### ISSUE TITLE
Add gamepad support

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#2092]
One of the old branches even supported LEAP motion input. I think it would be nice to have a least conventional (X-Box) gamepads/controllers working for in-game movement.

**Comment by Cervator** [comment]
Yep I miss playing with the Leap Motion although it admittedly was a pretty basic prototype needing some more design and usability tweaking :-)

Destination Sol has controller support as well, via LibGDX. Works great, I've been able to test it.

**Comment by msteiger** [comment]
This is almost complete now. I implemented it based on JInput (LWJGL2 uses it under the hood already). LWJGL3 uses GLFW, but the Java bindings are fairly outdated (LWJGL3 apparently uses the C bindings).

**Comment by Cervator** [comment]
@msteiger did we forget to close this when controller support was added, or does it cover something else?

Also I am reminded of an amusing mention on IRC recently that a drawing tablet or something got picked up and made available in the in-game options :-)

**Comment by msteiger** [comment]
Thanks for the catch. I think that this can be closed. About the tablet gamepad: there's a type flag - I wonder what it reports for the tablet. We could filter it out, if it's a sensible value.
