### ISSUE TITLE
Game Crashes when going to menu.

### ISSUE THREAD

**Issue by theTechnoKid** [MovingBlocks/Terasology#2094]
Log file [here][1].

[1]: https://docs.google.com/uc?id=0B5l2RT_UOCXRQVM1YThOWlViSEU&export=download

**Comment by Cervator** [comment]
Hi @theTechnoKid - more details would be good. Exactly what did you do and what system do you have?

The log file seems to indicate you made it into the game, something broke/harvested a blueberry bush? There should also be an init log that shows what happened while loading the game.

What video card do you have and how much memory? What OS are you on and what Java are you using? Some of those details should be in the init log.

**Comment by theTechnoKid** [comment]
Ok. I'll find them and post them soon.

**Comment by theTechnoKid** [comment]
I am using an AMD Radeon 7310 on Windows 8.5 with Java 8.

**Comment by Dokman** [comment]
@theTechnoKid Windows 8.1? or 8.1?

**Comment by Cervator** [comment]
Guessing 8.1 might be enough of a change to be called Win8 and a half, heh :-)

Still need a good description of the actions taken immediately before the crash and the symptoms of it. The one log file doesn't show much.

It may help to launch the game from a command window - some errors can escape logging if they crash the game hard enough

java -Xms128m -Xmx1024m -jar libs/Terasology.jar

**Comment by theTechnoKid** [comment]
OK. I'll do it now. I had to go to sleep yesterday. And yes, its 8.1 sorry :)

**Comment by theTechnoKid** [comment]
[terasologycrash.txt](https://github.com/MovingBlocks/Terasology/files/76693/terasologycrash.txt) Here's the console output of the crash.

**Comment by Cervator** [comment]
Thanks! The log indicates extreme sluggishness on the ability for the game to keep up

"Delta too great (7638)" means 7.6 seconds passed between game loop updates, normally the goal is 60 updates per second a.k.a. 60 FPS.

The AMD Radeon 7310 is a low-end video card almost comparable to integrated Intel HD Graphics which sadly run the game poorly even on a good day :(

Normally we still don't see the game loop running so slowly. Do you have a lot of things running in the background or very little system memory available? If the game is launched with very little memory it'll have trouble performing even on good systems.

In-game you can press F3 then F4 to get some performance metrics, seeing all that debug text would be helpful, but I think your system as configured isn't going to be able to play the game well if at all :(

**Comment by theTechnoKid** [comment]
OK thanks very much :) I'm using a school computer which is extremely bad for gaming anyways.
