### ISSUE TITLE
Duplicate and unused Json merge methods.

### ISSUE THREAD

**Issue by MaloJaffre** [MovingBlocks/Terasology#2116]
There are two methods: [JsonMergeUtil.mergeOnto](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/utilities/gson/JsonMergeUtil.java#L29) (unused method) and [Config.merge](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/config/Config.java#L197) which are not implemented in the same way, but they do almost the same thing.
Which of them can we remove?

**Comment by Cervator** [comment]
@msteiger what do you think? The JsonMergeUtil.java version is the only thing in the class so we could probably just delete the whole class. Especially if it is showing as unused anyway.
