### ISSUE TITLE
More tweaking for better controller support

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2125]
## Description

This is a follow up issue to #2108. Not super high priority but fun to play with :-)
## Definition of 'Done'
- [ ] add more input mappings (XBOX controller mapping is present)
- [ ] harden against crashes / improve logging
- [ ] recognize disconnect and reconnect
- [ ] add documentation to our wiki on how to configure controllers
- [ ] [Optional] include a list of tested controllers
## Requirements
- you will work with the game's input system for which you will need basic/intermediate Java skills
- you will need a controller of sorts to test things
## Where to start?
- #2108 added controller support and gives an overview of involved classes
##

**Comment by jdrueckert** [comment]
Controller support is currently not working properly and also not a priority.
Once we are in a better place to take controller support up again as an actionable feature to be prioritized, we can revive this or create a new issue based on the state of our code-base at that point in time.
