### ISSUE TITLE
The player's head can bump slightly too far into the ceiling, seeing through the world

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2138]
Only noticed this while testing another PR but am thinking it is a consequence of #2133 since that had to do with the player's vision, or the location of as much :-)

Easy way to reproduce: blast a horizontal tunnel with the railgun and walk into it, jumping into the low hanging ceiling repeatedly. It looks like the players eyes are too far up in the character's physics capsule or what not?

@Josharias this one is all yours, probably an easy fix to adjust the height/offset or something, maybe with your next round of related changes, no rush :-)

Edit: Was not present in Alpha RC2, so I figure it is super recent.

**Comment by Josharias** [comment]
I have a sneaking suspicion that this has to do with an oddity I found when looking closely at LocationComponent values.  It seems like the character's position is being placed 0.9 higher than it should be.  There must be something deeper in the interaction between the character system and the physics engine.  I just havent put my finger on it yet.

![image](https://cloud.githubusercontent.com/assets/5922109/12441919/acf570fa-bf00-11e5-9645-a2240ad9560d.png)

![image](https://cloud.githubusercontent.com/assets/5922109/12441992/36cf7b40-bf01-11e5-8a4f-8db96e9e609c.png)

**Comment by Josharias** [comment]
On second think over this,  the gaze mount point would then be taller than the physics bounds of the character regardless of how the feet were located.  So I just need to extend the physics shape to 1.8 or reduce the camera mount point to 1.6.  OK. Can do.  Expect a PR tomorrow...
