### ISSUE TITLE
Can not create new worlds

### ISSUE THREAD

**Issue by DRSDavidSoft** [MovingBlocks/Terasology#2142]
Great work guys, just please fix this error:
http://pastebin.com/TvnjATmA

**Comment by Cervator** [comment]
Hi @DRSDavidSoft - you are enabling too many modules :-)

Generally you want to stick with a gameplay template as those have been tested. Some extras can be enabled and make sense but it varies from case to case and can be tricky to find out without looking more deeply at the code and assets.

**Comment by DRSDavidSoft** [comment]
Hi and thanks, I should have knew that :)
However, what causes this kind of problems? Lack of enough RAM? Too much to handle for CPU?

**Comment by Cervator** [comment]
Compatibility issues between the modules. Imagine trying to run Minecraft with every mod ever. Not quite *that* bad, but bad :-)

Also just missed you on IRC - we're there but not always staring at the screen, need to give it a few more minutes :D
