### ISSUE TITLE
Make package/class list in ModuleManagerImpl into a collection, add to ApiScraper

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2143]
Currently ModuleManagerImpl holds our external whitelist - which core Java packages and such modules can use. Each statement is a step to add one to the permissionProviderFactory

We should turn that into a list approach of some sort and let an external caller retrieve the list for display elsewhere, specifically for the ApiScraper so it can also include the external whitelist in addition to the internal stuff.

And then actually do that piece too. And anything else sensible to make the generated Modding API look even better :-)

Ping the https://github.com/MovingBlocks/Terasology/wiki/Modding-API page itself as it has a pending note to check here. Next after this would be actually publishing the Modding API doc list somewhere after builds/releases.

**Comment by MaloJaffre** [comment]
I added ```@Documented``` to ```@Api``` (seeMovingBlocks/gestalt#49).
We can now view in javadoc if a class is in API.

**Comment by Cervator** [comment]
Neat! How does that work exactly? I get now that `@Documented` is just a marker of sorts, does it have an outright impact?

From a quick look I'm guessing either it'll create complaints if something marked `@Documented` lacks Javadoc (?) and/or the Javadoc will include the annotations?

**Comment by MaloJaffre** [comment]
@Documented applies only to annotations.
Annotations are not printed in the javadoc when applied to a "thing"unless we add @Documented to the annotation.
Before:
```APIFoo
....```
After:
```@Api APIfoo
...```

**Comment by Cervator** [comment]
Alright, cool :-)

**Comment by Cervator** [comment]
Closing as complete! Next step in #2159
