### ISSUE TITLE
Just Reporting Crash

### ISSUE THREAD

**Issue by zurh** [MovingBlocks/Terasology#2144]
Not sure if this helps. If not I can stop reporting.

First Time checking things out/Playing.
Created Light and Shadow world.
Placed down the red and black boxes.
Objects start jumping around.
Crashed to desktop.

log file: https://docs.google.com/uc?id=0B5l2RT_UOCXRQ0lUanFIeDdRS0E&export=download

**Comment by Cervator** [comment]
Hi @zurh thanks for the report :-)

There is likely another log file with the actual errors in them, but there are know issues with the creatures in L&S like #1304. Work in progress for sure. I see lots of errors when I test although I don't generally crash.

Feel free to attach the other log file (should be a "game" or "world" log, the one you attached is the "init" log) but it is probably an already known issue. We just need to get to it!
