### ISSUE TITLE
Terasology was shut down by no reanson: IllegalStateException: Seed was not been set

### ISSUE THREAD

**Issue by LucaApolzan** [MovingBlocks/Terasology#2146]
I'm trying to generate a world in TerasologyOmega on Microsoft Windows 10 (x64 (64-bit))
The code was:
08:09:54.524 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceTop.FRONT with id 19
08:09:54.526 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceTop.BACK with id 20
08:09:54.531 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[LightAndShadowResources:clubsAceBottom]
08:09:54.532 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceBottom.LEFT with id 21
08:09:54.532 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceBottom.RIGHT with id 22
08:09:54.533 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceBottom.FRONT with id 23
08:09:54.533 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:clubsAceBottom.BACK with id 24
08:09:54.548 [main] WARN  o.t.r.assets.mesh.ObjMeshFormat - Skipping unsupported obj statement on line 3:"mtllib redpawnhammer.0.5.5.mtl"
08:09:54.559 [main] WARN  o.t.r.assets.mesh.ObjMeshFormat - Smoothing groups not supported in obj import yet
08:09:54.592 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'name' onto 'engine:Item'
08:09:54.821 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
08:09:54.821 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'maxGroundSpeed' onto 'engine:CharacterMovement'
08:09:54.821 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
08:09:55.168 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Breather'
08:09:55.218 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'name' onto 'engine:Item'
08:09:55.311 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:DoorTop]
08:09:55.312 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.LEFT with id 25
08:09:55.312 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.RIGHT with id 26
08:09:55.313 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.FRONT with id 27
08:09:55.313 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorTop.BACK with id 28
08:09:55.328 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:DoorBottom]
08:09:55.329 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.LEFT with id 29
08:09:55.329 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.RIGHT with id 30
08:09:55.329 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.FRONT with id 31
08:09:55.330 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:DoorBottom.BACK with id 32
08:09:55.338 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'name' onto 'engine:Item'
08:09:55.383 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[LightAndShadowResources:heartsAceTop]
08:09:55.384 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceTop.LEFT with id 33
08:09:55.384 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceTop.RIGHT with id 34
08:09:55.384 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceTop.FRONT with id 35
08:09:55.385 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceTop.BACK with id 36
08:09:55.388 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[LightAndShadowResources:heartsAceBottom]
08:09:55.388 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceBottom.LEFT with id 37
08:09:55.389 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceBottom.RIGHT with id 38
08:09:55.389 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceBottom.FRONT with id 39
08:09:55.389 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block LightAndShadowResources:heartsAceBottom.BACK with id 40
08:09:55.915 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "KUgon9Yj82JGvllH4IfBgexXeQo2jRxG"
08:09:55.949 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: Seed has not been set
	at org.terasology.world.generation.WorldBuilder.build(WorldBuilder.java:95) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.pathfinding.PathfinderTestWorldMapGenerator.setWorldSeed(PathfinderTestWorldMapGenerator.java:50) ~[na:na]
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:107) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:62, origin/master, 62]
08:09:55.949 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...

**Comment by Cervator** [comment]
Hi @LucaApolzan - I take it you picked the Pathfinder Test world and that's what broke? That's a known issue: #2003

I think every other world should work, so if that's all that crashes you should be good to go, just avoid that one :-)

The fix isn't very difficult, that particular world just doesn't have an active maintainer at the moment.

**Comment by Cervator** [comment]
Fixed by https://github.com/Terasology/Pathfinding/pull/26 ! Closing.
