### ISSUE TITLE
Replace applet version of game with Java Webstart

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2147]
We got Webstart working for the Launcher in the past, although mostly as an experiment. With Oracle finally making the death of applets official (http://www.theverge.com/2016/1/28/10858250/oracle-java-plugin-deprecation-jdk-9) we should probably switch to a Java Webstart facade or Jenkins job.

Applet still does work in Firefox, I coincidentally just fixed it as the LWJGL version had drifted out of sync, but IE and Chrome might already be done for. Unless you use an older version anyway.

Like the applet a webstart version should probably just include the super basic Core setup only, no extra modules. Maybe when we have a working Iota dist we can go with that.

When complete we should remember to update assorted documentation and links, like the splash site and https://github.com/MovingBlocks/Terasology/wiki/Project-Overview
##

**Comment by msteiger** [comment]
Do you think it's worth creating a WebStart version of the game or should player use WebStart to get the launcher and run the game from there?

Iirc, the webstart file is not linked with the java executable if  the "Support Java in Browser" setting is not ticked in the system settings. Thus, the browser will just attempt to download the webstart launcher file without doing anything.

**Comment by Cervator** [comment]
Mainly I wanted to get the idea process started :-) I don't know/remember a lot of details about webstart.

The applet was always about having a super easy non-committal way to try out the game. Worked well since you just open a page then get game. Got gradually worse as the security issues started piling on and you had to go through more hassle to have it run.

With webstart - if the user still has to jump through a bunch of hoops to get the game running, that are equal to or greater than simply downloading the game - then maybe we shouldn't bother :(

Or at least do it low priority and mark it clearly how to make it work.

On launcher vs. game I'd consider the launcher a more committed way to get the game, not so much a preview. So that would just be the "normal" way to get and install the game I'd think.

**Comment by Cervator** [comment]
Closing as being heavily out of date.
