### ISSUE TITLE
p

### ISSUE THREAD

**Issue by byroncratf** [MovingBlocks/Terasology#2149]
necesito ayudaaaa

**Comment by Cervator** [comment]
I understand that, but how can we help if you don't include some details?

We need to know what happens. Does the game crash? Does it run slow? What exact computer do you have?

The game creates log files that can contain clues to what's wrong. If you crash and our "CrashReporter" appears it gives you the option to upload those logs somewhere, like pastebin.com or Google Drive.

Please write a thorough explanation of your problem. Consider using https://translate.google.com/
