### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lordmythus** [MovingBlocks/Terasology#2150]
https://docs.google.com/uc?id=0B5l2RT_UOCXRYTlnOXQ5TWU4bWc&export=download

**Comment by Cervator** [comment]
Hi @lordmythus - could you please explain what happens and where/when do you crash?

Thanks for the log file, can you look for any more? That is the initialization log and holds good info, but I am expecting you crashed in-world or while creating a world, which would be in the game/world log.
