### ISSUE TITLE
Tutorial on basic entity system usage

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2153]
We should make a basic tutorial on using the ES in one or more modules akin to @Josharias' great world gen tutorial: https://github.com/Terasology/TutorialWorldGeneration/

It should have its own module with a small multi-page guide in the wiki.

Suggestion: Maybe we could base it on an example like Spawning/Portals/Oreons. While the current modules are old and kinda aged a new set just for the tutorial should be easy.

Goal is catching on to how to come up with what's a Component, what's a System, and what's the benefit we gain from the ease of adding new Components to an existing prefab.

In Spawning/Portals/Oreons this is illustrated by Spawning applying `SpawnableComponent` to a creature like an Oreon and `SpawnerComponent` to something like a portal block. Then the System class simply runs through any Spawners and looks for valid Spawnables to spawn.

Going to the next level would simply be marking one of the Spawnables as a Spawner itself - I did that with GelCubes once upon a time, every 10th spawned would become a Queen and herself spawn new GelCubes. Easy to demo in a prefab or in code.

Another extra would be using the tag system there to loosely couple Spawners and Spawnables. At present the Oreons have several tags applied (an Oreon Guard is tagged "oreon", "guard", "oreonguard" or something) while portals have a list of tags they can spawn (as a fair warning this is about the last thing I worked on ages ago so it wasn't finished)

In that case a new module that _is not_ in the dependency chain could introduce a new creature or portal and show how it can affect or be affected by the other modules simply through tag management without ever introducing a hard dependency. In fact the tutorial could try to be clever and _be_ the module that tweaks how Spawning/Portals/Oreons work when it too is enabled. Although those might need a little cleanup if so.

Edit: Probably should also cover multiplayer angles like authority on systems and the related annotations
##

**Comment by flo** [comment]
Just for reference. There is already an introductional article about it: https://github.com/MovingBlocks/Terasology/wiki/Events-and-systems

**Comment by Cervator** [comment]
Thanks for adding the link @flo :-) I remembered the page but forgot to link it.

One of my goals with the wiki overhaul is to push some of the doc like into tutorial modules that'll break if we change anything that would make the doc go out of date. Previously we've had nice pages in the engine wiki but with no hard links to the code - we'd have to rely on somebody remembering or bumping into the doc by chance. And peppering engine code with wiki links is probably not ideal.

In a tutorial module we can pair example code right to each bit of the documentation, teaching the user how to use it, and if we ever change the engine the module build will fail and alert us to probably needing to update the tutorial as well, huzzah! Heck we could probably demo a few simple unit tests (of actual content using said engine features) or something too.

**Comment by skaldarnar** [comment]
We have:
- https://github.com/MovingBlocks/Terasology/wiki/Entity-System-Architecture
- https://github.com/Terasology/TutorialEntitySystem/wiki
- https://github.com/Terasology/TutorialEventsInteractions/wiki
