### ISSUE TITLE
Player / camera location seemingly not reset after respawning / falling to your death

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2156]
I think this is from your recent tinkering @Josharias so sending your way :-)

If you currently die, say from flying way up in the air, then respawn your viewpoint seems to be locked at the range from where you fell, yet centered to the point where you died. Or something like that.

After respawn I'd get some weird situations where I couldn't see anything around me yet I could hear myself breaking blocks and see items get picked up. After a few attempts and moving the camera around I might spot something in the distance, and finally I caught a fully visible world (other examples may be where I moved out of chunk visibility range from spawn?) where my vision reappeared up in the sky from where I fell, and moving my vision down just a little bit was like a roller coaster ride :-)

Some screenies:

Hey I found my hand and the selection grid! But chunks aren't rendered here, hmm

![terasology-160206165556-1152x720](https://cloud.githubusercontent.com/assets/1063833/12869635/7ad29c32-ccf3-11e5-8858-e3b5171a0d47.jpg)

Oh hi tree in the distance!

![terasology-160206165509-1152x720](https://cloud.githubusercontent.com/assets/1063833/12869637/84907122-ccf3-11e5-806b-50d15037405a.jpg)

Well this doesn't look so bad. Wait - I'm not flying, nor falling

![terasology-160206165758-1152x720](https://cloud.githubusercontent.com/assets/1063833/12869640/8d5b14b0-ccf3-11e5-9339-75153d7893b8.jpg)

Moved mouse a fraction of an inch forward to pan down, got a weeeeeee dive forward

![terasology-160206165801-1152x720](https://cloud.githubusercontent.com/assets/1063833/12869641/90a93b42-ccf3-11e5-83da-ab89ce484f28.jpg)

**Comment by Josharias** [comment]
Chuckle.  Yup looks like something is not rebooking up quite right after respawn.  Is it only on respawn after death?

**Comment by Cervator** [comment]
That's the only way I've reproduced it, yeah, but I haven't tried being super thorough :-)

**Comment by Cervator** [comment]
Closing as fixed by #2164!
