### ISSUE TITLE
Tutorial module: Events, interactions, and inventory

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2158]
Akin to #2153 and #2155 - a dedicated tutorial module for taking a step-by-step approach to learning how events work (beyond the super basics) and how to interact with something (inventory, interaction screen, etc)

Maybe #2153 will minimally touch on how to catch an event of interest, but just to show how you can get an entity and use a component attached to it. This one should go into details about you consume/cancel events, do more fancy things with them, and interact with some core systems like inventory.

We have a forum thread on interaction screens: http://forum.terasology.org/threads/interaction-screens.1106/ - it linked to a tutorial n the wiki which I removed in the great wiki purge intending to get something updated elsewhere, namely this dedicated tutorial!

The original tutorial is still available at https://github.com/MovingBlocks/TempDoc/blob/master/Tutorial:-How-to-make-blocks-with-custom-UI.md

Bonus: probably should wait and see what magic new inventory magic @Josharias is sprinkling on the engine before doing this :-)

We should also be sure to update / replace the forum thread when this is done.

I marked this with the multiplayer label thinking this might get advanced enough to touch on specific things to consider there. Unsure. Might be needed in the others too (like marking variables in Components for multiplayer)
##

**Comment by Cervator** [comment]
Addition: With #2175 merged we now have some fun explosions to play with. Tutorials are always better if they contain explosions, right? 

Probably some good examples in there of configuration, the "Action" setup, and interactions between things.

**Comment by Cervator** [comment]
Another angle: Show how a *layered* set of related systems might flow through a series of events differently. Thinking something like damage being modified due to equipment (both armor and weaponry), magic (shielding etc), and special modes like ghost/god mode.

Got to thinking about it while reviewing https://github.com/MovingBlocks/Terasology/pull/2323 which makes ghost/god mode not hurt the player, but by explicitly checking for that in the health system. The really old issue #652 that the PR fixes gets a little into event cancellation, which should probably be used instead, but I don't think we have any great examples or best practices for how to do so.

I did find a water breathing setup in the AlterationEffects module that uses event cancellation to prevent drowning damage, but I'm not sure how completed all that was. I think it was one of the things @MarcinSc started near the end of sorts of the active period for Throughout The Ages development (alchemy/potions) - unsure if usable, pinging in case of knowledge :-)

Pinging @portokaliu and @xrtariq2594 for general interest.

**Comment by Cervator** [comment]
Addendum from #3003 - on death the player's inventory now persists. Different gameplay modes may want to vary that (lose all, keep all, drop all, partial, etc). We should improve support for that if needed and cover it in the tutorial.

**Comment by skaldarnar** [comment]
Closing as we have a bunch of tutorial modules and improved on the docs in the engine wiki about events and interaction between systems.
