### ISSUE TITLE
Setup video

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#217]
I was going over old Facebook comments and spotted a follow-up I missed months ago with somebody asking how to install. In my personal style of overwhelming knowledge I offered both normal game download and full DevSetup info - which was too much and the user suggested making a video.

I suppose we could do that for a local dev setup at some point, maybe especially the Git + SSH setup (even though that's pretty well documented on GitHub)

**Comment by Margretor** [comment]
@Cervator Isn't this issue covered? The gradle script seems to do the "magic".

**Comment by skaldarnar** [comment]
With GitHub promoting `https:` connections over ssh and the fancy gradlew setup in place pretty much everything is covered. If you still want to do a video of sorts, I'd say it should contain the following: 

- log in to github and __fork__ the project
- __clone__ from your fork (console command) and add upstream __remote repo__
- __fetch__ some modules
- __create__ a new module
- run __idea__ task and open up in intellij -> do changes
- __run__ the game via a) command line, and b) intellij

I'm not sure if it is worth the effort. The video would showcase more or less our custom setup, and how to use the gradle magic in place.

**Comment by Margretor** [comment]
I think the wiki provided with this project is more than enough to get someone started but this issue is still open.

**Comment by Cervator** [comment]
This issue is really old, yeah. It can be easy to think our Gradle utility will do everything really easy but that's probably in part because we're already developers and perhaps already familiar with some of the concepts (pinging @AWebb3701 / Kazimir on that note since he rightfully woke me up to that perspective)

A modder, texture artist, play test enthusiast, or other individual who hasn't done much if any coding before might get a lot out of seeing a basic video that covers what @skaldarnar mentions above. "A picture is worth a thousand words" so a video is probably worth about a million :-)

Still, a video can take some effort to set up and maintain. So we need somebody who doesn't mind re-recording an update once in a while. Maybe ideally a set of really *small* videos of a minute or less in length that each cover a very small part of the process. That makes it easier to re-record updates later. We can put them all together in a playlist and link from various tutorials.

Other ideas for what to cover:

* Using a GitHub native client (GitHub Desktop or whatever it is called these days)
* Bypassing Git entirely and using a src zip downloaded from GitHub
* Bypassing *source* completely and using a downloaded game zip to mod in assets like new blocks, which is entirely doable with plain "directory modules" - aka extracted jar files that live in a regular directory
* Grabbing and using useful tools that relate, like 2D texture editors or Voxelshop
* Highlighting the runtime asset reloading (there is an existing video or two on this) and exactly *what* reloads in what situations - like what needs a fresh stack created in-game, what needs a new block placed vs. applies to an existing block, and so on
* Using Eclipse instead of IntelliJ

There are lots of possibilities, really. I'm pretty sure we're talking more about a whole series of small snippets.

**Comment by rzats** [comment]
Closing in favor of #2569 - most of the discussion was brought over to the DoD 🙂
