### ISSUE TITLE
Slight display issue in dropdowns with more items than their default point to activate scrolling

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2185]
Tiny follow-up to #2183 for @AlexanderGrooff and friends! Easiest explained with a screen capture:

![terasology _ alpha_2016-02-26_00-14-29](https://cloud.githubusercontent.com/assets/1063833/13343837/830474ae-dc1e-11e5-929d-9a6c76fa0313.png)

It seems the scrollable area is correct when it is at or below the threshold for adding scrolling. When more items are added a slight bit of overflowed empty space gets added in the list. Probably just a small calculation quirk somewhere?

**Comment by AlexanderGrooff** [comment]
Thanks, I'll have a look at it!

**Comment by Cervator** [comment]
Additional thought: Maybe we should leave slightly more than x entries visible if there are > x entries total. 

Rationale: If there are exactly three gameplay templates a fixed dropdown showing just three makes perfect sense. If there are four and we show a perfect fit for three maybe it'll be easy for users to miss that there are more?

If we show a partial 4th item to make it obvious there's more to scroll down to see that may help make that more obvious than the visible scrollbar alone.

Not the same as the original item in this ticket, but very similar. Just visibility vs. empty space.

**Comment by AlexanderGrooff** [comment]
That seems like a good idea :+1:. I'll work on the two subjects simultaneously somewhere this week.

**Comment by Cervator** [comment]
:+1: :+1:

**Comment by genuinelucifer** [comment]
@Cervator I was trying to see this issue but I can't replicate it. All the dropsdowns that I see are actually sized exactly without any extra space below the items. Am I missing something?

**Comment by AlexanderGrooff** [comment]
@genuinelucifer I am able to replicate it. Assuming the worldgenerator menu has three items in it, you can set the `worldGenerator.setVisibleOptions(3);` in CreateGameScreen.java to 2. After doing that, I got the same image as @Cervator showed.

**Comment by genuinelucifer** [comment]
@AlexanderGrooff Oops. I understood the issue incorrectly.
Thanks for your help I was able to come up with a patch. I am submitting a PR now.
