### ISSUE TITLE
Crash (Pathfinder Test World - dupe of #2003)

### ISSUE THREAD

**Issue by FinnT730** [MovingBlocks/Terasology#2186]
[https://docs.google.com/uc?id=0B5l2RT_UOCXRX09GemFTbS1Ldk0&export=download](url)

**Comment by Cervator** [comment]
Hi @FinnT730 - we need more than just a single log file to be able to help. What problem are you even encountering?

All I can tell is that you're using the latest (as of right now) unstable build, which is by its nature likely to be unstable :-)

Some details of what happens including more logs would be helpful.

**Comment by FinnT730** [comment]
Hi @Cervator - I will try to give you more log files very soon! And I will try the stable build and the unstable build!

**Comment by Cervator** [comment]
Thanks :-)

Can you explain what actually happens?

I can see two issues

* You might be trying the "Pathfinder Test World" - that one is known to be broken: #2003
* Your audio isn't initializing right. Is there anything unusual about your sound setup?

```
19:05:39.410 [main] WARN  o.t.e.subsystem.lwjgl.LwjglAudio - Could not load OpenAL manager - sound is disabled
org.lwjgl.LWJGLException: Could not locate OpenAL library.
```

Hopefully the sound failure just gracefully disables sound. Have you tried other worlds?

**Comment by FinnT730** [comment]
Its is the Pathfinder Test World. I did not know if it was already be reported!
I don't have sound problems.

**Comment by Cervator** [comment]
Alright so that's the only problem then? In which case we can close this or keep it open till the Pathfinder test world is fixed (or you could just subscribe to its main issue if you like)

Good to hear the sound is OK - weird that the log listed that but it could be a blip/quirk :-)

**Comment by FinnT730** [comment]
That is the only problem! But I will keep this issue open for other people!
Thanks for the help!

**Comment by Cervator** [comment]
Fixed by https://github.com/Terasology/Pathfinding/pull/26 ! Closing.
