### ISSUE TITLE
Unable to kill deer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2189]
Even with the mighty axe of @MrBarsack !

I figure that got shaken lose with recent changes since PVP also broke for a little while.

To reproduce: Enable WildAnimals, grab Mr Barsack's axe from the starting goodie chest, `spawnPrefab deer` and thwack the deer with the axe (which insta-kills anything) - no deer chops :(

(I tried with PolyWorld active but doubt that relates)

**Comment by oijazsh** [comment]
This appears to be because `destroyEntityOnNoHealth` in unset in deer.prefab in WildAnimals and the HealthComponent seems to be defaulting to setting the above value false. It could be fixed by setting `destroyEntityOnNoHealth` in deer.prefab or by changing the default value to true - but that may affect any prefab that relies on it defaulting to false.

**Comment by Cervator** [comment]
Ah! This makes sense now I think. @Josharias moved some things around and some prefab templates changed. The ability to die was readded for players but probably whatever template the deer uses is immortal now (missing that bit)

Thanks for the research! :-) I'm not sure where we should fix it, but we still have the flexibility to break whatever and refix.

**Comment by Josharias** [comment]
Nicely diagnosed!

I think adding ```destroyEntityOnNoHealth`` on the deer is probably the correct move as then the HealthComponent keeps the natural java default for that field.  

Apparently I accidentally finished implementing that field's function when I moved the health system to the Core module.  It looks like the ThroughTheAges modules have that value specified appropriately, but LightAndShadowResources does not.

**Comment by ClintRajaniemi** [comment]
@Josharias I fixed this particular issue and the deer will now disappear after reaching zero health. I've created a pull request against WildAnimals. If I've not done the submission correctly, please let me know as I've never proposed changes in github.

**Comment by Cervator** [comment]
Hey @ClintRajaniemi you did it right - thanks! :-)

Adding you to the credits, do you have a forum account yet? I think I saw a clint on IRC was that you?
