### ISSUE TITLE
Don't know what the issue caused this but here you go the logs

### ISSUE THREAD

**Issue by MKnance** [MovingBlocks/Terasology#2219]
### What you were trying to do
play on a server and singleplayer
### What actually happened
it loaded one loaded but was super duper laggy even on minimal setting with black shadows at random spots 
### How to reproduce
I don't know how to reproduced it all i did was logon and blamo the problem pretty much was there 
* Step 1
* Step 2
* Step 3

### Log details and game version
http://pastebin.com/trCLMg69
### Computer details
An older machine with  Radeon HD 5450

**Comment by Cervator** [comment]
Hey there. We talked some on IRC, but the symptoms do make it sound like the video card/driver (on Win7) isn't getting along well with the game :(

There might not be much else we can do unless you can find some more logs and we spot some solid issue in there. A screenshot might also help but it is hard to troubleshoot that way.

**Comment by Cervator** [comment]
Closing from lack of follow-up / vague issue / likely video card.
