### ISSUE TITLE
Modules don't work when they are just downloaded[bug]

### ISSUE THREAD

**Issue by Kakrain** [MovingBlocks/Terasology#2220]
### What you were trying to do

enable a module
### What actually happened

I downloaded that module (and the dependencies were already enabled), but it wouldn't let me activate it. I had to close the program and run it again for it to let me enable it
### How to reproduce
- Step 1
  create a game
- Step 2
  select the module that is going to be enabled (it shouldn't be downloaded yet)
- Step 3
  download the module and try to activate it
  ### Log details and game version
### Computer details

64 bits Windows 8

[Terasology-init.txt](https://github.com/MovingBlocks/Terasology/files/166747/Terasology-init.txt)
[Terasology-init.txt](https://github.com/MovingBlocks/Terasology/files/166748/Terasology-init.txt)
##

**Comment by Leonardoas26** [comment]
Just adding my observations: This happens when attempting to download a module that has "Core" as a dependency. 

Here's the relevant error message
[Module Download Error.txt](https://github.com/MovingBlocks/Terasology/files/174870/Module.Download.Error.txt)

**Comment by jdrueckert** [comment]
Cannot reproduce
