### ISSUE TITLE
[crash] it crashes when i try to create a game with Rails module enabled

### ISSUE THREAD

**Issue by Kakrain** [MovingBlocks/Terasology#2221]
### What you were trying to do

play a game with the rails module
### What actually happened

it crashed
### How to reproduce
- Step 1
  enable Rails
- Step 2
  create game
- Step 3
  it crashes
### Computer details

64 bits 
[Terasology-init.txt](https://github.com/MovingBlocks/Terasology/files/166787/Terasology-init.txt)
windows 8 
##

**Comment by SkySom** [comment]
Assuming you're using a relatively current version of Terasology, the Rails module is incompatible. We are in the process of rewriting it to work with current versions. Possibly related to https://github.com/Terasology/Rails/issues/3

**Comment by Cervator** [comment]
Closing this as obsolete, Rails have been fixed since :-)
