### ISSUE TITLE
Add same single/multi subtitle for Create Game screen as Select Game screen

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2233]
Pretty much a clone of #2173 for the next screen in. @BdeBock @AlexanderGrooff I feel bad even submitting this after all the hassle the first one caused you, please don't hate me! I figure it'll be easy this time through :-)

The fixed screen :sparkles: 

![terasology _ alpha_2016-03-13_21-52-49](https://cloud.githubusercontent.com/assets/1063833/13733190/09eeb39a-e966-11e5-97df-e30385132190.png)

One screen deeper in, no subtitle :crying_cat_face: 

![terasology _ alpha_2016-03-13_21-52-57](https://cloud.githubusercontent.com/assets/1063833/13733196/1e85a9e4-e966-11e5-835e-8d66f84f72c1.png)

**Comment by AlexanderGrooff** [comment]
Haha no problem, we'll look into it :+1:

**Comment by Cervator** [comment]
Closing as fixed by #2235. Thanks! :-)
