### ISSUE TITLE
Missing or bad .gitignore in some modules

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/Terasology#2242]
I fetched all modules and imported the projects to eclipse. 24 were instantely marked as dirty, caused by a missing or outdated .gitignore:
- [ ] Adventure
- [ ] BlockNetwork
- [ ] Books
- [ ] BoomSticks
- [ ] BoundlessWorlds
- [ ] CakeLie
- [ ] Combat
- [ ] Crops
- [ ] DynamicBlocks
- [ ] FunnyBlocks
- [ ] GrammarSystem
- [ ] Hunger
- [ ] Index
- [ ] Malicious
- [ ] ManualLabor
- [ ] Maze
- [ ] Minerals
- [ ] Miniion
- [ ] MoreLights
- [ ] Potions
- [ ] RgpSystem
- [ ] Sample
- [ ] Soils
- [ ] TheBetweenlands

Sure, some are outdated but if one continues to work on them a proper gitignore could avoid commiting wrong files.
It would also add some clearness to the large workspace which is very handy to search for code examples.

Any option to fix this without forking 24 repos and making 24 pull requests? :)
##

**Comment by skaldarnar** [comment]
Good point. Easiest way would be to fix them along the next PR for that module. Alternatively, someone of the MovingBlocks team might find the time to push the updated .gitignore directly ... (**not** volunteering)

**Comment by Cervator** [comment]
Sounds like a me thing when my day job calms down :D

I put a `.gitignore` under `/templates` in the engine project, that's what gets dragged into a new module for a `gradles createModuleX` - but naturally changing the template doesn't update all the modules, alas.

I can do this next time I have cause to do a big spammy multi-module update.

**Comment by skaldarnar** [comment]
https://github.com/github/gitignore

**Comment by msteiger** [comment]
I agree with @Cervator here. We should create a gradle task for it, spam the latest `.gitignore` file across all modules and commit (maybe auto-commit with gooey's account).

**Comment by skaldarnar** [comment]
Nobody complained about this for a long time, considering this as resolved.
