### ISSUE TITLE
Add Terasology to up-for-grabs.net

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2244]
http://up-for-grabs.net is a list of open-source projects that have curated tags marking beginner-friendly issues, helping newcomers to OSS find repositories to contribute to. Since Terasology already has a `contributor-friendly` tag, it seems like a perfect fit for the website!

**Checklist:**

- [x] Browse through the `contributor-friendly` tag [(link)](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3AContributor-friendly) and identify items within the scope suggested by up-for-grabs:

>What sort of tasks are a good fit?

>- Tasks should take no longer than a few nights' worth of work
>- Tasks should stand alone - avoid core functionality on which other tasks depend
>- Tasks should be well described with pointers to help the implementer

- [x] Mark them with an `up-for-grabs` tag (a different naming convention e.g. `newbie-friendly` is OK)

- [x] Create a Terasology.yml file with some info about the project [(instructions)](https://github.com/up-for-grabs/up-for-grabs.net#add-your-project) then submit it in a PR to [up-for-grabs](https://github.com/up-for-grabs/up-for-grabs.net).

_This should be pretty easy, but requires sufficient permissions for the Terasology repo (for modifying tags)._

**Comment by rzats** [comment]
Made a Terasology.yml file template: [gist](https://gist.github.com/rzats/8e4663fbfe302de80122)

(The tag name on lines 13/14 should be replaced with whatever the newbie tag will be called)

**Comment by msteiger** [comment]
Sound good to me - we somehow should (need?) to ensure that this isn't going to be a one-time action, but a continuous process. We need somebody to curate the workflow at least for a while.

For similar reasons, TS is not (yet?) present at http://indiegames.com/ and other opensource/indie game lists and websites. A bad/outdated representation can be worse than having no representation, imho.

What's your take on this, @Cervator ?

**Comment by Cervator** [comment]
> What's your take on this, @Cervator ?

Exactly that :-) Mentioned that on IRC. Also reason for not having jumped on a bunch of stuff like this before (as well as being low on time)

We could do better with public representation like that, especially now that the v1.0.0/alpha release is done (tho not yet announced). So maybe the time has come to talk some people into helping with that sort of organizing.

Earlier I was looking at GitHub permissions needed to edit labels and such, maybe we should set more people up for that if they're interested, like @rzats or @SkySom

**Comment by rzats** [comment]
@Cervator - sure, I'd be up for sorting the tags out! Submitting a PR as well, for that matter - although the website _may_ expect a core contributor to add the organisation to the list though.

**Comment by Cervator** [comment]
Hey @rzats I created a new @MovingBlocks/hunterteam group here on GitHub and put you in it. Currently adds write access to Terasology + TerasologyLauncher for issue management :-)

Hunter Team is sort of a longer story, comes with a badge in the forum which you've got now too. I am thinking that team could be a sort of next step beyond plain Contributor, maybe mixed up with casual mentoring (actually finding new contributors to help work some of the issues)

Did you see http://forum.terasology.org/threads/continuing-mentoring-beyond-gsoc-and-new-issue-markings.1522 yet ? It is my little write-up on a new style mentoring system and 3 related issue categories (including GSOC)

@SkySom how about you? :D

**Comment by rzats** [comment]
@Cervator: nice! I actually got added to [TerasologyJavaLauncher](https://github.com/MovingBlocks/TerasologyJavaLauncher), which doesn't seem to have much activity, instead of TerasologyLauncher - but that's fine as I can _apparently_ edit my own permissions:

![permission editing interface](http://i.imgur.com/gPWsNqZ.png)

And yep, I got tagged in that thread a while ago - going to use that as a reference for label assignment.

**Comment by rzats** [comment]
I've browsed through the open issues and assigned every _Contributor-friendly_ issue one of these labels:

- [Bite-size](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3ABite-size) (**49 open** - that's way more than the up-for-grabs average!)
- [Mentor-size](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3AMentor-size) (28 open)

@Cervator: would be nice if you reviewed all of these - particularly because some of the older issues may already be finished (it's not entirely clear from the discussion). After that, the [Contributor-friendly](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3AContributor-friendly) label can be safely deleted or (preferably?) manually removed from all the open issues and the PR to up-for-grabs can be submitted.

Also, one small thing to consider is label coloring. The dark-green color [Content](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3AContent) uses (#007D00) would be perfect for Bite-size issues - it's pretty much a universally accepted "go for it!" signal. This means that the Content label's color would need to be changed to something else, though.

**Comment by Cervator** [comment]
Whoops on the launcher repo bit. And yeah I made you a team maintainer for that group as well so you can tweak at it like so if needed :-)

Checked out the lists. Moved #2153 from bite-sized to mentor-sized since it is a tutorial on an engine topic that you'd probably need a bit more familiarity with the ES to be able to do well. There are a few other items in either category I might waffle on switching back and forward, but it is hard to be sure. Probably we can just tweak over time.

Switched color between bite-size and content, no problem there. Nice to have the green stuff grouped anyway (bite-size, mentor-size, bounty). We can get rid of the Contributor Friendly label now but should probably check for any links using it first and maybe replace them with a bite-size+mentor-size link instead.

**Comment by SkySom** [comment]
I'd probably keep it for now, but slowly phase it out. As you've been pointing it out as the go to for quite some. For it to just disappear may be a bit confusing. And yeah I'm in. MC has been losing some of my motivation so I'll need somewhere to put it lol

**Comment by skaldarnar** [comment]
Agreed on keeping contributor friendly for now. That's the references we handed out to all the GSOC students and interested people in the last weeks, so I would keep them around for some time. Maybe start removing them when the actual coding period starts (just to have some date).

**Comment by rzats** [comment]
Alright, won't hurt to keep it legacy for some time.

up-for-grabs PR now live: [up-for-grabs.net#391](https://github.com/up-for-grabs/up-for-grabs.net/pull/391)

**Comment by rzats** [comment]
And a followup - I've also added similar labels to TerasologyLauncher:

- [Bite-size](https://github.com/MovingBlocks/TerasologyLauncher/labels/Bite-size) (5 open)
- [Mentor-size](https://github.com/MovingBlocks/TerasologyLauncher/labels/Mentor-size) (4 open)

Would submitting the launcher as a separate project be a good idea? It's strongly tied in to Terasology but may be interesting in and of itself to people interested in JavaFX.

**Comment by Cervator** [comment]
We could just let Contributor Friendly disappear by attrition as they get fixed, so long as we don't apply any new ones :-)

Then we can just fix up the links as we come across them.

**Comment by rzats** [comment]
The up-for-grabs PR has been merged and Terasology's live on the [website](http://i.imgur.com/bYhVpej.png)!

![screenshot showing the Terasology project on up-for-grabs.net](http://i.imgur.com/bYhVpej.png)

Leaving this open until _Contributor-friendly_ has been fully deprecated.

**Comment by Cervator** [comment]
Deleted all remaining Contributor Friendly labels when I recently created the new Hacktoberfest label. Closing this as complete :-)

In visiting up-for-grabs.net a minute ago Terasology was right near the top, woo!
