### ISSUE TITLE
Module not working on its own (block picker)

### ISSUE THREAD

**Issue by ToXeye** [MovingBlocks/Terasology#2248]
### What you were trying to do

Use the blockpicker module without any additional modules than that

Pressing a lot of buttons until I find a menu

### What actually happened

I pressed B and then terasology crashed with a null pointer exception

### How to reproduce

* Step 1
Start a new game with only the basic module and the block picker module

* Step 2
Enter the game to see how it crashes when you push B

* Step 3
Profit
### Log details and game version
http://pastebin.com/ST2UsWPb
### Computer details
OS: Windows 10 Home - 64 bit
CPU: Intel i5-2500 - x64
RAM: 4GB

(although since it's a null pointer exception, I would guess there might be another module which makes this module work : - )

**Comment by ToXeye** [comment]
I would then guess that it would work with all the dependencies fixed

http://pastebin.com/SHb6P6WU

However, it did not work

**Comment by ToXeye** [comment]
I found out even more about it. The module is for 0.1.1 so I'm better off writing my own block picker : - )

**Comment by skaldarnar** [comment]
@ToXeye don't re-invent the wheel by starting from scratch. Try to fix the existing module :wink:

**Comment by Josharias** [comment]
I would be happy to give control of the BlockPicker module to you.  It has fallen low on my priority list.  I would not mind if you revamped it completely and made it your own.  Let me know if you are interested.

Some ideas from others are on the forum too: http://forum.terasology.org/threads/block-picker.1083/

**Comment by Josharias** [comment]
Crash bugs fixed in in BlockPicker 0.1.2.  @ToXeye mind giving it a try and see if you have less crashing profits?

**Comment by Cervator** [comment]
Confirmed "less crashing profits" - thanks @Josharias ! :D 

Closing as complete :-)

@ToXeye let us know if you find otherwise. Hope you're doing well!
