### ISSUE TITLE
GLSLMaterial binding issue with Texture and FBO

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#2261]
So the way that textures occupy the same slot space as FBO's may cause some problems in the future. The current model does not introduce this problem, but an FBO can occupy the same active slot as a Texture, if a texture is ever bound to an GLSL shader that is using FBO's. At the moment the only shader that suggest this problem is the ShaderParametersLightGeometryPass. Any GLSLMaterial that takes advantage of both an FBO and Texture will not work properly. A suggested solution is to allow Shaders to accept an FBO in as a property. I believe FBO's may have to be reworked to accommodate this change.

It uses this workaround to avoid the issue: 

```
 if (CoreRegistry.get(Config.class).getRendering().isCloudShadows()) {
     Texture clouds = Assets.getTexture("engine:perlinNoiseTileable").get();

     GL13.glActiveTexture(GL13.GL_TEXTURE0 + texId);
     glBindTexture(GL11.GL_TEXTURE_2D, clouds.getId());
     program.setInt("texSceneClouds", texId++, true);
 }
```

**Comment by emanuele3d** [comment]
I just noticed this issue. You are correct that texture slot assignment is all a bit insecure. I'm currently working on the render nodes and therefore at a higher conceptual level, but I will eventually look deeper, at the materials and in particular at the shader parameter classes which is often where texture assignment occurs. So: I'm aware of the issue, it will get more robust, bear with us.
