### ISSUE TITLE
Support for disabled UI elements

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2268]
Currently to the best of my knowledge we can't visually disable UI elements (please correct me if I'm wrong!), such as making a checkbox greyed out while being stuck in a particular setting.

This would help out #2246 as volumetric fog is broken but has a valid toggle in the graphic settings now. We should have the option to disable such an option so we can keep it, but leave it passive until the actual feature finally works again.

Probably not super hard for somebody familiar with UI work or interested in learning. May be relevant to @rzats' interests in doing NUI work.

**Comment by msteiger** [comment]
Sounds reasonable to me. A `disabled` family mode already exists and has been implemented for buttons. Adding this to checkboxes and drop-down lists would probably cover most ground.

**Comment by Cervator** [comment]
Closing as completed by @2274, could be further enhanced by #2277 :-)
