### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by emancooldude** [MovingBlocks/Terasology#2269]
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by skaldarnar** [comment]
Hello @emancooldude 

We are sorry that the game seemingly crashed for you. To help you we need some more information. Please fill in the the bug report form you've posted with info on what went wrong and on what system you are playing (PC/Laptop, Windows/Mac/Linux, ...). Furthermore, the game log will be helpful - it should have shown up in the CrashReporter with options to upload it or copy&paste to this issue.

**Comment by Cervator** [comment]
Closing from (total) lack of detail :(
