### ISSUE TITLE
Timer Trouble

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#227]
As noted in #224 we might eventually face a choice between more accurate clocks provided by core Java classes vs more portable clocks in LWJGL expected to work the same everywhere for LWJGL's needs. That's not really a rush item, however, so leaving this here for later tweaking, especially when we've got more exposure to the platforms we might encounter issues on (for this one it was Mac)

Copy pasted links:

http://lwjgl.org/forum/index.php?topic=3177.0
http://lwjgl.org/forum/index.php/topic,4452.0.html
- http://lwjgl.org/forum/index.php/topic,4452.msg24209.html#msg24209

**Comment by msteiger** [comment]
I think we can close this issue. Pinging @mkienenb for confirmation.

**Comment by rzats** [comment]
Closing as (most likely) obsolete.
