### ISSUE TITLE
No UI Animation System (Required for Terasology/Breathing#4 and #1639)

### ISSUE THREAD

**Issue by viveret** [MovingBlocks/Terasology#2271]
There is not any UI animation system (to my knowledge) to support these features / fixes, which would be required by Terasology/Breathing#4 and #1639. What can we do about it?
I'm thinking something along the lines of [Android's method](http://developer.android.com/guide/topics/graphics/view-animation.html) of animation using a formatted text file (like JSON) to specify animation details.

**Comment by msteiger** [comment]
Interesting suggestion. In my opinion, such a formal specification would be overdoing it, though.

I'd rather define a set of Java classes that define basic animations and put that in `engine`. Modules can use those out-of-the-box or define their own animations by overriding the `update(float)` method.

Such animators exist already for in-game entities: https://www.youtube.com/watch?v=0sAIA1eaUPQ
Code: https://github.com/Terasology/ItemRendering

I might be able to help working on the specifics.

**Comment by Cervator** [comment]
Trying to work this out in my head - the health bar currently shows changes as the player gains / loses health. Is that just a UI element that's updating or an animation?

Once upon a time in legacy @small-jeeper had added a decoration where the toolbar would roll out (with some cogs on the side and everything!) into the full inventory. Was pretty neat but pre-NUI so it didn't get converted. Is that more of an animation than a simple update in the UI?

IIRC you can bind UI elements to a backing data element so they get updated automatically. I don't actually know off-hand how the health bar updates, either in Core or the hunger/thirst in Josharias Survival or Throughout the Ages.

Would animation be more for taking updated data (say 1-10 for health) then mapping each value to a specific state of a custom UI element like a paperdoll representation of the player's health? Sort of like you say specifying stages in a JSON file?

**Comment by viveret** [comment]
There would be default time and value interpolators for traversing animations, and the json file would describe starting and ending conditions. 

The health bar currently just renders whole or half icon images without transition.

**Comment by viveret** [comment]
Based off the ideas on [Android's Animating Resources](http://developer.android.com/guide/topics/resources/animation-resource.html)

FrameComponent (basically a component that changes):
- [ ] References to values or Objects to transition from / to

Frame:
- [ ] List of frames components

Base Animation Mutator (Transitions between 2 or more frames):
- [ ] From and To frames
- [ ] Time delay and duration
- [ ] Type of interpolation (linear, quadratic, exponential, logarithmic, square inverse...)
- [ ] Repeat (set number (once, many), infinite)
- [ ] Repeat mode (repeat, reverse)

**Comment by msteiger** [comment]
Hmm .. interesting. A simple specification in JSON UI files and implementation in Java might have some potential.

I think the referenced objects shouldn't be `Component` instances - maybe `UIWidget` instances? This would be in analogy to how layouts refer to widgets.

Maybe you can try that out along one or two simple examples: UI buttons fading in/out when a screen opens or HUD elements moving in/out from the border (remember Warcraft 3 menus?)

**Comment by viveret** [comment]
Component in the generic sense of the word and not any sort of existing Component implementation. I mean components like rotation, translation, color, alpha, size, etc.

**Comment by viveret** [comment]
@Cervator Should I open a pull request (that shouldn't be merged until its finished) so that we can view the animation code?

**Comment by Cervator** [comment]
@viveret If you've already got some code to review (cool!) then sure :-)

**Comment by Cervator** [comment]
Closing as complete! Go forth and animate all the things! :D
