### ISSUE TITLE
DefaultCelestialSystem does not fire its time events

### ISSUE THREAD

**Issue by LadySerenaKitty** [MovingBlocks/Terasology#2276]
I don't think the DefaultCelestialSystem is correctly firing off its time-of-day events.  This could hamper module developers, and maybe even development of Core and engine parts.

### What you were trying to do
Trying to receive the OnMidnightEvent during module development.

### What actually happened
Did not receive OnMidnightEvents.

### How to reproduce

* Develop a module.
* Add a listener for OnMidnightEvent.
* Test-run the game with the module.

### Log details and game version
No relevant log entries.  Terasology 1.0.0.

### Computer details
Apple iMac
quad-core Intel i7 3.1GHz
16GB memory
Nvidia GeForce 750M 1024MB
Oracle Java 8u77

**Comment by planetguy32** [comment]
I think I see what's wrong here, PR incoming.

**Comment by Cervator** [comment]
@LadySerenaKitty this is fixed now, feel free to adjust your calendar stuff if it makes a difference :-)

You can confirm with Seasons - it should now output its little log statement at midnight.

**Comment by LadySerenaKitty** [comment]
Yay!
