### ISSUE TITLE
Visually distinct UI elements for enabled/disabled (and support for more disabled types)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2277]
*Edit: Started as a plain follow-up to #2274, after #2280 I'm hijacking it for a bit more detail, see new todo list below*

We can disable checkboxes now, huzzah! Yet they look the same. We should make that (and similar) situation appear more unique / grayed out :-)

A few more details in #2274 and maybe related to #2275 as well.

While in the main menu you can still access the game console and `showScreen migTestScreen` will show a screen with a bunch of test elements on it (close with `ESC`) - good place to test all the elements both for functionality, disable/enable, and visual distinction.

- [x] `UIButton` - done!
- [ ] `UISlider` - no disable support (so naturally no look either)
- [ ] `UIDoubleSlider` - no disable support (so naturally no look either)
- [ ] `UIText` - can be disabled, but doesn't have a unique look yet
- [ ] `UIDropdown` - can be disabled, but doesn't have a unique look yet
- [ ] `UIDropdownScrollable` - can be disabled, but doesn't have a unique look yet
- [x] `UICheckbox` - kinda done - very faint difference in appearance? Could be more distinct?
- [ ] `UIList` - no disable support, buttons have visual distinction so may just need the support
- [ ] `UIBox` - N/A ? Not sure why we would disable one of these or have it show differently. Maybe if you're grouping elements and want to show the entire group as disabled (like a part of a tech tree you haven't gotten to yet) ?
- [ ] `UIScrollbar` - can be disabled, but not sure if it shows well enough on the test screen to see a difference in appearance?
- [x] `UISpace` - included for completeness, but pretty sure this one is N/A
- [ ] `UILabel` - *MISSING* from the test screen, but otherwise supported and distinct (#2280) - just need to add it to the test screen for completeness

Any other elements? Please comment if so, we might as well catch em all!

**Comment by Cervator** [comment]
Bump - rewrote the initial description some with a nice todo list based on `showScreen migTestScreen`

Since we surprisingly have 3-4 different contributors suddenly working on UI topics please post a note of interest here if wanting to do it so we don't end up with overlap :-)

**Comment by tdgunes** [comment]
I can send PRs for this issue. Would be great to if you can assign this one to me.

**Comment by Cervator** [comment]
Hehe done! Via bot noticing your submitted PR. I love it when automation works :D

(granted, had I been awake 5 hours ago I might have been able to beat the bot to the assignment step)

In any case the comment alone is good to have to avoid overlap so yay!

**Comment by tdgunes** [comment]
Kudos to our bot, I didn't know that it's smart. 👍
