### ISSUE TITLE
Update translations for view distances

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2285]
With #2279 we have updated names for the view distances. Need to apply the updated keys to other language files manually then translate where able. If a language seems inactive/incomplete just mark it "fuzzy" in Weblate later (that's kinda what that's for, right?) or maybe blank it out / use a placeholder+fuzzy.

Note that the values aren't actually used yet, pending PR #2226 does that (if anybody wants to help bring that one fully up to date and apply and final tweaks feel free!)

I'm also noticing that `menu.lang` still has the old key names (may be fixable on this issue or the PR?)

`menu_en.lang` before:

```
    "video-preset-custom": "Custom", 
    "video-preset-epic": "Epic", 
    "video-preset-insane": "Insane",
    "video-preset-minimal": "Minimal", 
    "video-preset-nice": "Nice", 
    "video-preset-uber": "Uber",
```

After (the preset message is new):

```
    "video-preset-message" : "Does NOT change view distance or field of view",
    "video-preset-custom": "Custom", 
    "video-preset-minimal": "Minimal",
    "video-preset-low": "Low",
    "video-preset-medium": "Medium",
    "video-preset-high": "High",
    "video-preset-ultra": "Ultra",
```

Language list for updates:

- [ ] Czech
- [ ] French 		
- [ ] Galician 		
- [ ] German 		
- [ ] Italian 		
- [ ] Japanese 		
- [ ] Polish 		
- [ ] Portuguese 		
- [ ] Romanian 		
- [x] Russian 		
- [ ] Spanish 		
- [ ] Swedish
- [x] Ukrainian

Maybe this would be a good way to help keep keys updated when we make changes? I think we've missed a lot of these, leading to messy `.lang` files.

**Comment by MottaTheHutt** [comment]
ah, I forgot to update these! I'll update the values in menu.lang and add an entry for the new preset-message.

I'll also update the key values in all of the alternate language files, since these would be needed for proper functionality. As for updating the literals into their respective languages, I can try my best?

**Comment by rzats** [comment]
@MottaTheHutt: I think the best solution regarding updating translations is to use English strings as placeholders (empty strings will NOT fallback to English strings, breaking the interface instead) and let Weblate contributors translate them eventually.

Also, here's two translations for the new strings that can be used in the initial PR:

**menu_ru.lang**
```json
"video-preset-message" : "НЕ меняет дистанцию или угол обзора",
"video-preset-custom": "Пользовательские",
"video-preset-minimal": "Минимальные",
"video-preset-low": "Низкие",
"video-preset-medium": "Средние",
"video-preset-high": "Высокие",
"video-preset-ultra": "Ультра",
```

**menu_uk.lang**
```json
"video-preset-message" : "НЕ змінює відстань чи кут зору",
"video-preset-custom": "Користувацькі",
"video-preset-minimal": "Мінімальні",
"video-preset-low": "Низькі",
"video-preset-medium": "Середні",
"video-preset-high": "Високі",
"video-preset-ultra": "Ультра"
```

**Comment by MottaTheHutt** [comment]
Thanks! I can put in English placeholders for the other files if you think that would be a better idea than attempting to translate. The preset-message is really the only thing I'm worried about trying to translate.

**Comment by Cervator** [comment]
PR #2285 was merged which covers the keys + placeholders. Need to update the Weblate branch and see how it looks there, then see what's left on this issue.

**Comment by skaldarnar** [comment]
How do English placeholders show up in Weblate? Ideally we want Weblate to highlight missing translations, probably need to support fallback when the having empty strings in the translations.

**Comment by Cervator** [comment]
> How do English placeholders show up in Weblate? Ideally we want Weblate to highlight missing translations, probably need to support fallback when the having empty strings in the translations.

I know we've hit this point a couple times, although I can't remember the details. @msteiger or @Halamix2 might. I do remember that leaving keys in a file without values didn't go well :-)

I'm thinking for non-English files any key with a value matching the English value get flagged in Weblate as either untranslated or fuzzy / warning over being identical. But I don't remember what happens for instance when a word actually matches between English and some other language.

Plenty of our language files are also missing entries entirely, for instance Czech for the CR: http://translate.terasology.org/projects/crashreporter/crashreporter/cs/ - it seems to be catching the total number of expected strings, yet only leaves entries for translation in the UI for keys that do exist? Quirky.

**Comment by Cervator** [comment]
Closing this as complete - almost all the translations have trickled in and the PR putting them to use was merged a while ago.
