### ISSUE TITLE
Hello-World

### ISSUE THREAD

**Issue by mertcanerso12** [MovingBlocks/Terasology#2292]
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by SkySom** [comment]
@mertcanerso12 Hello! Though I'm not sure what you are saying here? Did you have an issue, or did you just want to say hi! If you wanted to say hi, I suggest going over to the forums at [forums.terasology.org](http://forum.terasology.org/forum/contributor-introductions.7/) and introducing yourself!

**Comment by Cervator** [comment]
Closing from lack of follow-up
