### ISSUE TITLE
Thread pool model update / salvage old PR

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2294]
Creating this issue in favor of keeping PR #1760 open any longer. There may still be value in those changes to salvage but I'm not sure @prestidigitator will have time to get back to it any time soon.

Just in case to safeguard the branch I've made a copy in our test org repo: https://github.com/Nanoware/Terasology/tree/threading

Not necessarily a topic for the faint of heart, threading is fun!

A good usage of a thread pool is the work / task system in Light & Shadow (or even Miniion/MasterOfOreon), although it admittedly may not be in the best shape itself.

Maybe related: #1770, #1737, #1296

Edit: An additional topic here could be adding some configuration for thread pools, such as limiting chunk generator threads to available cores minus 1 or 2 (min 1, of course). World gen can _really_ chew through processing at times, to the point where a poorly cooled system or one doing a lot of multitasking could hit some trouble.
##

**Comment by pollend** [comment]
superseded by : https://github.com/MovingBlocks/Terasology/issues/4798
