### ISSUE TITLE
Inventory related behavior on right-click

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2295]
Follow-up from #2262 after which you can now left click with a held stack from an inventory to drop the stack outside the inventory where it drops to the ground.

Discussion in the PR touched on what to do with what kinds of clicks. At the same time playing with the inventory and comparing to MC I'm remembering that with MC right click with a held stack over an inventory cell drops a single item from the stack into that cell.

Currently we just have right click on a stack == pick up half. Maybe we should go ahead and add right click *with held stack* == drop one item into cell. With #2262 merged we could do the same to drop single items from an inventory. You could just pick up a single item and drop it that way but if we add it for inventory cells I figure we might as well add it for dropping :-)

Regular right click in the world will activate an item but I figure that is distinct from working an inventory and holding a stack on the cursor.

Slightly related / similar: #2101

**Comment by genuinelucifer** [comment]
@Cervator If I understand correctly, it is required that while left click (outside the grid) drops the whole stack. Right click (outside the grid) should only drop 1 item from the held stack...
I'm submitting a PR for this in a few minutes.

**Comment by Cervator** [comment]
Cool :-)

That approach makes sense to me but I mainly wanted to bring up the options we have for what to do next. I think it would be a sensible approach especially combined with *right click on inventory cell while holding stack* -> drop 1 quantity from held stack if possible.

**Comment by genuinelucifer** [comment]
@Cervator Please review #2296

**Comment by Cervator** [comment]
Will too, going to bed for tonight though. Also would like to see if @flo is OK with the approach.

Want to look at how to do something similar when right clicking a stack into an inventory cell?

**Comment by genuinelucifer** [comment]
Great. Good Night :)

**Comment by flo** [comment]
I would have preferred right click to activate an item, but having it drop 1 item is better than nothing. With right click activating an item it would be possible to add item to item interaction. e.g.when you have a axe selected and right click a wood block it could split up  in planks. Or item to world interaction. e.g. someone might add a block selection window that is displayed at the right where you can directly pull from items into the world. Pining @Josharias  and @MarcinSc for feedback as they are content creators.

**Comment by flo** [comment]
Against right click for 1 item drops speaks:
* It is already possible to pickup (and then drop single items with a mouse wheel)
* It is already possible to drop single items with the mouse wheel when you have a stack picked up
* We could use it for item to item and item to world interaction.

For it speaks:
* Users that have used minecraft before might expect this behavior
* Scrolling the mouse is not as comfortable as a right click, when dropping 1 item is something often used in a gameplay module
* Right click functionality might be more easily discovered, mouse wheel scrolling might be made later on to scrolling an item list?

**Comment by Cervator** [comment]
>  With right click activating an item it would be possible to add item to item interaction. e.g.when you have a axe selected and right click a wood block it could split up in planks.

Very good point! I totally missed that possibility and was more thinking about how weird it might be to set off TNT by accident while trying to move it around in an inventory. 

... which actually could also be amusing in a different way ... :D

I think that might call for a separate little mini-project to play with. It would be a whole new (and powerful) interaction mechanic.

Although: Couldn't we actually have both? Make it default behavior to drop a single item from a stack into an inventory slot. But if you're holding a saw then right click a cell with a sawable item in it then do the item interaction instead. Seems like that would fit right in with the entity system. 

If the held item has one component (say `Saw`) then first attempt a check to see if there is a target item with another component (say `Sawable`) and if so then do that interaction, if not then fall back on default behavior and just place the held item into the slot.

**Comment by flo** [comment]
hmm, having both makes it to complex. I think the interface should have simple rules like "right click drops 1 item" or "right click uses item". I don't have strong feelings about it, I just wanted to give the pro & contra.

**Comment by Cervator** [comment]
I went ahead and merged the related PR but am reopening this since the issue was only half addressed. Right click with a stack outside an inventory now drops one item which is pretty handy (thanks @genuinelucifer!), but right click on a cell in an inventory still does nothing.

I think there's potential to discuss the issue further in connection to some of the forum threads related to default mouse and related behavior. Will try to pull together the related threads over the next few days :-)

In the meantime if it is easy we could consider adding the simple option of right click in inventory cell -> insert one item from the held stack. Then close this out in favor of a later feature request coming back with something more interesting from the forum.
