### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2297]
Hola! @Cervator has created a [ZenHub](http://www.zenhub.io) account for the **MovingBlocks** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

---
#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.
#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:
- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.
### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @Cervator._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)
##

**Comment by Cervator** [comment]
@Josharias I'm finally playing with this more seriously. Was wondering how this issue creation thing would actually make a team though. Have you spotted how that all works? If you've got a working personal setup for JS how would you go about making it visible for another user?

Probably it is in the docs somewhere, I was just wanting something to play with for a few minutes before bedtime. Will look at it more tomorrow :-)

**Comment by MaloJaffre** [comment]
Yes, it works for me.

**Comment by rzats** [comment]
While browsing GitHub stuff with the addon installed, I've noticed that DestinationSol's [great convergence PR](https://github.com/MovingBlocks/DestinationSol/pull/22) seems to have an estimate of "40".

![image](https://cloud.githubusercontent.com/assets/13783592/14636816/5347404c-0636-11e6-9a64-db51710a2c87.png)

Don't see any logs related to this (i.e. _User X has estimated this at 40_), so it might have been automatically generated somehow?

**Comment by Cervator** [comment]
I have a vague recollection that I tested ZenHub once in the past and probably did the 40 estimate way back then as it was the highest value I saw :D

And yeah since ZenHub is a browser addon that wraps existing GitHub I figure they take a few shortcuts like literally wrapping some of the page elements (probably harder to insert timestamped status message into the main stream of items)

**Comment by rzats** [comment]
The estimate changes are actually logged now - see below for an example!

![ZenHub estimate logging screenshot](https://cloud.githubusercontent.com/assets/13783592/14647999/d2a9a37a-0668-11e6-955c-6d7facb654bf.png)

Might just be a feature added sometime after the point you were testing it, I suppose  ¯\\\_(ツ)\_/¯

**Comment by Cervator** [comment]
Looking good. Been playing with it a bit in Nanoware/Terasology. 

I turned https://github.com/Nanoware/Terasology/issues/31 into an Epic and on the board there "merged" in MovingBlocks/Gooey. Then I could add an issue from the Gooey repo to the epic on Nanoware/Terasology. 

I could even make a separate Epic in the Gooey repo, add issues to it there, then add *that* epic to the *other* epic. So dependencies and what have you. Should be useful!

**Comment by Cervator** [comment]
After this was initially experimented with GitHub released projects, and IMHO ZenHub got a bit laggier and crowded ... am leaning toward trying to stick with the native UI (worked decently for GSOC 2017). Still considering available options and am always up for discussing needs vs what's available, but figure this issue is probably OK to close at this point.

**Comment by emanuele3d** [comment]
I agree. Projects seem to duplicate pretty much the whole ZenHub functionality.
