### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Gooberpatrol66** [MovingBlocks/Terasology#2300]
http://pastebin.com/fcNcJZaM

**Comment by Cervator** [comment]
Hi @Gooberpatrol66 - it helps if you actually include some details about what is going on. Hard to troubleshoot with a single link to a log.

From what little I can see it looks like you're running the game from source? And the logs stops after `Initializing display` so if I go on the assumption the game is crashing then likely you're attempting to run the game with an older or weaker video card, or some similar issue, and it stalls during graphics initialization.

Most those issues are fatal, with the usual options being to make sure you are using the latest graphics drivers and/or if you have an unusual video card setup that you're using only the better card with the right driver.

**Comment by Gooberpatrol66** [comment]
>From what little I can see it looks like you're running the game from source?
running ./gradlew game

>so if I go on the assumption the game is crashing then likely you're attempting to run the game with an older or weaker video card
Quadro FX 880M with 340.93 driver

**Comment by Cervator** [comment]
Thanks for the details :-)

We've had known issues with Quadro cards in the past since they are aimed at graphics workstations not games. I expect that'll be similar with other LWJGL-based games. Does Minecraft or similar Java-based games run OK on that system?

If it is a fundamental issue with the focus for the video card there may not be much we can do. If it is Terasology specific then we may be able to, but it would take some effort and volunteering to narrow down the details (none of our regulars have Quadros that I'm aware of)

**Comment by Gooberpatrol66** [comment]
Installing xrandr got it to work.

**Comment by Cervator** [comment]
Thanks for digging deeper! I do believe that has come up once or twice in the past but I'm unsure if that should fall under game troubleshooting or initial OS setup for gaming. We even have it noted in the wiki:

https://github.com/MovingBlocks/Terasology/wiki/Common-Issues

(presently near the bottom)

**Comment by emanuele3d** [comment]
@Gooberpatrol66: it would be really useful if you can find the log with the error. @Cervator can maybe pitch in to say where to find it. 

We typically have problems with older or integrated graphic cards that do not support OpenGL capabilities Terasology requires, i.e. OpenGL 2.1. This is the first time I see a problem with a Quadro. I just checked the specs of the FX 880M and I do not see any obvious shortcomings. If you could post a log with an actual error I can have a look at it and in the best case scenario fix a bug or in the worst we can associate in the documentation the specific error you faced with your solution, installing xrandr.

Please let us know!

**Comment by Gooberpatrol66** [comment]
A log besides the one linked in the pastebin? Where would that be located?

**Comment by Cervator** [comment]
@Gooberpatrol66 you *may* only have the one log file if the game crashed/stalled immediately. If our CrashReporter popped up and that was the only tab then yeah that's the only file.

Game logs are put in a game save directory stored in your user home, varies a bit based on OS.

I suspect a mid-graphics initializing crash without much if any more detail though.

**Comment by Gooberpatrol66** [comment]
>If our CrashReporter popped up and that was the only tab then yeah that's the only file.

yeah that happened.

**Comment by Cervator** [comment]
Yep that's the whole log then. I'm not sure how we'd get more debug logging without something custom :-(
