### ISSUE TITLE
Can't launch game

### ISSUE THREAD

**Issue by maxim-sheronov** [MovingBlocks/Terasology#2308]
### What you were trying to do
I'm trying to start game with launcher.

### What actually happened
When I press Play button, game crashed.
Log attached. ( I don't see crash in this log )

### Log details and game version
https://docs.google.com/uc?id=0B5l2RT_UOCXRN2tqMWdTOTkzV2M&export=download

**Comment by Cervator** [comment]
Hi @Halamix2 - the log indicates the game crashed while attempting to initialize the graphics. Some issues like that manage to crash silently without a more explicit error message.

This being the last line in the logs suggests as much:

`22:02:43.752 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display`

What video card do you have? A few times this has happened on laptops with Intel HD graphics and sometimes there is a better second video card present, but Terasology launches using the weaker Intel card.

**Comment by maxim-sheronov** [comment]
Hi!
I have GTX 970 and Intel HD 4600, but it is not used.
Also my system is Ubuntu 15.10

**Comment by maxim-sheronov** [comment]
How can I fix it? Is disabling integrated video in BIOS is only  possible solution?

**Comment by maxim-sheronov** [comment]
So, I have disabled integrated video in BIOS settings. And game started successfully. But nonetheless, I think it is a bug. 
Thank you for fast respond :)
If you can tell me some variants what I can try to launch the game with enabled integrated video, I will try.

**Comment by Cervator** [comment]
You probably have a video card management app of some sort? Both NVIDIA and ATI cards have a software suite that might include a simpler option to set what card to use per game. We have some instructions in the wiki: https://github.com/MovingBlocks/Terasology/wiki/Common-Issues (with exact steps for NVIDIA )

Yeah I wish Terasology actually worked on all the Intel cards but .. our ability to support older/weaker cards is limited :-) May improve over time but likely not in the near future.

I tweaked the log statement that ends up last in the log when this happens so it'll be easier to catch. Adding this issue to our next release for reference and considering it resolved for now :-)
