### ISSUE TITLE
Update credits to link to individual contributors

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2319]
... because I'm too lazy to do it :-)

Or it could be from there being like 100+ people on there and I'm having a hard enough time finding time to do important stuff! :blush: 

In short: Update the credits list under /docs to use `[username](url)` style link to the contributor's GitHub user page.

Alternatively for contributors without a GitHub user page can link to their forum user page instead

Bonus: Vary the username in the link if the contributor's primary nick differs from GitHub user (IRC nick, forum username, or other preference by the contributor)

Example: @begla would list as [Benjamin 'begla' Glatzel](https://github.com/begla) 

`[Benjamin 'begla' Glatzel](https://github.com/begla)`

I realize not all the contributors will easily map and I have notes that might help connect a few, but so long as the bulk gets done I'll consider this issue complete :-)

Probably useful: https://github.com/orgs/MovingBlocks/teams/contributors - the main contributors team, most are included there. Forum member list: http://forum.terasology.org/members/

Extra bonus: Find a way to multi-line the longer teams in a clean fashion, mainly the `General` category. Alphabetic sub-groups? Max 175 chars per line printed? I dunno.

**Comment by xrtariq2594** [comment]
Sure. I'll try my hand at this.

**Comment by xrtariq2594** [comment]
Okay, every section except "General" have been done.

**Comment by xrtariq2594** [comment]
Okay, around first half of "General" has been done (about 40 names or so). Around 40 left to go...

**Comment by xrtariq2594** [comment]
Alright, I pushed the updated credits to my personal repo.

Check it out [here](https://github.com/xrtariq2594/Terasology/blob/develop/docs/Credits.md)

**Comment by Cervator** [comment]
Looks good @xrtariq2594 please submit it in a pull request so we can merge it :-) Will stand by on adding new names to the credits till this is merged to avoid conflicts.
