### ISSUE TITLE
Crash after hitting blocks below surface.

### ISSUE THREAD

**Issue by gemurdock** [MovingBlocks/Terasology#2322]
### What you were trying to do

Destroy blocks after going really far down in the earth.

### What actually happened

It worked until it paused, then crashed.

### How to reproduce

Play game.
Go down far.
Start harvesting blocks and make your way upward.

### Log details and game version

http://pastebin.com/9dQFnEek

### Computer details

http://pastebin.com/aH1yZkGL

**Comment by Cervator** [comment]
Hi @gemurdock and thanks for the detailed report :-)

You are running out of memory:

22:30:45.997 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown java.lang.OutOfMemoryError: Java heap space

Our game launcher allows you to set your memory settings easily, or you can try running with command line arguments like so:

`java -Xms128m -Xmx2048m -jar libs/Terasology.jar`

That would allocate up to 2 GB of memory (2048mb). The default using the standard executables is 1 GB, but there are ways to launch the game that ends up allocating less (like trying to double-click the jar file)

**Comment by gemurdock** [comment]
Game won't start if I change memory setting.

**Comment by Cervator** [comment]
Any chance you're using a 32-bit Java? That won't be able to allocate as much memory as a 64-bit (typically 2 GB will crash 32-bit)

You'd need to run that from the right directory for it to do anything.

To check your Java:

```
C:\>java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```
