### ISSUE TITLE
Terasology Freezes and crashes when I try to open BlockPicker

### ISSUE THREAD

**Issue by mikey12345** [MovingBlocks/Terasology#2324]
### What you were trying to do
I was trying to open BlockPicker.

### What actually happened
The game froze, and eventually crashed.

### How to reproduce

* Step 1 Open terasology.
* Step 2 Create a new world, with the blockpicker module enabled.
* Step 3 Walk around, and remove a few blocks, for a few minutes.
* Step 4 Press "b", to open blockpicker.

### Log details and game version
I do not know what game version I am using, I downloaded the latest Omega build(from May 24, 2016

### Computer details
Dell Precision M4400
Core 2 Duo P7800(I think, it is 2.53gHz)
2GB DDR2 800mHz
500GB SATA HDD
Archlinux, with kernel version 4.5.4
NVIDIA Quadro FX 770M, Driver 340.96, OpenGL 3.3, 32 CUDA Cores.
[terasology_2016-05-24_11-00-11.714.log.txt](https://github.com/MovingBlocks/Terasology/files/280150/terasology_2016-05-24_11-00-11.714.log.txt)

**Comment by Cervator** [comment]
Hi @mikey12345 and thanks :-)

BlockPicker is broken at present - it is a known issue: #2248

**Comment by Josharias** [comment]
Crash bugs fixed in in BlockPicker 0.1.2.  @mikey12345,  mind giving it a try and see if it is fixed now?
