### ISSUE TITLE
Error report during the gameplay

### ISSUE THREAD

**Issue by free2geo83** [MovingBlocks/Terasology#2326]
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by msteiger** [comment]
Hi there - please fill the form and add some details on what problem you have or use the forum for a general discussion so we can help you.

**Comment by Cervator** [comment]
I had really hoped the issue template would help these empty reports, but oh well. What else can we do, I wonder - link to localized versions for non-English speakers? Probably it'll still happen.
