### ISSUE TITLE
showScreen() autocompletion breaks screen initialization

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2329]
### What you were trying to do

Open a NUI screen with the help of `showScreen` autocompletion (introduced in #2286).

### What actually happened

The screen opened fine, but was not properly initialized - more specifically, the [`ControlWidget.initialise()`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/ControlWidget.java#L25) override for the screen was never called. Any further attempts to re-initialize the screen, even without using autocompletion to trigger the console command or without using the console at all, have subsequently failed - this is caused by the NUI asset already being loaded into memory when [`NUIManager.createScreen()`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java#L258) is called; therefore, [`initialiseScreen()`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java#L325) is not called [later on in the same method](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/internal/NUIManagerInternal.java#L268).

### How to reproduce

1. In your IDE of choice, place a breakpoint at the first line of [`MigTestScreen.initialise()`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/MigTestScreen.java#L29). (Also works with any other UI screen.)
2. Launch the game in debug mode from the IDE. In the main menu, open the console and type `showScreen migTestScreen` WITHOUT using autocompletion. Verify that the breakpoint is triggered.
3. Shutdown and re-launch the game in debug mode. Re-open the console and type `showScreen mig`, then press Tab so that it autocompletes to `migTestScreen`. Verify that the breakpoint is NOT triggered and that some values are therefore not loaded properly.

Might be relevant to @tdgunes's interests.

**Comment by Cervator** [comment]
Can confirm this issue. While testing #2288 (merged to latest develop as of right now) if I used auto-completion the MigTestScreen didn't look quite right and hit an NPE on `ESC` - seemingly breaking on trying to automate the return to the main menu or something.
