### ISSUE TITLE
Remove support for italics

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#2330]
Italic font style is not sensible in CJK and other Asian fonts. I therefore suggest removing it entirely to be consistent across all languages. It also makes font rendering somewhat easier.

It is currently not used in any part of engine/Core. There are potential use cases through the HTML paragraph builder, though.

**Comment by Cervator** [comment]
Sounds fine to me. We can still color text and bold (?) for emphasis I figure?
