### ISSUE TITLE
got a crash while generating a new world for a customized experience not sure if actual bug/crash or too many modules in use at once

### ISSUE THREAD

**Issue by SDUBZ** [MovingBlocks/Terasology#2335]
###what were you doing
i was trying to create a custom experience for a world to play on

it started to load and then crashed about 50% of loading files

### How to reproduce

I had city for a world gen.
I had quite a few modules enabled if i knew where the modules were listed i would be able to show you what was selected
### Log details and game version
log: http://pastebin.com/c7QEA58g

game version: alpha 1723
### Computer details
intel i7 3700 non K
amd radeon hd 7970
32 GB of ram/ 6gb allocated
windows 10 64bit insider build 14352

**Comment by SDUBZ** [comment]
did a reread and not sure if im right but it seems to be a issue with weather manager, i am new to modding this game

**Comment by SkySom** [comment]
Probably Weather manager hasn't been updated to the newest version of Terasology. Someone may need to look at updating it. Try removing it and see if that fixes the crash for now.

**Comment by SDUBZ** [comment]
yeah loads up without the weather manager module thought it might be

**Comment by SkySom** [comment]
Closing in Favor of Issue being reported on WeatherManager Module

**Comment by Cervator** [comment]
Hi @SDUBZ - yep you are enabling too many modules, and on top of that seemingly downloading modules like the WeatherManager that aren't considered stable :-)

Ideally stick with one of the "Gameplay templates" as those are tested and usually in pretty good shape. You can play around with a few extra modules at a time and see if they work OK together.
