### ISSUE TITLE
@In fails to initialize something that works via direct CoreRegistry retrieval

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2336]
We had a bug report that the WeatherManager module was crashing the game. Found and fixed the issue, but I don't understand the cause:

https://github.com/Terasology/WeatherManager/commit/fd8b96f6a2e86ea682ec8a06535031c1215c4d9f

When using `@In BlockManager` you'd get null, while `blockManager = CoreRegistry.get(BlockManager.class);` created a valid reference.

It seems the `@In` strategy works fine elsewhere in code. Could it be related to `CloudRasterizer` being registered as a world gen plugin?

What should be the desired approach to take in this sort of scenario? What would be the new-gen `Context` way to do it?

Pinging @msteiger @LinusVanElswijk @flo @Josharias and @immortius for potential interest.
##

**Comment by Josharias** [comment]
Yup,  looks like we have not yet added dependency injection for these world gen classes.  Possibly the spot for this dependency injection would be in WorldImpl.initialize()?
