### ISSUE TITLE
Filtering modules can impact world gen availability on create game screen

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2342]
It seems a bit inconsistent exactly how to make it trigger, but the most obvious way I can provoke it is opening the "Modules" menu off "Create Game" then entering gibberish in the filter box, resulting in no listed modules. Then going back to "Create Game" suddenly shows no world generators available (regardless of what modules you actually have enabled)

I suspect whatever module context is being used for the filtering manages to slip back to the active module context being considered on the create game screen. Something needs to be reset or encapsulated better. Probably an easy fix.

![modulesfilteredfunny](https://cloud.githubusercontent.com/assets/1063833/15807932/b73ac594-2b37-11e6-9e81-63ba95a6d1f7.png)

Maybe slightly related: #2074 - as it attempted to change how stuff preloads for preview and such.

**Comment by kartikey0303** [comment]
I can try working on it. Although how should I reproduce the bug?

**Comment by Cervator** [comment]
Hey @kartikey0303 - I suggest downloading the latest Omega zip so you have a copy of all the stable modules:

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

You can both confirm it by playing the game that way and then copy all the modules (the jars under /modules from the zip) into your source workspace under /modules, excluding any modules you have in source form (BuilderSampleGameplay, Core, and CoreSampleGameplay at least)

That way you can run the game from source with all the modules present, giving you enough stuff to filter modules and replicate plus fix the issue :-)

**Comment by kartikey0303** [comment]
Removing the line `moduleConfig.clear();` around line 539 in `SelectModulesScreen.java` seems to fix the issue. Someone please confirm.

**Comment by Cervator** [comment]
Thanks for the note, will try it soon :-)

As a reminder to myself, after this we may want to add a button (a little x inside the textbox?) to clear the filtered text. Additionally we could use a checkbox that'll filter between local only and local + remote modules.

**Comment by Cervator** [comment]
I can confirm commenting that line out fixes the filtered world generators - however, it does seem to be needed, as otherwise you then can't de-select modules :-)

If you enable a bunch of modules, close the screen, then re-open it the modules from earlier are still enabled.

**Comment by nihal111** [comment]
@kartikey0303 are you working on this or can I take it up?

**Comment by kartikey0303** [comment]
The method I mentioned seemed to work. Cervator told me that he will look into it. Removing that line actually fixed everything..

**Comment by Cervator** [comment]
Oh, right, let me clarify.

Removing `moduleConfig.clear();` *did* correct the issue stated, but it then introduces a different bug: modules can no longer be de-selected (they never get cleared)

We need to figure out and maybe split apart some module-holding collection(s) of some sort. So you *can* filter in that textbox, but without having its state affect what the main create game screen thinks is available for world generation.

Probably the same collection is being used for the filtering and the world gen scanning. So by filtering you clear out the stuff you need back on the main create game screen. Something like that.

**Comment by RootG** [comment]
I am still having this issue. I don't know what causes this situation. It's very annoying and forces me to clone source code. Sometimes I see this issue even with a fresh copy.

![a](https://cloud.githubusercontent.com/assets/17679464/21342692/ee25e0e8-c69b-11e6-8bc6-fb787a4e4fe6.png)

**Comment by skaldarnar** [comment]
@RootG This can happen if the project and/or some module have not been built properly. Usually, this can be fixed (when run from source) by creating the project files again (`gradlew idea`), forcing to compile and build the game, or by force-rebuilding the project from within IntelliJ (or your favorite IDE). The available generators should show up after a restart of the game.

**Comment by RootG** [comment]
@skaldarnar I get ClassNotFoundException when I try to run game from IntelliJ. "git status" says that it's up-to-date. "gradle", "gradle clean", "gradle idea", "gradle game" any of this commands did not solved the problem. I even tried to remove compiled files/jars that "gradle clean" does not remove.
```
Exception in thread "main" java.lang.ClassNotFoundException: org.terasology.engine.Terasology
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
```

**Comment by iojw** [comment]
@RootG What worked for me when I faced this issue was running `gradlew idea jar` and then rebuilding the project from Intellij if `gradlew idea jar` alone doesn't work. Try and see if it works for you.

**Comment by Cervator** [comment]
Hi @RootG - yep that is a different issue where the workspace goes "stale" in some fashion, or hasn't fully built in the first place. We need to find a better solution for the dependency tree to force all modules to build properly in a source workspace.

Inside IntelliJ you can also force the building of specific modules if you're suspicious of their current state by right clicking their directory (under /modules) then triggering "Recompile module [x]"

**Comment by RootG** [comment]
@iojw Rebuilding the project from IntelliJ solved the problem. Thank you.
