### ISSUE TITLE
Prefabs with empty lists cause failures - add support?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2343]
Am a little unsure whether we should support this or not. I found that Signalling was crashing due to declaring empty lists in some prefabs. Fixed:

https://github.com/Terasology/Signalling/commit/675e60417bf4ef520dc5dbadbccd52cc6ca87b73

In this case the default value in the Component was an empty list anyway so I just removed the explicit declaration in the prefab.

Should we support empty lists in case somebody wants a non-empty default with an option to declare empty in a prefab?
##

**Comment by skaldarnar** [comment]
I might have hit a similar issue with the `GenericMapTypeHandler`  in #5106.

https://github.com/MovingBlocks/Terasology/pull/5106/files#diff-c6be1c5c55421730e29c41ceeb68423c1c934fad2ae12db59f9ffa1df8f0ae7cR65-R71

I believe that it should be allowed to write the equivalent to empty collections in prefabs, and we should fix those issues (if they still exist).
