### ISSUE TITLE
Sort entries in the language dropdown under player settings

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2350]
Just merged a PR that does much the same for the launcher, realized we need it here too.

https://github.com/MovingBlocks/TerasologyLauncher/pull/369

Maybe of interest to @mtjvankuik who did the launcher version :-)

**Comment by mtjvankuik** [comment]
I have made a PR in which the issue is fixed.

**Comment by Cervator** [comment]
@mtjvankuik cool but to where? :-) I don't see it under PRs in this repo

**Comment by mtjvankuik** [comment]
It took a bit longer than expected, due to some files that were committed which should not be committed. In 2 minutes i have made the PR :')
