### ISSUE TITLE
Change default gameplay template to JoshariasSurvival

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2352]
I occasionally remember we should do this, and it must be easy enough to do where I can do it real quick. Then each time I don't get around to it. So time to just put an issue in so *somebody* can give it a shot :-)

In short: Force Josharias Survival to be the selected gameplay template by default in the dropdown if it is present. Naturally after the user has made a different choice respect and return to that if the screen is reloaded.

**Comment by xrtariq2594** [comment]
I'm on it.
