### ISSUE TITLE
Avoid using the zip FSP in SaveTransaction

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#2354]
The `SaveTransaction` class uses the forbidden (eclipse speak) class `com.sun.nio.zipfs.ZipFileSystemProvider`. 

It should use `FileSystems.newFileSystem()` instead.

Pinging @flo for potential interest.
##

**Comment by Cervator** [comment]
Interesting, I thought we had evicted everything `com.sun` long ago. I see we have a couple `win32` usages too but maybe they have to work differently for OS specific stuff.

Reminds me of #1637
