### ISSUE TITLE
https://docs.google.com/uc?id=0B5l2RT_UOCXRX3JHQThKd2h6c0U&export=download

### ISSUE THREAD

**Issue by rida05** [MovingBlocks/Terasology#2371]
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by Cervator** [comment]
Hi @rida05. I understand you're trying to report an issue, but it helps if you actually explain it some, such as by reading the issue template and filling in the details.

In this case the log is clear enough to answer it anyway, I'm afraid your computer is not good enough to run Terasology:

```
21:06:55.115 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.lang.RuntimeException: Can not initialize graphics device.
...
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
```
