### ISSUE TITLE
Switch from X to checkmark for active checkboxes?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2383]
Had feedback provided that [X] could be confused as disabled ("Xed out") whereas a checkmark :white_check_mark: would make it clear that the feature is enabled.

I'm unsure how common alternative interpretations like that are, but we have a very wide audience from a vast amount of different cultures. I wonder if there are any general practices / recommendations like that in any internationalization material?

Pinging @flo @rzats @tdgunes @Josharias @Halamix2 @msteiger @LadySerenaKitty and anybody else interested in providing feedback or making the switch if it seems sensible.

**Comment by rzats** [comment]
A cursory Google search suggests that it's a fairly reasonable change :smile: 

![Google it!](https://cloud.githubusercontent.com/assets/13783592/16394928/42509d68-3cc0-11e6-9c0c-3ccfaed25231.png)

Another alternative option is using colored/non-colored rectangles for checked/unchecked checkboxes (e.g. [League of Legends](https://i.sli.mg/oOokZU.png), [IL-2 Cliffs of Dover](https://i.sli.mg/nMk0Zu.jpg)), though I don't think this would fit well with NUI's default skin.

**Comment by emanuele3d** [comment]
Quick sort-of side-question: is the license on most images stored on the Wikimedia Commons compatible with Terasology's licensing? Just looking for checkmarks leads to this page that has plenty:

https://commons.wikimedia.org/wiki/Category:Green_check_marks

But often the best icons are part of very well designed collections (Crystal Clear and Nuvola are among my favourite) and if the licenses were compatible there might be a strong case for using those, potentially modified, to deal with at least part of Terasology's icons needs.

**Comment by Cervator** [comment]
Yeah an icon set of some sort might be nice. Colored rectangles may be problematic for colorblind users, but the checkmark could always be green or something just for added (but optional) emphasis.

A lot of the Wikimedia stuff looks to be public domain so that would be compatible, yup, Although it might be faster just to make one ourselves if we didn't want to find some sort of set.

**Comment by kartikey0303** [comment]
I can try making one similar to the cross we have currently. I think we should just make one similar to the one we have otherwise we have to have a major UI change if we need to have colored ticks.

**Comment by kartikey0303** [comment]
![capture](https://cloud.githubusercontent.com/assets/14962635/16412824/e8591a60-3d4b-11e6-8093-4683a5442965.JPG)

**Comment by Cervator** [comment]
@kartikey0303 please go ahead and add one of those checkmarks in a PR, I think the last one is best, the one in the screenie is a little less obvious than the other two :-)

**Comment by LadySerenaKitty** [comment]
A checkmark is definitely better than an X from an accessibility view.  They both have universal meanings in computing. @kartikey0303 I like the third checkmark in your list.  The first is a no-go, it's too horizontal.

*flails paws*

**Comment by Cervator** [comment]
Closing as completed pretty thoroughly by first #2495 then #2500 :-)
