### ISSUE TITLE
Rendering freaks out when maximizing the game windows

### ISSUE THREAD

**Issue by ToadsworthLP** [MovingBlocks/Terasology#2392]
### What you were trying to do
Switching to maximized window

### What actually happened
Rendering freaks out completely, like this:
https://www.dropbox.com/s/eavi910v0e0kj80/bug2.PNG?dl=0

Switching back to normal window size doesn't fix the problem.

### How to reproduce

* Open Terasology on Windows
* Enter a world
* Maximize the game window

### Log details and game version
The log doesn't output any errors, everythings normal there
Version: latest build, also happens in dev environment

### Computer details
Windows 10, 64-bit, NVidia GeForce GTX 850M

**Comment by Cervator** [comment]
Thanks for the report :-) Full screen isn't tested too often so that's a good catch.

Could you check if the same issue occurs in Alpha 1? 

https://github.com/MovingBlocks/Terasology/releases/tag/v1.0.0

I just tried both Alpha 1 + 2 and full screen worked in both. Maybe it is system-dependent somehow. I've got a Radeon Win7 system with a mid-range card a couple generations old.

**Comment by Cervator** [comment]
Oh, I should probably link this to the forum thread on the diagonal issue, much more info there now I see and the issues are probably related: http://forum.terasology.org/threads/strange-constant-diagonal-artifacting.1565

**Comment by emanuele3d** [comment]
Hmmm.... they do seem pretty different issues to me... =)

@ToadsworthLP: Can you press F3 and then F6 and then cycle through debug render modes with F7 when this problem occurs? Ideally you'd capture a movie of this so I can see what you get. Alternatively, can you tell me if you just get a lot of blank screens (bad sign) or if you get a number of strangely rendered worlds (that would be good)?

**Comment by Cervator** [comment]
Sorry, rephrase: different issues, likely shared cause - something on that system isn't getting along with our rendering :-)

**Comment by tdgunes** [comment]
@ToadsworthLP can you try PR that I recently posted? Also would be great to have your visual settings (sending the logs would be ok (video settings are inside).

**Comment by Cervator** [comment]
@ToadsworthLP I went ahead and merged this after testing so the latest dev build should contain the fix. In 5-10 minutes after it builds anyway :-)

Please confirm if fixed on your system! Fixed something anyway

**Comment by ToadsworthLP** [comment]
I'll test it on Saturday or so, don't have that much time to spend,
maintaining the biggest Gronkhs Life in the Woods MC modpack out there
isn't an easy job (btw that was the reason why possibly later than
saturday, not the reason I dont have time during the week XD)

**Comment by Cervator** [comment]
No problem @ToadsworthLP, no rush at all :-)

Let us know some more about that modpack sometime, although probably on IRC or in the forum. I'm curious.
