### ISSUE TITLE
The Great Retexturing - Part 1

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2407]
This is the first batch of texture requests come about from http://forum.terasology.org/threads/needed-texture-list-let-drullkus-help-texture-all-the-things.1566 - more will follow later, but these are the more obvious textures we know need replacements first :-)

Related GDoc at https://docs.google.com/spreadsheets/d/1AxCyqn7XB6w0n52N0AAyxVuSPH0OoqU_p2jNQuKtP1U/edit?usp=sharing - will be edited some over time

Desired textures are 16x16 PNGs with I'm sure some more magic (transparency and such) but am not much of an art/3d wizard... 32x32 could work rarely as well if something should be really detailed. Expected use is in the very base of the project (the eventual Iota module series) similar to something like vanilla Minecraft with [CC 4.0 BY license](https://creativecommons.org/licenses/by/4.0/) (comparable to Apache 2.0). Later batches might be more optional and suitable for other license types.

Actual texture list for round one focus follows. There are existing textures for all/most of them, GMC! and a few unknowns (see GDoc)
- [x] BirchBark (sides)
- [x] BirchTrunk (top/bottom)
- [x] Brick (optional: extra variants like whitewashed bricks etc. See GDoc/forum for details)
- [x] Cactus (side texture, top, and bottom. Note that we have a slightly smaller cube shape for this)
- [x] Chest (likely multiple textures - optional request for a double chest)
- [x] CoalOre
- [x] Cobblestone (optional: extra variants like broken, mossy, aged, etc - see GDoc/forum)
- [x] CopperOre
- [x] CopperBar
- [x] DiamondOre
- [x] Dirt
- [ ] Glass (unsure how to draw that! Existing just has a frame of sorts, other transparency variants possible)
- [x] GoldBar (solid Gold block - there is a shininess system that can make blocks partially reflective)
- [x] GoldOre
- [x] Grass + GrassSide
- [x] Gravel
- [x] GreenLeaf (tinted for different tree types somehow..)
- [x] Ice (maybe some transparency/translucency possibilities)
- [x] IronBar (again could be shiny!)
- [x] IronOre
- [ ] Ladder
- [ ] Lava (has a separate texture strip for animation variants)
- [x] OakBark (sides)
- [x] OakTrunk (top/bottom)
- [x] PineBark (sides)
- [x] PineTrunk (top/bottom)
- [x] Plank (optional: 3 variants to match the 3 tree types instead of one generic)
- [x] RedShroom
- [x] Sand
- [x] Snow + SnowSide
- [x] Stone
- [x] TallGrass x 3 variants (billboard plants in three sizes, usually go on top of grass blocks)
- [ ] Water (has a separate texture strip for animation variants)

A few have "special" stuff attached to them. Can probably dig up some extras if needed, some/most of it is already covered in code or forum already ... _somewhere_ ... :-)

The "bars" (solid blocks) have always been kind of weird to me personally. We have a neat "ingot stack" shape that might be nice to apply bar textures to.
##

**Comment by Drullkus** [comment]
Holy crap, that's a lot o.o

**Comment by Cervator** [comment]
> Holy crap, that's a lot o.o

Haha, told you! And that's only the "high" and "critical" priority blocks we really need to replace. Again the reason I was beginning to wonder if it would be smart to start with an existing texture pack of some sort then just add the extras unique to Terasology :-)

**Comment by Drullkus** [comment]
Did you guys come up with a preferred style for the retextures?

**Comment by Cervator** [comment]
Not so far, I just made it through origin research and making the list. I think style for the base set is somewhat open-ended, but likely "mild" if that makes sense? The more novel and unique approaches are more likely for gameplay settings like Light & Shadow. 

Main importance for the base set is that they look nice in large numbers, since a lot of those textures (mainly terrain types and trees) are likely to be what gets seen the most.

If you see @glasz on IRC sometime maybe see if he's available for a quick talk, he's likely the wisest among us on such a topic :-)

**Comment by LadySerenaKitty** [comment]
Can it be SVG?  SVG would be great since texture size (16px, 32p, etc...) just means a re-export of the SVG assets to PNG.  Can be done in the client.  SVG can be beautiful if done right.

**Comment by Cervator** [comment]
I have no idea, maybe? It might be more of a "Just nobody has added support for that yet and `.png` is easy"

**Comment by LadySerenaKitty** [comment]
Come August, I'll be able to look into getting SVG rendering support into Terasology, if anyone is interestered.

**Comment by Drullkus** [comment]
Honestly, not sure about SVG. I'm also under some heat on trying to get Chisel Legacy stuff retextured 😅

I haven't touched Adobe Illustrator for ~5 years, I may have forgotten it all when I became highly specialized at photoshop. There's a new tool coming out called Shadron that really want to give a spin for minecraft mod textures, and maybe terasology too. Can I do block animations like I can in minecraft? 

What's this about Light and Dark in terasology? :o

**Comment by Cervator** [comment]
Light and Shadow the gameplay setting's art thread is over here: http://forum.terasology.org/threads/las-light-and-shadow-art-discussion.762/ - it is/was the first "novel" setting for some sort of gameplay we came up with. There are a few others :-)

No rush at all on the textures, take your time with higher priority projects!

Block animations need improvements. There are ways but:

* Lava and water use texture strips for their animations but are hard coded (ancient) :(
* The ChangingBlocks module will simply loop a blockspace through a defined series of blocks to change the texture at certain intervals (such as a plant growth system)
* The computer modules outright render something custom to in-game computer monitors. I have no idea how they work but they cooperate fine with the module sandboxing so no OpenGL hackery involved - https://www.youtube.com/watch?v=BYEX7myddBQ

Lots of other cool tools for voxel graphics these days. We've been in touch on occasion with the author of VoxelShop for instance, which is pretty cool for actual creatures. Had thoughts about embedding it in-game even :D

**Comment by skaldarnar** [comment]
@Drullkus PNG textures are fine imho. If you happen to make them as SVGs we could use a simple script to export them in different sizes. 

Which leads me to a question/suggestion: To have a texture set in different resolutions we would need different modules at the moment (can you confirm that @Cervator?). It would be a nice improvement if you could provide textures in different resolutions in a module, and offer an option to select the desired texture quality in-game. Otherwise, group modules with same name but different suffix, e.g., `MyTexturePack16` and `MyTexturePack64` in the module selection...

**Comment by Cervator** [comment]
I believe that is correct @skaldarnar although at the same time I remember there's some automated down-sampling in place *somewhere* - but pretty sure not like that.

Resolution-based modules with overrides would work but indeed be a bit more awkward than necessary. At the same time that would work right now, while texture resolution setting would both need code support plus a UI piece to select it. 

I think some initial testing showed a minimal performance hit from higher res, although I'm not sure how thorough that testing was.

**Comment by Cervator** [comment]
First round of texture updates has finally been merged via #3344, thanks @dacharya64 ! :-)

I've updated the GDoc and checked off the textures in the OP list here

@Drullkus hi been a while! Still would be thrilled if you end up with any spare times for textures here or elsewhere, tho no obligation :D

**Comment by dacharya64** [comment]
Latest commit #3346 now has retextures for everything on the list except Ladder, Water, Lava, and some of the optional variants (different kinds of brick cobblestone, double chest)

**Comment by skaldarnar** [comment]
✔️  I'll just declare this as done.
