### ISSUE TITLE
Rendering Relevant Entities

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#2412]
While working on the magic dome for LaS I came around a specific problem. The dome basically is a sphere, placed at (0,0,0). I want this sphere to be always visible right away from the start. However, when the player spawns far outside so that the chunk around (0,0,0) is not loaded, no sphere is visible. 

I'm adding a `RelevanceRegionComponent` to the entity, and once the chunk is loaded (e.g., when the player gets near enough) it stays active.
https://github.com/Terasology/LightAndShadow/blob/master/src/main/java/org/terasology/ligthandshadow/barrier/MagicDomeSystem.java#L58-L69

I'm trying to get the sphere rendered without the necessity to have the player come nearby. Is the current behavior a bug as the entity should also be rendered being relevant? Is it possible to request a specfic chunk to be loaded? 

@immortius seems to be responsible for the implementation, so here's a ping for you. Not sure who else might have a clue about this, pingin @msteiger @Josharias @flo

**Comment by flo** [comment]
Adding a RelevanceRegionComponent shoulds like a very bad idea to me as you force the server to have chunks loaded permanently that are not relevant to the user except for the sphere.

I would guess that your issue is that you create a always relevant entity during the generation of the chunk (0,0,0). So you need to the chunk to get generated to have the entity be created.

To avoid this you could create the entity in the `postBegin` of a system when the entity isn't there yet. Propably (since it seems to be a graphic that is only relevant to clients) it doesn't even need to persistent. So you could just always create a non persistent entity in the system.

**Comment by Cervator** [comment]
Yep that's already the approach: https://github.com/Terasology/LightAndShadow/blob/feature-magic_dome/src/main/java/org/terasology/ligthandshadow/dome/MagicDomeSystem.java#L67

I'm not sure but I think it goes something like this:

* If the player spawns at 0,0,0 the dome is present and being rendered, even if you then teleport far away (you can see the dome from way further away than the chunk rendering distance - thanks to the relevance thing?)
* If the player spawns far away the dome is *created* still and its effects are felt (the player is pulled toward it) but it isn't being rendered until the player gets to a distance where the "owning" chunk would load normally. Which could be further in than the edge of the dome itself.

IMHO we should try to stay away from forced chunk loading (chunk loaders in MC are a huge problem) but may need more utility in the area of chunk-independent entities (but not necessarily clog up world-level entities that never unload either). The [Sector thread in the suggestion forum](http://forum.terasology.org/threads/new-conceptual-layer-sector-plus-musings-on-multi-world-node.1420/) tries to talk a bit about all that.

**Comment by skaldarnar** [comment]
@flo I removed the code bit where I add the relevance region component. Furthermore, I create the enitity in a system, as the EntityProvider approach does not allow to load a specific location (as you said).

There referenced PR #2414 addresses the rendering as it will take the entity's relevance into account. The reason why it's not rendered in the first place was that the block at (0,0,0) was not relevant. Now, the check for relevance will be true if a) the entity is `alwaysRelevant` or the chunk is loaded.

**Comment by msteiger** [comment]
Can we close this one then?
