### ISSUE TITLE
Duplicated block ids

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#2423]
After some play-testing I ended up with duplicate block ids after reloading a world. In the first run, I cheated myself some blocks and items, including torches. In the second run (exit game, restart), placing torches on the ground still worked, but placing torches on walls would produce cobblestone stairs. 

Below are the relevant log entries with duplicate ids:

```
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:torch]
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:torch.TOP with id 79
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:torch.LEFT with id 80
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:torch.RIGHT with id 81
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:torch.FRONT with id 82
19:16:13.300 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:torch.BACK with id 83
```

```
19:24:48.701 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:cobblestone:engine:stair]
19:24:48.702 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:cobblestone:engine:stair.LEFT with id 80
19:24:48.702 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:cobblestone:engine:stair.RIGHT with id 81
19:24:48.702 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:cobblestone:engine:stair.FRONT with id 82
19:24:48.702 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:cobblestone:engine:stair.BACK with id 83
```

There was nothing unusual in the logs, pretty strage to see this happen...
##

**Comment by Cervator** [comment]
I think there are some undiscovered bugs still hiding in the block id allocation process. I've seen a similar issue if I enable a series of modules resulting in an unusually high number of allocated blocks - almost like there's still something overflowing from the `byte` range despite the block id being a `short` now. Maybe on reloading? Reminds me of #2170 in that case.

**Comment by skaldarnar** [comment]
The overall number of assigned block ids was not significantly higher, probably even under 100. Although at first I thought of the overflow issue, the number of allocated blocks was way to low for it..

**Comment by Cervator** [comment]
Might not be an overflow at all. Maybe something goes goofy in the translation between block ids and saved block tiles, maybe if textures other than 16x16 are used then coordinates end up being off - but only after reloading a world? It seems likely it'll be a composite issue like that, somehow.

**Comment by skaldarnar** [comment]
Haven't seen this in a while, likely fixed.
