### ISSUE TITLE
Increase default amount of memory assigned to the game

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2424]
At present most ways to run the game will start with a max of 1 GB memory (`-Xmx1024m`) but that's cutting it close in some game contexts. While users can increase it manually or by using the launcher it may be worth increasing the defaults within the game files themselves.

There are a few places to hit:

- [x] Launch scripts under the PC facade (easy)
- [x] IntelliJ launch configs in `config/gradle/ide.gradle` (also easy)
- [ ] ~~Compiled `exe` files for Windows (both x32 and x64 - maybe less easy)~~ Moved to #2506

The area was last touched by @shartte I believe as part of his work on improving game launching approaching the idea of embedding an appropriate Java and/or scanning for one. Maybe still out there? :-)

While it probably isn't hard to figure out I haven't tried it and can't remember much of the related details. I believe https://github.com/MovingBlocks/TerasologyJavaLauncher is involved, there are some notes under the PC facade in this repo and also a separate https://github.com/MovingBlocks/TerasologyJre repo - but pretty sure that relates more to the JRE bundling.

As for what we should increase memory to if we go with 1.5 GB that's still a safe value for 32-bit JVMs yet a nice bump in available memory by default. For the exes if this is baked in we could stick with 1.5 GB for the 32 bit exe but maybe increase the others to 2 GB.

Ideally we'd get back to work on the embedded JRE but that's a bigger topic

Low priority / nicely isolated so a good bite-size topic.

On a related note the game launcher doesn't enforce a default and will adopt whatever the game is set to unless the user picks a specific option in its config. That's probably fine so long as we keep useful defaults.

I am unsure if directly launching the game via `Terasology.jar` (if you even can anymore with it living in `/libs` but being launched one dir up) gets you sane memory settings. It may well be that uses Java standards which are way too low. I don't know if there are any good options there. Only run a starting process but then re-launch with the project default somehow?

**Comment by segfault802** [comment]
I've made this change and will submit a PR shortly.

**Comment by Cervator** [comment]
Closing as complete with #2506 having been split out into a separate issue for later. Thanks! :-)
