### ISSUE TITLE
Translation support for prefabs (and other?) assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2433]
We have translation capacity now and our Weblate instance up at translate.terasology.org but that's currently limited to strings in the UI. We need to add support to also do translation inside prefabs so an "Axe" can be translated to other languages. Logistically we also need to find an easy way to set up one Weblate project per module and maybe have a base shared dictionary for words likely to be repeatedly translated in different places.

There is an old discussion with some notes at http://forum.terasology.org/threads/internationalisation.1028/

This isn't likely to be super straight forward but may be doable by an experienced individual or be suitable for a mentoring setup of some sort.

This issue replaces old #1343 since basic translation was implemented.
##

**Comment by skaldarnar** [comment]
We are no longer using weblate. 
Closing as outdated.
