### ISSUE TITLE
Add RESTful API option to the game server

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2436]
Lots of labels on this one! GSOC-level item at full implementation.

At present administrative options for the server are minimal, pretty much entirely based on an authoritative player issuing commands via the in-game console, either gaining said authority by hosting the server through a client or using a one time permission key generated in the server's `config.cfg` 

There are also no real ways to interact with a server or world other than with a game client. No way to do a mapping website for instance. Or even editing the world save but that's more of its own item separate from this, although some dynamic modification options could fit here.

We need to change that and attaching a RESTful API to the game server seems the most sensible way to accomplish that. #929 talks about that a little but really this issue should be a prerequisite for that other one, there won't be anything to administrate until we expose some stuff. @msteiger started a little experiment with https://github.com/MovingBlocks/FacadeServer but I'm unsure how far it got or how we should architect it. 
- Do we make it a classic game facade like the old Applet facade, or a potential Android facade one day?
- Do we instead register some sub-system at startup that exposes end-points?
- Do we keep a web container setup in a different repo that you run separately to create a web front-end while it communicates with a piece of the server on the back-end?
- Can we use some existing frameworks like http://swagger.io to handle documentation and presentation for the API, to make it easier to write new functionality to target published end-points?
- Do we allow modules to somehow register API end-points that can communicate with the outside world in some way? How does that interact with the sandboxing and overall security? Maybe related to #1703

Lots of questions and things to think about! I would like to target something like this for a future major release, including it in our overall API contract, with a lot of extra effort on presentation and documentation. This is a geeky area we could present as an excellent feature for Terasology, maybe even Gestalt? Destination Sol will get multiplayer eventually, and gestalt-module + asset is nearly working on Android now! :-)

Potential things to interact with in the game via REST:
- Authenticate via web as an in-game user. Maybe by submitting your public key (ideally via #1433)?
- Run commands in the console command system, limited to your authenticated user's privileges. Example: kicking a user
- Request world details for display in a mapping app. Could this be an example of something exposed via module, such as the Minimap module allowing "export" of its display to a website?
- Show details and chat from the game (score system, death messages, that sort of thing)
- When it is possible to enable/disable modules for an existing world maybe an admin console that could do that? Or upgrade existing modules.
- Editing a game whitelist/blacklist (#1608)
##

**Comment by skaldarnar** [comment]
Adding to the list:

* creating a new world (how to share the world settings with a client)
* load an existing savegame (without restarting the whole server)

**Comment by snowyu** [comment]
FYI: 

* [OpenAPI Standard - Swagger Specification](https://openapis.org/) 
* [Swagger UI](http://swagger.io/swagger-ui/): dynamically generate beautiful API documentation and sandbox from a Swagger-compliant API.

**Comment by Cervator** [comment]
I've seen Swagger before and have been very curious about it, just haven't gotten much deeper. I guess it is just for a server RESTful API, not so much the internal modding API (just straight up java calls / javadoc). Unless there's some clever way to (ab)use it for that somehow :-)

@snowyu are you familiar with it any? Interested in investigating it and comparable tools a bit further?

**Comment by snowyu** [comment]
There are other available frameworks that have gained some popularity, such as RAML, APIBlueprint, etc to describe your API using a common language that everyone can understand. . But Swagger(now the "Open API Initiative"...) provides more benefits than just helping create clear documentation.

There are two main ways to take advantage of Swagger:

* design-first: This means you're using Swagger to design your API before you've written any actual code.
* code-first: This means you've already written the code for your API, and you'll be using Swagger to document your API.

The Open API initiative doesn't care of the transport and format. It care about the language of the describing API which it's human/machine readable and easily adjustable.  The [Swagger codegen project](https://github.com/swagger-api/swagger-codegen) allows generation of both client libraries and server stubs from a Swagger definition. You can write your own codegen too.

* transport: /HTTP/CoAP/...
* format: Json/bson/xml/yaml/...

Reference:

* https://www.infoq.com/news/2016/01/tony-tam-oai-initiative-swagger

**Comment by Cervator** [comment]
Oh I certainly don't doubt it for the *server API* and I think it would be cool to do design-first then generate some code and simply hook up the stubs to the correct code in the game server. 

I was curious if it might be somehow possible to use it to generate *internal API* docs on anything exposed in the Modding API (which would be vastly more than we'd expose via REST from the game server). Like documenting all our `Event` classes in a nice way to make them more discoverable - yet those would have nothing to do with any transport endpoints, they're pure Java-to-Java :-)

We got the JavaDocs, just not a pretty way to highlight *just* the stuff we expose to modders writing module code. So classes annotated with `@API` for instance.

**Comment by snowyu** [comment]
I think the most internal API should be organized via the resource(REST) way. if so you can write your customized codegen to do such thing. but the interactive document feature(sandbox) is lost, or write an interactive document mod to it. That's great.

**Comment by msteiger** [comment]
Yes, this is plan - also swagger is being used. We're starting with code and create a swagger doc. from it. This has not yet been done. Basically there's two options: create the swagger.yml during the build/deployment process and to serve it live from the running instance.

Maybe you want to dig into the server facade? https://github.com/MovingBlocks/FacadeServer

**Comment by hybrideagle** [comment]
I figured I'd add my 2 cents on the issue.
It's probably better to do this directly from the engine, rather than from a facade, since we would want support for this with our current facades, and the facades aren't supposed to have much logic in them anyway. Here's what I think we should do:
1. Set up an internal network manager like [this one](https://github.com/MovingBlocks/Terasology/pull/2618). 
2. Create a server-handler framework for translating HTTP requests to Events and back, probably using something like [nanohttpd](https://github.com/NanoHttpd/nanohttpd). 
   - First, you would tell the framework to create a service and define its Socket interface.
   - Then you would give it a series of Translators(Processors?), which would be responsible for receiving a request for a single HTTP endpoint url, and converting the request to an event.
   - When a client sends a request to the Socket endpoint, the Socket would trigger a method in the framework, which would then trigger a method in the Service, which would send out an Event(Voice of God, I guess?) with an id, and long-poll for responses. 
    - The handling System would listen to that event, and then call the Service's `completeRequest(ResourceUrn endpoint, string json, int returncode)` or something. There could be another layer here to handle the complexities of the HTTP protocol. 
    - The framework would then send the data out, and complete the request.  
3. Create Systems that handle the events, and collect the relevant data, JSON-ify it, and send it back to the server-handler to complete the request.
4. Throw a Swagger API over these endpoints(code-first or design-first, either works).
(Note: this is descibed for HTTP requests, but it could fairly easily be extended for any generic protocol, or even a message queue, using something equivalent to topics.)
@Cervator @snowyu  what do you guys think?
Also, I'm considering working on this for GSoC. Is anyone willing to mentor me?

**Comment by snowyu** [comment]
Just for your hint, there are another way too If you wanna do it directly into the engine. 
Use the reflection mechanism first. No translate HTTP request to events back.
Which means:

* Class is resource.
* A series of conventions methods: such as prefix `get`, `create`, 'delete', 'isExists'  map to HTTP Methods. or annotations.

* A codegen could generate the source code scaffold.
* A Manager could collect these classes , execute restful methods and make swagger api json/xml.
* And then the transport layer(server-handler framework) could  use these information(through the manager) too to execute http/tcp RPC.

**Comment by gianluca-nitti** [comment]
For reference, if anyone is interested, I'm working on the features proposed in this issue as my GSoC 2017 project. Here are some relevant links:
- Main repository: FacadeServer ([MovingBlocks upstream](https://github.com/MovingBlocks/FacadeServer) - [fork with my branches](https://github.com/gianluca-nitti/FacadeServer/branches))
- [Project board](https://github.com/orgs/MovingBlocks/projects/5)
- [Devlog website](https://gianluca-nitti.github.io/GSoC-2017-devlog/) (based on [this template](https://github.com/MovingBlocks/DevlogTemplate))
- [Project page on the Google Summer of Code website](https://summerofcode.withgoogle.com/projects/#4882946033975296)

**Comment by Cervator** [comment]
Closing this as completed by @gianluca-nitti as part of GSOC 2017 - huzzah! :-)

See https://github.com/MovingBlocks/FacadeServer for the implementation of the new facade that lets a server be more readily controllable. See https://gianluca-nitti.github.io/GSoC-2017-devlog/ for a bunch of nifty blogs about all the work that was done.

Thank you so much @gianluca-nitti! And mentors @msteiger & @skaldarnar 

Lots more that *could* be done, but thrilled to have taken this first giant step :-)

**Comment by fioresarro** [comment]
@gianluca-nitti is it possible send me a private message? Thank you in advance.

**Comment by gianluca-nitti** [comment]
@fioresarro yes okay, I just sent you an email.
