### ISSUE TITLE
Tutorial: Transitioning to "The Terasology Way" of thinking, for MC modders

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2444]
It has come up from time to time that there is a distinct way of thinking/architecting for Terasology if you're used to modding for something like Minecraft. We sometimes refer to it as new contributors with a MC background getting to a point where the ideal usage and advantages of our entity system just sort of _clicks_ and you get the distinction, but we don't have any good tools to help people get there. Just the existing sort of _objective_ presentation of how the entity system works in general, plus some tutorial work on how to code for Terasology.

If we put some MC flavored examples in a tutorial to help convert design thoughts from typical ways to do a few things in MC (very block centric?) to how it can be done better in Terasology (very entity/event centric?) that might help out MC modders _click_ faster, rather than first dig a frustrating hole of MC style coding within Terasology's architecture - which could easily end any interest in further coding..

It would also allow us to keep existing tutorials _objective_ in the sense of purely covering how to do something in Terasology, not talking about how that is necessarily different from anything else.

Difficulty: we would really need somebody who is already familiar with both sides to do this. Not to mention the usual time availability and affinity for writing good tutorials / docs.
##

**Comment by DarkWeird** [comment]
https://github.com/progwml6/ironchest (https://github.com/cpw/ironchest)

As a source, we can use the MC Iron Chest mod.
It was introduced as a reference implementation in early Forge(aka Minecraft ModLoader) by Forge developer.
this will demonstrate the difference in side-by-side style.

**Comment by skaldarnar** [comment]
Closing as out-of-scope.

We are improving on the documentation about how to use Terasology's ECS, for instance in https://github.com/MovingBlocks/Terasology/wiki/Event-Types. Specifically writing a "migration guide" for Minecraft modders is not planned.
