### ISSUE TITLE
Tooltip message that ends up hitting the right side of the window starts "vibrating"

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2452]
I am guessing it is trying to adjust itself in some fashion to fit on screen while also being centered on the mouse cursor, but should probably instead just chill out and sit still even if it can't be perfectly centered on the cursor anymore :-)

Noticed it with the Potions module with a potion (so a more substantial tooltip message) in the right-most toolbar slot.
##

**Comment by Cervator** [comment]
@nihal111 reported this does not appear to happen in the behavior tree editor for some reason:

https://usercontent.irccloud-cdn.com/file/JmYCWs6S/%232453

Yet I retried with potions and after `giveitem doublejumppotion` placed a potion in the right-most tool slot at default resolution and it still sort of blinks in and out:

![terasology - j__dev_terasology_git_integrate_terasology - pc - intellij idea 2_2016-10-04_22-36-09](https://cloud.githubusercontent.com/assets/1063833/19099323/4b5cee46-8a83-11e6-8df0-13306ed362d0.png)

**Comment by segfault802** [comment]
I'd like to try tackling this.  An interesting observation I made while testing: Hovering the mouse in the empty space below the 2nd line of text causes the flickering to stop.  After seeing that multi-line tooltips are stored in a UIList I tried running it with my fix for issue #2508 (pending PR #2546) and this "safe zone" disappears.

I also noticed that the tooltip doesn't have any problems when it only has to offset horizontally from the mouse pointer (by placing the potion in the inventory and narrowing the window).  Other items with short multi-line tooltips don't have a problem with vertical offsets when placed in the toolbar and hovering the mouse at the bottom edge of the screen  It seems to be a combination of both vertical and horizontal offsets that triggers this.

**Comment by Cervator** [comment]
@segfault802 great! Go for it

Would assign to you but you'll need to accept our org invite at https://github.com/MovingBlocks first - please let me know when you do :-)

**Comment by segfault802** [comment]
I fixed this by adding a flag to UIList that can be used to make it non-interactive.  This way tooltips can be rendered without drawing creating an interactive area.  I could have probably just piggybacked the existing selectable flag but wasn't if there was (or will be) something else that requires a non-selectable but still interactive list.
