### ISSUE TITLE
Flakey MD5 loading when models have floats with two-digit iparts

### ISSUE THREAD

**Issue by kaen** [MovingBlocks/Terasology#2464]
### What you were trying to do

Load an md5 animation and skeleton file
### What actually happened

Errors were thrown while parsing apparently valid md5
### How to reproduce

Edit the `deer.prefab` in WildAnimals to use the attached skeletonMesh or animation. The loader will throw a parse error.
### Log details and game version

Terasology develop: f5bdc4099b2d0407ebbe166d0bd8f73d6c3f81d2

```
java.io.IOException: Invalid bounds line: " ( 0.219587 0.219587 0.219587 ) ( 0.219587 16.896273 13.914334 )"
```

The files were taken unmodified from http://opengameart.org/content/boneman

Other errors are encountered if you manually edit the file to fix the one above.

I noticed that the MD5 loader float regex is dubious. It appears to only allow one digit before a decimal point? So 16.xxxx will always break it? 

https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/md5/MD5SkeletonLoader.java#L51
https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/md5/MD5AnimationLoader.java#L50

[boneman.txt](https://github.com/MovingBlocks/Terasology/files/450245/boneman.txt)
[boneman_idle.txt](https://github.com/MovingBlocks/Terasology/files/450244/boneman_idle.txt)
##

**Comment by Cervator** [comment]
Just cross-posting here from the forum to make sure it is covered - @flo posted an update at http://forum.terasology.org/threads/help-importing-minetest-player-model-skins.1593/#post-13897 having tweaked the Blender addon some more. Would be good to know if it helps this! If the RegEx still needs a tweak maybe we can cover that with this issue :-)

**Comment by flo** [comment]
yes, the regex needs to be adjusted. I haven't adjusted the bounding box calculation yet. 

The model above has a corrupt bounding box as minX and maxX is the same. 
@glasz  tried to fix it, but I think i still saw an issue where it was smaller than expected.

**Comment by skaldarnar** [comment]
@jdrueckert can this be closed now that we sunsetted md5 and switched to glTF?

**Comment by jdrueckert** [comment]
We don't use md5 assets anymore.
