### ISSUE TITLE
Automatically spawned chests start empty in multiplayer, can fix by breaking then placing again

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2474]
Scenario to replicate:

* Start GooeysQuests with a local headless server
* Connect with a client
* Get Gooey to spawn
* `e` click Gooey then select spawn a dungeon
* Find a chest, it'll be empty. 
* Same thing in single player works fine.

Can fix it by breaking the empty chest then placing it again. Suddenly it'll have its intended contents.

The following highly suspicious log statement appears during this scenario:

`22:20:49.833 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.logic.inventory.InventoryComponent) over an existing component for entity 154`

Similar / related issues to perhaps also look into at the same time:

* #1693
* #1690

**Comment by flo** [comment]
This was a bug in the StructureTemplate module. I  fixed it. The problem was indeed the addition of the `InventoryComponent`. I added a forum post about the fix.

**Comment by Cervator** [comment]
Thanks @flo - renamed the issue accordingly. Appreciated :-)
