### ISSUE TITLE
API to get away from the sandbox

### ISSUE THREAD

**Issue by SoniEx2** [MovingBlocks/Terasology#2482]
I need an API to get away from the sandbox so I can use LLVM and stuff from the game, as well as output arbitrary executable files (with the executable flag set). I also need a way to send files to the client (with a download GUI).

**Comment by Cervator** [comment]
hi @SoniEx2 - if this is anything like the thing we talked about on IRC the other day it needs *waaay* more detail, use cases, and other fun stuff, and is much more appropriate for a forum suggestion thread. It is a lot more esoteric and niche than something that's a given for implementation (the tracker here is more for bugs and enhancement requests for stuff we know we want and need)

The closest similar suggestion might be http://forum.terasology.org/threads/acoustic-renderer.1176 which is a pretty wild "out there" idea that would have a very tiny user base, yet be awesomely interesting to code if somebody wanted to dedicate the time to it.

Alternatively if you just want a fork you can play around in with security disabled that's an option too. A few such fork exists including on that is customized as a code analytics visualizer (generates a world based on number of classes, lines of code, etc)

**Comment by SoniEx2** [comment]
One easy option is to add an "unsafemods" dir that doesn't get synced and isn't accessible from normal mods, and doesn't get affected by the sandbox. For slightly better security, unsafemods should use a different loading mechanism than normal mods. That way you can't just put a normal mod in the unsafemods dir.

**Comment by Cervator** [comment]
Varying the permission system for the module sandbox is still a huge task. Much more appropriate for a suggestion thread so it can mature some before any implementation is attempted. Going to close this in the meantime.
