### ISSUE TITLE
Headless server: engine module sync on join fails (1.2.1-alpha)

### ISSUE THREAD

**Issue by qwc** [MovingBlocks/Terasology#2486]
### What you were trying to do
Running latest stable docker image. (clean installation, no old configs)
Connecting with the latest stable client. (clean installation, no old configs)
### What actually happened
An engine module sync was triggered but failed, not able to join.
### How to reproduce

* Server with latest stable docker image (you may use docker, but this issue may be triggered without docker too)
* latest stable client
* connect to the server

### Log details and game version
(Will follow, I need a more verbose logging configuration on both ends first)
### Computer details
Arch Linux, latest. (anything else needed? O.o)

**Comment by Cervator** [comment]
Heyo, thanks for the report and details earlier :-)

When I mentioned needing to add more logs I meant we may need to add more actual logging to the code :D I don't think you're missing any actual log statements due to log level settings. 

One other topic just to be sure: you were running a docker server using the alpha 4 binary (latest stable release) or very latest (develop) build? Binary in either case I take it. Client was running using binary or from source?

**Comment by qwc** [comment]
Both were the latest stable releases, not a development build.
Client was run by binary.
But I could test the latest development builds too, today evening maybe, MET. ;)

**Comment by Cervator** [comment]
Mainly wondering as running from source gets the version flagged as a snapshot, less worried about any actual recent change :-)

But if both are binary then yep, should work. I'll try to replicate it soon myself if I can find the time.

**Comment by qwc** [comment]
Well, I've now tried the 1.2.2-SNAPSHOT.

Everything works. So it's a problem of the latest alpha.
Should I switch back to the latest alpha and provide you with the hopefully good enough logfiles?

**Comment by Cervator** [comment]
It would be interesting to get more details on what broke, yeah. Just to run a sanity check I ran a binary alpha 4 headless + separate client and didn't have to sync anything, but then that makes sense, we ran a whole event based on that release so it was covered pretty well :-)

Another quite important bit of information would be how the Join Server menu appears as you attempt to connect in a situation that ends up failing to sync. For me it looks like so:

![clipboard_2016-09-20_19-53-25](https://cloud.githubusercontent.com/assets/1063833/18692952/eca7f50c-7f6b-11e6-982f-7f6ba78b1c91.png)

You see the three entries active for the server are all in green meaning the client already has the right version. If you see that and *still* got a sync process that is rather peculiar as there's no reason the sync should even happen. If you see engine at a different release level (and/or it is listed in red) then something is out of whack either on the server or client. Any chance the docker packaging process grabbed something other than what the client you were using to test got?

**Comment by qwc** [comment]
Okay, now there's a big "WTF" moment.

The only thing I can recall in my mind was that, I've seen a engine 1.0.0 there which would be quite old. Core and CoreSampleGameplay were green in the join server window, only engine was red, but currently can't tell which version at the time of failing.
Maybe there was an error setting up the docker image with alpha4 which did not catch my attention, what's almost impossible because I've followed every step on my local machine, but well still just almost.
Okay, my turn now: double double check everything is correct on image download, if that's the case, checking the image. 

Big sorry, if that turns out to be a false negative.

**Comment by qwc** [comment]
I take everything back and assert the opposite.

Damn, how embarrassing, I really started the OLD latest image (alpha1), don't really know how that could happen. Well but it happened, so the fault was on my side. ;)

With the real latest image 1.2.1-alpha everything works as expected. Sorry to have wasted your time. ;)

**Comment by Cervator** [comment]
No worries at all! Happens :-)
