### ISSUE TITLE
crash on Alpha4

### ISSUE THREAD

**Issue by snowyu** [MovingBlocks/Terasology#2488]
### How to reproduce

1. create a new DynaCity for single play.
2. enter the game
3. move around and crash.

### Log details and game version

https://docs.google.com/uc?id=0B5l2RT_UOCXRYzBYMzIxQ3MySmM&export=download

**Comment by Cervator** [comment]
Hi @snowyu and thanks for the report :-)

This is a known issue that should be fixed soon. The DynamicCities template is missing a module that contains a valid culture to create buildings for. Try enabling the MedievalCities module manually in addition to the DynamicCities template - that should provide a culture to spawn buildings for and avoid the crash.

**Comment by snowyu** [comment]
comfirmed. It do not crash after enabling the MedievalCities module.

**Comment by Cervator** [comment]
Fixed / rearranged by https://github.com/Terasology/DynamicCities/pull/24 and related changes to the MedievalCities module. The gameplay template that shows up in-game now is MedievalCities so a culture is present for sure :-)
