### ISSUE TITLE
Static components

### ISSUE THREAD

**Issue by SoniEx2** [MovingBlocks/Terasology#2499]
Inspired by #1736 I think Terasology should have "static components" - components with a fixed set of values which are only loaded once. These would be added like ordinary components, but a prefab composed solely of static components would not produce an entity (unless forced to).

Those components can be reused between entities, instead of being re-instantiated for each entity. This should save some RAM.

In addition to that, static components could be used to automatically register new block IDs, instead of registering entities. This would be GC-heavy however, as you'd have to convert a block ID into an entity (i.e. instantiate a new entity) every time something attempts to access that entity. (Altho it would provide a mechanism closer to what we currently have with block families. ... But perhaps we could have reusable entities somehow?) (Also, Java's GC and JIT are quite good with temporary objects, so this might not be a problem.)

Static components should fully integrate with block models and you should be able to apply different textures and stuff based on their values, similar to how Minecraft does it.

**Comment by skaldarnar** [comment]
I might be slow catching up, but why was this closed again? Did you discuss this on Slack, IRC, or in the forum?

**Comment by SoniEx2** [comment]
The idea here is partially bad. A better idea would be to make the .block file similar to the .prefab file as in it contains a list of entities and each entry is a separate block ID, like [this](http://forum.terasology.org/threads/move-fields-in-block-onto-components.1625/).
