### ISSUE TITLE
Add option to clear the filter textbox on the Select Modules... screen

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2507]
At present during game creation you can customize modules, and while picking modules you can filter them by name using the filter textbox at the top. However, you have to manually erase the text if you want to clear the filter.

While that isn't particular laborious it is pretty standard for filter boxes to have a simple clear option of some sort. Two ways to solve this one:

* Easy: Simply add a small independent "Clear" or "X" button by the filter label or textbox. It should clear the filter text, with the module list updating to reflect the cleared filter
* Challenging but more useful: Make a new UI widget, a variant of  `UIText` maybe named `ResettableUIText` that has a tiny little built in `x` at the right side within the text box. Clicking the `x` clears the text and triggers any regular related events as if the user had erased text (`updateOffset()` maybe among other things?)
 * Extra: If this approach is taken also add the new UI element to the UI test screen (see in-game via console using `showScreen migTestScreen`) below `UIText`

**Comment by arpan98** [comment]
I'm working on this.
My approach - Create a class `ResettableUIText` which inherits all it's data members and functions from UIText (Had to change some members from `private` to `protected`). Override the `onDraw` method and split the canvas 80-20 (or some fraction) into text-box and cross button. Subscribe a listener (?) to the button and then trigger the relevant events.
Does this look okay?
