### ISSUE TITLE
Fix offset causing excess space at the bottom of the modules list

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2508]
With the current Omega module lineup present the module list becomes *way* long too. Probably the calculated length of the scrollable field is out of whack with the scrollbar somehow. This has been tweaked a time or two in past issues, guess it is easy to disturb :-)

Example screenie:

![terasology _ alpha_2016-10-07_22-17-34](https://cloud.githubusercontent.com/assets/1063833/19209616/0b6a2780-8cdc-11e6-93a4-8ade8569060f.png)

**Comment by arpan98** [comment]
I would like to work on this issue. However I am unable to figure out the source of this issue. Tweaking the values [here](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layouts/ScrollableArea.java#L143) works in some cases, but a concrete solution can be found only if the underlying cause is identified.

**Comment by Cervator** [comment]
Sure. While I don't have any useful knowledge directly related to scrolling in the UI, I remember some past fixes, maybe looking at discussion and code fixes there will help :-)

Check out [this search](https://github.com/MovingBlocks/Terasology/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20scroll) that covers closed issues with "scroll" in them, maybe especially #2185 which was fixed by #2201 and involved a similar problem with excess space.

If that doesn't help maybe @rzats can spot something related.

**Comment by segfault802** [comment]
I'm currently looking into this...

**Comment by segfault802** [comment]
I can fix this by eliminating the style margins from the scroll list height calculation, but I don't think this is the right solution.  For some reason the canvas style reports having 4px top and bottom margins when calculating the scrollbar height but 0px when drawing it.  I still need to determine why this is happening.

(Also, didn't mean to steal this from someone else, I had done some preliminary and didn't refresh my browser before posting my previous comment.)

**Comment by arpan98** [comment]
Not at all @segfault802. I was and still am very clueless about this issue! :smile:

**Comment by segfault802** [comment]
The ended up being pretty trivial.  The UIList drawing code was getting a reference to the style margins before setting the correct part.
