### ISSUE TITLE
Having certain modules (with substantial item/block count?) causes invisible blocks in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2516]
During Alpha 5 play testing I enabled a few more modules than usual, for variety and birthday fun.
- _CakeLie_
- CheatsForAll
- ChrisVolume1OST
- JoshariasSurvival
- _Potions_
- ShatteredPlanes
- StructureTemplates

However, after minimal playing and requesting blocks via console chests and TNT would place in an invisible way. The blocks clearly existed on the server - you could walk into their blockspace every so slightly before the server pushed you back, indicating to me that the client thought the space was empty yet the server knew it was not. 

You could additionally start breaking the invisible blocks just fine and get the block breaking overlay rendered, and the block would pop. Yet you could open or trigger TNT using `e` to activate the block (maybe the client thought the space empty, so a request to activate was never sent?)

After some additional testing I suspect it has something to do with enabling enough modules to cross some threshold where there are sufficient blocks and items defined to have something go out of whack. If I disabled CakeLie and Potions I could no longer replicate the issue. 

That makes me wonder if it relates to #2423 somehow - although it isn't quite the same scenario.

The same exact module config failed to reproduce the issue in single player, so it must have something to do with client and server being separate and not matching up in some way.
##

**Comment by Cervator** [comment]
A somewhat related thought comes to mind: when you break blocks in some cases the particle effects that come off them do not always match the actual block (often you get diamond ore block particles even when breaking dirt or something). *Somewhere* there are still bugs in connecting blocks with different systems.

**Comment by 4Denthusiast** [comment]
This is possibly the same as #3095.

**Comment by skaldarnar** [comment]
Fixed by #3886
