### ISSUE TITLE
Windowed / borderless fullscreen mode

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2517]
Feature request that came in from today's play test. At present we only support regular windowed mode and regular fullscreen. Plenty of games have a nice hybrid where you can run a borderless windowed mode you can still move the mouse out of. Similar to maximizing the windowed game but that leaves in place the menu bar + task bar.

*Probably* this just involves switching the fullscreen checkbox under graphic options to a drop-down with three options:

* Normal window (default)
* Borderless maximized
* Fullscreen

Or something like that (maybe check the naming other games use)

Then affect some toggle in LWJGL/OpenGL to set the correct mode as you confirm the setting. I don't know where it is but am hoping looking at the existing fullscreen code would make this easy enough to be bite-sized.

**Comment by kartikey0303** [comment]
I can try this. In involves adding an additional dropdown for borderless fullscreen and implementing the same in LWJGL/OpenGL. Right?

**Comment by coty91** [comment]
Already took care of it.
