### ISSUE TITLE
Question - How can I install on Suse?

### ISSUE THREAD

**Issue by kholyphoenix1** [MovingBlocks/Terasology#2520]
Hello, 

How can I install on openSuse 42.1?
1. I extract the package.
2. Terminal: chmod + x run_linux.sh
3. Terminal: .\run_linux.sh

Message:

For more details, see the log files in /root/.local/share/terasology/logs/2016-10-09_12-29-35

**Comment by Cervator** [comment]
Hi there. It seems like there's a bit of the log missing :-)

You should have 1-3 files at that path, could you please attach them as full files or paste into something like a GitHub Gist or pastebin?

I take it you have a Java 8 JRE installed.

**Comment by kholyphoenix1** [comment]
Hello, install JDK 8 Update 101 both versions. (X86) and (x64).

`linux-5vsz:/home/linux # cd /home/linux/Downloads/TerasologyOmega
linux-5vsz:/home/linux/Downloads/TerasologyOmega # chmod +x run_linux.sh 
linux-5vsz:/home/linux/Downloads/TerasologyOmega # 
linux-5vsz:/home/linux/Downloads/TerasologyOmega # clear
linux-5vsz:/home/linux/Downloads/TerasologyOmega # ./run_linux.sh          
codeLocation: /home/linux/Downloads/TerasologyOmega/libs/engine-1.2.2.jar
Found the natives dir: /home/linux/Downloads/TerasologyOmega/natives
17:05:24.637 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
17:05:24.692 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=68, buildId=68, buildTag=jenkins-TerasologyStable-68, buildUrl=http://jenkins.terasology.org/job/TerasologyStable/68/, gitBranch=master, gitCommit=4d9443e2c2c12809ca04e4e6e5b33a7a87ad0a97, dateTime=2016-10-08T05:50:43Z, displayVersion=alpha, engineVersion=1.2.2]
17:05:24.693 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: /root/.local/share/terasology
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: /home/linux/Downloads/TerasologyOmega
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 1.8.0_101 in /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: OpenJDK 64-Bit Server VM, version: 25.101-b13
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Linux, arch: amd64, version: 4.1.31-30-default
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 1365 MiB
17:05:24.694 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 8
17:05:24.923 [main] INFO  o.t.e.s.c.ConfigurationSubsystem - Video Settings: {"pixelFormat":24,"windowPosX":379,"windowPosY":235,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"animatedMenu":false,"viewDistance":"${engine:menu#view-distance-moderate}","flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":true,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"dumpShaders":false,"volumetricFog":false,"screenshotSize":"${engine:menu#screenshot-size-normal}","screenshotFormat":"jpg","cameraSettings":{"cameraSetting":"${engine:menu#camera-setting-normal}"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
17:05:25.024 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Tasks-0.2.0-SNAPSHOT
17:05:25.025 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Dialogs-0.1.0-SNAPSHOT
17:05:25.026 [main] INFO  o.t.module.ModulePathScanner - Discovered module: JoshariasSurvival-1.0.0-SNAPSHOT
17:05:25.040 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WoodAndStone-0.1.2-SNAPSHOT
17:05:25.041 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LightAndShadow-0.1.1-SNAPSHOT
17:05:25.042 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SubstanceMatters-1.0.0-SNAPSHOT
17:05:25.042 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ItemRendering-0.2.0-SNAPSHOT
17:05:25.043 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CakeLie-0.1.1-SNAPSHOT
17:05:25.043 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Oreons-0.2.1-SNAPSHOT
17:05:25.044 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ThroughoutTheAges-0.1.1-SNAPSHOT
17:05:25.045 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Miniion-0.2.1-SNAPSHOT
17:05:25.053 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Rails-0.1.1-SNAPSHOT
17:05:25.054 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Malicious-0.1.1-SNAPSHOT
17:05:25.054 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PolyWorld-0.7.1-SNAPSHOT
17:05:25.055 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Valentines-0.1.1-SNAPSHOT
17:05:25.056 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ComputerMonitors-0.1.1-SNAPSHOT
17:05:25.056 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Minerals-0.1.2-SNAPSHOT
17:05:25.057 [main] INFO  o.t.module.ModulePathScanner - Discovered module: StructuralResources-0.2.1-SNAPSHOT
17:05:25.057 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SimpleFarming-0.1.1-SNAPSHOT
17:05:25.058 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AnotherWorld-0.2.0-SNAPSHOT
17:05:25.059 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ManualLabor-1.0.1-SNAPSHOT
17:05:25.059 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CopperAndBronze-0.1.2-SNAPSHOT
17:05:25.060 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Fluid-0.1.1-SNAPSHOT
17:05:25.061 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Signalling-0.1.1-SNAPSHOT
17:05:25.061 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LegacyMusic-0.1.1-SNAPSHOT
17:05:25.062 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Core-1.2.2
17:05:25.063 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AnotherWorldPlants-0.1.1-SNAPSHOT
17:05:25.063 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChrisVolume1OST-0.2.1-SNAPSHOT
17:05:25.064 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PlantPack-0.1.1-SNAPSHOT
17:05:25.064 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ShatteredPlanes-0.0.1-SNAPSHOT
17:05:25.064 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WorldlyTooltip-0.1.1-SNAPSHOT
17:05:25.065 [main] INFO  o.t.module.ModulePathScanner - Discovered module: StaticCities-0.2.0-SNAPSHOT
17:05:25.065 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MarkovChains-1.5.1-SNAPSHOT
17:05:25.066 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BlockPicker-0.1.2-SNAPSHOT
17:05:25.066 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MasterOfOreon-0.1.1-SNAPSHOT
17:05:25.067 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Minimap-1.0.0-SNAPSHOT
17:05:25.067 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Economy-0.1.0-SNAPSHOT
17:05:25.068 [main] INFO  o.t.module.ModulePathScanner - Discovered module: StructureTemplates-0.1.0-SNAPSHOT
17:05:25.068 [main] INFO  o.t.module.ModulePathScanner - Discovered module: TutorialAssetSystem-0.1.0-SNAPSHOT
17:05:25.069 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Durability-0.1.1-SNAPSHOT
17:05:25.069 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Potions-0.2.0-SNAPSHOT
17:05:25.070 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Workstation-1.0.0-SNAPSHOT
17:05:25.070 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Books-1.0.0-SNAPSHOT
17:05:25.071 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CoreSampleGameplay-1.2.2
17:05:25.071 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Seasons-0.9.1-SNAPSHOT
17:05:25.072 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChangingBlocks-0.1.1-SNAPSHOT
17:05:25.072 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Lakes-0.0.1-SNAPSHOT
17:05:25.073 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MultiBlock-0.1.1-SNAPSHOT
17:05:25.073 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WorkstationInGameHelp-1.0.0-SNAPSHOT
17:05:25.074 [main] INFO  o.t.module.ModulePathScanner - Discovered module: DamagingBlocks-0.1.1-SNAPSHOT
17:05:25.074 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Sample-0.1.1-SNAPSHOT
17:05:25.075 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ManualLaborEventualSkills-1.0.0-SNAPSHOT
17:05:25.075 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ModularComputers-0.1.1-SNAPSHOT
17:05:25.075 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CustomOreGen-0.1.1-SNAPSHOT
17:05:25.076 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BuilderSampleGameplay-1.2.2
17:05:25.077 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Maze-0.1.1-SNAPSHOT
17:05:25.077 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Genome-0.1.1-SNAPSHOT
17:05:25.077 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CheatsForAll-0.1.1-SNAPSHOT
17:05:25.078 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Spawning-0.1.1-SNAPSHOT
17:05:25.078 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LightAndShadowResources-0.2.0-SNAPSHOT
17:05:25.079 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Breathing-0.1.1-SNAPSHOT
17:05:25.080 [main] INFO  o.t.module.ModulePathScanner - Discovered module: DynamicCities-0.2.0-SNAPSHOT
17:05:25.080 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WildAnimals-0.1.1-SNAPSHOT
17:05:25.080 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AlterationEffects-0.2.0-SNAPSHOT
17:05:25.081 [main] INFO  o.t.module.ModulePathScanner - Discovered module: QuestExamples-0.2.0-SNAPSHOT
17:05:25.082 [main] INFO  o.t.module.ModulePathScanner - Discovered module: IRLCorp-1.1.1-SNAPSHOT
17:05:25.082 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BlockDetector-1.2.0-SNAPSHOT
17:05:25.082 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChrisVolume2OST-0.1.1-SNAPSHOT
17:05:25.083 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MarcinScIncubator-0.1.1-SNAPSHOT
17:05:25.083 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Journal-0.1.1-SNAPSHOT
17:05:25.084 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CommonWorld-0.2.2-SNAPSHOT
17:05:25.084 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MoreLights-0.1.1-SNAPSHOT
17:05:25.084 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Portals-0.1.1-SNAPSHOT
17:05:25.085 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BlockNetwork-0.1.1-SNAPSHOT
17:05:25.085 [main] INFO  o.t.module.ModulePathScanner - Discovered module: EventualSkills-1.0.0-SNAPSHOT
17:05:25.085 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WeatherManager-0.1.1-SNAPSHOT
17:05:25.086 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Equipment-0.1.0-SNAPSHOT
17:05:25.087 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MusicDirector-0.2.1-SNAPSHOT
17:05:25.087 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ClimateConditions-0.1.1-SNAPSHOT
17:05:25.088 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MedievalCities-0.1.0-SNAPSHOT
17:05:25.088 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MobileBlocks-0.1.1-SNAPSHOT
17:05:25.088 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Caves-0.2.1-SNAPSHOT
17:05:25.089 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SimpleLiquids-0.1.1-SNAPSHOT
17:05:25.089 [main] INFO  o.t.module.ModulePathScanner - Discovered module: FunnyBlocks-0.1.1-SNAPSHOT
17:05:25.090 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Soils-0.1.1-SNAPSHOT
17:05:25.090 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PhysicalStats-0.1.0-SNAPSHOT
17:05:25.090 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Cities-0.6.1-SNAPSHOT
17:05:25.091 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Hunger-0.1.2-SNAPSHOT
17:05:25.091 [main] INFO  o.t.module.ModulePathScanner - Discovered module: TutorialNui-0.1.0-SNAPSHOT
17:05:25.092 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Machines-1.1.0-SNAPSHOT
17:05:25.092 [main] INFO  o.t.module.ModulePathScanner - Discovered module: GrowingFlora-0.1.1-SNAPSHOT
17:05:25.092 [main] INFO  o.t.module.ModulePathScanner - Discovered module: OreGeneration-0.1.1-SNAPSHOT
17:05:25.093 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Pathfinding-0.2.0-SNAPSHOT
17:05:25.093 [main] INFO  o.t.module.ModulePathScanner - Discovered module: InGameHelp-0.1.0-SNAPSHOT
17:05:25.093 [main] INFO  o.t.module.ModulePathScanner - Discovered module: TutorialWorldGeneration-0.1.1-SNAPSHOT
17:05:25.094 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PotentialEnergyDevices-1.0.0-SNAPSHOT
17:05:25.094 [main] INFO  o.t.module.ModulePathScanner - Discovered module: FluidComputerIntegration-0.1.1-SNAPSHOT
17:05:25.095 [main] INFO  o.t.module.ModulePathScanner - Discovered module: GooeysQuests-0.1.0-SNAPSHOT
17:05:25.095 [main] INFO  o.t.module.ModulePathScanner - Discovered module: NameGenerator-0.4.1-SNAPSHOT
17:05:25.095 [main] INFO  o.t.module.ModulePathScanner - Discovered module: TutorialDynamicCity-0.1.0-SNAPSHOT
17:05:25.096 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Fences-0.1.1-SNAPSHOT
17:05:25.469 [main] INFO  o.t.audio.openAL.OpenALManager - Initializing OpenAL audio manager
17:05:25.611 [main] INFO  o.t.audio.openAL.OpenALManager - OpenAL 1.1 ALSOFT 1.15.1 initialized!
17:05:25.611 [main] INFO  o.t.audio.openAL.OpenALManager - Using OpenAL: OpenAL Soft by OpenAL Community
17:05:25.612 [main] INFO  o.t.audio.openAL.OpenALManager - Using device: OpenAL Soft
17:05:25.612 [main] INFO  o.t.audio.openAL.OpenALManager - Available AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
17:05:25.612 [main] INFO  o.t.audio.openAL.OpenALManager - Available ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
17:05:25.613 [main] INFO  o.t.audio.openAL.OpenALManager - Max mono sources: 255
17:05:25.613 [main] INFO  o.t.audio.openAL.OpenALManager - Max stereo sources: 1
17:05:25.613 [main] INFO  o.t.audio.openAL.OpenALManager - Mixer frequency: 48000
17:05:25.617 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Starting initialization of LWJGL
17:05:25.617 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initial initialization complete
17:05:27.091 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)
java.lang.ExceptionInInitializerError
        at org.terasology.engine.subsystem.lwjgl.LwjglDisplayDevice.setFullscreen(LwjglDisplayDevice.java:65)
        at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:218)
        at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:169)
        at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:260)
        at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:195)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:361)
        at org.terasology.engine.Terasology.main(Terasology.java:152)
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
        ... 7 more
Caused by: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.LinuxDisplay.openDisplay(Native Method)
        at org.lwjgl.opengl.LinuxDisplay.incDisplay(LinuxDisplay.java:305)
        at org.lwjgl.opengl.LinuxDisplay.internAtom(LinuxDisplay.java:629)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:734)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
        ... 7 more
For more details, see the log files in /root/.local/share/terasology/logs/2016-10-09_17-05-23`

**Comment by Cervator** [comment]
I'm afraid that last line there is pretty clear :(

`17:05:27.091 [main] INFO o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)`

What's your video card? Anything unusual about its driver?

**Comment by kholyphoenix1** [comment]
I understand the error. I put the error here so I could help others. 
My video card is GeForce.
Thanks!

**Comment by Cervator** [comment]
That's a [brand / line of cards](https://en.wikipedia.org/wiki/GeForce) - bit unspecific :-)

Appreciate the report, but it is unlikely we can act on it. Unless for some reason you're hitting this with a *newer* video card, like a GTX 980 or something. I am guessing you have an older edition, maybe a mobile card of some sort?

**Comment by kholyphoenix1** [comment]
Solved. Thanks!!

**Comment by Cervator** [comment]
Great! What fixed it? Video card driver update? Good to hear in any case, will close this then :-)

**Comment by kholyphoenix1** [comment]
08:51:44.197 [main] INFO  o.t.audio.openAL.OpenALManager - OpenAL 1.1 ALSOFT 1.15.1 initialized!
08:51:44.197 [main] INFO  o.t.audio.openAL.OpenALManager - Using OpenAL: OpenAL Soft by OpenAL Community
08:51:44.198 [main] INFO  o.t.audio.openAL.OpenALManager - Using device: OpenAL Soft
08:51:44.198 [main] INFO  o.t.audio.openAL.OpenALManager - Available AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LIN$
08:51:44.199 [main] INFO  o.t.audio.openAL.OpenALManager - Available ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_dis$
08:51:44.199 [main] INFO  o.t.audio.openAL.OpenALManager - Max mono sources: 255
08:51:44.199 [main] INFO  o.t.audio.openAL.OpenALManager - Max stereo sources: 1
08:51:44.199 [main] INFO  o.t.audio.openAL.OpenALManager - Mixer frequency: 48000
08:51:44.205 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Starting initialization of LWJGL
08:51:44.206 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initial initialization complete
08:51:45.999 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)

**Comment by kholyphoenix1** [comment]
I installed **NVIDIA-Linux-x86_64-340.98.run**.
The same error continues...'

**Comment by kholyphoenix1** [comment]
Before placing the Video Card.
I was using Intel HD Graphics 2000 and the game opened normally.

**Comment by Cervator** [comment]
Both of those sadly are pretty old :(

**Comment by kholyphoenix1** [comment]
Ahhh, thanks!! Solved...
