### ISSUE TITLE
Main menu background track not looping

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2527]
### How to reproduce
- Open game
- Turn up the audio and find some work to do :stuck_out_tongue: 
- Wait

The background track should play once and not loop back. That is the game goes silent after a while, once the song finishes.

Probably an easy fix.
##

**Comment by rzats** [comment]
#2364 is slightly different but related. That one actually occurs on my machine almost immediately after the game is loaded and can be reliably reproduced.

**Comment by nihal111** [comment]
@rzats Yup, I have seen that too. Always get that after a `Delta too great..`, isn't it the game trying to minimize load by stopping the track?

**Comment by Cervator** [comment]
Yeah these two issues are related but distinct. This one is much more of a "Huh, I guess nobody just ever thought to put the track on repeat" while the other one is a weird bug. That one works perfectly fine when running the game from a binary, making it even weirder.

**Comment by omomthings** [comment]
Problem fixed, was nothing.. Pull request pending ! Have a good day
