### ISSUE TITLE
Water stops being rendered when resizing the window

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#2528]
### What you were trying to do

Resize Terasology's window to verify the rendering engine performs correctly
### What actually happened

The water stops being rendered, leaving a big ugly hole in the ground.
### How to reproduce
- Either start Terasology in window mode or toggle the Fullscreen OFF before loading a game
- Create/Load up a game and find a lake/sea
- Resize the window by dragging one of its border - the water disappears

I suspect this also occurs when trying to take screenshots at resolutions that are different from the current window/display resolution.
### Log details and game version

This problem was introduced in commit 0378926c (really ba84900) - my bad.
##

**Comment by emanuele3d** [comment]
The plot thickens.

Simply going to the Video Settings menu and changing a setting such as Fog or Water Reflections trigger the water to show up again. Interestingly, after this operation the water stays visible even if the window is resized. 

Very peculiar.

**Comment by Cervator** [comment]
Peculiar indeed! I can confirm the issue, although "Film Grain" and "Cloud Shadows" didn't restore the water, "Fog" did though. And then yep, no further breaking on resize. Fun with states :-)

**Comment by Cervator** [comment]
Possible addendum or *very* similar/related issue: the window resizing (now?) also seems to cut out block rendering in the areas the window resized to. Sample screenie (also showing the missing water again):

![terasology-161105122245-1268x776](https://cloud.githubusercontent.com/assets/1063833/20031738/b2d564ee-a352-11e6-95df-aeb04cc756e7.jpg)

Going to the graphic settings and tweaking stuff fixed the water as noted above. Amusingly the fixed water then *does* display in the newly resized margin.

http://i.imgur.com/rvFle1u.png

Unsure if that is a separate fix is closely tied to this enough to count as the same issue. Your call @emanuele3d :-)

**Comment by Cervator** [comment]
Closing as fixed by #2844!

At least the resizing stuff is dealt with. Not totally sure if that's the same as "weird things can happen when applying video settings changes" but I think that was improved too recently.

**Comment by vampcat** [comment]
@Cervator There are still *some* oddities surrounding the video setting (like having Parallax mapping + extra lighting causes weird black edges) but that's mostly coz of shaders, everything else should be fine now. That too will be fixed very soon :D
