### ISSUE TITLE
Add Arabic language file to support translations

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2539]
Request came in via IRC. Technically requests can be submitted via Weblate that may also create a placeholder language file, but I think we end up usually creating the language file here manually. 

Could also do it for the CrashReporter and Launcher while we're at it.

_Note:_ there are translation changes in develop (and maybe in pending PRs) that haven't been pushed to Weblate yet, and I haven't checked if there are any uncommitted changes over there as well.

Pinging @msteiger @skaldarnar @Halamix2 
##

**Comment by skaldarnar** [comment]
Hm, I've created a new translation using Weblate which reported some strange error. The file was created nonetheless (`menu_ar.lang`) but does not show up in Weblate. 

https://github.com/MovingBlocks/Terasology/commit/5a011afe0a909f1c774ca5bf0c0771ea5e3242a0

`develop` and `weblate` have been synched before adding the new language.

**Comment by skaldarnar** [comment]
Arabic is addad, although not translated yet. Closing.
