### ISSUE TITLE
Warn user if mapping a key already in use elsewhere

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2552]
Currently when you have the nice input mapping screen up you get to pick a mapping, then separately click OK to confirm the choice. However, there is no warning at all if the key or whatever is already in use.

As a user I would like to see a warning pop up with a red label indicating "Mapping [x] is already in use for function [y]" so I can think about that for a moment before confirming or reverting my choice.

**Bonus** will-love-you-forever-if-also-adding-this: Keep a multi-line log in the main mappings screen (not the popup) where any such overwritten mappings appear until either:

* User goes and sets a mapping for the function that was overwritten (clear that one)
* User leaves the mappings screen entirely (clear all)

Slightly related: #2551, #2384, #2145, #2125

**Comment by zeokav** [comment]
Hi! I'm new to this project but this looks like a good entry point. Where exactly int the project files do I look for this?

**Comment by skaldarnar** [comment]
@zeokav you could start at `org.terasology.config.BindsConfig` and work through `setBinds`, `hasBinds` etc. This should be a good start. Scan for usages of these methods and/or set some breakpoints to find out how the things work.

**Comment by zeokav** [comment]
Okay I figured out where the check happens. What we need is a popup dialog if it's already taken, asking for confirmation, right? I will look for the popup dialog similar to what's being used when a button for input rebinding is clicked.

**Comment by zeokav** [comment]
@Cervator @skaldarnar Sorry for bugging you guys with such newbie doubts (I will get a hang of it soon), but where do I set screens? I was trying to mirror something like the ChangeBindingPopup (calling it ConfirmChangePopup) and instantiating the ASSET_URI with "engine: confirmChangePopup" but the console raises a message saying that it can't find screen 'confirmChangePopup'.

**Comment by skaldarnar** [comment]
@zeokav did you create `confirmChangePopup.ui` file similar to [changeBindingPopup.ui](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/menu/changeBindingPopup.ui)? That's needed for displaying something. You should be able to use our NUI editor to create the ui file easily.

**Comment by rzats** [comment]
Closed as completed by #2574.
