### ISSUE TITLE
Game controller input still being consumed with the game window inactive

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2554]
## Description

If you de-focus the game window (switch to some other window) while having a game controller of some sort hooked up, input from the controller still affects the game (unlike mouse or keyboard). This is _probably_ not a hard bug to solve.
## Definition of 'Done'
- [ ] de-focusing the game window will ignore all input (especially from attached controllers)
## Requirements
- you will work with the game's input system which requires intermediate knowledge of Java
- access to a game controller of some sort to test it out :-)
## Where to start?
- #2108 added controller support, the PR gives a good overview of involved classes
##

**Comment by GabrielXia** [comment]
Hey does controller here means something like XBOX controller ? If so, how could we test without test without a XBOX ?

**Comment by Cervator** [comment]
Yep like an Xbox controller, but *any* USB / bluetooth controller, connected to your PC. Don't need an Xbox but yes you do need some sort of controller to be able to work this :-)
