### ISSUE TITLE
Crouch follow-ups

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2555]
As a follow up to #2544:
- [ ] Add falling off ledge prevention.
- [ ] Change key mappings as per discussion [here](http://forum.terasology.org/threads/crouch-and-prone-controls.1622/)
##

**Comment by Cervator** [comment]
Some more:

- [ ] Switch back out of the temporary `x` key (covered by the key mapping note above but just to get an explicit reminder)
- [ ] Tiny / general: Clear out any empty javadoc headers when making changes anyway (like `/** */` leftover from a script removing author tags)

**Comment by oniatus** [comment]
Closing as proposed in https://github.com/MovingBlocks/Terasology/pull/2961#issuecomment-341993601
Follow up issue is #1075
