### ISSUE TITLE
Player name case sensitivity issues (in particular for console commands with a player target)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2558]
This one might already be tied up with @oniatus and his work on unique player naming, but could likely also be done separately by just adding case insensitivity to certain commands. In general I suspect we should simply not consider case sensitivity in player names at all (if `MyName` and `myname` are players only one such player could be in the same game)

The specific problem: if you use commands like `givePermission cervator2 cheat` it'll fail if the target player is actually `Cervator2` - that should be pretty easy to fix.

Different commands may be getting and comparing the player name using different strategies. For instance the `givePermission` command in `PermissionCommands` goes and does a `playerName.equals(name)` so simple switching that to `equalsIgnoreCase` would fix that instance. May need to search for command classes (find Java files with `@Command` in them) then spot any commands using `player` in some sense.

I'm not sure if it would be less work to somehow change the back-end handling of player names, like keeping a display name (with capitalization) and a technical name always in lower case. That's why I'm curious what @oniatus is getting to :-)

**Comment by rzats** [comment]
Fixed by #2568!
