### ISSUE TITLE
Display active savegame path in the main menu

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2566]
### Description

Terasology's savegame files can end up in several different locations depending on the player's OS (and the optional -homedir command line parameter). While the savegame path can be viewed and changed in the [Terasology Launcher](https://github.com/MovingBlocks/TerasologyLauncher), displaying it in the Create/Load World screens would be a welcome addition.

### Definition of 'Done'

A visible label is present in the Create World and Load World screens showing the player's current savegame path.

### Required skills

The issue involves working with the game's codebase and requires intermediate level Java skills. Knowledge of Terasology's [NUI](https://github.com/Terasology/TutorialNui/wiki) interface framework is also helpful!

### Where to start?

- The savegame path can be retrieved using the [`PathManager.getSavesPath()`](https://git.io/vPxkr) method.
- Adding the path to interface screens requires modifying their asset files ([createGameScreen.ui](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/menu/createGameScreen.ui) & [selectGameScreen.ui](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/menu/selectGameScreen.ui)), as well as the code-behind classes ([`CreateGameScreen`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/CreateGameScreen.java) & [`SelectGameScreen`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/SelectGameScreen.java)). For a quick overview on working with interface screens, check out the [NUI Quick Start](https://github.com/Terasology/TutorialNui/wiki/Quick-Start) tutorial!

**Comment by segfault802** [comment]
I'd like to implement this.  I'm already familiar with the UI code from working on previous issues and you've made the requirements pretty clear.

**Comment by rzats** [comment]
@segfault802: this was actually implemented by #2572 - I just didn't get to closing the issue yet. Sorry for the confusion 🙂 

Some similar issues you might find interesting are #2028, #2376 and #2377.
