### ISSUE TITLE
Create a video tutorial for setting up the game environment

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2569]
### Description

While setting up the game from source is fairly easy due to the gradle build system handling most of the boring and complicated parts, it can be a little overwhelming for new contributors. A modder, texture artist, playtesting enthusiast, or other individual who hasn't done much - if any - coding before might get a lot out of seeing a basic video that covers installing the game from source and making some basic changes.
### Definition of 'Done'

A single tutorial video (~10-15 minutes) or a playlist of several _really_ short videos (~1 minute; will make it easier to link to specific parts from different tutorials, as well as push updates) is created, containing a tutorial showcasing the following:
- Creating a GitHub account and forking the project.
- Cloning the game to your desktop from the fork, either using `git clone` (a console command) or git client (GitHub Desktop, TortoiseGit etc.)
- [Configuring a remote for the fork.](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
- Fetching several custom modules or create a new one.
- Running the `gradlew idea` task and launch the game using IntelliJ IDEA.
- Running the game via command line and IntelliJ.
- Making a simple change to the engine code and pushing it to the GitHub fork, then creating a pull request.

Optional ideas that can be added on later as advanced followups include:
- Using Eclipse instead of IntelliJ IDEA.
- Using a source zip downloaded from GitHub to bypass working with Git.
- Bypassing source files entirely by using a downloaded game zip to mod in assets like new blocks. This is doable with [path modules](https://github.com/MovingBlocks/gestalt/wiki/Modules#pathmodule) - extracted JAR files that are located in a regular directory.
- Downloading and using useful related tools: 2D texture editors, Voxelshop and so on.
- Highlighting [runtime asset reloading](https://github.com/MovingBlocks/gestalt/wiki/Gestalt%20Asset%20Core%20Quick%20Start#reload-assets-changed-on-disk) - when does a fresh stack of objects need to be created in-game, what operations require placing a new block and don't apply to an existing one and so on.
### Required skills

A basic understanding of the topics being covered (Java / Gradle / IntelliJ) is nice to have, but can be picked up as you go along :)
### Where to start?
- Most of the information the tutorial should cover can be found in the [Dev Setup](https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup) tutorial and associated wiki articles.
- [OBS Studio](https://obsproject.com/) is a great (open-source!) video recording program, but feel free to use whatever software suits you best!

**Comment by dacharya64** [comment]
I know some video editing / graphics stuff, so happy to take this on if needed. I feel I have a pretty good grasp of getting a dev environment up and running as well.

**Comment by Cervator** [comment]
@dacharya64 - belated response here, but if you still want to look at that sometime (even after GSOC) then I'm pretty sure we can simply hook you up with access to our Youtube channel so you can publish it there, even as a draft for review before publishing :-)

We also have a little few-second intro that could be added in front and we usually add the music from one of the soundtrack pieces. Probably something to dig into a bit in #outreach on Slack sometime (like where that intro is, I don't see it in an obvious place on the official channel so it might be on somebody else's account)

**Comment by aloeankh** [comment]
I'd be pleased to cover this topic, and can link a sample of what my first steps would be in a short video clip, if still relevant. I noticed this issue was last opened in 2018, but it seems to be a quick fix.

**Comment by aloeankh** [comment]
I actually found [this](https://www.youtube.com/watch?v=cCMQ5VaKnfw&t=132s) YouTube tutorial on the very concept this thread aimed to solve! Should this issue be closed and the video added to Wiki and Dev Setup doc?

**Comment by Cervator** [comment]
Oh hey @aloeankh ! Sorry for missing your comments, hard to keep track of all the GitHub thing, partly why we spend so much time coordinating on Discord/Slack :-)

Yeah there are existing videos, but since they're hard to keep current a new one would still be useful. The one you linked is nearly 3 years old and some users also use different tools and so on. Having a few different ones can be helpful 👍

**Comment by skaldarnar** [comment]
We had videos or pictured tutorials every now and then, and while they are helpful they are also quite hard to maintain.

Closing this as "not planned" currently, but that does not mean that we'll never have video tutorials 🙃
