### ISSUE TITLE
Implement a crossbow or similar ranged item

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2570]
### Description

Terasology has a railgun item that allows players to destroy the environment in a series of over-the-top explosions! The goal of this issue is to create a smaller-scale version of the railgun potentially allowing players to destroy environmental objects as well as NPCs.
### Definition of 'Done'

A crossbow item is added to the game's Core module, building off the existing railgun while adding the following:
- An appropriate icon. Instead of a crossbow you can use any ranged weapon of your choosing - longbow, sling or something even more creative 🙂
- A maximum range for the crossbow's projectile.
- A crafting recipe or quest to create the crossbow - this could be as simple as gathering a few resources and having them in your inventory.
- _[Optional]_ An ammo system - the crossbow uses projectiles from the player's inventory to fire and can't be used if none are available. The projectiles will also need to be created from a crafting recipe.
- _[Optional]_ Allow the explosion effects from the crossbow to hit NPCs and other non-block entities. This is the trickiest part and fairly low-priority, so it can be completed separately.

In the future, the crossbow may need to be integrated with the physics-based combat system (see #2072) - however, until that's finalized, it can remain a standalone item along with the railgun and TNT.
### Required skills

The issue involves working with the game's codebase and requires intermediate level Java skills. Some knowledge of Terasology's asset system is helpful but can be learned as you go along.

### Where to start?
- Review the [Add New Item](https://github.com/Terasology/TutorialAssetSystem/wiki/Add-New-Item) tutorial for information on how to add new items and test them in-game.
- As mentioned previously, the crossbow should be based on the existing [railgun item](https://github.com/MovingBlocks/Terasology/blob/develop/modules/Core/assets/prefabs/railgunTool.prefab). Any additional in-game logic will need to be added to the [`org.terasology.logic.actions`](https://github.com/MovingBlocks/Terasology/tree/develop/modules/Core/src/main/java/org/terasology/logic/actions) package in the Core module.

**Comment by nickdex** [comment]
Hey, I would love to work on this. This is my first time contributing to a project so I might fumble with things a bit.
For the issue please check the checklist below
- Fork the repository to local machine.
- Follow steps from this [link][1] to add a new item.
- Base its charecterstics on [Railgun][2].
- Create a crafting recipe for it.
- Do the optional steps.

Any links to helpful pages are appreciated.

[1]: https://github.com/Terasology/TutorialAssetSystem/wiki/Add-New-Item
[2]: https://github.com/MovingBlocks/Terasology/blob/develop/modules/Core/assets/prefabs/railgunTool.prefab

**Comment by skaldarnar** [comment]
Hi @nickdex the checklist looks good for a start. With the tutorial on creating a new item and the railgun prefab at hand you pretty much have everything you need.

You can start working on it in your fork and open a PR whenever the first steps are done, e.g., you've created a new item based on railgun. Look at other assets for items and tinker around with it. You can update a PR whenever you want, and it's a great place for discussion. 

A crafting recipe or quest would likely be integrated with an existing module, e.g., Equipment, GooeysQuest, or Josharias Survival. Start simple, we'll come this later :-)

**Comment by nickdex** [comment]
That would be pretty good, I didn't know that I could update PR later. Thanks for the info :)

**Comment by rzats** [comment]
(Belatedly) closing as completed by #2640!
