### ISSUE TITLE
Develop an in-game credits screen

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2578]
### Description

Terasology has a long list of contributors and credits, located at [docs/Credits.md](https://github.com/MovingBlocks/Terasology/blob/develop/docs/Credits.md). It would be really cool to have the credits viewable ingame as a typical [closing credits](https://en.wikipedia.org/wiki/Closing_credits) screen.

### Definition of 'Done'
- A new NUI widget, `UIScrollingText`, is created. It is designed to load a large text string (too high to fit on a single screen) and scroll from the bottom of the screen to the top until the entire string is shown. _[Optional / Advanced]_ API features include:
  - A function to start/stop scrolling.
  - A scroll speed modifier.
  - The ability to automatically "restart" the widget when it fully reaches the top.
  - Fancy text support (HTML, Markdown etc.)
- A new NUI screen is created, with a `UIScrollingText` containing a modified version of Credits.md (intro paragraph removed, has each contributor / icon / library on a separate line, potentially with links removed). It should be accessed using a new button added to the main menu.
### Required skills

The issue involves working with the game's codebase and requires intermediate level Java skills.
### Where to start?
- Check out the [NUI Quick Start](https://github.com/Terasology/TutorialNui/wiki/Quick-Start) tutorial for information on how to create a NUI screen.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38732242-develop-an-in-game-credits-screen?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).

**Comment by Cervator** [comment]
For a fun little side-comment our adopted project Destination Sol actually has this! Although I'm not sure I would necessarily copy code from there, it was originally written somewhat rushed and is based on LibGDX :-)
