### ISSUE TITLE
Switching hotbar item while holding attack button causes an extra attack

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#2581]
### What you were trying to do

I was trying to switch to a better tool to break dirt while joined to a headless server.
### What actually happened

The game instantly attacked extra each time I switched to a different hotbar item,  not regarding the cooldown time.
### How to reproduce
1. Hold the attack button while breaking a block
2. Mash the 1-9 keys to switch between hotbar items
3. Much excitement for increased digging speed!
### Log details and game version

Current develop branch (e08708b48b24ef11bbdd4a52d007ceaf997f6249) in a headless-remote client scenario. 
##

**Comment by Cervator** [comment]
Closing as fixed by #2582
