### ISSUE TITLE
Chunk (30,0,0) refuses to load

### ISSUE THREAD

**Issue by Taose** [MovingBlocks/Terasology#2603]
### What you were trying to do

Effectively I copied the following seed: PZMCjQ4G2JaE2ZNTvVoYs1yX4CuvorhT launched into a new world and headed east towards the islands. Just carried a torch, jumped through the forest. No special speed/ghost or whatever and just carried on. (View Distance is Far, frame rate around 40-60). 

Using the minimap I could already see that the chunk failed to load on approach as the others loaded around it. On arrival I can confirm it was indeed dead. 

This also happened on a prior run of the seed in a previous world. Same chunk refused to load then too. 

### What actually happened

Chunk Refused to load, dead world is dead. 

### How to reproduce

* Step 1
Use seed: PZMCjQ4G2JaE2ZNTvVoYs1yX4CuvorhT
Modules: Caves 0.2.1, Chris Volume 1&2, Music Director, Core Content/Gameplay, Lakes 0.0.1, Minimap

Game: Core Template, Perlin

Map Details: 
- Seed: PZMCjQ4G2JaE2ZNTvVoYs1yX4CuvorhT
- Trees 0.60
- Oceans 55
- Flora 0.60
- Humity: 2, 0.14
- Caves: 0.50, 0.3, 64, 1, 0.3, 1
- Rivers: 11
- Hills & Mountains: 0.81, 0.52
- Lava Lakes: True

* Step 2
Head to pos: 967.5, 62.41, 0.6 
* Step 3
View dead chunk

### Log details and game version
[Terasology-init (copy).txt](https://github.com/MovingBlocks/Terasology/files/587460/Terasology-init.copy.txt)
[Terasology-Kasub (copy).txt](https://github.com/MovingBlocks/Terasology/files/587461/Terasology-Kasub.copy.txt)
[Terasology-menu (copy).txt](https://github.com/MovingBlocks/Terasology/files/587462/Terasology-menu.copy.txt)
Game Version: Alpha Terasology Stable-68 2016-10-08 (Omega)

### Computer details
Hardware: 
[2016-11-12 Spec Sheet.html.zip](https://github.com/MovingBlocks/Terasology/files/587463/2016-11-12.Spec.Sheet.html.zip)
Memory: 15.6GiB
Processor: Intel® Core™ i7-4790K CPU @ 4.00GHz × 8 
Graphics: AMD Radeon R9 200 Series  
HDD: 1TB

Software: Ubuntu 15.04 64-bit (kernel: 3.19.0-73-generic)
Java: OpenJDK 1.8.0_45-internal (latest I can get)
OpenJDK runtime: same
OpenJDK server: 25.45-b02 (mixed mode)

**Comment by Feralmouse** [comment]
**Work Around**

While this won't restore a dead world because the chunks won't reload.... you can mitigate against these events by limiting yourself to View Distance: Moderate/Near until all the chunks you want are loaded.
