### ISSUE TITLE
give more than 127 blocks in one command (use multiple stacks?)

### ISSUE THREAD

**Issue by portokaliu** [MovingBlocks/Terasology#2607]
What you were trying to do:
Give myself more than 99 blocks with the giveBlock command with a single command.

What actually happened
The sound of collecting items played, no error was returned and the 999 blocks I asked for were nowhere in sight.

How to reproduce:
* Open console and type "give stone 999"
* Observe no stone has been given.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39261328-giveblock-multiple-stacks?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5279&utm_medium=issues&utm_source=github).

**Comment by Cervator** [comment]
Interesting! Apparently 128 is the magical number (and a familiar one at that) where it no longer works. `give stone 127` not only works but gives you a single stack of 127 stone despite the max size being 99. Or at least that's the size at which we'd split into a second stack.

Probably this has something to do with `BlockItemFactory` line 71 where the quantity is cast to a byte (which is what `stackCount` is on the `BlockItemComponent`). Instead we should likely have a case within the `give` command or the `giveBlock` method that truncates the quantity to 99 and lets the user know that happened.

**Comment by portokaliu** [comment]
I was thinking the latter would be the more efficient case, having the command also look through the inventory to check if there are free spaces to put blocks (which I think it already does). Filling the inventory with blocks doesn't sounds like a bad idea (especially if we use it like in minecraft to `give 46` :> )
