### ISSUE TITLE
Alpha 6 release - QA and module changes

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2619]
Trying something new: an issue specific for releasing a new stable build, configured as a ZenHub Epic, so we might have a way to link to all issues/PRs in the module ecosystem, which has been a lot harder to document for releases.

An additional thing to start doing is formal QA for releases, which also has a potential tie-in with Google Code-In, but more on that later.

Marking as "Blocker" since this issue would be a natural requirement for completion before we can do the associated release. Seemed natural.

*General note*: For any users viewing this issue *without* the ZenHub browser addon installed you won't be able to see the extra Epic bits.

On the other hand this may be too tricky still to do via pure Epic organizing. Difficulty:

* Have to add each module repo to the ZenHub board for this repo (takes a while and unsure how it'll scale/bloat the board)
* Probably still cannot have a repo present on multiple boards (ideally we could have a board on JoshariasSurvival that only includes its sub-modules, while all of them would be present here)
* Adding issues via ZenHub epic organizer only considers *open* issues - so you'd need to add everything to the epic before closing it (which will be missed and then we have to reopen to add, then close, causing notification spam)
* Closing a merged PR then re-opening may end up listing it as closed rather than merged?
* Need to poke the ZenHub team for some advice here

Some plain links instead so I can at least notate what I've been merging (will edit in further)

* https://github.com/Terasology/Equipment/issues/4
* https://github.com/Terasology/Equipment/pull/15
* https://github.com/Terasology/Equipment/commit/6fa977f4d3bfd044958d000f6f9b7cb460b98016
* https://github.com/Terasology/Alchemy/pull/4
* https://github.com/Terasology/Alchemy/issues/3
* https://github.com/Terasology/PhysicalStats/pull/2
* https://github.com/Terasology/PhysicalStats/issues/1
* https://github.com/Terasology/Machines/pull/22
* https://github.com/Terasology/Thirst (new module split out from Hunger)
* https://github.com/Terasology/EdibleSubstance (new module split out from .. ManualLabor I guess?)
* https://github.com/Terasology/DamagingBlocks/pull/1 (relates to #1697)

Not necessarily part of Alpha 6, but noteworthy none the less so I wanted a reminder in here!

* https://github.com/Terasology/Climbables - new by @portokaliu 
* #1977 - done partially by @Josharias for the JS/TTA modules. We could probably do a few more elsewhere and consider it fully complete as part of Alpha 6. Maybe.

**Comment by Cervator** [comment]
Releasing Alpha 6 so closing this now. Ambivalent about the approach. I think we need it for test plans but it is a bit of a pain either using ZenHub to link to module issues/PRs or manually trying to do so.

**Comment by OvermindDL1** [comment]
If you were just using ZenHub to track and link the issues together like this, perhaps the newly added [Projects](https://github.com/MovingBlocks/Terasology/projects) tab in this project might be a better place to put new ones that do not require plugins?

**Comment by Cervator** [comment]
@OvermindDL1 I've thought about trying out Projects, yeah, but it sounds like they're solely part of the single repo, unlike ZenHub (or Waffle.io)'s ability to do cross-repo stuff :(

I suspect GitHub itself will probably get there sooner or later. I just want it to work nooowww :D

**Comment by OvermindDL1** [comment]
> I suspect GitHub itself will probably get there sooner or later. I just want it to work nooowww :D

Hehe, I know how that goes.  If only github/gitlab/bitbucket/etc... would all settle on one git-based storage like that, then we could expand it easily.  ^.^
