### ISSUE TITLE
Extend Genome module to include human/animal genetics

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2648]
https://github.com/Terasology/Genome/issues/4 sounds like a great potential task for GSOC - moving it here for the label 🙂 

_[...] When in nature, the animals would not simply be copies of each other, but each would have unique characteristics. In addition, when breeding captured animals, the player can decide to breed genetically strong animals to yield more strong animals (for labor, food, etc.). The gameplay would change by introducing a genetic factor to the environment of Terasology. The player would experience a lot more diversity in nature, and can manipulate living entities to create ideal animals or plants for the player’s needs_

**Comment by marti1125** [comment]
Hello @rzats I am really interesting in Terasology could you suggest some issues I could get start.
thanks! I am Java Dev. My idea is to prepare me for participate to GSoC

**Comment by rzats** [comment]
@marti1125: the issues tagged as [Bite-size](https://github.com/MovingBlocks/Terasology/issues?page=1&q=is%3Aissue+is%3Aopen+label%3ABite-size) or [Mentor-size](https://github.com/MovingBlocks/Terasology/issues?q=is%3Aissue+is%3Aopen+label%3AMentor-size) are great first issues to start with! Alternatively, GSoC project ideas can be found under the [GSOC](https://github.com/MovingBlocks/Terasology/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AGSOC) tag - you could find a project you like and start working on some of the related issues 🙂

**Comment by MalyshevValery** [comment]
Hi, @rzats I want to work with this issue/project during this year GSoC maybe you could advice me from where I should start exploring Genome issue

**Comment by rzats** [comment]
@MalyshevValery: [setting up an environment](https://github.com/MovingBlocks/Terasology/wiki/Preparing-an-Engine-Workspace), downloading the Genome module and running it from source is a good start. Otherwise I'm not much of an expert in this particular area, but @skaldarnar @mjuvekar7 @xrtariq2594 might have some ideas.

**Comment by MalyshevValery** [comment]
Hi, @mjuvekar7 , as you can see higher I'm interesting in solving this issue during GSoC. I've looked through the code of Genome( I'm going to run it with a simple model in one-two days). I wonder are there any modules Genome for breeding?
I've seen that you're working on improving SimpleFarming module but I think extending of generating plants from PlantsPack and WildAnimals

**Comment by mjuvekar7** [comment]
Well currently not too many modules use genome. I think a few modules from Throughout the Ages have some genome integration, but that isn't too great currently. I wouldn't go for plants pack since simple farming is basically just a newer version of the old plants pack and simple flora modules. Could chat later on IRC to discuss modules which could use genome integration.

**Comment by MalyshevValery** [comment]
Hello again @mjuvekar7. Could you please give any of your contacts to discuss some ideas of involving Genome module into others. (Maybe you know that time of writing proposals is coming)

**Comment by mjuvekar7** [comment]
Sure. I'm mandarj on IRC and Slack, and I'm usually online after 1 pm Indian time (7:30 am GMT). If you could tell me your IRC Nick I could PM you my email

**Comment by MalyshevValery** [comment]
My IRC nick is ValeryMalyshev. I will be online at the 8 am GMT

**Comment by MalyshevValery** [comment]
My IRC nick is ValeryMalyshev.

**Comment by skaldarnar** [comment]
Keeping https://github.com/Terasology/Genome/issues/4, no need to have this as duplicate.
