### ISSUE TITLE
Crouching doesn't properly uncrouch in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2651]
When crouching in multiplayer everything is fine *if you're the host* - but if you are a connected client and attempt to crouch you sort of get stuck vibrating slightly and rapidly up and down, even long after no longer crouching. Something in the process does not seem to terminate correctly when purely a client. Maybe you get stuck in a crouch/uncrouch loop.

You can "fix" the issue temporarily by flying / ghosting as that gets you ungrounded, at which point you are incapable of crouching. But the issue returns after you land and takes logging out then back in to solve permanently.

**Comment by gianluca-nitti** [comment]
For reference, here is a gif showing the bug: http://imgur.com/a/K83Jn

**Comment by oniatus** [comment]
Closing as proposed in https://github.com/MovingBlocks/Terasology/pull/2961#issuecomment-341993601
(Issue should be fixed with the PR)
Follow up issue is #1075
