### ISSUE TITLE
Error Loading Game

### ISSUE THREAD

**Issue by WH1CRT** [MovingBlocks/Terasology#2656]
![screenshot_1](https://cloud.githubusercontent.com/assets/22790918/21074762/b29a6e72-bef8-11e6-960a-659fdb81cf97.png)

What you try to do
- Trying to load the game

 What actually happened
- My launcher stopped responding causing the application to end. 

Log details and game version

 Computer details
Windows 7 64-Bit
RAM: 16GB
Processor: i-7 CPU @ 3.40GHz

**Comment by WH1CRT** [comment]
I just resolved my own issue it was simply because I had hardly any space left in my primary hard drive.

- Will

**Comment by skaldarnar** [comment]
Thanks for reporting the problem. I left a note on the launcher project to prevent this from happening in the future.
