### ISSUE TITLE
Unable to run Alpha 65 and load the save file created in 70 Alpha

### ISSUE THREAD

**Issue by WH1CRT** [MovingBlocks/Terasology#2658]
What you were trying to do
- Load the oldest version of Terasology Launcher under "Alpha 65"
- Boot up the save file created in version "70 Alpha" 
- To play the latest save file in the oldest version of Terasology

What actually happened
- The crash report screen was displayed with a list of what had happen within the application.

![screenshot 5](https://cloud.githubusercontent.com/assets/22790918/21075240/7b209870-bf04-11e6-8ddc-60e0cd66f4a0.png)

How to reproduce
- Create a save game in 70 Alpha 
- Run 65 Alpha and select singleplayer.
- Select the latest save file you created.

Game version
- 65, 70 Alpha

Computer details:
- Windows 7 64-Bit
- Processor: Inter(R)Core(TM) i7-4770 CPU @ 3.40GHz 3.40GHz
- RAM: 16.0GB

**Comment by skaldarnar** [comment]
Although the Alpha releases should be backwards compatible, we make not mention about about being _forward_ compatible. That is, a game created with Alpha 65 should work in Alpha 70, but not necessarily the other way around. 
Thus, I'm closing this as non-issue.
