### ISSUE TITLE
New UI Widget Proposal | Tab

### ISSUE THREAD

**Issue by smsunarto** [MovingBlocks/Terasology#2695]
# Tab Widget

Tab Widget is a widget that allow multiple panel to be contained in a single window. This would make it easier for the user to navigate through menu/interface without actually needing to go back and forth the menu/interface
Reference: https://en.wikipedia.org/wiki/Tab_(GUI)

Concept:
--------

![Concept](http://puu.sh/sXGzz/5e9cfb3f87.jpg)

Example of Usage
----------------
The tab widget can be used in the "Settings" menu of Terasology. Currently, to change settings of different category you need to go back and reselect the category that you want to change. With tab, this process could be much easier and simpler. User can simply navigate between settings category using the tab widget. This not only save space, but also save the user time & effort. (Refer to the picture above)

**Comment by emanuele3d** [comment]
Oh YES please. =D

**Comment by Cervator** [comment]
> Oh YES please. 😄

I'll have what he's having!

Also, my memory told me this rang a bell, and sure enough there is *something* over in the MasterOfOreon module about tabbed UI stuff - https://github.com/Terasology/MasterOfOreon

MOO is pretty dated and this point and was barely begun, but it did have a nice menu element. Am not sure how much work it would be to apply any needed tweaks to get it up to speed and made more generic where we could keep it in the engine or something. This issue could involve checking that out first thing before we start from scratch. Maybe it'll be super easy! Somebody please try! :D 

The BlockPicker module would be an ideal target for later, if it doesn't have something like that already. I also think the journal/help modules have a sort of tabbed UI thing.

Anyway! Stuff to look at :-)

**Comment by jellysnake** [comment]
I've completed this over [on my fork](https://github.com/jellysnake/Terasology/tree/Add_UITab).  
I just need to do some testing and then I can pull it.

**Comment by smsunarto** [comment]
Seems good @jellysnake

**Comment by smsunarto** [comment]
Closing since it's now already added.
