### ISSUE TITLE
Use value comparisons instead of reference comparisons in StateChange.isDefaultInstance implementations

### ISSUE THREAD

**Issue by eviltak** [MovingBlocks/Terasology#2706]
### What you were trying to do
Solve the original problem (i.e. removal of duplicate `SetViewportToSizeOf` state changes) #2688 highlighted.

### What actually happened
State changes which are value identical to the default state change are not being reported as such to `AbstractNode.addDesiredStateChange`, its only caller.

### How to reproduce

* Run the game, load a world.
* Check the logs for the generated render task list with `SetViewportToSizeOfTask` tasks which are identical to the default (reset) state change task (i.e. the `SetViewportToSizeOfTask` which is run _after_ the node's `process` task).

### Cause
This happens because `StateChange.isDefaultInstance` incorrectly returns `false` for all instances of a state change as it performs a _reference_  comparison instead of a value comparison.

cc @emanuele3d

**Comment by eviltak** [comment]
This issue is redundant. `StateChange.isDefaultInstance` already exists.

**Comment by eviltak** [comment]
This issue is being reopened with a new purpose.

@rzats I'd like to claim this issue as part of GCI.

**Comment by Cervator** [comment]
Heya @eviltak - here you go :-)

https://codein.withgoogle.com/dashboard/tasks/4678651473821696/
