### ISSUE TITLE
New UI Widget: The Radial Item Selection Screen

### ISSUE THREAD

**Issue by mjuvekar7** [MovingBlocks/Terasology#2713]
I am writing this ticket with the intent of proposing a new method to select and organize items in the player's inventory: a radial, categorized menu.

This has been inspired by the radial 'buy menu/wheel' in the game Counter Strike: Global Offensive, where weapons that a player can buy are categorized into different classes (rifles, SMGs, etc) which are displayed on a radial menu. When a user accesses the category he wants, the radial menu changes to show the different guns in that category. Images of this can be found [on this forum page](https://forum.overclock3d.net/showthread.php?t=44527).

I propose that this categorical organization of items be brought to Terasology's inventory display system. In such a system, all items should be categorized into groups such as "tools", "food", "fuel", "armor", etc. and displayed on a radial menu. This categorization could also be module-wise (for ease of use during testing and debugging). Such a menu could also be extended to allow the user to create custom groups and to organize his/her items however he/she wants. Mockups of this can be found [here](https://github.com/mjuvekar7/TerasologyWikis/blob/master/Radial-Mockup.png) (Will have to be beautified; I'm not really an art person as you can probably tell).

For such a widget to be made, a new API would have to be made which would help the engine associate items with what group they fall into.

**Comment by Cervator** [comment]
Radial menu is definitely on our wishlist, for years now! So much more potential than just inventory, too :-)

In fact we actually had one, years ago, but the code was never fully submitted or merged. There is a great and long thread on the topic, with one of the message [here](http://forum.terasology.org/threads/mouse-button-behavior.704/page-2#post-6991) including a video preview (other videos in the thread too)

**Comment by jellysnake** [comment]
I have started working on this in my fork.

**Comment by mjuvekar7** [comment]
Good luck, have fun jelly! Ask me for help on IRC if you need it. :)

**Comment by Cervator** [comment]
Missed closing this a while ago when #2721 was merged :-)
