### ISSUE TITLE
UI Widget Proposal: UITextHint

### ISSUE THREAD

**Issue by TimVerhaegen** [MovingBlocks/Terasology#2740]
Hello there

# Write a proposal for a new UI widget: UITextHint

**What is UITextHint?**
Nowadays, people are lazy. They just DON’T want to hover over a UIText to see the tip! To make it as easy as possible for our users to gain important information, we should use a UITextHint! It’s basically a string of text that displays on the UIText (or any other input system), that goes away whenever the user writes something. This information could contain for instance information on what to write, a quote, or even an aesthetic meme.

**What is UITextHint’s purpose?**
As described above, people are lazy! This UITextHint could make the user’s life easier. Every single piece of modern software has this functionality, so I think a game such as Terasology should have this as well.

**How can developers implement this?**
This is a tricky question. Mainly my idea would be having a new attribute added to NUI, usable for UIText widgets. This could make it even easier, as it’s just one line of code really. This however would need some cooperation from the NUI developers. But once this cooperation is there, it’s really easy to implement a new sweet UITextHint widget.
So there are really two options; one would be adding a new Widget which would be called UITextHint, the other would be adding an attribute.

**How should this Widget be exposed?**
Quite easy for this one, basically just the text which is displayed by the hint, and perhaps some extra options such as the shade of the text? (Color)?
Most of the hints aren’t the same color as actual text, but slightly lighter, darker color. (ARGB-Color?)

**Personal point of view on this module**
As an avid supporter of hints, I think this would be extremely useful for UI-intensive modules, such as my own LOTRModule which I still have to start working on. :) 
I’d personally really prefer the new attribute, as this would be easier for everyone, more powerful and requires less lines of code.

**Hint example screenshot:**

![text-field-nocomment](https://cloud.githubusercontent.com/assets/17968114/21720022/18e75248-d421-11e6-9da2-2eda87d7e7da.png)

If anything is unclear to you, please tell me so I can improve.
Thanks

**Comment by Cervator** [comment]
Catching up with some issues here and there - this reminds me a lot of #2543 which could be used as sample code to implement this. #2543 introduced a text widget variant with a clickable `x` to clear the box, and really this functionality here would call for something similar, just placeholder text that goes away when a user starts typing.

Just would need to a new widget like the other PR and introduce a way to set the placeholder text, maybe add a hook that clears it on typing. Should hopefully be pretty straight forward to do :-)

**Comment by arpan98** [comment]
Having worked on #2543 , I could work on this as well and it shouldn't be too difficult.
