### ISSUE TITLE
Time out gracefully and return to menu when failing to spawn the player

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2753]
At the moment it is possible under some conditions to fail to spawn the player, usually in the case of a bug affecting world gen causing all the chunk generator threads to die (so no world to spawn in!)

The symptom for that at present is simply stalling on the Create/Load world screen. We need to come up with a way to time out and return gracefully to the menu instead, presenting an error message to the user that no suitable spawn position could be found and that there may be something wrong with the world.

In #2750 related code was touched and an `Optional` prepared that could be checked as part of this.

To reproduce introduce a bug in a world generator that'll crash chunk generation threads on purpose.

Shouldn't be too terribly difficult.

**Comment by zeokav** [comment]
@Cervator Won't timing out, in general, not fit for extremely slow machines (worst case (?)). 
Also, I finally got done with my internship so I'd like to start again with some more bite-size because I lost touch. 😛 
How do I mess with the world generator?

**Comment by Cervator** [comment]
Probably there is a way to keep track of time and state to where you can tell if there is still world being generated (Chunk generation is still succeeding on occasion), and suppress / extend the timeout in that case :-)

To mess with world generation find a `Rasterizer` class and introduce an error in `generateChunk` - that way when the error is encountered it'll crash that ChunkGenerator thread while the game itself continues (so it'll stall trying to find a spawn point)

**Comment by zeokav** [comment]
What I'm trying to do right now - 
Making generateChunk throw an exception in case there's a timeout while generating a chunk for which I use a Timer with maybe a 1000ms delay for each chunk (Couldn't figure out how else to check for non responsiveness). Also wanted to know if there's a wrapper for handling exceptions or if I can just throw them like I would in normal java. 
The error is handled by popping up a new screen telling the user what the problem was. 
I also wanted to know how to rollback to the menu undoing all that was done till the point of error.

**Comment by Cervator** [comment]
That might not work since it is generateChunk causing the chunk generator threads to die, and there are a bunch of them. The timeout needs to be hooked up to the game loading progress itself (like whatever kicks off the progress bar after the player starts creating a world) and if chunks haven't become available (or no spawn position can be found) *then* time out and return to the main menu.

Since you would hook that up at the same place that triggers the menu state change probably there is an easier place there to return back to where you came from. I wouldn't want to try interacting with that from a chunk generator thread :-)

**Comment by zeokav** [comment]
Coming back to my initial question - how long should I let the timeout be? Like it would technically depend on the computational speed of the machine it's running on, right?
In the StateLoading class, the progress bar only updates after a state change (after a loading process completes) and not in between, say when a chunk is generated. I could put a timeout but I don't know what the threshold should be so that it doesn't mess with normal loading on 2005 pro gaming rigs.

**Comment by Cervator** [comment]
The overall duration of a game load could vary substantially between machines, yeah. But say you're in the step where chunks are generating I'd expect any *one* chunk generation request to finish within a few seconds, and if there isn't one for say 20 seconds there's probably *something* wrong.

Maybe the timeout detection can just be activated after chunks begin generating, letting each chunk gen thread refresh a central `long timeLastChunkGenerated`, and if that ever ages past 20 seconds time out and revert game loading with an error?

It might be between progress bar stages, that'd be okay but could be improved. Could be cool if the engine could estimate how many chunks were needed and reflect that in in progress bar.

If we *can't* interrupt between stages then that'd be problematic because yes the realistic time to load can probably range widely between fast and weak systems and I don't have any hard data on how widely it might realistically vary :(

**Comment by zeokav** [comment]
@Cervator Apparently the chunks do not stop generating on error - in fact they generate infinitely many times. 
Like, if I log down the count of steps, when the game is bug free, there's around 85 chunks accounted -

> 21:48:15.844 [main] INFO  o.t.e.m.l.AwaitCharacterSpawn - Chunk updating: 85
However, if I introduce an error, the number increases significantly and it does not stop

> 21:43:20.212 [main] INFO  o.t.e.m.l.AwaitCharacterSpawn - Chunk updating:314161

So, there goes the last chunk generated method. However, we could set an upper bound on the number of chunks generated before timing out 🤔

**Comment by Cervator** [comment]
Sorry for missing the update here - that behavior seems bizarre. That's with NPEs killing the chunk generator threads? I don't know how the engine could keep thinking in that case that more chunks are still being generated :/

Pinging a few people that might be interested or have some ideas: @flo @rzats @oniatus

**Comment by Cervator** [comment]
Bump - doing an overall issue review. Wanted to post in here a link to #2838 which is similar but maybe not quite a duplicate of this one.

**Comment by Cervator** [comment]
Closing as fixed by #3645 !
