### ISSUE TITLE
room-scale VR gameplay

### ISSUE THREAD

**Issue by indianajohn** [MovingBlocks/Terasology#2761]
I have an open PR implementing tracked controllers using OpenVR (SteamVR) that looks like it's going to be merged soon, and another that will be made after that one in which some basic room-scale VR gameplay is implemented. The purpose of this issue is to report on that progress and solicit some ideas as to how to proceed. In order to understand some of the stuff that I'm going to be talking about you might want to watch the following video to get a better idea of what room-scale VR is: https://www.youtube.com/watch?v=6-hKcimW1JQ

The following is effectively done, and will probably be merged within a few weeks pending code review.
* Targeting of blocks by moving a motion controller into the block.
* Triggering of up to 10 different controller actions using buttons on the two motion controllers. This is simply done through the existing controller API.
* Movement using the trackpad on the left motion controller.
* Display of the tool in the location that the tracked motion controller is currently occupying.

The following things I consider highly plausible and have soft plans for implementing.

* Teleportation-based locomotion. In such a system, a ray would project from the off-hand motion controller when a button was held down. You could point that ray at the round some distance away and release the button, and you would "blink" to that location. This sort of thing is highly necessary, because thumbpad-based movement, while necessary for moving small distances while performing tasks (such as mining), will cause motion sickness in most people if it's done for more than a very short period of time.
* The creation of a canvas renderer that allows menu usage through VR. The `CanvasRenderer` interface is currently implemented in `LwjglCanvasRenderer`, and this is the mechanism through which menus are rendered. By creating a simple system for rendering a plane in VR space in front of the user and rendering to a frame buffer, it would be possible to make a `CanvasRenderer` implementation that a VR user could see. Then, by allowing the user to point their motion controller to the plane, mouse control could be simulated. If this were done, players could do inventory management and menu navigation without taking the headset off.

The following are "bonus" things that would really add some pop to the game.

* Other sorts of locomotion - climbing? Skiing? There's lots of thoughts on this. This video is pro-watch: https://www.youtube.com/watch?v=p0YxzgQG2-E
* Archery - using the motion controllers to pick up an arrow, draw it into the bow, pull back, and release. It works very well in many VR games and is very cool.
* Melee combat. See https://www.youtube.com/watch?v=Grzo18EFfJM
* I'm open to suggestions, within the realm of plausibility.

**Comment by Cervator** [comment]
I've gone ahead and flagged this for GSOC although this as written is specific to room-scale - I like that the suggestions here could be expanded on in any different and interesting directions :-)

I figure the primary GSOC value here would be developing more appropriate VR UI elements along with some basic gameplay like in the archery example. Noting you as a potential point of contact @indianajohn, hope that's ok!

**Comment by jdrueckert** [comment]
VR support was removed in #5112 so I'm closing this issue.
If VR support is re-introduced this issue is now linked to the PR that removed it, so it can be reopened or directly considered during the re-introduction
