### ISSUE TITLE
NUI Editor: family node has wrong type

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#2763]
### What you were trying to do
I tried to give a UILabel in the NUI editor a family attribute with the value "title"
### What actually happened
A family node got added that has no value, but allows for the addition of a layoutInfo node.
### How to reproduce
1. Open the NUI editor. To do so press ESC ingame and then click at the bottom right on "Developer Tools". Then select "NUI Editor Screen".
2. Select a screen (e.g. addServerPopup from the combo box at top left
3. Navigate to the first UILabel
4. Remove the family node if it has one by selecting it and then pressing delete
5. Right click the UILabel node and select in the context menu "Add.." and in the sub menu "familiy".
6. Notice how the added node has no value and no way to set it. Check out what the context menu offers when you right click it.

**Comment by flo** [comment]
@rzats: since you made it you probably know a quick fix for this.

**Comment by flo** [comment]
Probably related bug: https://github.com/MovingBlocks/Terasology/issues/2764

**Comment by rzats** [comment]
(Should have been closed by #2270, but wasn't - closing manually)
