### ISSUE TITLE
NUI Editor: layoutInfo can be added via context menu to a layoutInfo

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#2764]
### What you were trying to do
I was checking out what options the context menu offers me when I right click a layoutInfo node in the NUI Editor.
### What actually happened
The context menu offered me the option to add a layoutInfo node to a layoutInfo node.
### How to reproduce
1. Open the NUI editor. To do so press ESC ingame and then click at the bottom right on "Developer Tools". Then select "NUI Editor Screen".
2. Select a screen (e.g. addServerPopup from the combo box at top left
3. Navigate to a layoutInfo node
4. Right click it and checkout what context menu option it offers in the "Add ..." sub menu. It offers to add a layoutInfo which is wrong.

**Comment by rzats** [comment]
(Should have been closed by #2270, but wasn't - closing manually)
