### ISSUE TITLE
Alpha 7 release prep and QA

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2766]
We should be able to do an Alpha 7 release soon including all the goodies from GCI.

This issue is meant as a focal point for release preparation efforts.

## Multiplayer Testing

The `Official Event Host` has been updated with [Omega 681](http://jenkins.terasology.org/job/DistroOmega/681/artifact/distros/omega/build/distributions/TerasologyOmega.zip) as the first potential release candidate and is running NeoTTA. Known issues (help find more!):

- [ ] Upgrading a workstation causes a client crash. Closing the workstation UI makes the "Update" button go away so clearly something is missing
- [ ] Progress bar missing when you craft something with duration like with the portable forging station (the item does finish crafting and appear if you wait)
- [ ] Amusingly you can place a basket *inside itself* - which is probably more of a general issue rather than specific to NeoTTA multiplayer, but still funny
- [ ] Out of memory issues can occur easily, especially via in-game help, probably related to odd-sized images in Cooking, SimpleFarming, Equipment, etc? Need to either look for more images to resize or try to figure out what causes the inefficiency about those kinds of images.
- [ ] ... help us find more!

Also should we include the overhaul of effects? @xrtariq2594? Seems to involve:

* https://github.com/Terasology/AlterationEffects/tree/alpha
* https://github.com/Terasology/Potions/tree/alpha
* https://github.com/Terasology/Equipment/tree/alpha

Some of those are quite a few commits behind their matching master branch though.

A few more issues from earlier are listed at http://forum.terasology.org/threads/google-code-in-2016-done.1634/#post-14394

## Other Issues

- [ ] StructureTemplates has been updated by @flo with some great new tooling but this means updates are needed to get away from an outdated "front" config in existing prefabs. See [its forum thread](http://forum.terasology.org/threads/structure-templates.1550/page-2#post-14536) for details. I did some version bumps but when I ran with MedievalCities the game went boom (I didn't try to adjust the templates directly yet).
- [ ] Updates needed in MedievalCities - @skaldarnar?
- [ ] Updates needed in TutorialDynamicCities - @CptCrispyCrunchy?
- [ ] Updates needed in RomanCities- @SufurElite?
- [ ] Updates needed in ModernCities - @mdj117?
- [ ] Updates needed in Mineshafts - @MaxBorsch?
- [x] Torchlight when held seems to be broken and the goodie chests from Core likewise - #2788, fixed via revert in #2806 of #2672
- [ ] Some held items appear fully lit regardless of environment light level - #2804
- [ ] Distant name tag display: either hide a tag if the other player isn't visible, or make only nearby tags show?

## Test plans

We have these now! Any volunteers to help execute them as part of testing?

- [ ] Potions
- [ ] .. need somebody to add more for what we have covered. @nihal111?

**Comment by Cervator** [comment]
Might also be good to work on some release notes on what's new, especially outside the engine. Although with everything from GCI including ... yikes that'd be a big list. I've tried to keep track in Trello on occasion but it might be worth tracking in a release prep issue like this one

* https://github.com/Terasology/FunnyBlocks/pull/8 - new "trap" type block that breaks after being stepped on

**Comment by nihal111** [comment]
I had created the doc containing everything that was done in GCI apart from PRs and issues that can easily be tracked. [Here](https://docs.google.com/document/d/1hHpthirUmtJbCIrAZ5FVqVtz_dzGEGl_oXkvjDwjhYE/edit?usp=sharing) it is :smile:

**Comment by xrtariq2594** [comment]
> Upgrading a workstation causes a client crash. Closing the workstation UI makes the "Update" button go away so clearly something is missing

Yep, that's a known issue. I tried resolving that in some personal repos, but no luck. The files in question involved are: CraftingStationWindow, CraftingStationWindowSystem, and CraftingStationUpgraded.

**Comment by xrtariq2594** [comment]
> Also should we include the overhaul of effects? @xrtariq2594? Seems to involve:

Sure! Go right ahead. Though, please open up a separate server for that, just in case something goes awry.

**Comment by Cervator** [comment]
Another useful play test today and thanks to @nihal111 we got the one outstanding blocker fixed!

Talked to @xrtariq2594 about NeoTTA and will probably hold on just a bit with merging the new effects system if I'm able to build the Alpha 7 release tomorrow. Omega 681 is on the event server now as a potential release candidate.

Talked to @emanuele3d about some best practices for artwork as the apple tree leaf blocks look a little odd now as they have transparent bits yet only the outermost textures render (all internal ones occlude, although the backside still renders due to the blocks set to double sided)

Suggestion from there we should probably add to a sort of best practices for artwork and outstanding work: 

* Avoid transparent pixels on textures meant to be used for tree canopies (OK for single block bushes)
* Add bite-sized issue to edit existing tree canopy type textures so that they don't have any transparency plus edit the .block files so that their doubleSided/translucent attributes are set to false (or removed if that's the default)
* We still need to clean up the images in Cooking some more

**Comment by skaldarnar** [comment]
@Cervator Alpha 7 is released, can this be closed or should it stay active for outstanding issues?

**Comment by Cervator** [comment]
Sorry for the belated reply @skaldarnar :D

I wanted to close this out by pushing forward any remaining issues to somewhere appropriate. I just submitted a similar issue for Alpha 8. We probably just need to create some follow-up issues here and there, much like we should after doing a play test and reviewing an associated project board.

Won't have time tonight but am beginning to like the extra bit of "glue" we can get with these issues and play tests. Easier to connect the dots and spot the repeat offender issues we hit :)

**Comment by Cervator** [comment]
Closing this at long last as part of Alpha 8 release prep, pushing forward a few open items to newer issues :-)
