### ISSUE TITLE
Content focus: exploration world

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2775]
Another potential content item for GSOC, akin to DynamicCities from 2016.

For GCI 2016 we got several new nifty pieces of content, such as the Dwarf Halls added by @MaxBorsch in [GooeysQuests](https://github.com/Terasology/GooeysQuests) and a bunch of examples of what can be done with the Structure Templates @flo put together, like a mine entrance or a guard tower. @iojw also had neato ruined structures in the midst of huge lava lakes in his [Inferno](https://github.com/iojw/Inferno)

## Goal overview

I think it is time to put a bunch of these together with a lot more added in an exploration-centric gameplay template. There's even a write-up in the forum for a maze-centric approach at http://forum.terasology.org/threads/maze-world-gameplay.1765/

We might not have quite enough creatures or nice combat to make tier-based dungeon crawling doable, but we do have a spooky skeleton that'll chase and kill the player if possible, or get taken out itself by a wary player. 

One main difference from GooeysQuests is that we probably should have all these things spawn "wild" without any interaction with the player(s) - no need to ask Gooey to spawn something specific.

An added challenge would be figuring out how to let differing types of structures interact - the world should probably have Caves enabled, along with multiple different types of underground features. How do we catch when they interact and avoid leaving things broken?

## Existing content to probably enable

Lots of modules to consider enabling

* https://github.com/Terasology/ChrisVolume1OST - need some music!
* https://github.com/Terasology/Caves - gotta have caves. Probably also leave some ore generation prefabs laying around like in JoshariasSurvival so there'll be minerals to find. Or if the focus should be on exploration should we skip crafting for now?
* https://github.com/Terasology/Lakes - nice addition especially when it creates underground lakes, even lava lakes
* https://github.com/Terasology/DamagingBlocks - so said lava can hurt you
* https://github.com/Terasology/SimpleLiquids - may be a dubious inclusion since it is a prototype, but it would be nice to seed occasional water or lava blocks to cause underground flows and waterfalls in caves
* https://github.com/Terasology/StructureTemplates - so we can add lots of neato structures
  * https://github.com/Terasology/Mineshafts - like these
* https://github.com/Terasology/Equipment - so chests can contain items you can find and equip
* https://github.com/Terasology/Hunger + https://github.com/Terasology/Thirst - for a bit of survival (seed some food and water items in chests)
  * Need to fix https://github.com/Terasology/Hunger/issues/4 so you can actually eat ...
* https://github.com/Terasology/Rails - so we could place rail tracks and maybe carts (with stuff in them?) in mines. 
  * ... requires pretty much fixing Rails first so it is more usable and stable
* https://github.com/Terasology/Books - so we could spawn occasional bookcases and books with lore maybe?
* https://github.com/Terasology/Potions - so potions can be left as treasure in chests
* https://github.com/Terasology/BlockDetector - maybe to help find caves and things below you? I think we got a cave-detecting ability. Could seed block detectors of various kinds in chests
* https://github.com/Terasology/Breathing - so you can drown. I think its status bar needs a fix
* https://github.com/Terasology/Dialogs - to include NPCs with dialog options?
* https://github.com/Terasology/Tasks & https://github.com/Terasology/QuestExamples - so you could find quests to acquire items or defeat scary skeletons. Probably a way to bind them to a book found in a chest).
* https://github.com/Terasology/EventualSkills - I believe we can tie skill discovery to (skill) books without too much trouble. Maybe we can come up with some useful ones to help exploration and add score
* https://github.com/Terasology/Journal - probably need to journal the exploration somehow
* https://github.com/Terasology/Minerals - so many minerals, so little time
* https://github.com/Terasology/Seasons + https://github.com/Terasology/WeatherManager - maybe it would be good to vary the seasons, maybe involve some harsh winters and hot summers
  * Actually need to finish the weather some more ...
* https://github.com/Terasology/WildAnimals - to liven up the world a bit. Spawning might need a bit of work for long-lived exploration worlds. Also need to throw in the skeleton from GooeysQuests
* https://github.com/Terasology/StructuralResources - everybody lives ingot stacks and roman columns! Right? Obelisks too!

## New stuff

Don't have these yet but would be prime candidates to create and include

- [ ] Some sort of scoring system so the player can have a score from the amount of exploration done. Maybe based primarily on chests looted and quests completed? Also needed for Light & Shadow #2576
- [ ] World feature: Enhanced dwarf halls - more structure segments, more loot, maybe a guardian of some sort
- [ ] World feature: Enhanced mine shafts - more structure segments, maybe usage of mine carts and ingot stacks. Maybe make the mines more sensible to actually have mined one or more specific minerals out 
- [ ] World feature: Dungeons of assorted types, like the main one from GooeysQuests, or variants with other shapes, materials, and discoveries
- [ ] World feature: Ruins. Assorted types like abandoned watch towers, broken down villages, busted city walls, and so on
- [ ] World feature: Mazes. We actually have https://github.com/Terasology/Maze but dunno if it would be immediately applicable or if we should use a StructureTemplates approach instead. Oh, there is also http://forum.terasology.org/threads/maze-world-gameplay.1765/ !
- [ ] World feature: Fortress or other large single structures (although are they abandoned?)

**Comment by ianbrobin** [comment]
@Cervator I'm not really sure if this is what you had in mind for an exploration world, but I was thinking of creating a puzzle pack with several levels and mechanics. 
I am going to include:
Blocks that break when the player passes over them.
Ice blocks(if they don't exist already).
Slideable/Pushable blocks(slides until it hits a wall)
Door and key mechanics
Kill blocks
Spawn points
Ability to change the "color" of the player so they can only pass through certain barriers
Block pushers
Buttons
Blocks that slide back and forth.
Tools that a creator of puzzles can use to create a puzzle
One way doors

To make it an "exploration world", I am planning to include several levels that the player can go through. I think this would be a good way to demonstrate the "playability" of Terasology.

**Comment by Cervator** [comment]
Well, based on the activity of this issue one might think there hasn't been a hectic summer of activity and discussion going on. But the base exploration world has now been completed by @nihal111 - woohoo! Thank you, and @SkySom @flo @smsunarto @xrtariq2594 and others :-)

There is still plenty to do and this item was popular with prospective students - hi again @ianbrobin! if anybody else would like to plug more pieces into the setup, please feel free. We might be able to build some smaller mini-GSOC projects on this item, as well as tiny GCI tasks if we make it in for later this year.

See http://nihal111.github.io/2017/08/15/GSoC-wrap-up.html and earlier blog articles to see some of the work that was done
