### ISSUE TITLE
Crash while trying to start a singleplayer game

### ISSUE THREAD

**Issue by cemsozens** [MovingBlocks/Terasology#2776]
### What you were trying to do
I cloned the repo and I am trying to start a new singleplayer game. I added some modules and choose a map. But when I try to start the game it crashes. Is there a way to fix this. I am new to this game. I know there is a longterm support release of the game. But I want to add some new features. 
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by cemsozens** [comment]
Hp 8gb RAM, gtx960, i7 6700. Runs on ubuntu

**Comment by iojw** [comment]
Hi @cemsozens, could you upload the logs somewhere and share it here? If you're running it from the terminal you should be able to see the logs there.

**Comment by cemsozens** [comment]
hi @iojw. This is the logs you want i believe. http://pastebin.com/0NNu4r8T

**Comment by jellysnake** [comment]
Hmm. Can you do me a favour and try and start the game with only the module _Core Content_ enabled and see if that crashes with the same error

**Comment by cemsozens** [comment]
Well actually that is another problem that we face. When I chose only core content I cannot choose a world generator.

**Comment by jellysnake** [comment]
Assuming you are running from the terminal could you try running gradlew jar and then gradlew game to see if that makes a generator appear?

**Comment by cemsozens** [comment]
Oh thank you very much. This fixed it. Now i have one more question: Is it possible for us to make some small changes in the code and then start it with gradlew?

**Comment by jellysnake** [comment]
Yup. Just make your changes then run `gradlew jar game`

`jar` makes the game compile and `game` runs it. If you plan on making anything other than the smallest code changes I recommend you install & set up intelliJ to make your life much much easier
