### ISSUE TITLE
Improve support for integration tests including a headless client

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2780]
This is inspired in part by http://forum.terasology.org/threads/the-world-of-varied-and-noteworthy-achievements.1209 but focused more specifically on preparing a new level of integration test.

At present we have a pretty limited amount of *types* of automated testing

* Standard unit tests
* Environment-based tests (start a headless environment to have modules loaded into a context you can test again)
* Some minor benchmarking tests

We ideally would approach full graphical window-based acceptance testing, much like a few other games have achieved, like Factorio (https://www.factorio.com/blog/post/fff-62 - somebody find out what tool they are using for that!). In the meanwhile it would be nice to take the environment-based tests one step further. As explained by @oniatus:

---

Most of the features, especially for multiplayer are tested in test sessions or short local test plans. However, this is expensive to reproduce and takes longer to find and fix bugs (have to launch at least two game instances fully loaded into a world).

The goal of this task would be to extract the API for starting a game with any configuration in singleplayer, headless or local hosted multiplayer mode and provide a facade to interact with the world and verify values in unit tests.

```
Server server = new HeadlessServer(...);
Client client = new Client(...);
server.register(client);
client.send(any event);
assertThat(server.getEntity(...).getComponent(...).value,is(42));
```

The task can be split in smaller steps:

1. Understand what happens when a player starts a game or connects to a server
1. Implement a facade to perform the steps without manual interaction
1. Implement options to interact with the game (sending events should cover most of the cases)
1. Add options to receive values from the game and verify them in unit tests

---

This could end up relating to #2436 in that a thought for achieving communication with a game server to then provide RESTful endpoints to the outside world might be through an irregular player connection, like indeed a headless client connected purely to be able to issue console commands, not to render the world at all or interact with any entities.

This item could be taken to varying lengths, starting with any more involved unit test support than our current `HeadlessEnvironment` provides up to and including automated acceptance tests, and even the shipping of a credits/testing/progress report world with the game. But a headless client able to observe a game would be a great mid-term goal.

As part of completing such a task we also need to pair our overall automated testing approach with a tutorial to help others learn how to better write more advanced tests. Or even point to some relevant regular unit testing resources that could be useful.

**Comment by Cervator** [comment]
@skaldarnar dug up another interesting blog entry for the related topic: https://engineering.riotgames.com/news/automated-testing-league-legends

**Comment by iaronaraujo** [comment]
I am interested in working on this during Gsoc! I will already begin to run some tools to generate more unit tests, so we can improve the test coverage!

**Comment by Cervator** [comment]
@iaronaraujo great! I take it you are also http://forum.terasology.org/threads/hi-hi-i-am-iaron.1812 :-)

**Comment by iaronaraujo** [comment]
Yep, that's me!

**Comment by Cervator** [comment]
Bump - getting some updated information in here.

1) Unrelated to GSOC @kaen has implemented a vastly improved headless testing environment that can include multiple clients connecting to a server with everything simulated including event support and so on. See http://forum.terasology.org/threads/moduletestingenvironment-integration-testing-with-in-process-engine-objects.1884/ and https://github.com/Terasology/ModuleTestingEnvironment
2) During GSOC @gianluca-nitti worked a server API item that has provided some new capabilities. It might not directly relate to this but could probably be useful so I wanted to drop a link to his blog with more details: https://gianluca-nitti.github.io/GSoC-2017-devlog/

So we kinda *have* headless clients now, plus additional capacity to interact with a running server. I'm not sure if that fully addresses this issue/topic to where we should close it, however. At the least we should consider it for review for next year's GSOC, probably as a new issue with some new goals - there are plenty of new stuff we could aim for!

Hi @iaronaraujo - I hope you're still out there and doing well, maybe even participating in next year's GSOC or interested in the area still. We'll be starting Google Code-In yet, there should be room for tasks that exercise the API or use the new testing capacity, we could use more volunteers/mentors to play with that :-)

**Comment by iaronaraujo** [comment]
Hi @Cervator ! Sorry for the absence, this year has been pretty busy for me.
It's good to know we now have a headless client, and I will check it out as soon as I can to see what I can do with it!
I don't think I will be able to participate in the Google Code-in, but I do intend to participate in next year's GSOC.

Thank you for updating me!

**Comment by Cervator** [comment]
Awesome to hear about future GSOC plans! Yeah life tends to get busy :-)

I hope you find some free time to play with the area, and look forward to a related GSOC app as soon as we get in! Just be sure to stay in touch :-)

(We will have some test related GCI tasks if you want to hang out on IRC and occasionally help with review or answering simple questions)

**Comment by Cervator** [comment]
Closing this as completed during GSOC 2018 :-)

Still plenty of improvements possible but the foundation has been built out!
