### ISSUE TITLE
Improvements for ping system

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2787]
Follow-up to #2768 - an improvement is desired to where the server pings all connected clients both for health-check type functionality and so that information can be provided to clients to show a ping overlay for each player (holding down `tab` in a multiplayer session)

Should be done without excessive connection usage and disposal, as indicated in #2768

There is also a small side-issue where a server-client player cannot use the ping command in the console as it believes said player is not engaged in a multiplayer session. That might just be a cosmetic issue to clear up for now since that setup may change in the future anyway (improvements to `Context` and possibly splitting apart single player to having a local server)

This shouldn't be *too* hard so marking bite-size, although it probably isn't a super beginner task. Check the linked PR to see some related code and consider reading https://github.com/MovingBlocks/Terasology/wiki/Entities,-Components-and-Events-on-the-Network

**Comment by GabrielXia** [comment]
Hey, could you please tell me how to test the code as a server in this case :-)

**Comment by Cervator** [comment]
Sure. server-client just means you run two instances of the game and host the server with one of them (start a multiplayer game). That instance has both has a server and a client, and if that client tries the command the mentioned weirdness gets logged to the game console.
