### ISSUE TITLE
Goodie chest broken and held torches no longer spread light

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2788]
I just noticed the goodie chest you start in with CoreSampleGameplay is empty, while it used to have a bunch of stuff in it, including a nested chest with even more stuff.

Probably we broke something relatively simple, but being able to spawn with stuff is pretty central so I'd like to make sure we find a fix for this before releasing Alpha 7.

Can anybody else confirm the bug any maybe dig into it a bit? We just need a minimal fix, nothing major as @jellysnake is presently extracting inventory so we don't want to make any substantial changes.

**Comment by nihal111** [comment]
Leaving a comment here just in case this isn't immediately worked on-
This commit breaks it- https://github.com/MovingBlocks/Terasology/commit/dd45f8e96fd44e0fb48ff27471aa5a83402419d1 (PR #2672 )
Also related to #2804

**Comment by Cervator** [comment]
Thanks a bunch @nihal111 ! I submitted and will merge PR #2806 to fix this and the held torch not casting light (split back out from #2804)
