### ISSUE TITLE
Verify if RenderingPipelineTask implementations can be private classes within State Changes

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#2796]
It appears most RPT implementations are strictly related to -one- StateChange implementation and viceversa. Given that RPTs should be instantiated only through the StateChange.generateTask() method, making them private classes within the associated StateChange implementation might be an easy way to enforce that.

For those RPTs where the relationship is not a strict 1:1 with a StateChange, we should resort to package-private classes or constructors.

**Comment by emanuele3d** [comment]
Tagging @tdgunes for feedback.

**Comment by Cervator** [comment]
Closing as (mostly) completed by #2826 - expecting any remainder might be different enough for its own follow-up issue if warranted? Not entirely sure if any more could be done at the moment.
