### ISSUE TITLE
Subtle rendering issue introduced by #2794 - billboard floating position off

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2800]
Took me testing two additional PRs after #2794 to notice this sneaky issue: the position a billboard is rendered at seems off based on how the player is moving. I found two ways in which it is exhibited (may be more):

1. When breaking a billboard plant while the player is moving toward and nearly has crossed into the blockspace holding the plant the breaking effect can weirdly float off to the side at the bottom of the window. Similar oddities can happen but that's the easiest to reproduce. Simply walk into billboard plants while breaking them right as you're entering their block.
1. In a multiplayer session walk one player up to another one. Observe their floating name tag acting weird (floating off to the side again). Also easy to reproduce but does take running at least two game clients connected in a world together.

Example of the name tag issue: 

![terasology-170223230853-1152x720](https://cloud.githubusercontent.com/assets/1063833/23290747/4122c2a8-fa21-11e6-90fc-8c6c3fb9558b.jpg)

Confirmed it did not exist before the introduction of #2794 so it is definitely caused by that. Also makes sense considering the topic of the PR.

Sending this your way @emanuele3d - you're keeping me on my toes! :D I suspect this is quirky but probably not very complex to solve. Nor is it a big deal so feel free to ship it with something else if you already have pending changes for other stuff.

**Comment by emanuele3d** [comment]
I managed to reproduce it. Investigating.
