### ISSUE TITLE
User can submit whitespace only messages to chat + enter with empty message should re-close the chat ui

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2834]
We need to add a `trim()` somewhere and a check to see if a message is non-empty before sending it :-)

Additionally pressing `enter` with a *completely* empty chat entry should close the ui but at present inserts a single space instead (then a second `enter` then would manage to send that as an empty message)

So: Trim the message the user is attempting to send and if it is at that point empty close the chat ui instead of sending a blank message

Probably should review `ChatScreen` and/or `ChatSystem` to get started on this.

**Comment by ThompsonTyler** [comment]
Hey Cervator, was able to get this fixed, but wanted some input(Will probably ask you on irc before you see this), should console close on an empty string as well? (The enter adding a space was a problem for all UIText, not just chat)

**Comment by ThompsonTyler** [comment]
Will send in PR once I am back at computer and available to fix the branching on my end :P

**Comment by Cervator** [comment]
Closing as completed by #2847 :-)
