### ISSUE TITLE
Improve bulk and quantity-based giving of items (as opposed to blocks)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2835]
At present we've simplified down to a single `give` command where we used to have separate `giveBlock` and `giveItem` commands. They still exist as methods and the `give` command simply tries to deduce which one to use.

However, quantity based giving isn't working for items, even for those that are stackable. Try for instance `give axe 42` - the console insists that it gave you 42 items of `Core:axe` but you only get one item. Same thing if the item is actually stackable (`Core:axe` is not but `Core:door` is). Repeated commands with a stackable item will happily increase the stack by one each time while telling you that you were given x items.

We need:

* Improve the ability to *actually* grant you multiples of a stackable item
* Improve the logging for when you requested an unstackable item without a given quantity (default quantity is 16 for blocks, but for an unstackable item (or block like `core:chest`) it should be 1 and the console should indicate that)
* Allow quantity-based requests for unstackable items to put one item in each available inventory slot (up to the max inventory size)

Additionally we could also use a variant of `bulkGiveBlock` that works for items. For instance with NeoTTA enabled you get 29 item hits for `search seed` right now and it would be great to be able to `bulkGiveItem seed` to get one (or a stack) of each seed so you can get on with life already and plant all the things :-)

... although at that point do we fold the two into `bulkGive` and react intelligently to blocks vs items?

Finally it would be good to actually respond to the max inventory space when giving a large quantity of anything. See #2607 and its implementation in #2678 - that setup simply keeps going so if you ask for ten million of something it will literally loop through the entire range even after the inventory is full and couldn't possibly accept more items.

See `ItemCommands` and `BlockCommands` to get started and keep an eye out for `TODO` tags that relate.

**Comment by Vizaxo** [comment]
Oops, sorry for spamming this thread with commits; I was rebasing my branch and didn't realise they showed up here.

Anyway, I think #2841 and #2842 cover everything in this. There are a couple of notes on #2841 (such as checking performance on servers), and I left bulkGiveBlock and bulkGiveItem seperate for now (instead of implementing bulkGive to do both).

**Comment by xrtariq2594** [comment]
Good work @Vizaxo!
