### ISSUE TITLE
Wrong initialisation of next block-ids in BlockManagerImpl

### ISSUE THREAD

**Issue by elwe74** [MovingBlocks/Terasology#2860]
### What you were trying to do

In a loaded game I tried to execute command "give core;dirt 20 stair"

### What actually happened

All grass block in some large area where changed to dirt stairs

### Cause:

In GameManifest.blockIdMap == knownBlockMappings   the ids are starting at 1. 
So the next possible blockId  "nextId" cannot be knownBlockMappings.size().

### Fix

Change line 96 in  BlockManagerImpl 
from
            nextId = (short) knownBlockMappings.size();
to
            nextId = (short) knownBlockMappings.size()+1;

**Comment by elwe74** [comment]
Ok, it is even more complicated. The ids in GameManifest.blockIdMap are not contiguous, so size()+1 is not the highest used id.

So we have to use 
       nextId = knownBlockMappings.values().stream().max(Short::compareTo).orElse((short) 0)+1;
which will waste possible ids (short is not so large...)
or change getNextId to look for already used ids.

**Comment by Cervator** [comment]
Hi @elwe74 and thanks for the detective work!

We do in fact have an outstanding issue where blocks get mixed up somehow. This sounds like the kind of thing that could be causing it.

However the issue has been really difficult to replicate and I can in fact not do so with your instructions. Can you reliably trigger the issue? If it can only happen on game loads then that makes sense for how it has been so obscure, only popping up once every few weeks/months or so.

Can you also confirm if the changed blocks still *act* like the original block they were? Or do they change function? #2622 is one of the prior reports. Do you have any modules enabled beyond Core?

Might be interesting to several other devs like @portokaliu

**Comment by elwe74** [comment]
Yes, I can reliable trigger it, but it depends heavily on the saved game. I had the "luck" that "grass" was redefined, oniatus in the PR has the same problem with  "core:RedLeaf" which are not so easy to see...

I had another case where "chest"s were building a lake acting like the expected "water".

#2622 seems to be a duplicate for me.

I've had only few modules loaded, Core, CoreSampleGameplay, BulderSampleGameplay and SimpleLiquids. (I'm trying to enhance SimpleLiquids).

**Comment by Cervator** [comment]
Ah yeah then that makes sense. Different combinations could lead to the issue or not in different ways.

By the way BuilderSampleGameplay is meant to exclusively be used on its own to showcase the engine running without any of the fundamental stuff in Core (like health, inventory, etc). Running it with any other modules ends up not really achieving anything, unless maybe you want its world?

Usually it makes sense to just run with one gameplay module :-)

Thanks again for reporting this! Going to add you to the credits for this, super good bug to have squashed. Closing as complete.
