### ISSUE TITLE
Better blender md5 exporter with some integration with Terasology

### ISSUE THREAD

**Issue by glasz** [MovingBlocks/Terasology#2862]
Terasology uses ID software md5 format for animated 3D character, and blender is a favourite for creating those 3D models.
Currently we rely on an existing blender addon to export the blender models in the md5 format. That exporter could use fixing (there are some pending issues) and improvement, and be customized to integrate some functionnalities specific to Terasology.
    Automatizing of some technical stuff like : triangulate all faces before attempting to export, checking for loos vertices, etc…
    Simpler animations export process : offer the possibility to build a list of animations from the action editor and export them all at once (currently you have to go through the export process again for each animation)
    Integration with terasology : we use a prefab text file to define some AI behaviours. This file could be generated from inside blender, with a UI thing to associate easily an animation with an AI behaviour

**Comment by DRAGONMANU** [comment]
I agree that there must be a better way to export animated models from blender to Terasology. This would be really helpful when making customised animated characters which I would like to work on for GSOC. 
I will try to modify the [addon ](https://www.katsbits.com/tools/#md5)in blender to give the required text file.

**Comment by flo** [comment]
There is already a Blender addon with some Terasology adjustments:

https://github.com/MovingBlocks/TeraMisc/tree/master/blender_addons/io_md5_exporter

**Comment by glasz** [comment]
Hello flo,
I hadnt seen the work you've done on it until now. It seems to triangulate the faces, apply the modifiers and all sort of quite useful things.
But i also had in mind some blender UI stuff to ease life, like batch exporting all animations at once, including possibility to specify the frame range, the naming, etc... And also associating anims with actions and then generate the prefab file automatically (with some UI to set prefabs options) from inside blender.

What do you think ?

**Comment by flo** [comment]
hi @glasz  the blender addon already supports multiple animations export and per animation start/end frame.

Prefab generation isn't there yet, but how a good prefab might look like might change.

**Comment by Cervator** [comment]
@flo can you think of any additional improvements we could use then? Does the addon cover both creature type models and block shape files?

If it is more complete than expected and at risk for dropping out of GSOC scope I'm curious what we might be able to add in :-)

**Comment by flo** [comment]
There is a separate addon for block shapes. There is still stuff that could be done for the addon, but I am not sure if it is enough for a gsoc

**Comment by Cervator** [comment]
Closing this as sufficiently completed by @kartikey0303's GSOC project for 2017, woohoo! Nice work Kartikey and thanks @flo @glasz @Quaternius and others :-)

There are naturally still plenty of more things we can do and enhance. The GitHub project https://github.com/orgs/MovingBlocks/projects/7 lists most of those together with a Google Doc we have. Still on the list to sort all that out into new issues (for some reason project pages sometimes takes org membership?) but they will count as new in any case rather than keeping this open :-)

See https://github.com/Terasology/TutorialAssetSystem/wiki#blender-addon-for-creatures for the resulting docs and tutorial work
