### ISSUE TITLE
Show players online on the Join Server screen

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2864]
Somewhat split out from old issue #1099 which led to several improvements in past releases.

The remainder is straight forward: Add a new "Players:" label on the Join Server screen and populate it with the number of players online for the selected server.

Actually how to do that I'm less sure about being straight forward, so not marking this bite-sized. It may be of interest for any GSOC students looking at server administration topics.

Screenie for current situation (no "Players:" entry)

![2017-03-26 23_57_56-terasology _ alpha](https://cloud.githubusercontent.com/assets/1063833/24340553/297dc512-1281-11e7-9fe9-b9fbf73c7cef.png)

**Comment by gianluca-nitti** [comment]
I think sending and getting the data should be quite simple, I think it could be done by adding an additional field to the the `ServerInfo`-related source files (interface, implementation class and protobuf schema), similar to what I done in #2856 for MOTD.
Not sure how to get the number of online players in the server (to send it to the client) and how to adapt the UI layout on the Join screen.
I'll have a look during this week if I find the time.

**Comment by ar0ne** [comment]
I'm on it.

**Comment by ar0ne** [comment]
I finished the story, but before I send PR could someone confirm that we don't have any limitations on server side for clients (max count of clients)?

**Comment by Cervator** [comment]
Closing as completed by #2869 - thanks @ar0ne ! :-)

No current cap that I'm aware on. One of these days maybe we need to artificially connect a bunch of clients to a server to see if it starts struggling at some point.
