### ISSUE TITLE
Protobuf updates

### ISSUE THREAD

**Issue by ar0ne** [MovingBlocks/Terasology#2873]
I worked on issue #2864 and found that we use old version of protobuf 2.6.1. Also as I see it for generation of java code from *.proto files, we have very strange gradle tasks. Could someone explain me how does it work, because I'm pretty sure it doesn't. As I see it now for compilation we should install old version of protoc application and run it manually instead of using gradle. 
The issue is to improve this situation by using protobuf gradle plugin as was mentioned here #1013.
Also I prepared pull request where I resolved the issue. 
Just need someone for code review.

**Comment by jdrueckert** [comment]
Protobuf gradle plugin used by now. Not on latest but almost up-to-date.
