### ISSUE TITLE
module carts: can't break carts with current development branch.

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#2887]
I'm working on the rails module and I am not able to break the cart for development. I ran git-bisect and found this revision produced the bug. It could be something else unrelated but this is what I've narrowed it down to. Could require modifying the Core module, but this revision produces a regression in terms of the HealthComponent and Entities. Would have to see how this affects other modules. 

0d3ce8e3e7356e1bce80e5f271e321fde5b5f261
### How to reproduce

* Install Rails mod: https://github.com/Terasology/Rails
*  checkout revision: 0d3ce8e3e7356e1bce80e5f271e321fde5b5f261
* can't break cart
* checkout revision 0d3ce8e3e7356e1bce80e5f271e321fde5b5f261~1
* can break cart

**Comment by pollend** [comment]
@indianajohn

**Comment by indianajohn** [comment]
I'll take a look at this over the weekend.

**Comment by pollend** [comment]
I was testing this with the WildAnimals mod. I can't hit any of the deer.

**Comment by indianajohn** [comment]
I'm working on this now, I think I see a way to fix it. Shouldn't take too long.

**Comment by pollend** [comment]
I think my pull request may of fixed the issue unless you have something else in mind @indianajohn #2891

**Comment by indianajohn** [comment]
Nope, I was unaware of that PR. That is basically what I was about to end up with.

Anyway, sorry for any trouble this caused and thanks for the fix.

**Comment by pollend** [comment]
was pretty happy that I got to use git-bisect
