### ISSUE TITLE
If a player has already picked a custom name don't prompt them to pick a custom name

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2912]
The first time a player enters either Host Game or Join Game they get a prompt to pick a name - but should really only get one if they *haven't already* picked a name.

At present you can start the game, go select a custom player name, then still have the game helpfully try to offer to set you up with a custom name. That's silly. Probably an easy fix :-)

**Comment by Malanius** [comment]
I'll take a look onto it.

**Comment by Cervator** [comment]
Completed by #2920
