### ISSUE TITLE
Problems with some types of targeting as a client in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2913]
When testing local multiplayer with either a client-server + client or headless + client there are problems with targeting for a pure client player. Specifically trying to break blocks with regular fists or tools doesn't seem to hit the right spot - in one case I was breaking blocks about 10 blocks away.

Amusingly if I tried to hit the hosting player with the client player *the client player would take the hit*

Probably a recent PR introduced this bug, but I don't have time at the moment to dig deeper. Might be fairly straight forward with a bit of digging.

Hosting player or single player is fine, so easy to miss during testing if no relation was expected.

**Comment by nihal111** [comment]
Leaving my findings here-
A VR related PR creates this issue
A recent commit by indianajohn (91db417b291c95a6024b41ed22fecce0eda1f4a3) seems to cause it.
Everything works fine till the commit just before that, (5b1853841155bdff9eefc7ae0510a0d0689192ee).

An older commit (0d3ce8e3e7356e1bce80e5f271e321fde5b5f261) was also discovered to have the same issue. Although this is older than Alpha7 and was probably fixed later.

**Comment by Cervator** [comment]
Poking @indianajohn for reference if curious to check it out :-)

More info in #general on Slack - in short it seems like the local player system on the server is always used to look for targeting *even on a different connected client-only player* or something like that. So as player 2 if you walk up to player 1 and attack, you'll actually manage to attack yourself (assuming player 1 is looking at you)

**Comment by Cervator** [comment]
"Fixed" by #2932 by reverting a tiny bit of #2793. Submitted #2933 as a follow-up to later find a more proper fix.
