### ISSUE TITLE
Rename view-distance "titles". [SUGGESTION] [TRANSLATION]

### ISSUE THREAD

**Issue by Translator5** [MovingBlocks/Terasology#2923]
What's about to name the View distance using Animals?
```
Extreme to Falcon
Mega to Eagle
Ultra to Owl
Far to Jackal
Moderate to Human
Near to Donkey
Blind to Mole
```
I think this is more suitable for this kind of game.

**Comment by emanuele3d** [comment]
It's a creative idea but it obfuscates something that should be quite unambiguous in my opinion.

I wouldn't mind if an external Module did it though. I'm just not sure modules have access to those strings at all. Perhaps in the context of working on internationalization support this could become possible.
