### ISSUE TITLE
Module changes needed as follow-up to PR #2728 to avoid API violation

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2941]
As noted near the bottom of #2728 it breaks a few modules using particle effects, which would be an API violation if allowed into a stable release.

Usually it'll be users of `BlockParticleEffectComponent` which has been split into multiple smaller pieces (see the fix for GooeysQuests), also sometimes there are simply prefabs to update. In JS the base engine block breaking particles were delta'ed but now those prefabs themselves are gone/moved/split apart.

Probably not terribly difficult to work on with the example of GooeysQuests and some experimenting. The particle effects themselves don't need to be perfect, we can adjust that over time. Just don't want the game to crash :-)

- [x] GooeysQuests - fixed by https://github.com/Terasology/GooeysQuests/pull/13
- [x] CopperAndBronze has an old Charcoal pit with two classes using `BlockParticleEffectComponent`
- [x] Smithing has the same as it is a renewal of TTA
- [x] LightAndShadow also uses BPEC in its `CardSystem`
- [x] Rails as expected also has some smoke particles in `MinecartSystem`
- [x] Sample has a single prefab
- [x] JoshariasSurvival has 3 prefabs

@MaxBorsch may mange to fix all these himself in the near future, but if anybody is interested in helping out do a search for "BlockParticleEffectComponent" or "BlockParticleEffect" (in `*.prefab` files) for the affected spots in the listed modules. The PR to GooeysQuests should help guide how the code is transformed - keep in mind the exact details of the effects aren't super important yet.

Bonus: Fix up places where the particles aren't quite looking right yet. For instance:

- [ ] GooeysQuests particles appear to have a black background rather than transparency
- [ ] Torches being broken result in a really weird particle/texture
- [ ] Block breaking particles from sand are too white-ish - maybe related to a different rendering quirk rather than there being anything wrong with the actual particle texture
- [ ] ... add your own!

**Comment by skaldarnar** [comment]
https://github.com/Terasology/CopperAndBronze/commit/06b10feaa40be1aa1a8e9d45a1db76fc9c158a51

**Comment by Cervator** [comment]
Checking off Light & Shadow + Rails - looks like some of the recent modifications to Rails removed the particle use in the first place.

I think that would be sufficient to cover the "Blocker" parts of this issue :-)

**Comment by Cervator** [comment]
I've gone ahead and deleted the 3 particle effect prefabs in JS as the new default particle effects are working fine there and I cannot remember why we had those in the first place - maybe for some reason that wasn't needed anymore anyway? Maybe @Josharias remembers and could let us know sometime.

I also deleted the `LavaSplash.prefab` from the Sample module as it is a sample of the old system so not really relevant anymore. We should do a whole tutorial module for the new system anyway.

With that I'm considering this issue completed and will close it woo! Will submit a separate one for tutorial + follow-up
