### ISSUE TITLE
Client entity polling in input system

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/Terasology#2949]
The current version of `InputSystem` created the list of entities for the input like this:
```
    private EntityRef[] getInputEntities() {
        return new EntityRef[]{localPlayer.getClientEntity(), localPlayer.getCharacterEntity()};
    }
```
This method is called for *every* input, for *every* bind. With a short counter i got something like 5k calls per second, which is 5k arrays for the garbage collector and 5k component lookups inside the localPlayer to fetch the character entity.

It is probably best to cache this array in the input system.
Note that the client entity is set *after* `InputSystem.postBegin()` is called. Maybe it is possible to change the loading states order, so that the client is initialized before the postBegin are called.
Another option would be to poll less frequently, namely once per update cycle.
A third option is probably to add an event or kind of a notification when the client entity changes.

**Comment by eviltak** [comment]
Closed via #3697.

**Comment by jellysnake** [comment]
@eviltak I think you're referencing the wrong issue or PR here? #3697 adds component filtering to the dump entities command. I'm unsure how that fixes this?

**Comment by eviltak** [comment]
The PR also includes commit 6517dc9, which fixes this issue. It wasn't mentioned in the PR description, but I have edited the description to reflect this as well for future documentation!
