### ISSUE TITLE
Console input sanitation before auto complete 

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2963]
### How to reproduce

* Open up console
* type in `tele[` and press TAB for autocomplete
* Check error in log
* type in `tele(` and press TAB for autocomplete
* Check error in log

There is a regex error that shows up. An error log like [this](https://www.irccloud.com/pastebin/3X2Tghl3/console%20error%20log). The input should probably be sanitised of parentheses and square brackets before regex matching happens to look for autocomplete suggestions.

**Comment by Cervator** [comment]
Closing as completed by #2964 :-)
