### ISSUE TITLE
Wireframe box for an moving entity does not change

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2972]
For an entity as attached below, I do get a wireframe box that houses the whole model. (appears by pointing cursor at the handle)
![image](https://cloud.githubusercontent.com/assets/13916513/26764490/517cca50-4985-11e7-96a1-5f665fd1dc31.png)

However, when the model moves, in this case, rotates, the wireframe box does not follow. That is, the wireframe box remains static or fixed at the initial position. But to trigger the wireframe box to appear this time, I have to follow the rotating handle with the cursor.

@emanuele3d will add more details.

**Comment by jellysnake** [comment]
Merging this into #2980 as the two are similar enough that they probably stem from the same bug
