### ISSUE TITLE
crash on first launch - development build alpha2001

### ISSUE THREAD

**Issue by Germs2004** [MovingBlocks/Terasology#2978]
Since I could not run the latest release build, I tried the latest dev build.  I ran the launcher, downloaded the dev version, and as soon as I click the Play icon, it crashes.  The game never loads, not even to the main menu.

log: https://pastebin.com/cmm1UmLt

The release build's log had a nice stack trace.  This dev build log looks pretty unhelpful.  In the crash popup window, it has this tidbit:

A fatal error occurred
UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native

**Comment by skaldarnar** [comment]
This is indeed not very helpful. What kind of PC are you using? Can you please share the specifications (in particular the GPU/graphics card). 
I'm not sure this is graphics related, just in case pinging @emanuele3d

**Comment by skaldarnar** [comment]
Related to #2977

**Comment by Germs2004** [comment]
Windows 10 Pro 64
Intel i5-3570 CPU
ASRock H77M motherboard
16GB RAM
NVidia GeForce GTX 1070
Running as regular user, not local admin account

**Comment by emanuele3d** [comment]
Doesn't seem graphics related: usually the log is a bit longer if there is a compatibility issue with the GPU and it would give a better hint about graphics being the issue. Never say never though...

**Comment by skaldarnar** [comment]
Well, the stats are definitely fine, from a hardware perspective there should be now problem running the game... We'll try to find someone who can test it out on a similar system.

**Comment by Cervator** [comment]
Heya @Germs2004 - thanks again for the two reports :-)

Both of them point to the same cause: an issue with JNA, the way Java handles access to native files. That you mention an odd RAID setup in your other issue makes me wonder if that's the only peculiar part about your setup? Have you tried replicating the issue on an admin account just to see?

JoshariasSurvival loads OK on my system just now, also on Windows 10

With your system stats it should be smooth sailing. It may be something about user security or a problem with your Java setup. What does "java -version" get you?

**Comment by Germs2004** [comment]
I did a clean reinstall of Windows a couple days ago and I'm still crashing when trying to load the latest Development version (#2,014 alpha 2017-07-06T05:18:05Z) using the launcher.  I browsed into the DEVELOP folder and executed Terasology.x64.exe manually, and a popup says "Could not launch the game."  I then executed Terasology.x86.exe, and it worked, though it was super slow once the world loaded.

I then used the launcher to run the latest Stable Release, and the game's main window loaded, but once I tried to generate a world, it crashed with the usual handful of logs.

In case it matters, after I reinstalled Windows, I redirected my user profile's Documents and Desktop folders to my D drive, I installed Java using Ninite, I'm running as a local admin user account, Windows 10 version is 1703 with all updates, I use Bitlocker and Hyper-V, though Terasology is running from a SSD on the host, not inside a virtual machine.

When I run java -version, I get this:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by skaldarnar** [comment]
@Germs2004 We have a new Launcher release (in case you want to test that, although there is nothing particularly addressing this issue in the release).

https://github.com/MovingBlocks/TerasologyLauncher/releases/tag/v3.2.0

Maybe you can try what @Cervator suggested: download the game zip directly (without using the launcher).

**Comment by Germs2004** [comment]
I've never played this game so I don't want to spend any more time trying to get it working.  I'll just close this ticket and try again some day.  Thanks for your help, I hope you get it all figured out.
