### ISSUE TITLE
When typing a chat message and another player sends chat two chat screens are open

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2990]
When in a multiplayer session you are typing you have a fairly large chat window with many lines available visible. When you *receive* a message a smaller less intrusive window shows up to let you see new messages at a glance.

If both happen at the same time you get *both* windows:

![2017-06-24 19_19_43-terasology - c__dev_terasology_git_terasology - terasology - _config_grad](https://user-images.githubusercontent.com/1063833/27512552-1ca47f8e-5912-11e7-96aa-c7d3988c4162.png)

That's silly. The typing window is already larger, just suppress the "preview" variant and show the new message normally. 

`ChatScreen` is one of the involved classes.

**Comment by grubdragon** [comment]
Hey! I'm a beginner and I'd like to work on this issue

**Comment by skaldarnar** [comment]
Hi @grubdragon and welcome! Feel free to start working on this issue.

As @Cervator already wrote, you could start investigating this in [`ChatScreen`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/console/ui/ChatScreen.java) and [`ChatSystem`](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/chat/ChatSystem.java).

[Line 88 in ChatSystem](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/chat/ChatSystem.java#L88) looks like, in theory, there is some check to prevent this behavior. Maybe this only occurs in multiplayer, or the old code is no longer working. You best start with looking at those points.

**Comment by grubdragon** [comment]
Hey @skaldarnar could you guide me through this issue? I'm not sure on how to proceed. What is our desired behavior?

**Comment by Cervator** [comment]
Bump - hey @grubdragon :-) Did you have any other questions or luck with this item?

**Comment by grubdragon** [comment]
Hey @Cervator was a bit busy with some other work, I'll try and look around.

**Comment by grubdragon** [comment]
@Cervator @skaldarnar , did some poking around, didn't find anything that would cause the functionality to break. I'll look at it again with fresh eyes tomorrow I guess.
