### ISSUE TITLE
Crash when rendering.

### ISSUE THREAD

**Issue by AWebb3701** [MovingBlocks/Terasology#2995]
### What you were trying to do
Getting a good picture of a huge hillside. I bumped my movespeed up to 3x and turned on extreme view distance, then reached a shoreline.

### What actually happened
Crashed as soon as the shoreline started to render. 

### How to reproduce

* Step 1
set player speed to 3x
* Step 2
set view distance to Extreme
* Step 3
render a shoreline.

### Log details and game version
Omega 768

**Comment by AWebb3701** [comment]
Whoops, I thought the pastebin was included. This is a pretty useless ticket then >.>

**Comment by Cervator** [comment]
Yeah the log would've let us confirm it, but the crash was probably from #2590 - that's typically what causes non-obvious client crashes during play tests, and I suspect would've been aggrevated by the rapid chunk generation. So will close this on that assumption, just keep an eye out :-)

I re-enabled some pastebin alerts so we should be able to catch missed log links easier in the future, until the new telemetry project is in place.
