### ISSUE TITLE
Close screen if entity interacted-with is destroyed

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#2998]
A UI Screen or a BaseInteractionScreen opens when some items like chests are interacted with using `E`. An item is can only be interacted with, from a close distance. The screen, however, once opened stays open, even when the block/entity interacted with is destroyed or if the player goes out of range.

### How to reproduce

* Open a `headless + client 1 + client 2` or `server/client 1 + client 2` setup
* Place a chest on the ground using client 1. Use client 1 to interact with the chest (`E`) and open its inventory screen.
* Use client 2 to destroy/mine the chest.

Client 1 would still have the inventory screen open. However, the items inside would disappear since the chest entity is destroyed.

### What should be done?
The UI Screen stays active only at the client side. A possible solution might be to check for the existence of the existence of the interaction target in every BaseInteractionScreen's (newly created) update method.
In addition, it can also be checked here if the distance between the player and the interaction target does not exceed the allowed maximum.

**Comment by flo** [comment]
There used to be such a check, it probably needs to be checked why it is not working.

**Comment by ThompsonTyler** [comment]
Current version of develop I cannot replicate this problem as brought up by nihal, placing a chest and destroying with client or server while looking at it with the other closes the chest's inventory screen for both instances.

**Comment by Cervator** [comment]
Can confirm - issue appears to have been fixed at some point. Maybe @nihal111 has some details or ideas of when/how :-)

Tried in both 2 client and 2 client + headless. Tried both clients breaking the other's chest as well as moving away from a chest with the UI open.

Only quirk I could find is that the player inventory doesn't move back to its regular position, but that seems like a non-issue (normally the player inventory goes about in the center of the screen, with a chest it goes below-center and stays there even if the chest inventory is forcibly closed)

Closing this as mysteriously fixed, thanks for the detective work @ThompsonTyler !
