### ISSUE TITLE
This is SPARTA, just 10x

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#3000]
I just wanted to do this.

**Comment by Cervator** [comment]
Cheater :D

Closing from a distinct lack of it being over nine thousand. Though at least it is a third of the way there!

![not9k](https://user-images.githubusercontent.com/1063833/27982643-01747c88-6375-11e7-9070-0d27ed7da05f.jpg)

**Comment by xrtariq2594** [comment]
Congratz on reaching issue #3000.
