### ISSUE TITLE
Crash on chunkloading

### ISSUE THREAD

**Issue by portokaliu** [MovingBlocks/Terasology#3002]
Attaching the log [here](https://pastebin.com/49yJVNMt)

This happened on the official event server.

I haven't seen any other issue about it, hence this one. Should have all the details in the pastebin since I took the crash reporting path.

**Comment by dkambersky** [comment]
Duplicate of #2590, most likely

**Comment by portokaliu** [comment]
yep yep, Cervator said as well it would most likely be that. Wasn't aware of the existence of it. Gonna close this one.
