### ISSUE TITLE
Health / Death issues

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3003]
Discovered during some Alpha 8 RC testing and fairly important for a stable build so marking this as a release Blocker. Some of the observations / issues noted during a headless + regular client multiplayer session with JoshariasSurvival + Combat active:

- [x] Health regeneration seemingly didn't work after losing some health, for instance to starvation
- [x] In some case dying didn't produce a death screen and led to other weird effects - happened to @portokaliu who might be able to provide more details. IIRC he had logged on to our test server a day before meaning with JS active hunger + thirst would've drained. Also crashed from something unrelated before.
- [x] Respawning didn't reset the hunger + thirst bars, which probably should be the case
- [ ] ~Respawning didn't reset the *inventory* - which for now is probably OK and convenient, but is likely something we need to be able to easily configure~ - moved to #2158
- [x] The `AliveComponent` recently introduced by @nihal111 may still need some tweaks for better reliability in multiplayer (which I figure could possibly be causing some of the issues)
- [x] Other systems may still need to be adjusted for the `AliveComponent`

Nihal might be able to help provide some more ideas on where `AliveComponent` might be involved and what changes might be good to apply to the setup soon.

On a related note I have an architectural curiosity: *should* we by convention expect the `AliveComponent` to be involved with mostly anything that can die? Or should we consider flipping it to where *only* things that have meaning beyond death (players, pets, things with pending rez spells cast on them, but not regular deer) get marked somehow and only concern ourselves with systems that work differently when an entity is persisted beyond a spot where they'd normally be destroyed?

I might be off on some of these details, leaving the test server up for now and will try to retest again soon and update. Maybe also interested: @skaldarnar @flo @SkySom

**Comment by OvermindDL1** [comment]
> On a related note I have an architectural curiosity: should we by convention expect the AliveComponent to be involved with mostly anything that can die? Or should we consider flipping it to where only things that have meaning beyond death (players, pets, things with pending rez spells cast on them, but not regular deer) get marked somehow and only concern ourselves with systems that work differently when an entity is persisted beyond a spot where they'd normally be destroyed?

I'd be for flipping it to something that is dead but still exists, so an `IsDeadComponent` or so, which when on a player entity shows the death screen and such?

**Comment by nihal111** [comment]
Collecting my thoughts here..

Broadly speaking, 

1. Most of the things that rely on the BeforeDeactivateComponent event to await player death, should now rely on the PlayerDeathEvent. (note that the BeforeDeactivateComponent event is sent to the player/character entity while the PlayerDeathEvent is sent to the client entity. Which I plan to change here- https://github.com/MovingBlocks/Terasology/pull/3030)
2. Most of the things that rely on the OnPlayerSpawnedEvent should now rely on both the OnPlayerSpawnedEvent and the OnPlayerRespawnedEvent. (note again the added advantage- this allows for one time events that only need to happen on the first spawn).

Fixes-

Hunger- https://github.com/Terasology/Hunger/pull/12/
Thist- https://github.com/Terasology/Thirst/pull/5

- The Hunger and Thirst systems were not being reset on death, since they relied on the OnPlayerSpawnedEvent alone. Now they are being reset on both spawn and respawn.
- There was one more BeforeDeactivateComponent event in both Hunger and Thirst, that I don't think need to exist anymore, so I've removed them.
```
@ReceiveEvent
    public void beforeRemoval(BeforeDeactivateComponent event, EntityRef entity, HungerComponent hunger) {
        hunger.lastCalculatedFood = HungerUtils.getHungerForEntity(entity);
        hunger.lastCalculationTime = time.getGameTimeInMs();
        entity.saveComponent(hunger);
    }
```

**Comment by nihal111** [comment]
Regarding switching the `AliveCharacterComponent` to `DeadCharacterComponent` or something like that- I don't have a problem with either approach. Doing so, however would make certain things easy, while others difficult.

For instance, to find all entities that are alive with a specific component (which is in general a more common case compared to finding all dead character entities), a simple `entityManager.getEntitiesWith(HungerComponent.class, AliveCharacterComponent.class)` would work well. If however, we switch to a `DeadCharacterComponent`, we would have to do something like:
```
for (entity: entityManager.getEntitiesWith(HungerComponent.class,)) {
  if (entity.hasComponent(DeadCharacterComponent.class) {
     continue;
  }
...
}
```
This has a few more iterations, but more importantly looks worse than the above code that use the AliveCharacterComponent.

**Comment by OvermindDL1** [comment]
Sounds like a `getEntitiesWith` needs another argument for a list of things that should not exist, that would be generically useful as well for tag components.

**Comment by nihal111** [comment]
Regarding your architectural concern @Cervator, the reason for the birth of the `Alive**Character**Component` was because it was decided to preserve the player entity (which was earlier being destroyed). This way the player entity or in essence the player would still retain _memory_ in the form of components. For instance, if a player has certain skills, he does not lose them by an accidental fall. If a player maintains a journal, the entries aren't wiped out on a respawn and so on..

The AliveCharacterComponent was brought in to **mark differently, entities in their dead and alive states**. The CharacterMovementSystem was later configured to have work only with AliveCharacterComponents.
From the javadoc for AliveCharacterComponent-

>  * This needs to be necessarily attached to all character entities that require CharacterMovementComponent
>  * for movement systems to work.<br/>
>  * Can be used to differently handle situations for character entities that can remain in a dead state
>  * or respawn after a while.

**Comment by Cervator** [comment]
Sorry about getting the name wrong and thanks for the fixes :-)

I checked off the death screen, hunger/thirst on respawn, and tweaks for the component. I can still replicate the lack of regen although I'm not sure on the exact details. Got it for both a player 1 and 2 in the same multiplayer game after using `hungerSet` to wipe out my hunger bar. Flying up in the air to take falling damage didn't break regen. 

At first I thought it was from you also needing to have the thirst bar somewhat filled, but adding a partial thirst bar (so both were partial) didn't change the regen. *However* maxing out *both* bars let regen kick back in! Despite thirst dropping so quickly that it doesn't stay max long. After that point I could `damage 90` and still regen fine now with both bars partial again. Maybe it'll ring a bell to @xrtariq2594 

On the architecture bit:

>If however, we switch to a DeadCharacterComponent, we would have to do something like:
>for (entity: entityManager.getEntitiesWith(HungerComponent.class,)) {
>  if (entity.hasComponent(DeadCharacterComponent.class) {
>     continue;
>  }
>...
>}
>This has a few more iterations, but more importantly looks worse than the above code that use the AliveCharacterComponent.

I actually did expect that, but with a slight angle on it. Yep you would need that code to add functionality *specifically for dead characters* that still have the other component. But by default (just getting entities with Hunger, regardless of Alive/Dead)  hunger would trigger in either case - but in the case of a dead deer the poor deer has now expired and its entity isn't around to trigger hunger while dead anyway.

In the case of a player who *can* persist beyond death (or other similar cases) then yeah any author who cares about the distinction for a specific bit of functionality would need to add a death check. What I'm wondering is which situation results in more extra code.

* Old system - no distinction, but death is death and nothing exists beyond it.
* New system as-is - anything that happens and involves characters need to include the `AliveCharacterComponent` or weird things may happen to dead things. But now dead things can persist and participate in certain activities! Yay :-)
* New system flipped - no new code requirements by default *but* any activity that involves characters will happen for both dead or alive things unless the author distinguishes between the two at the logic level
* Other semi-random idea - block all events that happen to things with `DeadCharacterComponent` attached (engine level critical priority that consumes the event) excepting things that somehow opt in (blacklist/whitelist approach of some sort). I guess that is somewhat similar to having a `getEntitiesWithAndWithout` but without the extra code everywhere, but with more hidden magic.

I'm not set on any particular option more curious about further opinions :-) And examples of what other scenarios exist where an entity persists beyond death. In the case of say an NPC corpse wouldn't it just switch to no longer be a character and lose a bunch of other components? Or even have a loot-specific entity spawn instead to hold the body + shinies?

Should a resurrectable pet be its original self persisted beyond death to be a target for a rez spell, or a completely different entity that's more like "Hey I used to be X. I'm going to hang out here for Y time units just in case somebody wants to rez me"?

**Comment by Cervator** [comment]
After some digging by @nihal111 the no regen mystery might be solved, there is a threshold for when the bars block regen and I was testing *just wrong enough* to be thrown off by it :-) Marking that one off too

**Comment by nihal111** [comment]
Just for reference -
https://github.com/Terasology/Hunger/blob/master/src/main/java/org/terasology/hunger/component/HungerComponent.java#L60

**Comment by Cervator** [comment]
Closing this as part of Alpha 8 as mostly complete, moved one remaining item to #2158

I don't know what architecture is ideal but am leaning toward whichever architecture is actually made to work, as inherently superior to something that is theoretical and does not in fact work - yet :-)
