### ISSUE TITLE
is Terasology working on Mac currently

### ISSUE THREAD

**Issue by manzoid** [MovingBlocks/Terasology#3007]
### What you were trying to do
Vanilla install of v1.4.0 on MacBook Pro, create a Core Gameplay local game.

### What actually happened

![image](https://user-images.githubusercontent.com/796541/28241222-345e328a-6945-11e7-890a-6fb9f3e02997.png)

### How to reproduce

* git clone https://github.com/MovingBlocks/Terasology.git
* ./gradlew build
* ./gradlew game
* Single Player > Create Game
* select `Core Gameplay` template (or any gameplay template *except* Sample Gameplay (that one works))
* create the game
* crash

### Log details and game version
https://drive.google.com/uc?id=0B5l2RT_UOCXRbHdZYXE2ZE1uQ00&export=download

### Computer details
![image](https://user-images.githubusercontent.com/796541/28241195-b6a076dc-6944-11e7-90c7-4ec40de2228a.png)

Java version:

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by Cervator** [comment]
Resolved on IRC earlier :-)

Problem was caused by connecting to the stable game server which is running alpha 7 and thus provoked the download of older binaries mixed with newer source.

Thanks for the detailed report and follow-up on IRC!

**Comment by tim-italist** [comment]
Yes in case anyone else runs into this, a bit more context -- as Cervator mentioned, when you connect to  one of the game servers, the .jar files corresponding to that server version are automatically downloaded to your local modules directory.

This can cause a mismatch between the core engine code (literally named "core") and other modules that you had previously downloaded locally that were meant for another engine version.

The specific fix was to look for .jar files under {project_root_dir}/modules with file names prefixed with "core" and delete them. This way your local engine version doesn't get overridden anymore and the module mismatch goes away.

**Comment by manzoid** [comment]
Yes in case anyone else runs into this, a bit more context -- as Cervator mentioned, when you connect to  one of the game servers, the .jar files corresponding to that server version are automatically downloaded to your local modules directory.

This can cause a mismatch between the core engine code (literally named "core") and other modules that you had previously downloaded locally that were meant for another engine version.

The specific fix was to look for .jar files under {project_root_dir}/modules with file names prefixed with "core" and delete them. This way your local engine version doesn't get overridden anymore and the module mismatch goes away.
