### ISSUE TITLE
Advanced chunk monitor prevents game from closing cleanly

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3010]
### What you were trying to do

Run and close the game cleanly with `monitoringEnabled` set to true (for example to test #3006)

### What actually happened

Game windows (there are two with the monitor visible) closed, but the game didn't exit. Some thread triggered by the monitor isn't exiting on game exit

### How to reproduce

* Toggle `"monitoringEnabled": false,` to `true` in `config.cfg` (run the game once to get one)
* Run the game
* Close the game
* Protip: Trigger a thread dump in IntelliJ to inspect threads that are still alive after exiting (little camera looking icon near the bottom left, in the run window)

**Comment by grubdragon** [comment]
Hey, I'll try tackling this issue
