### ISSUE TITLE
New option to filter online available modules from the module screen

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3014]
At present the "Select Modules..." screen populates the list with all modules available in the local game installation **and** all available from our meta server for download - which can become quite a lot of modules, especially if you're developing in a small focused workspace and don't need the added *noise*

We could add a simple "Local Only" checkbox on the page that would filter out any module not originating from the local game / skip querying the meta server for updates. That could also dual purpose if needed as a *refresh* if for some reason you wanted the list of modules available online reset and repopulated (just click the checkbox twice)

I suggest shrinking the "Disable All" button then fitting the new checkbox on either side.

Shouldn't be too hard so marking bite-size. Start by looking at `SelectModulesScreen.java`

Bonus: Persist the setting in `config.cfg` so the choice is remembered (review similar settings elsewhere in the menus for inspiration)

Screenie of current state:

![2017-07-20 20_46_55-terasology _ alpha](https://user-images.githubusercontent.com/1063833/28444788-a0a2a40c-6d8d-11e7-9193-09f1b221b677.png)

**Comment by nihal111** [comment]
Instead of shrinking "Disable All" and adding the "Local Only" checkbox to the left of it. I think a better idea would be to add an new row below the "Disable All" button that has 2 checkboxes- "Local Only" and "Show Library/API".

The Library modules (like Pathfinding, AdvancedBehaviors etc) and API modules (like WorldyTooltipAPI) are always displayed. These clutter the module list now.

**Comment by nihal111** [comment]
https://github.com/MovingBlocks/Terasology/issues/2935 was the issue I was referring to earlier. The one which requires the need of "Show Library/API"
But this also requires the creation of new fields like `isLibrary` and `isAPI` in module.txt

**Comment by Cervator** [comment]
Closing this as completed by #3017 :-)

The library checkbox is disabled until we can actually use it, good suggestion!
