### ISSUE TITLE
Crash after F5 menu

### ISSUE THREAD

**Issue by jugendhacker** [MovingBlocks/Terasology#3015]
### What you were trying to do
I tride to close the F5 Menu.
### What actually happened
The Game crashed!
### How to reproduce

* Step 1
Press F5
* Step 2
Click on some Buttons
* Step 3
Presss Esc

### Log details and game version
https://pastebin.com/9HAQy8rt

**Comment by skaldarnar** [comment]
Thanks for the report @jugendhacker.

@dkambersky is currently working on the behavior trees as GSOC project, so let's see what he might have to say about this :-)

**Comment by dkambersky** [comment]
Looks to be an issue with the Behavior system or Interepreters not being initialized. However this is in the old, soon to be replaced, implementation, so I wouldn't worry about it. I'll try and reproduce this in the new system just in case.

**Comment by dkambersky** [comment]
I can confirm this works fine in the new system. Should we close this or leave it up for now?

**Comment by jugendhacker** [comment]
I think we can close this
