### ISSUE TITLE
Crash when generating world

### ISSUE THREAD

**Issue by ciskos** [MovingBlocks/Terasology#3026]
### What you were trying to do
Start game

### What actually happened
Crash when generating world

### How to reproduce
Just start the game

### Log details and game version
Log - https://pastebin.com/pjj5q2Sv
### Computer details
Notebbok - HP Pavilion 17-e040sr
CPU - AMD A10-5750M
Videocard1 - ATI/AMD Radeon HD 8650G (RICHLAND DEVASTATOR MOBILE) [Hewlett-Packard]
Videocard2 - ATI/AMD Radeon HD 8670M/8690M (Sun XT) [Hewlett-Packard]
RAM - 8GB
Windows - x64

**Comment by Cervator** [comment]
Hey there @ciskos 

It looks like there's a bit of a mismatch inside the game:

```
13:11:08.230 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: engine:1.4.0
13:11:08.235 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Core:1.4.1-SNAPSHOT
13:11:08.235 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreSampleGameplay:1.4.1-SNAPSHOT
```

The engine v1.4.0 is our latest stable release Alpha 7. But 1.4.1 is the latest dev build. Did you by chance update any modules using the in-game module browser?

Running those two together might very well cause crashes like that.

How did you get a hold of a copy of the game? Using our launcher or a direct game zip? Did you grab the latest stable release or a dev build?

**Comment by ciskos** [comment]
Hello.
Yes I was download modules and update some of them.

The copy of the game was downloaded from official site - terasology.org .
Using launcher.
The launcher download latest stable release.

I reinstall the game, now it works fine. Thanks for your time :) .

**Comment by Cervator** [comment]
Great, thanks for letting us know. And I thought it was odd to get two log snippets (forum too) both indicating a version mismatch but didn't make the connection ... :D
