### ISSUE TITLE
ESC key does not close the Join Game screen

### ISSUE THREAD

**Issue by nihal111** [MovingBlocks/Terasology#3034]
The `ESC` key closes the "Single Player" or the "Host Game" screens from the main menu. But it does not close the "Join Game" screen.

**Comment by JamesB01** [comment]
I can take a look at this, if you're happy for an Open Source noob to be involved?

**Comment by Cervator** [comment]
Hi @JamesB01 - absolutely! That is exactly what the Bite-sized issues are for :-)

Welcome! Let us know if you have any questions.

**Comment by Cervator** [comment]
Oh! One thing I might suggest is to check out https://github.com/Terasology/TutorialNui to learn more about our GUI stuff. Although for this particular case you can probably just examine similar code that does it the right way and apply it to this other screen. Anyway, in case you wanted to know what makes it all tick :-)

**Comment by JamesB01** [comment]
Coolio.  Do I need to become a collaborator (sorry, pretty new to Github and not 100% on how everything works - just taken me like two hours to get it open in netbeans!)

**Comment by Cervator** [comment]
No need, just fork, clone, load it up, try to fix something, commit to your fork, make a PR. Easy :-)

Then a bit of code review, merge, add you to credits, and tadaa you're a contributor!

More setup info over at https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup if you haven't found it yet - we're the best set up for IntelliJ and the least set up for poor ole Netbeans I'm afraid. But it _should_ work :-)

**Comment by Cervator** [comment]
Auto-closed with PR #3057 merged. Unsure if that's you on a different account @JamesB01 but in either case I hope we see you around more! :-)
