### ISSUE TITLE
Exiting a world then reloading that save shows whatever held item the player had in the location where you left

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3043]
Seems like #2605 wasn't _quite_ fixed by #2810 anyway - maybe? 

![terasology-170802232128-1152x720](https://user-images.githubusercontent.com/1063833/28904518-8d70bf58-77d9-11e7-93cf-fb48e4f74df1.jpg)

But rather than there always being a copy of the held object at 0,0,0 it seems like now a copy is made / persisted wherever you were when you exited said world. On each reload a new fixed item matching the held item appears where you were last.

Suspecting it is related to #2605 and #2810 at least. Maybe interested: @Tropid, @portokaliu @vampcat @nihal111 

Fairly critical item for the Alpha 8 release so marking it as a Blocker. Help sincerely appreciated! :-)

**Comment by portokaliu** [comment]
It is most likely that one. I'll see if I can fix it this evening/night

**Comment by Cervator** [comment]
Closing as fixed by #3049! :-)
