### ISSUE TITLE
Accidentally changing the view distance can cause bad performance and a crash

### ISSUE THREAD

**Issue by Vizaxo** [MovingBlocks/Terasology#3055]
### The problem

For a while I've had an intermittent problem where sometimes the game would get slow, start stuttering, and then eventually crash with an OutOfMemoryError or other GC problem. I thought it was something to do with the changes I was making to entities or something with Dynamic Cities, but I reproduced it on a fresh build on the flat world today

Then I realised that I'd accidentally hit `Home` a couple of times, setting my view distance to extreme. This was causing the memory to spike very high, up to the maximum, and the stuttering was caused by the GC going crazy trying to keep the game alive. When the memory got too high the game couldn't cope, and crashed.

### The solution(s)

I think there are really 2 problems here: one is that I could change the view distance and not notice, and the other is that setting the view distance too high caused a crash, rather than gracefully degrading.

I think that a message should pop up when the view distance changes to inform the player of what happened (and/or maybe changing the view distance without going into the menu should be disabled by default, to prevent confusion if the button is accidentally pressed).

There should also probably also be a way of detecting that the current view distance is unsustainable, warning the player that they haven't allocated enough memory, and automatically degrading to a lower view distance instead of crashing.

**Comment by Cervator** [comment]
I would consider the following a decent definition of done:

* To increase visibility log a change of the view distance to the chat bar area. That happens already when a player enters or leaves a multiplayer session (along with a few other cases). Should be easy to run two instances of the game, look for the exact string that having player two join causes, then search the code base to find where it is to get a good example :-)

As a bonus make the message include a warning if the "MEGA" or "EXTREME" view distance is selected (neither is really expected to be viable for the vast majority of PCs)

I had posted about an issue in the past about better marking the view distances / marking some programatically to be unusually heavy, but am having trouble finding that issue.

**Comment by Cervator** [comment]
Closing this as completed by #3140 - the harsh impact to performance still remains but is now vastly more visible. The performance issue is a bigger piece I think we'll naturally improve over time.
