### ISSUE TITLE
Enhance game executable scripts to pass forward command line arguments

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3068]
As @nihal111 just noticed it doesn't actually appear that our executable scripts accept command line arguments, say if you're trying to launch the game with `-homedir` on Linux. The Windows exe works fine as does running via command line using `java ...`

When I was working on #2979 to get the Groovy Wrapper working I noticed the `gradlew` script (which my `groovyw` is just a slightly modified copy of) has extensive handling for command line arguments, environment settings, etc. Maybe we can just copy a small part of that into the `run_linux.sh` (and `run_macosx.command` if somebody can test on a Mac) so any command line arguments passed will be passed forward and placed `... -jar libs/Terasology.jar <HERE>`

Probably not very hard since that is a very common need so finding examples be it inside `gradlew` or on Google should be easy. However it does require access to a Linux and/or Mac system for testing.

**Comment by TheFlash98** [comment]
Hey @Cervator I don't understand what you mean by `run_linux.sh` and `run_macosx.command`, where are these files?

**Comment by Naman-sopho** [comment]
@Cervator  
I am new to the project, so what I could gather is, to add a feature to handle the command line arguments passed to the shell script `run-linux.sh`. Correct me if I am wrong.
Also, is there a fixed number of command line arguments to be handled?

**Comment by TheFlash98** [comment]
The command line arguments have to be handled in the `run_linux.sh` and I think this issue requires you to only handle changing environment when running the game from source. I hope this helps till @cervator replies.

**Comment by Cervator** [comment]
@Naman-sopho - hi there, you are correct :-) I think usually such hooks are limited to maybe 10 or less arguments, if even that.

@TheFlash98 - thanks for catching it early! Although I dunno if there actually is a use case for using the scripts while running from source. At that point you'd be adding arguments in a run configuration or via command line parameters when using Gradle. 

I just mentioned the observation of `gradlew` / `groovyw` doing parameters as an example :-)

**Comment by Naman-sopho** [comment]
@TheFlash98 @Cervator 
I've opened a PR but it seems like too easy a solution to the issue :) . Can you please review it and point out if I am missing something?
