### ISSUE TITLE
Game crash on second world load due to odd particle initialization / lifecycle

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3087]
Noticed by @portokaliu - after you leave the game world once `ParticleSystemManagerImpl.shutdown()` executes  `particleUpdater = null;` probably in an attempt to clean something up. However the `initialise()` method that sets it only runs on *game* start, not entering a new world. So on attempt two `particleUpdater` remains null and NPEs the game.

Blocker level critical for Alpha 8 but probably relatively straight forward fix: _don't do that_ - question is whether we should not null it out, instead favoring a better cleanup. Or if we just want a hack fix then add null checks and reset the variable to a valid new updater.

Needs a bit of poking around to see what the better option is. Submitting this so we don't forget. Pinging @MaxBorsch if interested (also: argh why doesn't your name auto-complete in a ping, I don't understaaaaand)

Unsure if we have a lifecycle step on entering a world to initialize this thing, or if we need one. Or if the particle system just needs a bit more tweaking - probably :-)

**Comment by portokaliu** [comment]
More precisely, the particleUpdater is initialised the second time as well, but it's being deleted right before the player enters the world due to a shutdown ( which I haven't been able to fully track just yet).

**Comment by oniatus** [comment]
Found the issue.
`ComponentSystemManager` holds a list of renderSubscribers (RenderSystems). The list is never cleared.
After the first run (does not matter if you create the world or load the game for the first time after engine startup), the Manager will hold a reference to a `SpriteParticleRenderer` which holds a reference to the first `ParticleSystemManager`.
At the second run, another `SpriteParticleRenderer` is added to the list. Then all render subscribers are executed. The first  `SpriteParticleRenderer` calls the first `ParticleSystemManager` which has been cleaned right now and causes a null pointer exception.
The solution would be to clear both lists in the ComponentSystemManager at shutdown.
I will open up a PR for this.
