### ISSUE TITLE
Alpha 9 release prep & QA

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3093]
Still playing with ways to track stuff better, like minor known issues across the module ecosystem, making it more visible in this tracker somehow :-)

Some outstanding but fairly recent and easy to discover issues from the past - found during testing for Alpha 7 and 8, left outstanding as 8 was being released. *Some* of these may be approachable for new contributors interested in things to fix.

*Mostly bugs*

* On upgrading a basic workstation in NeoTTA to advanced the player client will crash - the upgrade will happen and you can jump right back in, but naturally that's a bit annoying. Not sure there is a module issue but https://github.com/Terasology/WorkstationCrafting/issues/3 might be about in the same area and see https://github.com/MovingBlocks/Terasology/issues/2766#issuecomment-284173570 for some more details
* Also NeoTTA: Progress bar is missing when you craft something with duration like when using the portable forging station (the item does finish crafting and appear if you wait)
* Clay hearth misbehaving in NeoTTA: https://github.com/Terasology/WoodCrafting/issues/4
* ~Lava huts from Inferno are a bit more dilapidated than expected: https://github.com/Terasology/Inferno/issues/3~ 
* Only some food items are actually edible - example "Cooking:apple" can be eaten with NeoTTA running, but "SimpleFarming:apple" cannot. Part of the cooking/food overhaul, not sure we have any explicitly related issues (if anybody knows feel free to add) but here are some that might relate:
  * https://github.com/Terasology/Cooking/issues/124
  * https://github.com/Terasology/Cooking/issues/113
  * https://github.com/Terasology/Hunger/issues/4 (may be out of date)
* The `GooeysQuests:dungeonMaze` prefab still places plain old stone walls while the other dungeon elements have been updated to a neater stone type. Should be a super easy change
* Gooey doesn't seem to respect the "Follow" option anymore in GooeysQuests
* Hunger/Thirst shouldn't count down on a server while a player is offline https://github.com/Terasology/Hunger/issues/13 and perhaps a new Sustenance module should centralize the shared logic

*More like open suggestions:*

* We have a [GDoc from GCI 2016](https://docs.google.com/document/d/1hHpthirUmtJbCIrAZ5FVqVtz_dzGEGl_oXkvjDwjhYE/edit) with the work that was done there. Some of it has yet to be fully merged or fixed - a good exercise might be checking out some of the items to see if they are accessible, ready to be merged, or need fixes (ideally then even providing said fixes if possible)
* Should spooked deer spook other deer?
* A bind command to pair a hot key with a console command like ghost
* Player name tags should be hidden beyond a certain distance and/or when the player is behind objects (may be tricky)
* Long standing issue: food/water probably shouldn't drain while the player is offline

*Outstanding but because part of v2*

* https://github.com/MovingBlocks/Terasology/issues/2070 - working behavior tree overhaul woo!
* https://github.com/MovingBlocks/Terasology/issues/2774 - sectors and such woo!
* https://github.com/MovingBlocks/DestinationSol - not even Terasology but also hugely improved during GSOC 2017 which is just finishing woo!

**Comment by iojw** [comment]
https://github.com/Terasology/Inferno/issues/3 has been fixed

**Comment by Cervator** [comment]
Closing as Alpha 9 is being released! I turned a related play test project board into more of a known issues thing: https://github.com/MovingBlocks/Terasology/projects/3 and carried on some of the linked issues there.
