### ISSUE TITLE
Further options for new Groovy-based utility commands

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3099]
With #2979 merged we now have the new [Groovy Wrapper](https://github.com/MovingBlocks/groovy-wrapper) in place for making easier and more powerful utility scripts than the somewhat awkward old `gradlew fetchModuleX` approach. Now we can has `groovyw module get X` instead!

I only prepared two initial options for fetching individual modules or all modules in a dependency tree. With that example in place I expect it will be fairly easy to go beyond that to include module creation in `module.groovy` and adding new *stub* scripts for facades, libs, and meta modules (each type would live in its own script like `facade.groovy`)

Likely there will be shared functionality between the scripts that could be centralized in a single include script of some sort. So here are some tasks:

- [x] Finish the module creation part of `module.groovy` (there is just a placeholder entry in the `switch` right now)
- [x] Create `facade.groovy` and make the new versions of retrieving and creating facades (shouldn't need to worry about dependencies so recursing isn't useful there). Good example to retrieve: https://github.com/MovingBlocks/FacadeServer (`gradlew fetchFacadeServer` -> `groovyw facade get Server`)
- [x] Create `lib.groovy` and retrieval and creation there. Also no dependencies/recursing there. Good example: https://github.com/MovingBlocks/CrashReporter (`gradlew fetchLibCrashReporter` -> `groovyw lib get CrashReporter`)
- [x] Create `meta.groovy` and retrieval plus creation (just an empty dir really) for meta modules. No dependencies or recursing needed, they're just storage repos. Good example: https://github.com/MetaTerasology/WildAnimals (`gradlew fetchMetaWildAnimals` -> `groovyw meta get WildAnimals`)
- [x] Centralize any shared logic resulting from the above tasks
- [x] Add entirely new option to *update* one, a set (dependencies), or all modules with a single command (so something like `groovyw module update X`, `groovyw module updateTree X`, and `groovyw module updateAll`)
- [x] Come up with some additional suggestions? Unsure if there is any point in bulk updating facades or libs. Maybe meta modules? Seems unlikely though.

Look in `config/gradle/utility.gradle` for how the old approach worked, which files to include or create, and so on. See also #2979 for more details about how the new system works.

**Comment by SkySom** [comment]
So does the new module get allow for telling it to pull all dependencies as repos?

**Comment by Cervator** [comment]
@SkySom `groovyw module recurse X` will :-) X plus all its dependency modules will be retrieved as source modules.

`groovyw module get X` just retrieves X solo

**Comment by grubdragon** [comment]
Hey! Can somebody get me started on this?

**Comment by digitalripperynr** [comment]
I have a PR waiting that centralizes the required functionality for modules, facades, libs etc into one single script with shared methods to reduce repetition of code.
The functionality works absolutely fine. Check #3206 for detailed info.

Also, in case the unified script is not accepted, I have Library Script( #3191 ) and Meta Module Script ( #3176 ) waiting as well.

The module script was already updated by @Cervator and is now included in the current release. It now includes interesting git remote functionality. The help portion needs to be tweaked a bit but the functioning is perfectly fine.
