### ISSUE TITLE
Compatibility issue with Java 9

### ISSUE THREAD

**Issue by dariost** [MovingBlocks/Terasology#3106]
Terasology crashes when trying to create a new game giving [this error](https://github.com/MovingBlocks/Terasology/files/1326193/terasology.log). 
After discussing it with @Cervator on IRC he found out the crash is related to the Java version installed on my pc.
```
$ java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```
Java 9 is now in [general availability](http://openjdk.java.net/projects/jdk9/) and has already landed in the [Arch Linux repository](https://www.archlinux.org/packages/extra/x86_64/jdk9-openjdk/).

**Comment by dariost** [comment]
I should also add that there's a lot of flickering while Terasology is starting (I did a [screen capture](https://www.youtube.com/watch?v=wl3YcXwqJDk), ignore the flickering that happens after 0:12 because that is my iGPU which is not fast enough to record the screen **and** load the game)

**Comment by gianluca-nitti** [comment]
I think I found a (one-line) fix, see #3107 for more information.
If you want to test you should be able to do it with a `git clone https://github.com/gianluca-nitti/Terasology && cd Terasology && git checkout java9-fix && ./gradlew game` in a temp directory.

**Comment by dariost** [comment]
@gianluca-nitti running `./gradlew game` gives an error (I added a `--info` for the [log](https://github.com/MovingBlocks/Terasology/files/1326480/gradlew.log))

**Comment by dariost** [comment]
After discussing it with @gianluca-nitti he found out that the problem with gradle was because of the [Arch Linux packaging](https://bugs.archlinux.org/task/55716); after having managed to get gradle to build Terasology I confirmed that Giancula's PR fixes the problem with creating a new game (the graphical flickering and glitches remain)
