### ISSUE TITLE
Being unable to stand after crouching causes noclip

### ISSUE THREAD

**Issue by jellysnake** [MovingBlocks/Terasology#3108]
Attempting to stop crouching in a 1 block tall space causes the player to clip through the ground.
This can then be repeated once the player is underground to crouchfall forever.

[Gif demonstration](https://gfycat.com/AmbitiousBabyishDeermouse)
(apologies for odd screencap)

**Comment by oniatus** [comment]
Closing as proposed in https://github.com/MovingBlocks/Terasology/pull/2961#issuecomment-341993601
The PR should fix this issue.
Follow up issue is #1075
