### ISSUE TITLE
Crash due to using Java 9

### ISSUE THREAD

**Issue by noxarivis** [MovingBlocks/Terasology#3125]
https://pastebin.com/jN0AD2UV

**Comment by jellysnake** [comment]
This crash is due to using java 9, which we don't yet support, as per issue #3106. If you install and/or run Terasology using Java 8 then it should load fine.

**Comment by noxarivis** [comment]
lol, no joke i didnt even install java9 (at least not knowing of it)
i will use  the netbeans java, (which should be jdk8)
thanks ans sorry
