### ISSUE TITLE
"Dropped items glitch!"

### ISSUE THREAD

**Issue by noxarivis** [MovingBlocks/Terasology#3126]
### What you were trying to do
Play the game
### What actually happened
after loading i had less than 1 fps,
i saw this glitch
![bildschirmfoto von 2017-10-18 12-30-56](https://user-images.githubusercontent.com/30774451/31715128-e7535606-b402-11e7-92ba-9b94fa347fe7.png)
![bildschirmfoto von 2017-10-18 12-32-50](https://user-images.githubusercontent.com/30774451/31715180-0f2d5e2e-b403-11e7-9d92-0dd521936345.png)

### How to reproduce

* Drop several irems
* close the game
* load the game

### Log details and game version
no logs yet,
Dev 2060
Stbl 72
### Computer details
/dev/Acer Aspire 3
RAM 8GB, Swap 8GB
Intel Core i3-6006U
HD-Graphics 520   

OS: Fedora 26 WS (Gnome 3.25.2 | Linux: 4.13.5-200.fc26.x86_64)   
Java: jdk1.8.0_141 (The default one of Netbeans)

**Comment by pollend** [comment]
Can you explain what is happening. Is this a result of poor framerate or is there something wrong with the physics component of the game. Can you expand on exactly what is happening.

**Comment by jellysnake** [comment]
Ah, I know this issue. It seems like #3043 has returned from the grave.

**Comment by noxarivis** [comment]
@pollend @jellysnake
The framerate is like 0,01FPS and I confirm that thease where items i held, so it might be the reincarnation of #3043

**Comment by noxarivis** [comment]
but it might also be the dropped items

**Comment by noxarivis** [comment]
BTW, i might help fixing bugs if i can, i kinda just started with java.
I just wait for Apache Netbeans 9 to be released.

**Comment by emanuele3d** [comment]
@portokaliu, this seems to be identical to the bug you fixed in #3049. Can you take a look?

**Comment by portokaliu** [comment]
@emanuele3d I will look into this tomorrow evening

**Comment by noxarivis** [comment]
any news?

**Comment by portokaliu** [comment]
I did look into it, but no solution as of yet. Still on it though. It might be the reworking of the "in hand" item dealio

**Comment by noxarivis** [comment]
its the only bug i found so fare, else its pretty stable

**Comment by jellysnake** [comment]
Hah, you've been lucky with your module choices it seems.

**Comment by noxarivis** [comment]
i use the default setting

**Comment by bbarker** [comment]
I believe I also ran into this in the default mod settings for Josharias Survival in the latest stable release. I had great FPS before, noticed rather slow but somewhat usable FPS after up the game again, and then  saw a similar effect.

I see there is already a fix in the works - I'd be happy to test it when it is released, or test it if desired.

**Comment by bbarker** [comment]
![image](https://user-images.githubusercontent.com/916366/32409955-c3e733bc-c18c-11e7-8fbd-c3040caa608b.png)

And from a slightly different angle:

![image](https://user-images.githubusercontent.com/916366/32409959-dc1990a6-c18c-11e7-9b02-49803482d4d8.png)

**Comment by jellysnake** [comment]
Thanks for the extra images @bbarker. It's a bug that we've had before, so seems to be rather persistent. If you are happy to help test then I'll tag you in the pull request. :)

**Comment by Cervator** [comment]
Closing as fixed by #3137 - hopefully for good this time. Would be happy to get some extra testing in this area, maybe an item to remember for next play test :-)
