### ISSUE TITLE
Implement pause while in menu

### ISSUE THREAD

**Issue by bbarker** [MovingBlocks/Terasology#3139]
At the suggestion of https://github.com/Terasology/JoshariasSurvival/issues/19#issuecomment-341944894, I'm opening an issue to implement pausing the game while in menu, if it is a single-player game (or maybe if only one player is in the game world, whatever makes more sense).

**Comment by portokaliu** [comment]
Is anyone working on this currently? Did see some `pause` related code added, but apparently it hasn't been touched since 2012

**Comment by Arihant-Joshi** [comment]
Can someone review my PR?

**Comment by Cervator** [comment]
PR reviewed and merged. Pause now works in single player. It is *possible* to make it work in multiplayer but that gets trickier fast.
