### ISSUE TITLE
Tidy up / refactor DebugControlSystem

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3141]
Came up while reviewing #3140 - the DebugControlSystem (DCS) has some rather weird stuff in it that doesn't seem to have anything to do with debug mode.

It is a very old class with lots of history so it probably slowly morphed into what it is today. It lacks Javadoc so I'm not really sure what the intent was but as I interpret it the only thing it should be doing is related to unique actions only available when debug mode (F3) is enabled.

Things to review/change to complete this issue:

- [ ] Add class-level Javadoc and any other javadoc possible when fully sure what it all does
- [ ] Should `onHideHUD` really be there? It does getting into something with `getDebug()` but is that really valid? The player should be able to hide the HUD regardless of whether debug mode is on
- [ ] `onIncreaseViewDistance` and `onDecreaseViewDistance` should be moved somewhere more sensible. Definitely not something that requires debug mode and it doesn't reference it at all
- [ ] `fireChangedEvent` was added with #3140 including support for sending change events to a series of interested parties in case that became relevant in the class - but with it already doing more than it is supposed to maybe it'll never need it. Do we have any such utility somewhere else already?

I'm not sure *where* the view distance stuff should get moved to. May be relevant to @vampcat or @emanuele3d's interests since rendering config is involved.

The translation bits may no longer be needed in this class with the view distance changing moved out. They should be added if not already present in a suitable target system. Feel free to look for similar issues there - for instance changing the view distance at present also results in a simple log statement in `RenderableWorldImpl` that at present isn't using the translated value, just the key. Fix fix fix! :-)

Another maybe extra: Should the view distance warning notification for MEGA and EXTREME just be merged with the regular notification so there's only one? Just with the warning added at the end when appropriate.

**Comment by emanuele3d** [comment]
Yes, it's one of those things I'd like to overhaul a bit but is lower priority compared to everything else. 

If it could be broken in smaller bits, all around some kind of cohesive vision, we could turn this into a chain of GCI tasks.

**Comment by Naman-sopho** [comment]
@Cervator @emanuele3d I want to work on this issue if its available.
