### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by tyronx** [MovingBlocks/Terasology#3148]
On a Nvidia GT 630M graphics card. Looks like your shaders are not very compatible:

20:40:15.397 [main] ERROR org.terasology.assets.AssetType - Asset instances remained loaded after disposal - [engine:messagePopup!instance]
20:40:16.011 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: engine:1.5.1-SNAPSHOT
20:40:16.011 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BuilderSampleGameplay:1.5.1-SNAPSHOT
20:40:19.807 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome org.terasology.world.biomes.UnknownBiome@30c03473 with short id 0.
20:40:19.902 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:clientInfo with inputs [/engine/assets/prefabs/player/clientInfo.prefab]
20:40:19.914 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:wrapper with inputs [/engine/assets/prefabs/behaviorNodes/wrapper.prefab]
20:40:19.915 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:blockType with inputs [/engine/assets/prefabs/blocks/blockType.prefab]
20:40:19.918 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:camera with inputs [/engine/assets/prefabs/player/camera.prefab]
20:40:19.920 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type Matrix4f: not a supported type or MappedContainer
20:40:19.920 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:FirstPersonHeldItemMountPoint.toolAdjustmentMatrix'
20:40:19.920 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type OpenVRProvider: not a supported type or MappedContainer
20:40:19.920 [main] INFO  o.t.p.t.TypeSerializationLibrary - Unsupported field: 'engine:FirstPersonHeldItemMountPoint.vrProvider'
20:40:19.922 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:player with inputs [/engine/assets/prefabs/player/player.prefab]
20:40:19.923 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
20:40:19.923 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'maxGroundSpeed' onto 'engine:CharacterMovement'
20:40:19.924 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
20:40:20.117 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Breather'
20:40:20.120 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:gaze with inputs [/engine/assets/prefabs/player/gaze.prefab]
20:40:20.122 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:counter with inputs [/engine/assets/prefabs/behaviorNodes/counter.prefab]
20:40:20.123 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:iconItem with inputs [/engine/assets/prefabs/iconItem.prefab]
20:40:20.125 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:itemBase with inputs [/engine/assets/prefabs/itemBase.prefab]
20:40:20.127 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:physicalDamage with inputs [/engine/assets/prefabs/damageTypes/physicalDamage.prefab]
20:40:20.129 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:itemPickup with inputs [/engine/assets/prefabs/itemPickup.prefab]
20:40:20.132 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:drowningDamage with inputs [/engine/assets/prefabs/damageTypes/drowningDamage.prefab]
20:40:20.132 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'damageSound'
20:40:20.133 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:client with inputs [/engine/assets/prefabs/player/client.prefab]
20:40:20.134 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:lookup with inputs [/engine/assets/prefabs/behaviorNodes/lookup.prefab]
20:40:20.136 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:firstPersonHeldItemMountPoint with inputs [/engine/assets/prefabs/player/firstPersonHeldItemMountPoint.prefab]
20:40:20.137 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:setAnimation with inputs [/engine/assets/prefabs/behaviorNodes/setAnimation.prefab]
20:40:20.139 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:inverter with inputs [/engine/assets/prefabs/behaviorNodes/inverter.prefab]
20:40:20.141 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:directDamage with inputs [/engine/assets/prefabs/damageTypes/directDamage.prefab]
20:40:20.142 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:globalBehavior with inputs [/engine/assets/prefabs/globalBehavior.prefab]
20:40:20.148 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:supportRemovedDamage with inputs [/engine/assets/prefabs/damageTypes/supportRemovedDamage.prefab]
20:40:20.150 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:blockItemBase with inputs [/engine/assets/prefabs/blocks/blockItemBase.prefab]
20:40:20.152 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:test with inputs [/engine/assets/prefabs/test.prefab]
20:40:20.174 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:null with inputs [/engine/assets/prefabs/null.prefab]
20:40:20.175 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:healingDamage with inputs [/engine/assets/prefabs/damageTypes/healingDamage.prefab]
20:40:20.177 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:playSound with inputs [/engine/assets/prefabs/behaviorNodes/playSound.prefab]
20:40:20.178 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:hand with inputs [/engine/assets/prefabs/player/hand.prefab]
20:40:20.201 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:selector with inputs [/engine/assets/prefabs/behaviorNodes/selector.prefab]
20:40:20.203 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:playMusic with inputs [/engine/assets/prefabs/behaviorNodes/playMusic.prefab]
20:40:20.205 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:parallel with inputs [/engine/assets/prefabs/behaviorNodes/parallel.prefab]
20:40:20.206 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:sequence with inputs [/engine/assets/prefabs/behaviorNodes/sequence.prefab]
20:40:20.208 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:repeat with inputs [/engine/assets/prefabs/behaviorNodes/repeat.prefab]
20:40:20.209 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:monitor with inputs [/engine/assets/prefabs/behaviorNodes/monitor.prefab]
20:40:20.211 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:timer with inputs [/engine/assets/prefabs/behaviorNodes/timer.prefab]
20:40:20.212 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab engine:explosiveDamage with inputs [/engine/assets/prefabs/damageTypes/explosiveDamage.prefab]
20:40:20.351 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "D3fvPXmzlw4M7vHOWDSsgkdfsR7S49xJ"
20:40:20.488 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[engine:unloaded]
20:40:20.488 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block engine:unloaded with id 1
20:40:20.798 [main] WARN  o.t.rendering.opengl.GLSLShader - Shader 'engine:chunk' failed to compile for features '[FEATURE_REFRACTIVE_PASS]'.

Vertex Shader Info: 
ERROR: 0:176: 'const void' : cannot declare arrays of this qualifier 
ERROR: 0:176: 'const' :  non-matching types (using implicit conversion) for const initializer  
ERROR: 0:202: 'x' :  field selection requires structure, vector, or matrix on left hand side 
ERROR: 0:203: 'y' :  field selection requires structure, vector, or matrix on left hand side 

Fragment Shader Info: 
No errors.

20:40:20.809 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.RuntimeException: Shader 'engine:chunk' failed to compile for features '[FEATURE_REFRACTIVE_PASS]'.

Vertex Shader Info: 
ERROR: 0:176: 'const void' : cannot declare arrays of this qualifier 
ERROR: 0:176: 'const' :  non-matching types (using implicit conversion) for const initializer  
ERROR: 0:202: 'x' :  field selection requires structure, vector, or matrix on left hand side 
ERROR: 0:203: 'y' :  field selection requires structure, vector, or matrix on left hand side 

Fragment Shader Info: 
No errors.

	at org.terasology.rendering.opengl.GLSLShader.registerAllShaderPermutations(GLSLShader.java:263)
	at org.terasology.rendering.opengl.GLSLShader.recompile(GLSLShader.java:124)
	at org.terasology.rendering.ShaderManagerLwjgl.addShaderProgram(ShaderManagerLwjgl.java:152)
	at org.terasology.rendering.ShaderManagerLwjgl.initShaders(ShaderManagerLwjgl.java:104)
	at org.terasology.rendering.world.WorldRendererImpl.initRenderingSupport(WorldRendererImpl.java:247)
	at org.terasology.rendering.world.WorldRendererImpl.<init>(WorldRendererImpl.java:232)
	at org.terasology.engine.subsystem.lwjgl.LwjglRenderingSubsystemFactory.createWorldRenderer(LwjglRenderingSubsystemFactory.java:33)
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:153)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:437)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
20:40:20.809 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...

**Comment by jellysnake** [comment]
Yeah, definitely a shader thing. Pinging @emanuele3d and @vampcat, perhaps you can shed some extra light.

**Comment by emanuele3d** [comment]
@tyronx: searching on the internet it appears some Intel integrated GPU have triggered errors similar to those you report. There is therefore a chance that Terasology is being run on the integrated GPU rather than your nVidia card. Please use your nVidia control software to force Terasology to use your nVidia card instead of the integrated GPU. That might solve the problem. 

Also updating the drivers of the integrated GPU might help, but of course I warmly recommend that you make sure to use the 630M for Terasology, as it's much more powerful. 

Please let us know if this helps you.

And thank you @jellysnake for tagging us!

**Comment by tyronx** [comment]
Ok, can try. Does that mean you do not plan on supporting integrated graphics cards?

**Comment by emanuele3d** [comment]
It's all about manpower. 

The rendering engine, over the past couple of years, has gone through some serious refactoring. The goal which is now in sight is an extensible, node-based architecture in which the nodes can be provided by modules (Terasology's term for plugins) rather than by the engine itself. 

This potentially means that we will be able to support multiple OpenGL releases (right now we support only 2.1-ish) and multiple hardware types in parallel: it will be a matter of writing nodes that are capable of adapting to the environment they find or it will be a matter of writing parallel sets of nodes that can be swapped at runtime, depending on the software and hardware environment.

So, in theory, once the refactoring is complete (end of 2018?), it will be much easier to support integrated GPUs. In practice it will still be a matter of finding somebody that, out of the default nodes, creates the alternative nodes catering for the Integrated GPUs and their limited OpenGL implementations. 

So, to answer your question: in the short term no. Integrated GPUs are too idiosyncratic to be supportable by a small crew. In the longer term though it might be possible, especially in the context of the Google Summer of Code and the Google Code-In initiatives.

**Comment by jellysnake** [comment]
Closing as solved and adding a link to #3170 as another occurrence of it
