### ISSUE TITLE
Default / Previous gameplay template remains selected even if dependencies are invalid

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3159]
### What you were trying to do

Play something like JoshariasSurvival which depends on a bunch of modules and is the default gameplay template selected if you run the game fresh via the Omega zip.

### What actually happened

While JS was selected and you could start the game that way it silently was in fact *not* activated as would be visible if you actually check the Modules section. Only JS itself was highlighted and one or more dependencies were listed as red.

### How to reproduce

* Have a series of modules available with one or more invalid dependencies. For instance increase the current version of a module to the next major version (2.0.0 -> 3.0.0) then anything that depends on it will show as red (cannot satisfy dependencies as a major new release is too new)
* Run the game while the previous gameplay template selection (or default on a first run) is affected by a 
broken dependency. It will have been set without considering the dependency state of the involved modules.
* You'll be allowed to start a game without realizing your selection is invalid. Making it really confusing to be dumped into a seemingly working Perlin world yet none of the JS stuff is active :-)

Instead if the selected gameplay template *cannot* resolve all its dependencies then disable the button that would start the game and perhaps color the selected gameplay template in red text. You could also highlight the Modules button's text in red. The user should be able to pick a different gameplay template and if that one is valid let the start game button activate.

As an extra we could do something similar if there is no valid world generator in that dropdown.

This could probably be turned into a GCI task if there is interest.

**Comment by morrilet** [comment]
Hey, I'm interested in giving this issue a shot. I've looked through the code a bit and it seems like I should be validating dependencies with DependencyResolver in the CreateGameMenu java file and updating the look of the menu UI from there, but I have a couple questions:

Is there better way to do this that I seem to be overlooking? Also, how do I go about changing the dropdown text color? Would I do this with the default skin, or can I affect the text element directly?
