### ISSUE TITLE
Terasology not using correct GPU

### ISSUE THREAD

**Issue by zeokav** [MovingBlocks/Terasology#3170]
### What you were trying to do
Setting the latest dev build up and play to see what's been up.

### What actually happened
I have a dedicated GPU (Nvidia Geforce) and an integrated Intel HD 530. But when I run the game, the logs return these following lines (Complete logs attached below): <br> 
...
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - Loading Terasology shader manager...
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - LWJGL: 2.9.3 / windows
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_VENDOR: Intel
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_RENDERER: Intel(R) HD Graphics 530
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - GL_VERSION: 4.4.0 - Build 21.20.16.4550
13:39:05.764 [main] INFO  o.t.rendering.ShaderManagerLwjgl - SHADING_LANGUAGE VERSION: 4.40 - Build 21.20.16.4550
...

On checking my Task Manager, the game was in fact running on my Integrated GPU (which btw isn't too powerful, hence, bad performance (<30fps))
Since I used a machine with an iGPU till last year, I don't really know if the problem is an old one. 
I even tried installing the stable release and forcing the executable to run using the Nvidia processor, but it didn't change anything at all. 

### How to reproduce
Just ran the game

### Log details and game version
Latest source on the develop branch
[2017-12-08_13-39-02.zip](https://github.com/MovingBlocks/Terasology/files/1541955/2017-12-08_13-39-02.zip)

### Computer details
RAM: 8GB
GPU: Nvidia GeForce GTX 960M
CPU: Intel Core i7-6700HQ
Java Version: 1.8.0_65

**Comment by zeokav** [comment]
UPDATE:
Read up a bit on how Nvidia has a middleware called Optimus that decides which applications use the GPU and which don't, to manage power. It started using the GPU when I manually selected the High Performance profile for Java from Nvidia's Control Panel. 
It all boils down to programatically making Java use the High Performance profile by default at the application startup phase.

**Comment by emanuele3d** [comment]
Hi @zeokav, and welcome back. We are aware of this problem and the solution you found (forcing the use of the discrete GPU through the manufacturer's software) is the only solution I am aware of: no programmatic solution so far, i.e. via LWJGL, which is the library we use to open the opengl context. 

If you do find a programmatic solution, please let us know.

**Comment by zeokav** [comment]
@emanuele3d heya! :D 
So I did a bit of hunting around and it ends up with the same response on pretty much all forums - 

> Export the global variable _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;. This is generally the best solution, however, depending on which language you're using, you may not be able to export global variables.

That's what's mentioned on the optimus [docs](http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf) as well. Setting environment variables for java applications at runtime is apparently not that straightforward. Need to do it before processes are launched, from what I can gather. Will try to find something though. 
Who would've ever expected C to make things simpler? 😕

**Comment by PS-Soundwave** [comment]
It's not the responsibility of an OpenGL application to choose the processor it runs on. There are programmatic workarounds that are both platform and vendor specific, but these are non-ideal for multi-card desktops, or systems with more capable iGPUs, and are primarily designed for optimizing workstations. It's an unfortunately clunky side effect of having a system with an iGPU that only makes use of a card as a graphics co-processor, but using the manufacturer's software is the correct approach to this issue.

**Comment by jellysnake** [comment]
Closing as solved
