### ISSUE TITLE
PrefabSerializer fails to find components...?

### ISSUE THREAD

**Issue by anuar2k** [MovingBlocks/Terasology#3179]
### What you were trying to do
I was trying to run a module fetched using gradlew `fetchModule` task.
### What actually happened
The modules I've downloaded using `fetchModule` task don't work properly (the log is full of ERRORs 'Prefab cointains unknown component "xxx"' compared to compiled modules downloaded using in-game browser, which work perfectly.
### How to reproduce
Just download for example Rails or Signalling module using gradlew `fetchModuleXXX`, run the game, turn on the module in the create world menu and play.

tl;dr: modules as folders with source **don't work** properly, but **JARs** do.

### Log details and game version
```
21:22:15.074 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab Signalling:SignalXorGate with inputs [/Signalling/assets/prefabs/SignalXorGate.prefab]
21:22:15.074 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'RotateableByScrewdriver'
21:22:15.074 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'SignalProducer'
21:22:15.074 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'SignalConsumer'
21:22:15.074 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'SignalConsumerStatus'
21:22:15.074 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'SignalGate'
```
### Computer details
Win7 64bit,
Java 8,
IntelliJ IDEA 2017.3.
Specs definitely enough for running this game (lol).

**Comment by anuar2k** [comment]
PS: Literally every prefab from modules downloaded using `fetchModule` task generates errors as mentioned above. Modules in *.jar format work, but it makes me unable to work with source in any way.

**Comment by anuar2k** [comment]
Update: I've solved the issue using "gradlew jar game" instead of "gradlew game" when running it.

**Comment by OvermindDL1** [comment]
Wouldn't this still break from running from the IDE though, like to debug?
