### ISSUE TITLE
API violation detected: inputSystem.getInputsForBindButton

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3184]
While rebuilding _all_ the modules for Alpha 9 final testing I found that the [Dialogs](https://github.com/Terasology/Dialogs) module failed to build, with `InputSystem.getInputsForBindButton` missing. Bit of research pointed to it having been removed in https://github.com/MovingBlocks/Terasology/commit/b91b832 which was part of #2948

That PR was biiiig and a nice overhaul of some input stuff so it isn't really a huge surprise that it managed to break something. And that's why it helps to build all the things - which I'm still antsy to get robots to do for me but oh well not yet :-)

Of possible interest to @oniatus @msteiger @rzats @vampcat @ThompsonTyler @eviltak ... pretty much anybody with some related exposure who can update the module real quick so it builds again :D

**Comment by anuar2k** [comment]
https://github.com/MovingBlocks/Terasology/pull/3219 fixed with this pr.

**Comment by oniatus** [comment]
Can't test it right now but `BindsConfig` has a method `List<Input> getBinds(SimpleUri uri)` which looks promising :) Maybe delegating to this method is simpler than implementing new logic.

**Comment by anuar2k** [comment]
@oniatus Well, usage of both BindsConfig and BindsSubsystem cause ModuleClassLoader denying access to these classes so I gotta find a way around the moduleloader to at least check if both methods return the same values.

**Comment by Cervator** [comment]
Closing as fixed by #3247 whether that's the cleanest fix or not. Stuff should build at least :-)

Thanks for the input and code fix ideas, can still apply a more proper fix in the future.
