### ISSUE TITLE
No world gen.

### ISSUE THREAD

**Issue by devvorb** [MovingBlocks/Terasology#3185]
### What you were trying to do
Run via ./gradlew game  and then create a world.
### What actually happened
But I wasn't able to select a world generation type
### How to reproduce

* Step 1: I ran from source with a high dpi and a gamer's graphics card.
* Step 2 The tried creating a world but needed to specify the world type but I had a major probleme  that I mentioned above.
This image shows that there is no pre selected world gen type
![terasology alpha_002](https://user-images.githubusercontent.com/34374483/34080901-8cad2a0c-e345-11e7-8e46-932982f2575e.png)
and this one shows the problem.
![terasology alpha_003](https://user-images.githubusercontent.com/34374483/34080903-8f2e058a-e345-11e7-959c-f3d10350b471.png)

### Computer details
a linux ubuntu,high dpi

**Comment by vorburger** [comment]
@devvorb I've attempted to reproduce this issue on another HiDPI screen, but it works for me.. so perhaps not related to that; there must be something else wrong that can cause the Choose World Generator drop-down to be empty...

**Comment by devvorb** [comment]
Excuse-me sir but where might I find CreateGameScreen?

**Comment by devvorb** [comment]
Well now it works without me having to change anything.
