### ISSUE TITLE
Enabling SSAO causing graphical bug.

### ISSUE THREAD

**Issue by l0ftyWhizZ** [MovingBlocks/Terasology#3211]
### What you were trying to do
- Enabled SSAO from the Video settings.

### How to reproduce
- Generate a game.
- Goto video settings
- Enable `SSAO`.

### Computer details
AMD Ryzen 1700
GeForce GTX 1060

**Comment by jellysnake** [comment]
Can you give us more information? What is the graphical bug that SSAO is causing?

**Comment by l0ftyWhizZ** [comment]
After an update to the branch, I am no longer able to reproduce the issue. Hence, closing it.
