### ISSUE TITLE
Multiplayer problems- Name change problems.

### ISSUE THREAD

**Issue by Graviton48** [MovingBlocks/Terasology#3226]
### What you were trying to do
This is about the problems I faced during the name change test.

There were some weird bugs:
### What actually happened
-> If I changed name in-game, the server would not pick up the new name.

-> I made the second character leave and rejoin the game with a  different name. But, when I pressed 
     'Tab' the server took the new name of the character but the character did not leave the game and did 
     not spawn again.This also points to a rejoining and respawning problem.The name on top of the 
     second character was the same old one!

->There was another problem. I changed the host's name in-game and no change was shown in the 
    game.

_This is the name change problem_
![arpit 4](https://user-images.githubusercontent.com/34807468/34947840-5b41b52a-fa31-11e7-9486-1ddc51ff09ec.png)

**Comment by jellysnake** [comment]
Closing this as it's already been noted in #3225. Thanks for the extra confirmation however
