### ISSUE TITLE
Bug - BlockPicker, Crouching and Floating Items

### ISSUE THREAD

**Issue by Safebox36** [MovingBlocks/Terasology#3235]
### What you were trying to do
Take all items from BlockPicker module.

I crouched into a window of a building and jumped.

I quit to main menu and reloaded game so player height would update to the change I made in the settings.

### What actually happened
Items removed were permanently removed even after attempting to place them back in the list.

Nothing happened initially but when I walked back into the room I clipped through the floor and remained crouched. Holding crouch clipped me through the ground further.

The last held item in my inventory created a larger one floating in midair were I loaded the game from. This occurred every time I quit and loaded but the previous items remained from the previous times.
![Screenshots](https://i.gyazo.com/62f633da5b52f69b55ec749070537d09.png)

### Log details and game version
Available from OneDrive link: https://1drv.ms/u/s!AvmO3M0gY2TKhVN8lEl_qnFttKtz

**Comment by jellysnake** [comment]
So it appears you are using the 1.5.0 version not the 1.5.1 version.
The crouching bug and the held item appearing bug have both been fixed in the latest version.

The block picker bug however I'm not sure has been documented before. Do you mind testing it on the latest release and opening an issue in the BlockPicker repository if it is :)

**Comment by Safebox36** [comment]
> So it appears you are using the 1.5.0 version not the 1.5.1 version.
> The crouching bug and the held item appearing bug have both been fixed in the latest version.
> 
> The block picker bug however I'm not sure has been documented before. Do you mind testing it on the latest release and opening an issue in the BlockPicker repository if it is :)
Sure, I'll update and try it again. I'll submit a new issue report if it still occurs and see if I can get more details on it.
