### ISSUE TITLE
Create a demo PR how to extend ApiScraper for API Testing

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/Terasology#3239]
Based on https://github.com/MovingBlocks/Terasology/issues/2317#issuecomment-359257325:
1. Extend the ApiScraper to output a list of all packages, classes and (this is new) all methods with their signatures
2. Create one class with a main method to manually write this output to something like an API-File
3. Create an automated unit test which calls the api-scraper and then compares to output against the stored api-file.

Goal is to have an automated validation of all api classes and their signatures in the engine where the file can be re-generated manually if we release a new version. This does not have to be feature-complete in the first version but we need an example how it would look like. In the best case we can use the PR directly for API testing.

**Comment by iaronaraujo** [comment]
I intend to work on this, but I noticed that @GabrielXia 's PR wasn't accepted yet. Should I fork his repository, wait for the merge or copy what he did to my own fork?

**Comment by oniatus** [comment]
This should be independent from the other PR so feel free to start over from the default codebase.

**Comment by Cervator** [comment]
Closing as completed by #3253 :-)

Submitted three follow-up issues: #3320, #3321, #3322
