### ISSUE TITLE
tfuyyui

### ISSUE THREAD

**Issue by elmatador86** [MovingBlocks/Terasology#3243]
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by elmatador86** [comment]
rytuukk

**Comment by elmatador86** [comment]
ok  you speak spanish

**Comment by skaldarnar** [comment]
Please provide more information. You can write in Spanish or use Google Translate.

Por favor brinde más información. Puedes escribir en español

**Comment by jellysnake** [comment]
Closing this as no response and appears to be spam
