### ISSUE TITLE
Merits and Thoughts on integrating Kotlin and Scala at the engine level.

### ISSUE THREAD

**Issue by syntaxi** [MovingBlocks/Terasology#3248]
Majority of prior discussion happened over on #2984 about returning Optional's vs Nulls and runtime cost.

Essentially discussion centred around zero cost aspects and any desire for it to be merge into the engine. Cervator raised a point about the potentials of it not being overly blocked as they are both JVM languages. Indications are showing that it could be as simple as updating the base build system to handle it.

More relevant discussion may have happened in the relevant modules for [Kotlin](https://github.com/Terasology/KotlinLib) and [Scala](https://github.com/Terasology/ScalaLib)

**Comment by asiekierka** [comment]
How about creating Modules for handling different JVM languages, providing useful adapters for them and the libraries they need at runtime?

**Comment by skaldarnar** [comment]
#### References

- **Adding `scala-lib` to whitelist** #3155 
- **ScalaLib module**: https://github.com/Terasology/ScalaLib
- **KotlinLib module**: https://github.com/Terasology/KotlinLib

**Comment by jdrueckert** [comment]
This is currently not actionable and this community has historically not shown much interest in adopting other programming languages than Java.
We are partially using Kotlin for our build tooling and a few motivated people do experiment with other languages, so we hope this comes up naturally again as soon as the community wants and accepts it.
