### ISSUE TITLE
Character can jump once under water

### ISSUE THREAD

**Issue by Maximetinu** [MovingBlocks/Terasology#3267]
### What you were trying to do
While diving, I was trying to surface by pressing spacebar.

### What actually happened
The first time I press the spacebar, a normal jump happens as if I was grounded.

### How to reproduce
* Step 1 - Get into the water
* Step 2 - Press spacebar once to see jump happens

### Log details and game version
Current latest stable: 74 alpha 2018-02-05T04:45:49Z

### Computer details
OS: Win 10 x64 CPU: i5-4690 RAM: 8GB Graphic Card: GeForce GTX 970 but irrelevant as it happens in other computers too

### Video
[Vimeo video showing the bug](https://vimeo.com/257262232)

**Comment by Maximetinu** [comment]
I've already had a look on this, it seems easy to solve.

[This](https://github.com/Maximetinu/Terasology/commit/ea6815ef8502df14da8ef17288d079b2de0ecda5) is the bugfix commit on my fork. As soon as I have your clearance I'll make the PR.

**Comment by mjuvekar7** [comment]
You should go ahead and make a PR. Much easier for us to test if it's a PR. No need to ask for clearance (it's open source!) :)
