### ISSUE TITLE
Remove newline character from the output of the Console.addMessage method.

### ISSUE THREAD

**Issue by emanuele3d** [MovingBlocks/Terasology#3268]
Occasionally, a command executed in the console might take some time, it might not be executed instantaneously. In this situation, it's useful for the console to output a small string before and after the execution of the bulk of the command, i.e.:

`Recompiling shaders... (pause) done!`

The (pause) is a real pause where the software is doing something and the word "done!" hasn't appeared yet. 

This is easy to achieve by framing the bulk of a command with two `Console.addMessage` lines, i.e.:

```
Console.addMessage("Recompiling shaders...");
ShadersManager.recompileShaders();
Console.addMessage("done!");
```

However, the addMessage method also adds a newline character at the end of the output, resulting in:

```
RecompilingShaders...
done!
```

Ideally, any newline character is explicitly added by the caller of the method rather than by default.

**Comment by vampcat** [comment]
Closing, as fixed  by #3268.
