### ISSUE TITLE
crash on screen lock?

### ISSUE THREAD

**Issue by ClemClone** [MovingBlocks/Terasology#3288]
### What you were trying to do
Went AFK with T parked at main menu.  Screen locks after ten minutes.

### What actually happened
Came back, T is crashed.

### How to reproduce

* Step 1
Step away.
* Step 2
Mix cocktail; enjoy with spouse.
* Step 3
Come back.

### Log details and game version
https://pastebin.com/E5g8pd82

### Computer details
XPS 13; Ubuntu 17.10

**Comment by oekonomi** [comment]
The link to the game log leads to a page saying that the log has been removed. If possible, could you please post the log or a working link to the log?

**Comment by ClemClone** [comment]
No use; the file is long gone.  Pastebin must've deleted the upload; I no longer have it.

**Comment by emanuele3d** [comment]
I'd like to suggest that step 2 can be hard to reproduce if A) you are under 21/18/16 in some countries (limited access to alcohol) and B) are unmarried (limited access to spouses). 

That been said, a few in the crew should be in a position to reproduce the problem no matter the stringent criteria of step 2....

**Comment by oekonomi** [comment]
I attempted to replicate the issue on Windows 10 (albeit with a different step 2) and the game didn't crash or freeze. This may be a Ubuntu specific issue.

**Comment by skaldarnar** [comment]
Closing as not reproducible (as per https://github.com/MovingBlocks/Terasology/issues/3288#issuecomment-382590193).
