### ISSUE TITLE
Player not dead after re-load

### ISSUE THREAD

**Issue by 4Denthusiast** [MovingBlocks/Terasology#3300]
When the player dies and doesn't respawn before re-loading the game, they start alive but on 0 health.

### How to reproduce

* Load a world with Core enabled.
* Die.
* Exit to main menu without re-spawning.
* Re-load game.

**Comment by Cervator** [comment]
This is probably fixed by #3203 ? Which I think is ready for merge, just haven't had a chance to catch up with PRs for a while :/

**Comment by mkienenb** [comment]
@l0ftyWhizZ Did you get around to recreating your PR to fix this?

**Comment by cvennel** [comment]
About to submit PR for this, in order to reproduce the bug I have to choose Exit Terasology instead of exiting to main menu.
