### ISSUE TITLE
Permanent day-time command

### ISSUE THREAD

**Issue by 4Denthusiast** [MovingBlocks/Terasology#3307]
When testing things, it's annoying to find that it's night-time and I can't see anything. setWorldTime fixes this, but only temporarily. I propose a command to toggle permanent day-time (possibly permanent noon) for a more convenient solution.

**Comment by dorasun** [comment]
Hi, I'm in a class on open source, and my group is trying to contribute to this project. We would like to try to tackle this issue!

**Comment by Cervator** [comment]
Hi @dorasun and welcome! Sorry about the delay in responding to you :-)

You're absolutely welcome, and rarely in open source do you need to ask first, although it is good to give notice if you start something you expect may take a little while, just so anybody else looking can tell there's likely some work pending.

@4Denthusiast agreed! Although I'm not sure what the better approach would be: freeze time or make daylight ignore the changing time of day. Probably the latter. 

Fun fact: in multiplayer when you change time with the arrow keys (with F3 debug mode on) it only changes your local time, the server is unaffected. Can't remember if `setWorldTime` affects everybody.
