### ISSUE TITLE
Crash if loading world

### ISSUE THREAD

**Issue by niansa** [MovingBlocks/Terasology#3338]
### What you were trying to do

I tried to load ANY world

### What actually happened

The Client closed, the server was still running.

### How to reproduce

* start the game
* load any world
* when the healthboxes do appear it crashes

### Log details and game version

https://pastebin.com/Ebnjwitq

### Computer details

Ubuntu 17.10, Processos: Intel® Core™ i3-3220 CPU @ 3.30GHz × 4 Graphics:  GeForce GTX 1050 Ti/PCIe/SSE2 Desktop: GNOME 3.26.2

**Comment by niansa** [comment]
It crashes at all servers. I'm using Version "v1.6.0 - Alpha 9"

**Comment by jellysnake** [comment]
Apologies on the delay in responding to this.


Hmm. This is odd, there's nothing I can see in the log that indicates the cause of the crash. Is this log from the server or from the client?
Additionally can you try and load a new world with no modules except Core enabled.

**Comment by Cervator** [comment]
One potential clue: Java 9. We haven't done a lot of testing on it. Alternatively the ~princess could be in another castle~ error could be in another log file

**Comment by niansa** [comment]
It's the log from the crash reporter...

**Comment by niansa** [comment]
Closed because I fixed it a long time ago by redownloading Terasology.
