### ISSUE TITLE
Add label + filter reset button for new module categories

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3354]
With #3347 merged we now have a filter listing for module categories. But I realized we don't have a way to reset the filters to default and the area could use a nice label. Should be fairly easy to do. Quick mockup:

![2018-05-07 18_23_37-terasology _ alpha](https://user-images.githubusercontent.com/1063833/39728295-4ead2736-5224-11e8-8d5f-1a0e46787adf.png)

So in other words move the checkboxes down a bit, add the indicated label above them, and add a new button that'll reset the filters to default below the checkboxes. Piece of cake! :-)

See https://github.com/Terasology/TutorialNui/wiki for a general intro to our UI system

**Comment by jellysnake** [comment]
Closing as fixed in #3354
