### ISSUE TITLE
AdvancedFilter options on module page selected but not filtered on startup

### ISSUE THREAD

**Issue by devibri** [MovingBlocks/Terasology#3356]
Related to the new advanced filter system (https://github.com/MovingBlocks/Terasology/pull/3347) for modules. When starting up the game and going to the module selection page, any advanced filter checkboxes that were selected in your last session are still selected, but the list of modules does not reflect the filters that are selected. Advanced filters should either start off as all unchecked on game load, or the list of modules should reflect those currently selected filters.

### How to reproduce

* Load up game, select an advanced filter in the module selection screen
* Close the game, restart, go to the modules screen again
* Previously selected advanced filters will still be selected
* The list of modules will not be the same as ought to be shown with selected filters

**Comment by TheFlash98** [comment]
PR #3105 added a new `onScreenOpened` which runs every time a screen is opened. That might just fix this :-)

**Comment by mkienenb** [comment]
Pretty sure this is fixed with the two trivial changes in PR #3359 (synchronize modules with advanced filters on window open. )

Maybe someone could review it so I can merge it... :)
