### ISSUE TITLE
Lava land crashed on Core Gameplay

### ISSUE THREAD

**Issue by Om-Pandey** [MovingBlocks/Terasology#3360]
### What you were trying to do
Trying to start the same with World Generation choosing Lava Land with Core Gameplay
### What actually happened
I was trying to load the Core Gameplay with Lava Land and it crashed while installing files  
### How to reproduce

* Run The Game
* Create a new Game in SinglePlayer
* Load a module called Additional Worlds from the Advanced Modules 
* Activate Module and select Lava Land under World Generation , run along with Core GamePlay

### Log details and game version

[lava error.txt](https://github.com/MovingBlocks/Terasology/files/1997297/lava.error.txt)

**Comment by jellysnake** [comment]
This is an issue specific to the Lava Land generator in the Additional Worlds module. This isn't very surprising as that module is primarily a parking group for the world generators added from GCI.
I think we should possibly consider adding a disclaimer to the module that not all generators in it will work.

**Comment by AahzBrut** [comment]
I repeated all the steps but could not reproduce the error.

**Comment by skaldarnar** [comment]
Not reproducible as per https://github.com/MovingBlocks/Terasology/issues/3360#issuecomment-507790354
