### ISSUE TITLE
Allow modules limited API access to files

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3366]
## Overview

_edit: @asiekierka is working on this as of August 2018_

This is a more narrow approach than something like #1703, specifically focused on giving modules limited access to files, still without allowing modules access to  `java.io.File` etc. Feedback appreciated on the concept, consider this an initial proposal. This would be in high demand for some projects like @asiekierka's GSOC item, and maybe a good way to satisfy _some_ of the needs of a more full-fledged permission system for opening up just about anything.

There are two approaches involved:

1. Create a subdir in the game data dir that allows modules to read, write, and delete to actual files, via `@API` listed engine methods doing the actual file manipulation
1. Allow modules `@API` access to an engine method that opens a file chooser for the user to manually select a given file for reading (and/or writing?)

### "Safe" file space

A minimal implementation here would define a new subdir in the game data dir (see `PathManager`) such as `<user home>/Terasology/sandbox` and make engine methods that wrap common file operations so they're only allowed to happen within that directory. Example:

Module class `X` calls engine method `public byte[] readSandboxFile(String filename)` which reads the `filename` at the root of the `sandbox` dir then provides the contents in a byte array to the calling module to do with as it pleases.

Now I doubt providing a byte array is necessarily the best way to provide the contents, but then I'm not paid to be on top of the best practices surrounding I/O these days, in fact I'm not paid at all! :-)

I don't know if it makes sense to provide a stream of some sort instead, a bunch of related things were put on the whitelist in the past by https://github.com/MovingBlocks/Terasology/pull/2494/files - there are also other fun things like virtual file systems that might come into play.

A more improved implementation might include some ideas like:

* Use `sandbox/global` for the space that any module has access to. Then allow exclusive access by modules to paths like `sandbox/modules/<module name>` allowing modules to have private spaces other modules cannot read. I'm not sure if there are glaring ways to get around this since modules can access each other just fine at present.
* Allow modules themselves to expose access to their private store for other modules. Maybe some simple little whitelist file like `sandbox/modules/MyModule/whitelist.txt` with a list of approved module names? Not sure this even has a good use case.

### File chooser request

Much like the above, but rather than exclusively target a safe sandboxed file space request a user manually select any file on the file system via traditional file chooser dialog. Again solely provide the data for a module to do something with, relying on the engine itself to do the I/O proper.

Maybe make it so the engine pops a disclaimer before showing the file chooser dialog, warning the user that modules can do anything they want with the related data.

Am unsure if this should be read-only, or if there also should be an option to write (or even overwrite?) a target file. That would be a very nice way to save a StructureTemplate exported prefab directly to a target file of the user's choice.

Key point here is that only the engine is able to engage the user with the file chooser dialog, requiring manual interaction with the user. No direct file access allowed at all.

## Concerns

This seems like a pretty limited risk, but I am sure there still are some. A module could excessively write to files in the file sandbox, causing I/O slowdowns or eating up a bunch of space. Maybe there should be a limit to how much I/O activity a module can request and/or a limit set on how much space a module can use. Probably easy enough to handle in a module's private dir, maybe the global space can have a higher but still finite cap.

Also: Unit tests please! Maybe a good thing to add to the [Malicious](https://github.com/Terasology/Malicious) module.

Pinging @engiValk for some nefarious speculation.

**Comment by Cervator** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Safe module file spaces](https://trello.com/c/s5tnUCZs/51-safe-module-file-spaces)

**Comment by llvieira** [comment]
Working on it... :-)

**Comment by asiekierka** [comment]
@llvieira Could you please get in touch about its design?

**Comment by llvieira** [comment]
@asiekierka yes, I can. I'm going to open a pull request so maybe it's better to discuss. I'm trying to keep it as simple as possible just to see if it would work, but I'm having some problems and I think you could help with. Let's transfer the discussion to my pull request so that you can analyse my code. :smiley:
