### ISSUE TITLE
Highlight possibility active buttons of UITabBox widget

### ISSUE THREAD

**Issue by ar0ne** [MovingBlocks/Terasology#3384]
### What you were trying to do
I've used UITabBox widget on my new screen GameDetailsScreen (#3382). And realized that we need to redo this widget, because we can't highlight active buttons. 

Actually, I've spent few days on that, and, unfortunately, looks like I don't have nice solution yet...
I'd like just to track this issue further, add to my GSoC board and fix it when I will have good solution/idea.

### How to reproduce
1. Fetch branch from PR(#3382) if it's not in develop yet.
2. Open Details for saved game.
3. Play with tabs and see that they're not highlighted.

**Comment by Cervator** [comment]
Closing as completed by #3429 - thanks @ar0ne ! :-)
