### ISSUE TITLE
Add memory for confirmed "safe" URLs to let the game open in a browser

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3414]
With #3405 we have a UI widget `UIButtonWebBrowser` that when clicked can open a URL in a browser. It requires confirmation from the user before doing so to avoid malicious modules sending a user off to some dubious site unknowingly.

At present that confirmation will be required every time. The purpose of this issue is to add a list of remembered safe sites so the user can OK a given URL and not be prompted again. Probably that should be added by including a checkbox (unchecked by default) on the confirmation dialog. If it is checked then on confirming the request add that URL to some new section of `config.cfg`

Any confirmation dialog then should go check that section first before popping up.

For similar functionality see `EnterUsernamePopup` which is used by `JoinGameScreen` when a user previously hasn't configured a player name. This should work similarly, although the config value will be a list rather than a single String.

On deleting `config.cfg` the list will be wiped and the user should be re-prompted again.

**Comment by awells111** [comment]
Would [this](https://github.com/awells111/Terasology/commit/71236ecff0cee454d098f695d2bede9d8da09e76) be the correct way to go about it? I created a WebBrowserConfig class and added it to RootConfig and Config. The config will be called in the way that [JoinGameSceen calls EnterUsernamePopup](https://github.com/awells111/Terasology/blob/0a9e8313358f1f403a09309d856d6a895213d527/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/JoinGameScreen.java#L163-L165):

```
        if (!config.getWebBrowserConfig().getSafeSites().contains("WEBSITE.com")) {
            //load UIButtonWebBrowser
        } else {
            //load website
        }
```

The below still need to be completed:
- safeSites in WebBrowserConfig still needs to be initialized.
- A list of safe sites needs to be saved in config.cfg.
- TwoButtonPopup needs to include a checkbox (unchecked by default).

**Comment by Cervator** [comment]
Oh hey @awells111 ! Cool to hear from you, sorry for not spotting your comment for a few days :-)

That looks about right, yep. Maybe @vampcat or @eviltak could give a bit more confirmation on the configuration part of things

Feel free to open a PR any time, even if you're not done yet, that's a bit more visible than issue comments and a great way to get early feedback :-)

**Comment by starlord1311** [comment]
@Cervator can i take up this issue?

**Comment by awells111** [comment]
Sorry I didn't finish this. I had two interviews come up that I had to prioritize. I don't mind if you finish it or else I can finish it this week.

**Comment by Cervator** [comment]
Hey both. Sounds like you're clear to try it out @starlord1311. If either of you makes progress just add a comment here so it is visible to others :-)

**Comment by starlord1311** [comment]
@Cervator can you tell me what i am supposed to do?

**Comment by Cervator** [comment]
@starlord1311 same story here as I suggested with https://github.com/MovingBlocks/Terasology/issues/3444#issuecomment-406898853 :-)

In this case @awells111 already provided some additional implementation tips

**Comment by llvieira** [comment]
Guys, as this issue is still open, I'm going to to take it up if you don't mind. :smiley:
