### ISSUE TITLE
Family Registry Handling

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#3418]
### What you were trying to do

Something I noticed looking through the source is that block family relations are handled in two different ways. BlockFamilyRegistry contains a mapping from string to class implementation of a block family and BlockManagerImpl.java. The one problem is that the module type is not carried when it's parsed from the json. The BlockFamilyDefinitionFormat needs to be reconciled with the BlockFamilyRegistry. The implementation is split across these three points. 

### What actually happened
Under additional rails, when I select one of the blocks that uses family:"module:family". the family that is given back is the freeform family .

**Comment by Cervator** [comment]
Closing as completed by #3421
