### ISSUE TITLE
Command line toggle for the module sandbox

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3444]
At present to disable the module sandbox for testing you need to edit `ModuleManagerImpl.java` like so: https://gist.github.com/Cervator/85da99b3400d880f6eae4ac3ca992676 (diff it against a normal version locally to see the 4 changed lines)

To ease testing it would nice to have a command line flag (`-permissiveSecurity` ?) and potentially an IntelliJ run config that enables it. See `Terasology.java` for the current usage of command line flags and `ide.gradle` for the run configs (clone an existing run config block then add the flag)

`ModuleManagerImpl.java` would need to be edited to support either case and default to security being on like normal. If the flag is found then instead switch to permissive mode like in the linked Gist.

To complete this we should also add details to https://github.com/MovingBlocks/Terasology/wiki/Modding-API as well as the usage text in `Terasology.java`

_Edit:_ As an example look at how `NO_SAVE_GAMES` in `Terasology.java` is used. It writes a config to `System` which can then be later read in the location needing the value - `InitialiseWorld`:

`boolean writeSaveGamesEnabled = context.get(Config.class).getSystem().isWriteSaveGamesEnabled();`

**Comment by starlord1311** [comment]
can i take up this issue? @Cervator

**Comment by Cervator** [comment]
Sure @starlord1311 - you don't need to ask, although posting a comment that you're going to try it out can be helpful if others are interested as well. Just coordinate via the issue :-)

And welcome!

**Comment by starlord1311** [comment]
@Cervator can you tell me what i am supposed to do?

**Comment by Cervator** [comment]
@starlord1311 so in these kinds of issues marked with Good First Issue we should already have put a decent amount of the details in the initial description, but it is up to you to dig deeper and figure out exactly what to implement :-)

In this case I pointed to a couple key places in the code that already do similar things, and where to put the new stuff. So you'll want to look at those places and try to understand what's going on.

Look at an existing command line flag in `Terasology.java` and look around for how it is used. In IntelliJ you can CTRL+left click classes or right click things then select "Find Usages" to jump between a single feature spread across different files.

Copy-paste the Gist's contents into your local copy of `ModuleManagerImpl.java` to see the 4 lines that change, and understand why. Then consider what conditional logic you can add to make the effective change vary without having to change the code. You'll want to hook a new `if` up to the new command line flag.

Finally look at the linked wiki page and see what you need to describe for a user new to the system who is curious how to switch security to permissive mode - namely that there's a command line flag for it now.

For live coding assistance join our chat (IRC/Discord, later you can ask for a Slack invite if you like) although keep in mind there isn't always somebody reading. Discord is better since then you can come back later and check the log if needed.

**Comment by Cervator** [comment]
I've added in a quick hack version of this via https://github.com/MovingBlocks/Terasology/commit/37c4dbf242aeeb5df6afafb9805ad0427ce6b555 for testing. This issue now includes undoing that with a clean solution and as such now counts as a blocker for v2.1.0
