### ISSUE TITLE
Add Screen to select Recording Name

### ISSUE THREAD

**Issue by iaronaraujo** [MovingBlocks/Terasology#3465]
## The Problem

Right now when the user records a game, the recording has the same name as the world that was recorded. Because of this, recording the same world twice overrides the first recording, unless the user manually changes the name of the recording or create a backup for it.

## Suggestion

To solve this problem, there should be a new screen that asks for the name of the recording when the player chooses to make one. The recording in the "recordings" folder will then have the name the user chose.

**Comment by hullmo** [comment]
A potential quick fix for this would be to add a timestamp to the filename, which I feel is a pretty common practice for automatically generated files like this. I think the idea of allowing users to choose the name makes sense, but having a unique default could also be beneficial.

The downside to either of these fixes is that the current state works as a bit of an automatic clean-up of files. Another potential fix would be to confirm overwriting the previously existing file. If the user does not want to overwrite they would then be prompted to supply a new name either for the new or old file.

**Comment by iaronaraujo** [comment]
That makes sense. It is a nice idea to have the game world as the default name, and then if the folder already exists, a new screen appears asking if the player wants to proceed with the overwriting.
