### ISSUE TITLE
Move Record and Replay UI elements (and more?) into a sub-menu

### ISSUE THREAD

**Issue by iaronaraujo** [MovingBlocks/Terasology#3468]
### Suggestion

Since Record and Replay is not relevant most part of the time, their buttons should be moved from the main menu to somewhere else.

**Comment by Cervator** [comment]
Updated title. My recommended approach would be to make a new main menu button named "Extras" then move the following buttons in there: "Record", "Replay", "Credits", "Metrics Menu", "Issue Reporter"

Maybe the identity storage should be cleared out to but ... we really need a better way to make some thing visible on the main menu, like little notification icons or something off to the side that might have a tool tip or expand into something. Anyway that could be a next step. 

Simply moving those items should be fairly easy and a good first issue. See https://github.com/Terasology/TutorialNui to get started :-)
