### ISSUE TITLE
Dropped item/Block entities causing large framerate drop

### ISSUE THREAD

**Issue by ThePreviousOne** [MovingBlocks/Terasology#3471]
When Dropping entities in a pile, entities not touching ground continue to move indefinitely

in my case this caused a framerate drop of 0.1 fps per block

### How to reproduce

* Step 1
Have a reasonably large stack of blocks (didn't test with items)
* Step 2
drop them individually into a pile

### Log details and game version
v2.0.0 - Alpha 10

### Computer details
uname -a Linux localhost 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
AMD RX 580

**Comment by Cervator** [comment]
Thanks for the report :-)

There is a PR #3432 with an experimental physics replacement that would majorly affect the area, although I'm sure we'll still need further optimizations. There are a few other similar issue like #3194 and #1680 for the railgun specifically.

**Comment by ThePreviousOne** [comment]
Forgot to mention this was using just the base game, not that is important.

**Comment by pollend** [comment]
this was before the bullet change.
