### ISSUE TITLE
Crash caused by UI in the select modules screen

### ISSUE THREAD

**Issue by aditmehta9** [MovingBlocks/Terasology#3482]
### What you were trying to do
When I clicked on the single player  for playing it asked for selecting world but I couldn't select and when i clicked on modules following happened:

### What actually happened

It crashed and showed me this:
https://pastebin.com/gGyQZiHe

### How to reproduce

* click on single player
* click on modules
* in windows

### Log details and game version
It crashed and showed me this:
https://pastebin.com/gGyQZiHe
### Computer details
RAM 8 GB
GRAPHIC CARD 2GB
Windows 64 bit

**Comment by Cervator** [comment]
Hi there. What version of the game did you try? What did you download? The very latest developer build is pretty unstable.

**Comment by aditmehta9** [comment]
Yes, I just downloaded the very latest master branch.
What should I do know?

**Comment by jellysnake** [comment]
Looking through the log this is a crash from the UI, namely the module filter code.

For now I'd recommend downloading one of the official releases. They can be found on the Releases page of this github repository

**Comment by Cervator** [comment]
Closing as obsolete / possibly fixed. The affected part of the UI has been majorly changed over the last few months. @aditmehta9 if you end up trying the latest develop build sometime and can still reproduce please reopen, but hopefully it'll work! :-)

**Comment by aditmehta9** [comment]
Ok, sir
