### ISSUE TITLE
Region3i.EMPTY bug

### ISSUE THREAD

**Issue by LinusVanElswijk** [MovingBlocks/Terasology#3486]
There is a serious flaw in the way Region3i deals with empty regions.

For some reason (optimization?) Region3i has a public and static instance Region3i.EMPTY.
There is nothing that prevents users from accidentally changing the empty region.
What makes it even worse is that the factory functions sometimes just return Region3i.EMPTY, to save the costs of a copy constructor.

This code snippet can destroy the invariant of the empty region being empty:
```
Vector3i a = foo();
Vector3i b = bar();
Region3i region = Region3i.createFromMinMax(a, b);
region.expand(otherRegion); // Oops, Region3i.EMPTY is now equal to otherRegion
```
### How to confirm
This test fails if added to the Region3i tests.
```
@Test
public void testFactoryShouldNotReturnTheEmptySingleton() {
    Region3i constructed = Region3i.createFromMinMax(Vector3i.zero(), Vector3i.one().negate());
    assertFalse(constructed == Region3i.EMPTY); // This fails
}
```

### Suggested Solution
Remove Region3i.EMPTY, and no longer threat is as special instance.
Add Region3i.empty(), creating a new empty region each time it is called.

**Comment by LinusVanElswijk** [comment]
I would like this issue to be assign to myself. :)

**Comment by Cervator** [comment]
A useful bug report *and* claiming it too? My favorite kind! :D
