### ISSUE TITLE
Crash report for CoreSampleGameplay after multiple play sessions in one game launch

### ISSUE THREAD

**Issue by brylie** [MovingBlocks/Terasology#3500]
### What you were trying to do
Try out the CoreSampleGameplay

### What actually happened
Got a NullPointerException

### How to reproduce

1. Start Terasology
2. Start new CoreSampleGameplay single player game

### Log details and game version
https://pastebin.com/vSbG7efe

Game version: Omega

### Computer details
Kubuntu 18.04

**Comment by Cervator** [comment]
Thanks again for submitting :-)

This one is a little tricky as it seems like the log file has several rounds of action in it, meaning you might have hit an issue that wouldn't get hit if doing it as the sole action when starting the game fresh.

Specifically `00:30:51.772 [New I/O worker #3] INFO  o.t.n.i.ClientConnectionHandler - Downloading core:2.0.0 (1.92 MB,1 modules remain)` sticks out. The shipped game was a develop Omega zip with v2.0.1-SNAPSHOT, meaning the game is trying to downgrade an embedded module. Maybe we should add either a warning or block downgrading modules, at least those shipped with the game and thus tied to the engine which isn't version tweakable at runtime.

There are also a couple `00:36:02.076 [Timer-1] ERROR o.t.n.i.ClientConnectionHandler - Server timeout threshold of 10000 ms exceeded.` although those probably matter less. But when you've tried joining a server whichever modules the server runs is what the game will try to load up.

I figure in the end you tried starting a CoreSampleGameplay session, but it crashed on start-up? There isn't a good error at the very end of the log file, which is a pity. I can start the game fresh and run CoreSampleGameplay just fine, so the original issue is likely not a problem, but a more tricky multi-session game setup workflow can lead to corrupt game state _is_ - and I'm pretty sure I've hit something similar myself.

I'm going to rename this a bit to try to cover hitting an odd error like this after entering and leaving multiple game worlds in one execution of the game then see if we can get some more details on that case 👍

**Comment by Cervator** [comment]
Going to close this as tentatively fixed - we just resolved for sure a _very_ similar sounding issue with #3903 and while its origin is dated after this issue was submitted I suspect it could have been the same bug surviving a refactor in the area.

Hope you're doing well @brylie, if you run into this again by chance sometime let us know! Fix is in `develop` now, should in in the builds soon.
