### ISSUE TITLE
Input settings screen does not handle some window sizes gracefully

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3508]
### What you were trying to do

Look at the input settings menu to gaze at its sheer awesomeness

### What actually happened

It looked ... less awesome than expected, as it seems like the margins are messed up somehow when the overall window size is of a certain size or less

<img width="338" alt="2018-10-20 22_51_41-terasology _ alpha" src="https://user-images.githubusercontent.com/1063833/47262591-bc1fb400-d4ba-11e8-9fa8-12fdf75241e8.png">

When I resized the window and made it larger suddenly the buttons popped into shape properly

<img width="430" alt="2018-10-20 22_50_56-terasology _ alpha" src="https://user-images.githubusercontent.com/1063833/47262587-a0b4a900-d4ba-11e8-9336-d3e1ac190a2d.png">

### How to reproduce

* Run the game at default settings (no prior `config.cfg` present locally)
* Go to Settings - Input - behold the monstrous proportions of things
* Cry in despair
* Try to increase the overall game window a bit
* Bask at the awesomely structured working version of the page

### Extra

See the https://github.com/Terasology/TutorialNui for an introduction to our UI framework. This issue has happened occasionally in the past, maybe when new elements have been added that have somehow thrown off the available dimensions / margin settings on that page? It could possible relate to the presence of specific modules that introduce input setting items (the list is built dynamically, part of what causes the slowdown in trying to load the page first time). 

Overly wide descriptions of each input setting? Yet it may happen primarily on shrinking the window _vertically_ ? We could probably eliminate the "Terasology" logo element on that page to help make more vertical space available. But still, the buttons shouldn't go screwy just because the window gets resized a bit. There must be a better way to gracefully degrade

**Comment by andrasveto** [comment]
This appears to happen when vertical screen height is below a certain amount (horizontal resizing doesn't affect it). This is present in Player Settings, Input Settings, and Metrics Menu, but not in Video Settings.

**Comment by Cervator** [comment]
Thanks for the detective work @andrasveto and the fix @JustPRV!
