### ISSUE TITLE
Remove the "terasology" title/logo UI element from vertically challenged UI screens

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3509]
It is nice to have on the clean and tidy front page of the main menu, but it is just kinda silly elsewhere:

<img width="491" alt="2018-10-20 23_34_48-terasology _ alpha" src="https://user-images.githubusercontent.com/1063833/47262837-dfe5f880-d4c0-11e8-9323-0dc844ad2f47.png">

Hunt down the UI screens on which this UI element is present and remove it if it makes sense. I'm not sure it is really needed anywhere past the front page. Search for UI fields of type `UIImage` with `"image": "engine:terasology"`

I tried to do this a while ago by just bulk removing it from a variety of `.ui` files but that caused some weird issues. Probably safer to do it one file at a time, test, and look more closely if anything weird happens :-)

To get started: look at our UI tutorial: https://github.com/Terasology/TutorialNui

**Comment by Edvinas01** [comment]
I would like to have a go at this. One more question though - maybe its worth keeping the title in the credits screen as well?

**Comment by Edvinas01** [comment]
One thing that caught my attention was that some of the UI screens have inconsistent layouts. For example the "Game details" screen has a panel which takes up the entire view-port:
![image](https://user-images.githubusercontent.com/8227320/47316724-74329580-d650-11e8-9b79-388acd8f0e29.png)

Then if you navigate to other screens, for example "Player Settings" screen, it contains a panel which sits in the middle of the view-port and doesn't fill it:
![image](https://user-images.githubusercontent.com/8227320/47316497-f2db0300-d64f-11e8-8fbc-2732676d5736.png)

When navigating through screens which vary in layouts its a bit disorienting as you have to spend a bit of time to get used to layout specific to each screen. I've looked through existing UI issues though there doesn't seem to be one regarding this case. Should I create one (though this does seem like a big task so I don't expect it to be finished any time soon if it does get picked up)?
