### ISSUE TITLE
No world generator when building from source (Eclipse)

### ISSUE THREAD

**Issue by dkienenb** [MovingBlocks/Terasology#3523]
### What you were trying to do
Run Terasology from eclipse, create a new world
### What actually happened
World generator wasn't avaible
### How to reproduce

* Git clone Terasology into Eclipse
* Run gradlew
* Import as new Gradle project
* Run Terasology via Run Configurations

### Log details and game version
https://paste.ee/p/TuGCu
Game Version: Latest, as of 10/23/2018
### Computer details
OS: Linux, OpenSuse
 ### Notes
This has the same symptoms as #3363, but doesn't appear to be a building error, as both automatic and manual builds didn't solve anything.

**Comment by pollend** [comment]
try running `./gradlew jar game`.

**Comment by dkienenb** [comment]
Tried that, it doesn't do anything other than normal. Also, I'm trying to run it from Eclipse, not from the terminal.

**Comment by dkienenb** [comment]
Never mind, after I ran that, I had those classes, and the game ran fine. However, it is odd that it didn't build from Eclipse, does that mean that I will have to run that every time I want to build?
