### ISSUE TITLE
After you break a block (such as grass or dirt) and pick it up then proceed to destroy and pick up another block, the current block you are holding will turn invisible

### ISSUE THREAD

**Issue by jmryan64** [MovingBlocks/Terasology#3544]
### What you were trying to do
I was trying to destroy a block of grass and pick it up, then destroy another block of grass.

### What actually happened
After i picked up the block of grass and then tried to destroy another block, the current block of grass i was holding disappeared

### How to reproduce

* Step 1) Use your fists and break a block of grass, then pick it up and equip it
* Step 2) Destroy another block of grass and pick it up
* Step 3) Try to destroy another block and you will see that the block you are holding disappeared (As you can see in the image below, i have the sand equipped but it disappeared)

![image](https://user-images.githubusercontent.com/42872606/48448098-87261a80-e763-11e8-9bbc-b7ce8fda782b.png)

### Log details and game version

Build number: 2231
GIT branch: origin/develop
Created at: 2018-10-05T03:16:57Z

### Computer details
Win. 10, GTX 1060 (Should not matter)

**Comment by jellysnake** [comment]
I can't replicate this on the latest built of Terasology. Do you mind checking if it is still happening for you?

Did you have any modules enabled? It looks like you did from the UI in that screenshot.

**Comment by jmryan64** [comment]
I just tried creating a new game with the same modules active (all that potions is dependent on) and i was unable to reproduce it as well. I think it is safe to close this issue since it was most likely a local issue with that specific save. I'll keep an eye out for it occurring again when i use the game later tonight.
