### ISSUE TITLE
Can't go back after enabling Animated Menus option in Video Settings

### ISSUE THREAD

**Issue by Graviton48** [MovingBlocks/Terasology#3553]
### What you were trying to do
Just saw the `Animated Menus` option in Video settings while in-game and checked/ticked it to try it out.

### What actually happened
After Animated Menus option was enabled , the back button didn't seem to respond...It was not taking me to the Settings Screen (Audio settings, video settings , etc.)

### How to reproduce

* Step 1 Go to Video Settings in-game
* Step 2 Enable `Animated Menus` option
* Step 3 Press `Back` button

### Computer details
CPU- Intel Core-i3 3220
GPU- Nvidia Geforce GTX 1050 2GB DDR5
RAM- 8 GB DDR3
Windows- 10

**Comment by Cervator** [comment]
Closing as fixed by #3615 ! Thanks all :-)
