### ISSUE TITLE
Unplugging joystick leads to crash

### ISSUE THREAD

**Issue by Konfuz** [MovingBlocks/Terasology#3556]
### What you were trying to do
* I tried unplugging my joystick by pulling the cord

### What actually happened

* My joystick got unplugged as planned
* Terasology crashed in a way not planned at all

### How to reproduce

* Step 1: Use a joystick
* Step 2: Pull the cord
* Step 3: No profit

### Log details and game version

https://pastebin.com/vKT69jL3

### Computer details

* In the logfile. More info on request.

**Comment by Alohacajun** [comment]
I'm still new to dev stuff in general, but what happens if you try this in a vanilla environment? I don't have a controller handy atm, maybe a module is conflicting with something?
