### ISSUE TITLE
Attempt to handle unexpected (old or weird) OSes that may not support our directory detection

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3566]
### What you were trying to do

A user attempted to run the game on a Windows XP system. Yes, WinXP still exists. No, it isn't likely to run the game well even if it didn't instantly crash :-)

It made me think though that there might be other current (or future) OSes we might encounter and maybe we can harden the process for a second chance at being able to run the game.

### What actually happened

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'SHGetKnownFolderPath': The specified procedure could not be found.` - apparently XP can't handle the Windows specific call trying to get a default directory to store game data.

### How to reproduce

* Run the game on Windows XP. If you can find something with XP on it

### Possible improvement

I've come up with two brief ideas that might be able to get around this issue, which is namely using native/OS specific code trying to get a game data dir to call default.

* If path detection fails fall back on showing the user a popup asking for a valid path to use (similar to what the game launcher does) - so wrap exception detection around the problematic call then attempt a fallback
* If the user supplies -homedir then skip that whole part of the code. Update the docs to say if you hit an issue like that try to supply -homedir yourself

**Comment by SanchitUke** [comment]
Hi!
I would like to work on this issue. I have not done any exception handling before. Can you direct me where to start? Thank you

**Comment by sladyn98** [comment]
@Cervator Looks like a good beginner issue to work on. Can I start working on this

**Comment by Adrijaned** [comment]
Hi @sladyn98, feel free to start working on this, as as far as I know noone else is yet.

**Comment by sladyn98** [comment]
https://github.com/MovingBlocks/Terasology/blob/4e95d495f21d5a687a48d1edb0f389fb66d7e1cc/facades/PC/src/main/java/org/terasology/engine/Terasology.java#L365

My plan was to add a FileChooser to the above point and instead of catching an IO Exception would catch a general Exception, thereby catching the OS error.This would give the user a chance to select the file path and thus proceed normally.
```JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());```

**Comment by DarkWeird** [comment]
@sladyn98 its will be problem in headless server

**Comment by sladyn98** [comment]
@DarkWeird So in that case we could use the fallback path that has been defined for the operating system.

**Comment by DarkWeird** [comment]
@sladyn98 
I don't think what use homedir - pretty idea.
Looks like game files directly in homedir.
I think problem must be  resolved in PathManager (looks like problem with detect default OS directory)

**Comment by sladyn98** [comment]
> I think problem must be resolved in PathManager (looks like problem with detect default OS directory)

Oh okay so could we add a try block around that code and in the catch block we prompt the user to enter the file path using FileChooser, for headless servers we just use the current directory.
