### ISSUE TITLE
Extract biome-per-block to a module

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3567]
With #3476 merged we can now add per-block data fields in a module. Previously we implemented biome-per-block in #1242 which @Adrijaned then included in a [nice wiki page on biomes](https://github.com/Terasology/TutorialWorldGeneration/wiki/Biomes)

However, biome-per-block isn't necessarily needed in every case, leaving to that field being unused per-block. Things like the new `BiomeChangeEvent` in #3560 wouldn't need to check movement constantly to see if a player is changing biome, only when the new module is active. Speaking of, we have an `OnEnterBiomeEvent` already, came in via #2954, is that a duplicate?

One tricky bit is that we have both biome-per-block and custom biome systems, including `CoreBiome` etc in the Core module. See for instance #2303 for some code changes made to _facet_ based biomes, which are less accurate (2D I believe) but perform better. 

Could the other biome stuff also be extracted? Possibly, but that may be far trickier since it is in use within the engine/Core. It would be like extracting Health or Inventory. It likely *should* be done at some point, but this issue is just to investigate and if possible deal with the per-block biomes, which are rarely used (see https://github.com/Adrijaned/DeadIslands for one usage)

Working this item would involve moving just the per-block biome stuff to a new module, which would remove the associated classes from this repo, breaking API, but I believe we could forgive that. It would also need to involve updating the tutorial on worldgen and sample code since the new module would be a dependency.

For a bit more historical background consider reading https://forum.terasology.org/threads/modding-per-block-storage-extensions.806 or other forum threads on the topic.

**Comment by Adrijaned** [comment]
Oh, didn't know about the existence of the other event... but mine will be easier to extract into the module :grin:. I'll try to tackle this after I finish some other work, if no one has by then

**Comment by Cervator** [comment]
Great :-) Let me know if you want to have a GCI task created for it when you're ready.
