### ISSUE TITLE
Screenshots shown in-game seem oddly narrow?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3584]
Might have been an odd UI alignment issue that snuck in recently. A picture is worth a thousand words:

<img width="567" alt="2018-12-23 20_55_00-terasology _ alpha" src="https://user-images.githubusercontent.com/1063833/50389192-2fc98180-06f5-11e9-9d25-b4fcd5a54ecb.png">

Considering that the game window is rather wide it makes no sense to me that a screenshot should end up being displayed that narrowly.

Some clues to start looking with: `GamePreviewImageProvider.java`, `SelectGameScreen.java`, `selectGameScreen.ui`

See the NUI tutorial to learn about our UI system: https://github.com/Terasology/TutorialNui/wiki

**Comment by e-aakash** [comment]
Can I work on this issue?

**Comment by jellysnake** [comment]
Yup, just submit a pull request when you have enough progress and we can review it.

Use the links in the issue as a good place to get started but feel free to also [join our Discord](https://discord.gg/Terasology) if you get stuck

**Comment by Vishwaak** [comment]
Can I also work on this issue ?

**Comment by Cervator** [comment]
Closing as completed by #3595 - sorry if anybody else has put in work on the same topic and didn't get it merged first :-)
