### ISSUE TITLE
Support expanding / collapsing the items in a drop-down with left and right keyboard arrow

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3590]
As a follow-up to #3588: If you click the expander part of a drop-down with the mouse cursor you can expand or collapse the list of options. Now that we can use `tab` to move between widgets you can work a drop-down without the mouse. However, currently up & down arrow just switch and immediately activate the new option. I believe it is more traditional to also have the left and right arrow keys expand and collapse the drop-down, letting you then scroll through the options with up/down and select an item.

<img width="253" alt="2018-12-26 00_24_59-terasology _ alpha" src="https://user-images.githubusercontent.com/1063833/50433258-0a7b7580-08a5-11e9-9bca-1b93a2da6baf.png">

Goal of this issue is to support just that :-)

I'm not sure I remember the most common convention or even if there is a one-true-convention for drop-down behavior. For instance should up/down while the dropdown is collapsed immediately switch between the items, or first expand the drop-down _and_ move one option up or down in the list? Or should that be left to having first expanded the list manually, at which point you are now purely selecting items and need to activate a chosen option with `enter` ?

**Comment by RatMoleRat** [comment]
This is already somewhat in place - `Enter` when a dropdown in selected by tabbing currently opens the dropdown if it was closed at which point the up and down arrows can be used to navigate through choices. `Enter` also closes and selects the currently selected option if it was already open.

**Comment by Cervator** [comment]
Closing as fixed by #3592!
