### ISSUE TITLE
Game crash on new world

### ISSUE THREAD

**Issue by jtrent238** [MovingBlocks/Terasology#3596]
### What you were trying to do
I just started the game and tried to load a world.
### What actually happened
crashed
### How to reproduce

Start a world

### Log details and game version
```
Terasology - Version
====================

Jenkins:
  URL: http://jenkins.terasology.org/job/TerasologyStable/77/
  Build number: 77
GIT branch: origin/master
Created at: 2018-10-25T02:29:53Z

http://terasology.org
https://github.com/MovingBlocks/Terasology

```
[terasology_2019-01-18_18-38-39.449.logc](https://gist.githubusercontent.com/jtrent238/60dc90b4319adf32ae6e1fc495b5015c/raw/857d84345f2f309919e345a70149c57fe0e85442/terasology_2019-01-18_18-38-39.449.log)
### Computer details
```
------------------
System Information
------------------
      Time of this report: 12/11/2018, 22:24:32
             Machine name: DESKTOP-D1F37RE
               Machine Id: {2B5685B0-90B5-4E9F-9F8E-1A433D3FDB9D}
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)
                 Language: English (Regional Setting: English)
      System Manufacturer: Dell Inc.
             System Model: OptiPlex 390
                     BIOS: A14 (type: UEFI)
                Processor: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 CPUs), ~3.1GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16356MB RAM
                Page File: 6918MB used, 11869MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17134.0001 64bit Unicode
```
full [Dxdiag.txt](https://gist.githubusercontent.com/jtrent238/f96725fd2c25f243a09136448f32d19c/raw/c4220bee3be01f8fcb5f0236eb9090f608f9cabc/DxDiag.txt)

**Comment by jellysnake** [comment]
Hey there, apologies for the delay in responding

It appears that the crash is due to AdditionalWorlds, and more specifically that a world generation plugin is broken. This is a known issue with the module, and if you try again without it enabled you should be fine.

I'm going to close the issue but if you still crash even with AdditionalWorlds removed, then please re-open or make a new issue
