### ISSUE TITLE
UIImage scaling improvements

### ISSUE THREAD

**Issue by PS-Soundwave** [MovingBlocks/Terasology#3598]
#3595 needed to be reverted due to widespread effects on UIImage scaling. However, it demonstrated that the current options for UIImage scaling, fitting and stretching, may not be sufficient for all use cases, and that other scaling modes (like filling) should be available.

Additionally, Cervator proposed that the decision between stretching and filling should be able to be made based on setting a limit to the amount an image is able to be stretched, after which the filling method is used instead. This would require a new scale mode, taking an additional parameter.

To do:
- [ ] Allow all scaling modes to be used with UIImage
- [ ] New scale mode: Context-sensitive stretch / fill

**Comment by Vishwaak** [comment]
Will a if condition to select the two different modes to fill in the image be helpful?

**Comment by jellysnake** [comment]
Closing as resolved through the PR.
If anyone has additional input on this issue then please reopen it and comment
