### ISSUE TITLE
Pull some extra menu items from the pause menu into an Extras sub-menu

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3608]
Much like #3468 (fixed in #3506) did for the main menu, we can do something similar on the pause menu. Observe:

<img width="490" alt="2019-02-02 13_39_20-c__windows_system32_cmd exe" src="https://user-images.githubusercontent.com/1063833/52167879-fde20c80-26ef-11e9-8537-75e11bd62177.png">

The three buttons along the button should be moved into an "Extras" button in the main lineup of buttons just like we have on the main menu. Should be a Good First Issue since the old issue/PR provides a great overview of what's needed, this is just targeting a different menu.

**Comment by shaunakdixit** [comment]
I would like to work on this.
I have gone through the docs of Terasology do I need to study more or I can start.
Its my first time in  open source so help me out a little

**Comment by shaunakdixit** [comment]
@Cervator would you please tell me that I'm on right track
![20190204_140149](https://user-images.githubusercontent.com/22188087/52197408-75957000-2885-11e9-8c6d-092701c3a5dc.jpg)
This is what I have to do to create a new button which includes "Metrics Menu ", "Issue Reporter", "Developer Tools" along with "Back" Button.

**Comment by jellysnake** [comment]
Yup, that's correct. When this new button is pressed just change the ui from being

```
┌───────────────────┐
│ Back               │
└───────────────────┘
┌───────────────────┐
│ Settings          │
├───────────────────┤
│ Extras            │
├───────────────────┤
│ Exit to Main Menu    │
├───────────────────┤
│ Exit Terasology      │
└───────────────────┘
```
To
```
┌───────────────────┐
│        Back        │
└───────────────────┘
┌───────────────────┐
│ Metrics Menu      │
├───────────────────
│ Issue Reporter       │
├───────────────────
│ Developer Tools      │
└───────────────────┘
```
And obviously move back to the pause menu when **Back** is pressed.

**Comment by shaunakdixit** [comment]
hello @jellysnake I completed the task
![image](https://user-images.githubusercontent.com/22188087/52303328-b7bdcf00-29b5-11e9-83d1-dd330f104f71.png)
as u can see in image but I'm not able to remove those **'?'** in **"extra"** button 
please help me out

**Comment by jellysnake** [comment]
Without seeing the code I'm not going to be able to help very well. If you make a Pull Request I can help much easier.

If you are new to GitHub and unsure how to do that, hop onto out discord (https://discord.gg/terasology) and we can help you out. (We also have an IRC if you're more old skool inclined :) )

**Comment by shaunakdixit** [comment]
hy @jellysnake can you please look into my code and can you suggest me a way to resolve that error of **'?'**
thanks

**Comment by Cervator** [comment]
Heya @shaunakdixit - I see the PR and it looks pretty good! :-)

I'm not sure why you're getting `?`s - I thought maybe that was just a placeholder for you. UI strings like that are defined in `menu_en.lang` (well technically `menu.lang` but the EN file contains the default English label) and in this case `extras-label` already contains the right label so that should work here too

**Comment by shaunakdixit** [comment]
> Heya @shaunakdixit - I see the PR and it looks pretty good! :-)
> 
> I'm not sure why you're getting `?`s - I thought maybe that was just a placeholder for you. UI strings like that are defined in `menu_en.lang` (well technically `menu.lang` but the EN file contains the default English label) and in this case `extras-label` already contains the right label so that should work here too

Ok @Cervator  thanks a lot for your help I think I got my answer why I'm getting **'?'** I'll make changes in my PR.
but I'm having one doubt that i need to change menu.lang also along with menu_en.lang

**Comment by shaunakdixit** [comment]
I made some changes in menu_en.lang and menu.lang in which I included my new keywords like **"extra-menu"** and **"extra-menu-title"** but my system is not with me so I have not tested it on my own.
Please have a look @Cervator and if I will be able to find some error l'll try to resolve it.
thanks :-)

**Comment by Cervator** [comment]
Closing as completed by #3617 ! :-)
