### ISSUE TITLE
Trees not falling down after cutting the trunk

### ISSUE THREAD

**Issue by darshan3** [MovingBlocks/Terasology#3639]
### What you were trying to do

I was trying to cut/destroy a tree in Core Gameplay. I removed an entire layer of wood from the trunk once using an axe and once using dynamite. I expected the rest of the tree to fall down.

### What actually happened

Nothing happens to the remaining section of the tree. It stays where it is and appears to be floating.

**Comment by pollend** [comment]
not technically an issue with the core game module. if you would like you can create a module that does just that.

https://github.com/MovingBlocks/Terasology/wiki/Developing-Modules

**Comment by pollend** [comment]
The base core module should be fairly bare and additional functionality is added from module space.

**Comment by Cervator** [comment]
To add: this functionality exists/existed in the Throughout the Ages gameplay template, where whole trees fell down if you cut the bottom block in the trunk. That's how the game is structured - more advanced modules add more advanced functionality :-)

Unfortunately it is also a whole lot of code to maintain so some modules are more well maintained than others. TTA has sadly been inactive a long time so it doesn't work very well anymore. But the code is in there - it just takes a bit of effort to dust it off and make it live again 👍

**Comment by jellysnake** [comment]
I also want to comment that simple farming would be an ideal place to have this, if it isn't already contained in there
