### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [MovingBlocks/Terasology#3646]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by Cervator** [comment]
Hi @gustavosizilio - yes, we've had https://jenkins.terasology.org/ in use for years and years.

PRs in this repo and a few others get auto-tested with links to build info etc :-)

Any follow-up question or something you're interested in changing / working on?

**Comment by gustavosizilio** [comment]
Thank you very much! I just want to study the builds. closing this issue. I appreciate your time!
