### ISSUE TITLE
Game build doesn't detect Dedicated GPU (even if you force it)

### ISSUE THREAD

**Issue by Haxsen** [MovingBlocks/Terasology#3652]
### What you were trying to do
Running terasology latest build on my laptop with dual GPUs (Intel HD:0 , Nvidia GTX970M:1).
### What actually happened
Starting the game doesn't auto detect the dedicated card, GPU 1. If you force it in Nvidia Control Panel (by selecting Terasology.x64.exe and setting it to High performance GTX970M GPU) or in Win10 Graphics Settings (by selecting Terasology.x64.exe and setting it to High performance GTX970M GPU), the game STILL doesn't use the dedicated GPU at all (tested using CpuID HWmonitor).
### How to reproduce

* Step 1 : Go to nvidia control panel / amd settings.
* Step 2 : Add custom application in switchable graphics.
* Step 3 : Set the application on High performance (so it uses dedicated GPU 1).
* Step 4 : Start HWmonitor or any other monitoring application.
* Step 5 : Watch if your dedicated GPU 1 is utilized or not.
* Step 6 : Open Task Manager > Processes and select Terasology, see the GPU Engine column at the end. (GPU 0 stands for integrated, GPU 1 for dedicated).

### Log details and game version
Terasology - Version

Jenkins:
  URL: http://jenkins.terasology.org/job/TerasologyStable/78/
  Build number: 78
GIT branch: origin/master
Created at: 2019-02-03T04:57:39Z

### Computer details
MSI GE72 Apache Pro (Laptop)
https://us.msi.com/Laptop/GE72-Apache-Pro-GTX-970M/Specification

**Comment by TheHxn** [comment]
Possible Solution from this [forum](http://www.java-gaming.org/topics/lwjgl-uses-wrong-graphics-card/37938/view.html):
Making the game automatically use the dedicated graphics card by writing a custom javaw.exe/java.exe launcher using the [JNI Invocation API](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html) .
When this process exports a symbol called "NvOptimusEnablement" as a DWORD with value = 1, then the dedicated graphics card will be used (unless of course the user overrides this in the Nvidia settings).

**Comment by skaldarnar** [comment]
Closing as "won't fix".
