### ISSUE TITLE
Log a warning if module defined in override.cfg doesn't exist

### ISSUE THREAD

**Issue by mayant15** [MovingBlocks/Terasology#3673]
The `override.cfg` file holds settings for the headless server. These are applied over the ones in `config.cfg`. Modules to be activated by the headless server are also defined here.

Right now, if a module that doesn't exist is defined in the override file, the server just ignores it and moves on. It would be better if an error or at least a warning is thrown in these cases. 

The `StateHeadlessSetup` class might be a good place to start. It sets up all configuration options which you would control using the in-game menu UIs.

**Comment by Cervator** [comment]
For more details about the override file see https://github.com/MovingBlocks/Terasology/blob/develop/docs/Playing.md#configuring-a-server :-)

`ModuleManagerImpl` might also be a good class to check on

Hopefully a Good First Issue, hop on our Discord for more questions, easy to miss notifications from GitHub 👍

**Comment by askneller** [comment]
I'll take this one.

**Comment by askneller** [comment]
I have created a pull request for this. https://github.com/MovingBlocks/Terasology/pull/3702
