### ISSUE TITLE
Enhance the `dumpEntities` command

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3683]
In `CoreCommands` there is a simple `dumpEntities` command that'll write all entities in the world to a debug file. That's great! But you don't always need _all_ the entities, but something more specific.

The objective of this Good First Issue is to make a variant of that command that takes a parameter (or a ... list of parameters) for a specific Component to filter by then only write out those entities instead.

Easiest would just be to take a single Component, I'm not sure if it would be more useful to allow passing multiple components that you'd then want either all entities with any component match or only the entities that have all the listed components.

See `entityManager.getEntitiesWith` examples to see how to retrieve entities with a specific set of Components.

**Comment by NWc0de** [comment]
Is this still up for grabs?

**Comment by OvermindDL1** [comment]
Remember that github has the ability to assign an issue to someone who's commented on the issue even when they are not a contributor now @Cervator.  :-)

**Comment by AahzBrut** [comment]
This issue can be closed
