### ISSUE TITLE
Rename ExternalApiWhitelist to ExternalApiAllowlist

### ISSUE THREAD

**Issue by SoniEx2** [MovingBlocks/Terasology#3729]
We should rename `ExternalApiWhitelist` to `ExternalApiAllowlist`. This shouldn't really break anything.

**Comment by jellysnake** [comment]
Whitelist is a well known term. It indicates things that are allowed, hence it fits here. Can you please elaborate as to why allowlist would be better than whitelist?

**Comment by SoniEx2** [comment]
Some ppl argue "whitelist" is racist. I don't know.

On the other hand "allowlist" is actually clearer for non-english-speaking ppl.

**Comment by jellysnake** [comment]
I understand the concerns about allowlist being clearer but I disagree. Whitelist is a term used _throughout_ technology, with a very consistent meaning. I will accept that "allowlist" might be more intuitive, it's a list of things to allow. I think that the fact that whitelist is so widely used however overcomes this.

**Comment by SoniEx2** [comment]
And we should still change it and encourage others to do the same.

**Comment by jellysnake** [comment]
I think we're going to need more widespread agreement before this is a reasonable change. Either through a number of projects changing it or alternatively, a decent number of people in this org agreeing. Until then I wouldn't regard this as a required change

**Comment by Cervator** [comment]
No.
