### ISSUE TITLE
javafx.fxml.LoadException crash on startup

### ISSUE THREAD

**Issue by yuvalif** [MovingBlocks/Terasology#3736]
### What you were trying to do
trying to launch the game

### What actually happened
launcher crashed

### How to reproduce
just call: ``$ bin/TerasologyLauncher``

### Log details and game version
log: https://pastebin.com/sDUztme7
stack trace: https://pastebin.com/89JJaf7Y

### Computer details
Fedora30
```
$ uname -a
Linux localhost.localdomain 5.2.9-200.fc30.x86_64 #1 SMP Fri Aug 16 21:37:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Cervator** [comment]
Hi @yuvalif - this is an issue specific to our launcher, primarily tracked via https://github.com/MovingBlocks/TerasologyLauncher/issues/413 :-)

We've solved it in a pending release of the launcher by embedding a JRE that includes JavaFX. Said version of the launcher should be released Soon ™️ !
