### ISSUE TITLE
Game does not launch

### ISSUE THREAD

**Issue by RastaManKing** [MovingBlocks/Terasology#3742]
Launch the game

Game splash screen flashed then game crashed

Step 1 - Install game (im using Arch Linux)
Step 2 - Launch game
Step 3 - Watch it not start

[rastamanking@GreenGoblin ~]$ terasology
PathManager being initialized. Initial code location is /usr/share/terasology/libs/engine-2.2.0.jar
Switched it to expected working dir: /usr/share/terasology
installPath was null, running from IDE or headless server? Setting to: /usr/share/terasology
Found the natives dir: /usr/share/terasology/natives
21:05:45.303 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
21:05:45.316 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=78, buildId=78, buildTag=jenkins-TerasologyStable-78, buildUrl=http://jenkins.terasology.org/job/TerasologyStable/78/, gitBranch=master, gitCommit=a05742f087c3b9a680284ccc1b91c8b1e38c3dc6, dateTime=2019-02-03T04:57:37Z, displayVersion=alpha, engineVersion=2.2.0]
21:05:45.316 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: /home/rastamanking/.local/share/terasology
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: /usr/share/terasology
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 12.0.2 in /usr/lib/jvm/java-12-jdk
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: Java HotSpot(TM) 64-Bit Server VM, version: 12.0.2+10
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Linux, arch: amd64, version: 5.2.11-arch1-1-ARCH
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 1536 MiB
21:05:45.317 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 8
21:05:46.013 [main] INFO  o.t.e.s.c.ConfigurationSubsystem - Video Settings: {"pixelFormat":24,"windowPosX":379,"windowPosY":235,"windowWidth":1152,"windowHeight":720,"displayModeSetting":"${engine:menu#video-windowed}","animatedMenu":false,"flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":false,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"vrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"uiScale":100,"dumpShaders":false,"volumetricFog":false,"screenshotSize":"${engine:menu#screenshot-size-normal}","screenshotFormat":"png","cameraSettings":{"cameraSetting":"${engine:menu#camera-setting-normal}"},"debug":{"enabled":false,"firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
21:05:46.046 [main] ERROR o.terasology.utilities.NativeHelper - Couldn't link static libraries. 
java.lang.NoSuchFieldException: usr_paths
	at java.base/java.lang.Class.getDeclaredField(Class.java:2416)
	at org.terasology.utilities.NativeHelper.addLibraryPath(NativeHelper.java:50)
	at org.terasology.utilities.LWJGLHelper.initLibraryPaths(LWJGLHelper.java:48)
	at org.terasology.utilities.LWJGLHelper.initNativeLibs(LWJGLHelper.java:39)
	at org.terasology.engine.subsystem.lwjgl.BaseLwjglSubsystem.preInitialise(BaseLwjglSubsystem.java:40)
	at org.terasology.engine.subsystem.lwjgl.LwjglTimer.preInitialise(LwjglTimer.java:35)
	at org.terasology.engine.TerasologyEngine.preInitSubsystems(TerasologyEngine.java:272)
	at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:208)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:390)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
[rastamanking@GreenGoblin ~]$ 

Alienware 15 R3 
Arch Linux

**Comment by Cervator** [comment]
Heya @RastaManKing - so you're running the game here with Java 12, while we've only really tested for sure that Java 8 works well. We know of a few issues on Javas 10-11, and are still digging around for more. Changes are this is from Java 12 somehow - although `Couldn't link static libraries.
java.lang.NoSuchFieldException: usr_paths` _could_ be some other sort of OS-specific issue.

If you're just trying to play we've been working of an overhaul for our game launcher, which would come with an embedded Java that'll work for sure with both the launcher and the game. Keep an eye out for that being released soon ™️ :-)

**Comment by OvermindDL1** [comment]
Really should update to at least Java11.  Java8 is no longer accessible in most repositories because Oracle changed it's license in a highly questionable way, thus it probably shouldn't be bundled either.

**Comment by Cervator** [comment]
Hi @OvermindDL1 ! Good to see you pop up on occasion. Absolutely agreed - the sooner we can vet out Java upgrades till 11 the better. We also have an embedded OpenJDK 11 + OpenFX 11 in our sights for the launcher as well :-)

**Comment by Cervator** [comment]
Just noticed this also got posted in the forum, at least I assume so based on the identical avatar pic :-)

https://forum.terasology.org/threads/problem-launching-in-linux.2276/

@Avalancs found a search hit for the same issue elsewhere, and reinstalling Java fixed it - although of course if that included a downgrade from 12 to 8 then yeah, that'll do it for sure :-)

Going to close this as resolved, with the caveat that we still do need to validate the game on newer Javas. Including Java *13* which of course just got released ;-)

At this pace I wonder if the Java 14 LTS will be out and ready by the time we've settled on 11 ;-)

**Comment by casals** [comment]
Message to the people of the future: got the exact same problem when running AdoptOpenJDK 8, but over a OpenJ9 JVM. Replacing it with a different JDK (v8) and completely cleaning the workspace solved the problem.
