### ISSUE TITLE
Can't run game with "./gradlew game"

### ISSUE THREAD

**Issue by PavelAplevich** [MovingBlocks/Terasology#3745]
I create local repo on my machine. Follow instructions, but if I try do **./gradlew game** i see this:

**java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.**

Logs file here

[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/3665893/Terasology-init.log)

And, i think, that's my another problem, but i hope u can help. If I try run any build in my IDEA, i see this:

**Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1394)
	at org.terasology.splash.overlay.ImageOverlay.<init>(ImageOverlay.java:38)
	at org.terasology.splash.overlay.TriggerImageOverlay.<init>(TriggerImageOverlay.java:30)
	at org.terasology.engine.Terasology.configureSplashScreen(Terasology.java:206)
	at org.terasology.engine.Terasology.main(Terasology.java:125)**

OS - Ubuntu 18.04.3 LTS 

java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by StripedMonkey** [comment]
Can't replicate on Arch Linux,
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

**Comment by NicholasBatesNZ** [comment]
I ran into the same issue myself on Ubuntu 18.04.3 LTS. This was after freshly cloning the game.
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

Using this same setup I am able to compile and run Destination Sol without issue.
Some limited googling suggests that the issue may have something to do with reflections..

**Comment by NicholasBatesNZ** [comment]
UPDATE:
Removing line 113 from TypeRegistry.java (`.useParallelExecutor()`) fixes the issue. Just one thing... I don't know why and I don't know what other repercussions there could be.. :P

**Comment by NicholasBatesNZ** [comment]
This should be fixed if/when #3750 is merged

**Comment by StripedMonkey** [comment]
Out of curiosity what CPU do you have? I've got the 8750H on this laptop and don't have any issues with it.

**Comment by PavelAplevich** [comment]
Intel core I5-7500  3.40x4

**Comment by NicholasBatesNZ** [comment]
And mine:
CPU: `Intel® Core™ i5-8400 CPU @ 2.80GHz × 6`
Graphics: `Intel® UHD Graphics 630 (Coffeelake 3x8 GT2)`
GNOME: `3.28.2`

**Comment by Cervator** [comment]
Merged the associated PR that in theory fixes this. @PavelAplevich could you try again with the very latest develop branch?

**Comment by PavelAplevich** [comment]
I can run the game. I think, all work's.
