### ISSUE TITLE
Improper stair collision; cannot climb stair without full block underneath it

### ISSUE THREAD

**Issue by Qwertygiy** [MovingBlocks/Terasology#3746]
### What you were trying to do
Climb up a staircase using blocks that utilize the "engine:stair" shape. 

### What actually happened
When attempting to climb from one stair block onto another stair block, in which the second stair block does not have a solid block beneath it, the character will become stuck and unable to climb without jumping.

### How to reproduce
You will need 4 blocks using the stair shape and 1 normal full block. Arrange thusly:

![image](https://user-images.githubusercontent.com/2421117/65924839-84083d00-e3bc-11e9-8cdf-95bca719fe16.png)

Or, in plaintext, where L = stair, X = full block, and ░ = air:

L░░░L░
XL░░░L

Attempting to climb the staircase without a block will leave the player stuck on the top of the first stair block. Attempting to climb the staircase with a block will work as expected.

I believe that this is related to improper collision heights in the stair shape, as the character's eye level is slightly lower when standing on the top half of a stair block than when standing on the top of a full block.

### Log details and game version

Dev branch, 9/30/2019.

### Computer details
![image](https://user-images.githubusercontent.com/2421117/65925212-dd24a080-e3bd-11e9-9e7b-79091c722659.png)

**Comment by misterHippo** [comment]
G'day, 

After discussing this on Discord with Gooey and skaldarnar, I'm flagging that this is still an issue in v78 (At least with brick stairs). I fall straight through the suckers!

(Will try and establish other aspects and edit later.)

System is an i5-4690 (3.5GHz), 16GB RAM, Win10 Home 64Bit, ASUS STRIX GTX 750 Ti (nVidia), Samsung EVO SSD - running v78 via the 4.0.0 launcher (as directed by Cervator)

**Comment by misterHippo** [comment]
Ok, new day, new update. :)

Have tried with barebones 2301 version. Only had access to dirt and grass stairs. Repeated tests, no issues found.
