### ISSUE TITLE
Game Crashed(Survival)

### ISSUE THREAD

**Issue by EaguaireSama** [MovingBlocks/Terasology#3758]
I was trying to play the survival mode while the game crashed
### How to reproduce

* Step 1 Get the latest Dev Build
* Step 2 and play the survival mode...

link to log file: https://drive.google.com/uc?id=1sK0YsaMcAnrUWP-d8TGtQfS16ftiHUkj&export=download
i have the latest Dev build

**Comment by Cervator** [comment]
Hi there :)

This is a know issue in the dev build, we're doing a big module overhaul, see #3737. We need to apply more fixes then get a new good build out.

For reference in general this is for JoshariasSurvival - we could keep this issue to track when JS is stable again

**Comment by Cervator** [comment]
Closing this as complete - JS works fine now in build http://jenkins.terasology.org/job/DistroOmega/1061/artifact/distros/omega/build/distributions/TerasologyOmega.zip and hopefully will keep working normally 👍
