### ISSUE TITLE
CheckStyle error - TreeWalker is not allowed as a parent of LineLength

### ISSUE THREAD

**Issue by rajiv-thorat** [MovingBlocks/Terasology#3780]
### What you were trying to do
Attempting to analyse the engine-tests project (well, a specifc file that I was working on). 
### What actually happened
Idea refuses to run the analysis because of an error.
### How to reproduce
Steps I followed were the ones from the wiki page to install the CheckStyle plugin in Idea. 
I could see the plugin tab with an option in the drop-down menu 'Terasology CheckStyle'. 
I assumed that Idea recognised the xml file (checkstyle.xml) from the metrics folder. 

The error that produced is : The Checkstyle rules file could not be parsed. cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. The file has been blacklisted for 60s.

### Computer details
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 26, 2019
Runtime version: 11.0.4+11 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.3.7-arch1-1-ARCH
GC: ParNew, ConcurrentMarkSweep
Memory: 926M
Cores: 4
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA, training

CheckStyle v8.25

Issue appears to be similar to #3113 .

Perhaps downgrading to an earlier version of CheckStyle could be a temp fix.

**Comment by Cervator** [comment]
Okay I *believe* this has been fixed now with #3835, at least I recognized the issue or a very similar one and was able to validate it went away after that PR :-)

Going to close this as fixed, but if you still see it @rajiv-thorat please let us know! And thanks for the report 👍
