### ISSUE TITLE
Highlight module dependency issues on Module Details page

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3795]
### What you were trying to do

Test a new Omega zip that ended up having some funny versions. Noticed some modules in red within the Gameplay Template drop-down as well as on the Advanced Game Setup page. Would have been nice to also see that after pressing the "Module Details" button while highlighting one of the red modules in the list.

### What actually happened

No highlighting at all on the Module Details page, although it outright lists enough to clearly spot an issue. See screenie below.

Find the code that results in coloring bad modules in red, then also apply it to the Module Details page in various places. See annotated screenie below.

See also #3131 for a bigger picture issue on the topic - but this one spot should be doable on its own without too much work, I hope!

### How to reproduce

* Mess with versions on a given module. For instance change Cities to v9.9.9 and modules like Light And Shadow should fail
* See the red highlight on the Advanced Game Setup page
* With Light & Shadow (or whichever affected module) highlighted click the Module Details page. No highlights!

### Screenies

Now you see it

![2019-12-07 01_02_15-Terasology _ Alpha](https://user-images.githubusercontent.com/1063833/70369835-3bbe3d00-188d-11ea-8fc7-8e32ef5e41cb.png)

Now you don't!

![2019-12-07 00_53_18-Terasology _ Alpha](https://user-images.githubusercontent.com/1063833/70369829-3234d500-188d-11ea-9af2-3cd38c6aed73.png)

To clarify: The minimum required version is 0.6.2, max supported is 0.7.0, yet actual installed version is 1.0.0, which is out of bounds, therefore the dependency resolution fails.

**Comment by AnujAgrawal30** [comment]
Hey, I would like to work on this issue.
I'm new to the codebase but on initial analysis was able to change the text color on the Modules List on the left column to red on any dependency issue.
Also, I guess the module Dependencies list was already showing red color to problematic dependencies.
However, I'm not sure how can I change the text of the Installed version text. Do I've to define a new Canvas for it and set the color as red? Please help
