### ISSUE TITLE
Using URL as key to Map is unsafe

### ISSUE THREAD

**Issue by kahing** [MovingBlocks/Terasology#3801]
https://github.com/MovingBlocks/Terasology/blob/dbfe54ea07bcecabe90a1fae5bdd67e1e0380b38/engine/src/main/java/org/terasology/utilities/download/MultiFileDownloader.java#L33

https://news.ycombinator.com/item?id=21765788

**Comment by Cervator** [comment]
Interesting! Thanks for the report :-)

I guess it might not take much effort to switch to a URI if anybody wants to try it - marking Good First Issue. May be more than one usage so anybody trying this should dig around a bit. May also want to check TerasologyLauncher

**Comment by Cervator** [comment]
Closing as fixed by #3805 :-)
