### ISSUE TITLE
Cannot close UI after reloading it in-game

### ISSUE THREAD

**Issue by Torpedo99** [MovingBlocks/Terasology#3816]
### What you were trying to do
I was trying to edit a few .ui files while they were opened in terasology.
 I changed a parameter in a .ui file and saved it (the game should hot reload the file), closed the ui and reopened it again (the new changes were there). Then tried to exit the UI by pressing the escape button.
### What actually happened
The UI did not close.
### How to reproduce

* **Step 1**: Launch Terasology and load a world. Use an external module for NUI like [TutoralNui](https://github.com/Terasology/TutorialNui). If you plan on using engine ui files (like console.ui and chat.ui) remember that engine assets can be hot reloaded, *but* you need to either work on the asset in the build folder or "recompile" it in IntelliJ so that the asset gets pushed to the build folder.
* **Step 2:** Try opening a UI, and then close it. (it should)
* **Step 3**: Update something in the corresponding .ui file in IntelliJ (something like the "text" parameter). If you're working with an engine ui file make sure to recompile it or directly edit the ui from the build folder instead.
* **Step 4**: Open the UI again.
* **Step 5**: Try to close the UI by pressing the escape key. It should throw an error.

### Log details
The error that is thrown on pressing the escape key: https://pastebin.com/gmdLeNvw

**Comment by IsaiahBlanks** [comment]
I've found that this bug has to do with the difference between the way a screen is created vs the way it is reloaded. When you call showScreen from the console, if the screen doesn't exist yet, nuiManager handle initializing it, which allows the object to be set with the nuiManager associated to it. However, when the object is edited during the game, it is recreated from its json, but this is not handled by the nuiManager, so it is never associated with the manager.
