### ISSUE TITLE
Broken "Join Game" to the local server.

### ISSUE THREAD

**Issue by CriDos** [MovingBlocks/Terasology#3829]
Broken "Join Game" to the local server.
Client side logs:
[Terasology-menu.log](https://github.com/MovingBlocks/Terasology/files/4134572/Terasology-menu.log)
[Terasology-.log](https://github.com/MovingBlocks/Terasology/files/4134573/Terasology-.log)
[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/4134574/Terasology-init.log)
Latest version: https://github.com/MovingBlocks/Terasology/commit/6671bf5ea07e6e97618ec314814519334a7f9e50

_Originally posted by @CriDos in https://github.com/MovingBlocks/Terasology/pull/3802#issuecomment-580292360_

**Comment by Cervator** [comment]
Thanks for the report @CriDos - can confirm, and this is a high priority fix then :-)

**Comment by sin3point14** [comment]
Some research i tried to do :-)
https://discordapp.com/channels/270264625419911192/270264625419911192/682401210392772622

**Comment by Cervator** [comment]
Thanks for the report @CriDos and the research @sin3point14 - this should now be resolved! :-)
