### ISSUE TITLE
Crash when creating world.

### ISSUE THREAD

**Issue by fisik-yum** [MovingBlocks/Terasology#3834]
### What you were trying to do
create a new world
### What actually happened
created world, loaded world, then immediately crashed
### How to reproduce

* Step 1-Create world(using core gameplay template.)
* Step 2That's all. 
* Step 3

### Log details and game version
https://pastebin.com/Sx4x2LCv
### Computer details
Windows 10 home 64-bit, Core i5-7200U clocked at 2.5 GHz and 8 Gigabytes of RAM

**Comment by Cervator** [comment]
Hi @fisik-yum and thanks for the log! What _version_ of the game did you work with though? Latest stable release? Local source workspace? Did you update any modules?

The errors in the log are odd - lava hasn't changed for a while, I think 🤔 Did you make any local modifications?

```
20:23:04.192 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'Core:AnimationTest'
java.io.IOException: Invalid tile - must be square with power-of-two sides
...
20:23:04.325 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'CoreAssets:Lava'
java.io.IOException: Invalid tile - must be square with power-of-two sides
...
```

**Comment by fisik-yum** [comment]
Okay, sure.
I was using the latest stable release of the game, and my installation directory was C:\terasology and my saves were located in C:\terasology\saves
and no local modifications and I did not update any modules.

**Comment by Cervator** [comment]
Thanks for the update @fisik-yum ! Glad you got it working. Will close this as resolved then :-)

Interesting note about the thumb drive! Not sure that's been tried much.
