### ISSUE TITLE
Server connection test updates actively selected server not the origin server

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3850]
### What you were trying to do

Look at servers accurately on the Join Game screen showing multiple servers

### What actually happened

Clicked a bad server (offline) first by accident, then selected a working server. When the failed ping test came back from the bad server it showed the result (being unable to connect to the server) on the good server, despite the other stats showing online and all is well.

Some threaded check holding that call probably needs to pick its update target better. Maybe at present it just updates the field regardless of the selected server, when perhaps it should be a call-back with the specific server queried? And if that isn't visible /selected then don't show it. 

### How to reproduce

* Make sure there's both a working and not-working server in the join game list
* Select the broken server (should start a server query that'll time out)
* Quickly select a working server and wait a second or two, the connection to the good server will show that it "failed"

**Comment by raisinrand** [comment]
I will try taking a look at this as a first PR.

**Comment by Cervator** [comment]
@raisinrand great, good luck!
