### ISSUE TITLE
JOML version upgrade version 1.9.22

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#3868]
https://github.com/JOML-CI/JOML/issues/218

I was trying to use the newest version of JOML but it seems to break the camera and I'm not entirely sure what is wrong. I would assume it has something to do with the view matrix where the scale gets flipped. I've run git bisect and narrowed it down to this commit: 59366778236e14b138769f6c2761d7c7b9fdaadc 

If it a problem with terasology that can be addressed but some behavior changed in the library and I'm not entirely sure what is wrong. this commit is pretty large so pinning down the exact problem seems difficult. I might try use a previous commit and slowly patch in changed for Matrix4f and see If i can find a direct cause. 

Any clue what changed between the previous version and this commit?

![resize](https://user-images.githubusercontent.com/854359/77617524-a86b4f00-6ef1-11ea-8835-a61ec16d0f0d.gif)

**Comment by pollend** [comment]
this was corrected with this issue: https://github.com/JOML-CI/JOML/pull/219

**Comment by httpdigest** [comment]
[Version 1.9.23](https://github.com/JOML-CI/JOML/releases/tag/1.9.23) is on Maven Central now.
