### ISSUE TITLE
Bobbing causes weird shift in lighting

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3881]
### What you were trying to do

Test something unrelated. One would normally expect to be able to move around the world with consistent lighting/shadows

### What actually happened

Only when walking with the "bobbing" gfx turned on: the lighting shifts subtly for each "bob" (every few steps). Doesn't happen if flying or if you turn off the effect.

### How to reproduce

* Run game normally and enter a world with "bobbing" enabled
* Move forward, ideally with a hill or something in front of you
* Observe subtle lighting shifts in tune with the head bobbing

*Note:*: It may be specific to time of day in-game - seemed to not happen in some cases but around World Time 0.5 it was strongly present.

It may relate to the recent JOML changes as I cannot replicate with the commit immediately preceding #3811 - but I haven't tested after that point commit-by-commit. @PS-Soundwave suspected as much, but upgrading to `1.9.23` from `1.9.19` didn't seem to have an effect. 

### Screenies

Easier to see the effect in-game, but it is there

![Terasology-200406221929-1152x720](https://user-images.githubusercontent.com/1063833/78626605-db4c0600-7854-11ea-9d49-2c489e54c85d.png)

![Terasology-200406221928-1152x720](https://user-images.githubusercontent.com/1063833/78626611-dedf8d00-7854-11ea-8d40-d33cdcb5ef54.png)

**Comment by pollend** [comment]
I think #3885 resolves this.

**Comment by Cervator** [comment]
Looks like! Thanks hunting it down :-)
