### ISSUE TITLE
Weird terrain effect: empty layers of blocks

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3882]
### What you were trying to do

Test GooeysQuests (and previously ShatteredPlanes in the previous weekend's play test). Some worlds and world generators were fine.

### What actually happened

The terrain generated with some rather major flaws: in GooeysQuests with seed `PO1D86SnyqL2zrSB` you start with a desert hill on one side and a grassy one on another, but the grassy one essentially is missing its entire interior (mostly full of open space with a few odd thick stone columns in some places) and about every other block height-wise going up the hill. 

Additionally some trees deeper in were very messed up, see screenie below. Also note that the grass blocks are entirely green, not normal ground/grass ... this I'm pretty sure we've seen before for ages.

In ShatteredPlanes we likely hit the same issue but there it presented by simply having an increasing gap between the very top surface layer of blocks and the bedrock below it.

This does *not* appear to relate to the recent JOML work as I could replicate it with the same seed having rolled the engine back to #3811 (with a small set of modules including GQ, all at latest but with some tweaks here and there like refreshing `build.gradle` files in modules and bumping Core to v3.0.0)

### How to reproduce

* Start the game and create a new game, be sure to go to the advanced screen
* Enter the seed value `PO1D86SnyqL2zrSB` and continue through the setup adding a Perlin world
* Observe swiss-cheese hills

![Terasology-200406221709-1152x720](https://user-images.githubusercontent.com/1063833/78627972-7692aa80-7858-11ea-8e2d-742387bf6a27.png)

**Comment by skaldarnar** [comment]
Fixed by #3886
