### ISSUE TITLE
Duplicate built packages persisting

### ISSUE THREAD

**Issue by 4Denthusiast** [MovingBlocks/Terasology#3972]
If a class is labelled (with its "`package org.terasology. ...`" line) as being in a package with a capitalised name, the built class is put in a folder with the capitalised name. If the source file is updated so that the package name is lowercase and it's re-compiled, both the upper- and lower-case versions of the package will persist, and both will show up from the `ModuleEnvironment`.

I don't know which of these features are essential to the bug occurring, but specifically I updated org.terasology.AdvancedRendering.rendering.AdvancedRenderingModule to org.terasology.advancedRendering.rendering.AdvancedRenderingModule, where in both cases the actual path to the file used the lowercase version, and ran `gradlew jar game` again, at which point `[Terasology]/modules/AdvancedRendering/build/classes/org/terasology` contained two folders, `advancedRendering` and `AdvancedRendering`, both of which contained classes, despite there no longer being any reference to the capitalised version in the source. A call of `moduleEnvironment.getSubtypesOf(ModuleRendering.class)` then returned both versions of the class, which caused problems once both of them tried to add the same nodes to the render-graph.

**Comment by skaldarnar** [comment]
A `gradlew clean` does "solve" this problem as the files renamed are being removed from the compile cache, is that correct? 

I would say that this is not inherently a problem of the module environment, it's actually doing the right job - there _are_ two "different" things with slightly different names to pick up. 

This may not even be a problem in some case-insensitive file systems... 

So, I'd call it a common pitfall developers should be aware of, but not necessarily something we should prevent against. Or am I missing something here?

**Comment by Cervator** [comment]
Agreed with @skaldarnar 👍 

I don't know if there's anything we can do to guard against it? We could perhaps throw some logic at trying to detect case-variant dupes (oh hey that would have been useful for that darn copper axe - https://github.com/Terasology/EquipmentSmithing/commit/269904af82ddbdce91a14c445df8fbe19dc1d055) - but would that be overkill? 🤔 

It might actually be a clever code scanning item? Make warnings if anything in the workspace varies only in casing

**Comment by skaldarnar** [comment]
>  but would that be overkill? 🤔
✅ yes, it would be. Unless we reuse existing tooling for it. 

I'm closing this as _won't fix_ now, but please re-open if there any new findings on concrete desire to work on this.
