### ISSUE TITLE
update build.gradle "compiling with a JDK newer than" warning for jdk11

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#3975]
We had [a talk about jdk versions](https://discord.com/channels/270264625419911192/696830442065625118/713123216071196752) today and I think we agreed it is fine to use jdk 11 for development.

Note this is _different_ than saying Terasology engine will start using Java 11 _language_ features; for the time being source compatibility remains at Java 8. This is just so the build environment won't scold people for using the current LTS release of OpenJDK.

it would have been faster to write a pull request than type up this issue if not for two things:

1. it needs documenting anyway ;)
2. the way it's currently written, it checks to see if the value is _exactly_ `JavaVersion.VERSION_1_8`, and we want the new check to allow anything 8 – 11, and that would have taken me several moments to look up.

**Comment by skaldarnar** [comment]
This came up several times on Discord by now, thus making a comment here to bump the importance 🤓
