### ISSUE TITLE
Define code style for sourcecode

### ISSUE THREAD

**Issue by ahoehma** [MovingBlocks/Terasology#398]
In addition to the https://github.com/MovingBlocks/Terasology/wiki/Checkstyle definition, the project should define an common source code style guide. 

In eclipse an code formatter could be used to keep the code always clean. I don't know if idea supports such a feature?!

Starting from the default java code style i would prefer such an environment:

 - always spaces, no tabs, ident = 2, tab == 2 space
 - max line length increase from 80 to 120 (widescreen monitors *g*)  - also for comments
 - automatic cleanup import statements, remove unused imports
 - use "final" where possible
 - remove trailing whitespaces
 - correct indentation
 - sort class members (methods, constructors, no fields)
 - add missing @Override and @Deprecated

My experience: with such a style guide it's easy to keep the code clean

For eclipse i can provide a configuration file

**Comment by Cervator** [comment]
Closing this from age, partial completion, and replacement elsewhere
