### ISSUE TITLE
Crash on viewing module details for a module with an absent optional dependency

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3981]
### What you were trying to do

Test to see if the Health module would exhibit any weirdness with the ModuleTestingEnvironment module not present (optional dependency)

### What actually happened

Game crashed when I tried to get module details (in the advanced game start screen) for Health (and I suspect any other combination of an optional dependency for a module not present)

### How to reproduce

* Have a workspace with an optional dependency, such as Health on the MTE (`groovyw module recurse CoreSampleGameplay`)
* Delete the MTE from your workspace
* Run the game and select Health via the Module Details button

Expecting a simple bit of hardening in the related display logic will be enough to bypass the crash: if a modue has an optional dependency that's not present just mark it as not present or don't allow the user to retrieve details on it.

### Log details and game version

```
19:34:49.736 [pool-3-thread-1] INFO  o.t.e.module.ModuleListDownloader - Retrieved 184 entries
19:35:05.276 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.moduleDetailsScreen.ModuleDetailsScreen$11.draw(ModuleDetailsScreen.java:321)
	at org.terasology.rendering.nui.layers.mainMenu.moduleDetailsScreen.ModuleDetailsScreen$11.draw(ModuleDetailsScreen.java:306)
	at org.terasology.rendering.nui.itemRendering.AbstractItemRenderer.draw(AbstractItemRenderer.java:30)
```

**Comment by skaldarnar** [comment]
We even do a null check in that method, but ignore it two lines later 🙄 will provide a quick fix, without extensive testing though...
