### ISSUE TITLE
Kill cheat causes OpenALException

### ISSUE THREAD

**Issue by cvennel** [MovingBlocks/Terasology#3984]
### What you were trying to do
For testing another PR, I was trying to trigger player death through 'kill' cheat command to check re-spawns. 
### What actually happened
When clicking re-spawn button after using kill command, game shutdown with OpenALException. Afterwards cannot open game file without surrounding updateListener in OpenALManager.java with a try-catch which defeats the purpose of throwing the OpenALException
### How to reproduce
* start a game
* use 'hjump' cheat to jump to death
* click respawn (should work just fine)
* use 'kill' cheat to cause player death
* click respawn (game crashes)

### Log details and game version

On develop branch, commit: e64d63320ff067d14e66a90621acc6882a26b22f

> 11:02:18.363 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] High-jump mode activated
11:02:25.019 [main] INFO  o.t.logic.characters.CharacterSystem - engine:physicalDamage is missing a readable DisplayName
11:02:25.049 [main] INFO  o.t.logic.characters.CharacterSystem - engine:physicalDamage is missing a readable DisplayName
11:02:26.760 [main] WARN  o.t.logic.players.PlayerFactory - entity org.terasology.entitySystem.entity.EntityBuilder@3e0e0ba7 does not have any known extent specification - using default
11:02:29.228 [main] INFO  o.t.logic.characters.CharacterSystem - engine:directDamage is missing a readable DisplayName
11:02:29.228 [main] INFO  o.t.logic.characters.CharacterSystem - engine:directDamage is missing a readable DisplayName
11:02:30.677 [main] WARN  o.t.logic.players.PlayerFactory - entity org.terasology.entitySystem.entity.EntityBuilder@12a9e864 does not have any known extent specification - using default
11:02:30.687 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
org.terasology.audio.openAL.OpenALException: OpenAL Error (40963) at Setting listener orientation - Invalid Value
        at org.terasology.audio.openAL.OpenALManager.updateListener(OpenALManager.java:284)
        at org.terasology.audio.openAL.OpenALManager.updateListener(OpenALManager.java:266)
        at org.terasology.audio.system.AudioSystem.update(AudioSystem.java:113)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:462)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:425)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:401)
        at org.terasology.engine.Terasology.main(Terasology.java:162)
11:02:30.687 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
11:02:30.829 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
11:02:30.863 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
11:02:30.894 [Saving-0] ERROR o.t.p.t.TypeHandlerLibrary - Unsupported field: 'Health:Regen.regenEndTime'
11:02:30.909 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Player51252
11:02:30.915 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Player51252" has left the game
11:02:30.915 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
11:02:31.021 [Engine-Task-Pool] INFO  o.t.rendering.opengl.ScreenGrabber - Screenshot saved to saves\Game 2\previews\1.jpg!
11:02:31.591 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
11:02:31.636 [Thread-5] INFO  o.t.e.s.rpc.DiscordRPCSubSystem - Discord RPC >> Disconnected!

**Comment by pollend** [comment]
the value is already nan when it was passed through JOMlutil. It could be but its probably unlikely to be the case.

**Comment by skaldarnar** [comment]
In `AudioSystem::update` we receive the view rotation Quat4f from the local player `localPlayer.getViewRotation()` which is all-zero 🧐 

In `OpenALManager::updateListener` we apply this all-zero quaternion as rotation:
```java
org.joml.Vector3f dir = JomlUtil.from(Direction.FORWARD.getVector3f())
                .rotate(orientation);
```

I don't know where this is coming from (yet), nor whether this is related to JOML at all. However, I saw a couple of places where we potentially could already switch to full-JOML methods, maybe that helps...

**Comment by cvennel** [comment]
It looks like `Direction.FORWARD.getVector3f()` returns (0.0, 0.0, 1.0) 
Then JomlUtil.from() on the result returns `(NaN       NaN       NaN)`

**Comment by pollend** [comment]
that just means a lot of the surrounding methods have changed. enough where you can start swapping stuff over.
