### ISSUE TITLE
modules.txt parse errors should mention the error is in module.txt

### ISSUE THREAD

**Issue by ktksan** [MovingBlocks/Terasology#4018]
Well my module.txt file had an error but instead of mentioning that the error was in module.txt the error showed:

Build file 'E:\terasology\modules\ClimateConditions\build.gradle' line: 18

An exception occurred applying plugin request [id: 'terasology-module']
Failed to apply plugin [id 'terasology-module']
expecting '}' or ',' but got current char '<' with an int value of 60

While my file did not have any '<':
My build.gradle file looked like:

plugins {
    id("terasology-module")
}

**Comment by keturn** [comment]
I expect implementation for this to be straightforward. The spot that reads `module.txt` during build time is this:

https://github.com/MovingBlocks/Terasology/blob/c5a2d2d95e5a740ad0c818d6945dadc6b6ff8895/buildSrc/src/main/kotlin/terasology-module.gradle.kts#L56-L57

at a minimum, a try/catch around that that does a `logger.error` with a message pointing to the module.txt should be sufficient. (and then I guess it should re-throw the exception? there's maybe a little research to be done here on best practices on error reporting in Gradle builds.)

The module.txt handling was hit the hardest by the Groovy to Kotlin translation, I think. I don't expect it to perform any worse than it did while it was in Groovy, but JSON and Groovy are very loose about which types are held by maps and arrays where Kotlin is very strict, so the code looks a bit frightful with its unchecked cast warnings and `!!` operators.

So there's more clean-up in that area a person _could_ do if they were so inclined, but it's not necessary to complete this issue.

**Comment by keturn** [comment]
I'm mucking around with reading module dependencies right now, so I'll pick this up.
