### ISSUE TITLE
unable to resolve world generator for CoreSampleGameplay

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4024]
### What you were trying to do

start a terasology game.

### What actually happened

new game failed with 

> Unable to resolve world generator '' - not found

### How to reproduce

* groovyw module recurse CoreSampleGameplay
* [IDEA] reimport gradle projects
* [IDEA] rebuild project
* [IDEA] run _Terasology PC_
* Singleplayer
* _Core Gameplay_ is shown as the Gameplay Template. :+1: 
* Start Playing
* :boom: 

### Log details and game version

[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/4718740/Terasology-init.log)
[Terasology-Game_1.log](https://github.com/MovingBlocks/Terasology/files/4718741/Terasology-Game_1.log)

some debugger investigation shows that the WorldInfo in InitialiseWorld.step contains only empty strings.

**Comment by keturn** [comment]
note at least, in this scenario, it _does_ recognize some world generators exist:

o.t.e.m.l.InitialiseWorld - Unable to load world generator . Available world generators: [
* Flat (CoreWorlds:flat), 
* Height Map (CoreWorlds:heightMap), 
* Perlin (CoreWorlds:facetedperlin), 
* Simplex (CoreWorlds:facetedsimplex), 
* dummy (ModuleTestingEnvironment:dummy)
]

just none of them are the empty string.

**Comment by DarkWeird** [comment]
It can be related on active modules(sometimes it is not work, like no module enabled. You must reenable one module for reenable all)
Check activeModules  on InitialiseWorld.step
