### ISSUE TITLE
Super easy: Update `docs/modules.md` to match current lineup, add tutorial section

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4040]
We've recently overhauled the module lineup quite a bit, and the file documenting the modules here in this repo is pretty out of date. But this makes for a real easy good first issue!

Compare https://github.com/MovingBlocks/Terasology/blob/develop/docs/Modules.md with the list at https://github.com/Terasology/Index/blob/master/distros/omega/gradle.properties#L2 and make sure it only contains what's in that omega line.

A few modules have been renamed, often with "Tutorial" in the name. Look at https://github.com/Terasology?q=tutorial for the full list. We no longer ship tutorial modules with the game (they're for developers, not players), so make a _new section_ in `Modules.md` to outline those.

So if there's an entry in the prop file you don't see, try to find it. If you go to the URL for the old name odds are GitHub will handily redirect you to the renamed version of the module. If there's an entry in the `module.md` you likewise can't spot try again to find it. Ask questions here or on Discord if in doubt!

If modules have been removed from the lineup yet are not tutorials, are they still worthwhile highlighting? Maybe in a new section of secondary or retired modules? Are any apparently temporarily taken out pending fixes?

Bonus: try out some of the tutorials and see if they still work. If not then submit issues to their repos and/or try to fix it yourself.

Bonus2: Take one or more updated screenies

**Comment by Owl-A** [comment]
I would like to work on this issue.

**Comment by Cervator** [comment]
Hi @Owl-A - please go for it!

And this explains the friend request on Discord, okay - had no idea when I saw it what it was about, so I skipped it. You don't generally need anybody _specific_ on Discord, just join the server and ask a question in an open channel then the first person able will get to it :-)

**Comment by Cervator** [comment]
Closing as completed by #4173 - thanks a bunch @devindoherty !
