### ISSUE TITLE
no ui no invetrory in the latest version and no selecting?!

### ISSUE THREAD

**Issue by Makaki472** [MovingBlocks/Terasology#4044]
### What you were trying to do
play the game 
### What actually happened
there was no ui
### How to reproduce
idk
* Step 1idk
* Step 2idk
* Step 3idk

**Comment by skaldarnar** [comment]
**Closing this as no further information was provided.**

I suspect this was either starting the bare-bone engine demo gameplay, or hiding the UI via `h` key by accident. Inventory and UI was showing up for all game modes during the latest play-test.
