### ISSUE TITLE
BlockRegion intersection tests incorrect.

### ISSUE THREAD

**Issue by 4Denthusiast** [MovingBlocks/Terasology#4086]
All of the BlockRegion.intersects* methods with floating-point arguments and the BlockRegion.containsPoint(Vector3fc) method are incorrect. The actual position of the corner of a BlockRegio is not (region.aabb.minX, region.aabb.minY, region.aabb.minZ) but (region.aabb.minX-0.5, region.aabb.minY-0.5, region.aabb.minZ-0.5), as points in the world with integer coordinates are actually at the centres of the blocks with the corresponding integer coordinates, not the corner. This means that the region covered by the BlockRegion is not the same as the region covered by its AABB.

Currently none of these BlockRegion methods seem to be actually used, so this does not manifest as an actual bug. Ideally it shouldn't be left in this state though, and the methods should be either corrected or removed.

**Comment by pollend** [comment]
@4Denthusiast I think I have a strong clue what you are trying to change. could you create a PR with these changes?

**Comment by sarthakhanda** [comment]
please allow me to work on this issue

**Comment by 4Denthusiast** [comment]
@sarthakhanda Go ahead. You don't need to ask permission to try to fix something, just submit a PR for it. If you need any more help, you can ask on our Discord server: https://discord.gg/4uKbB8J.
