### ISSUE TITLE
Disable Identity Service Login

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4104]
We've got an increasing amount of questions and reports regarding the **Identity Service Login** from players trying out the game. While the backing service (https://github.com/MovingBlocks/terasology-key-server) is in maintenance mode and not working correctly, we should disable the login option from the UI to not confuse players.

ℹ️   Fixing the Identity Service itself is a different issue!

I believe this is the part of the UI that renders information for the Identity Service:
https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/resources/assets/ui/menu/playerMenuScreen.ui#L64-L104

Related forums post: https://forum.terasology.org/threads/unable-to-login-to-terasology-multiplayer.2314/

**Comment by sarthakhanda** [comment]
please allow me to work on this issue

**Comment by skaldarnar** [comment]
@sarthakhanda your welcome to do so!

Fork the project, set up your [development environment](https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup) and start coding 🤓 Hop on your Discord in case you have any questions.
