### ISSUE TITLE
Block collision area not updating with CeilingSupportedFamily

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4115]
The Ceiling Block Family introduced by https://github.com/MovingBlocks/Terasology/pull/3978 works nicely, besides that the block collision/targeting area is not updated with the upside-down block.

![image](https://user-images.githubusercontent.com/1448874/89451935-36d3c500-d75d-11ea-8367-7da8f26e4a51.png)

For instance, the screenshot above shows that the bottom part of the block is targeted (where the `engine:halfBlock` would usually be), which makes it impossible to place another plank slab upside-down next to the other.

I tested this with a simple `plankSlab.block` like this:
```json
{
  "basedOn": "CoreAssets:Plank",
  "family": "ceilingSupportingHorizontal",
  "shape": "engine:halfBlock"
}
```

**Comment by pollend** [comment]
duplicate issue: https://github.com/MovingBlocks/Terasology/issues/4403
