### ISSUE TITLE
[nightly 1102] Game crash when trying to play with Josharias Survival

### ISSUE THREAD

**Issue by KydZombie** [MovingBlocks/Terasology#4181]
### What you were trying to do
Trying to load into/create a Josharias Survival world
### What actually happened
Game crash with "NoSuchMethodError" relating to customOreGen
### How to reproduce

1. Download Nightly Build 1102
2. Try to load into or create a new Josharias Survival world

### Log details and game version
https://drive.google.com/uc?id=14WiHJAOM79VDOxVQqBQ0hNafay5I7bOT&export=download
Nightly build 1102
### Computer details
i5-8600k
GTX 1660ti
16GB ram
Windows 10 Pro

**Comment by harunamiya** [comment]
I have same problem when i try to play on nightly build 1102, and create survival on josharias survival world it crashes, 
it says nosuchmethoderror


https://drive.google.com/uc?id=1zBoL1TrkVYLe9B4fnpf_9Vwc2jC7-iqg&export=download

my computer specs are
windows 8.1
amd fx 6300  (graphics card )
six core prosessor 3,50 ghz
16 gb ram
64 bits os

**Comment by jdrueckert** [comment]
@Gizmordo @harunamiya Thanks for reporting this :+1: 
Should be fixed with Nightly 1103, feel free to check :slightly_smiling_face:
