### ISSUE TITLE
feat(JOML): SkeletalMeshComponent: scale renders new gltf models invisible

### ISSUE THREAD

**Issue by casals** [MovingBlocks/Terasology#4197]
# What you were trying to do

Chore: updating modules to work with new `glTF` assets

### What actually happened

We noticed that when a creature prefab uses both a `glTF` model and the `scale` property from `SkeletalMeshComponent`, it becomes invisible in the game. Might be worth noting that `scale` is an instance of `org.terasology.math.geom.Vector3f`, so there might be a link with the latest JOML changes.

First observed at MR - PR #101 
Original issue [here](https://github.com/Terasology/MetalRenegades/issues/102#issue-718909887)

### How to reproduce

* Step 1: Modify one of the citizen prefabs in MR by including the `scale` property in its component
* Step 2: Spawn the citizen in-game and notice that it's invisible

**Comment by skaldarnar** [comment]
@casals @jdrueckert @pollend was this fixed by #4198 ?

**Comment by jdrueckert** [comment]
From #4198:
> This is a quick fix. We need to change all the methods in OpenGLSkeletalMesh using Vector3f, which also involves dealing with SkeletalMeshData.
