### ISSUE TITLE
JOML: Question about `Region3i` >>> `BlockRegion`

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4200]
I was looking at `Region3i`/`BlockRegion` (JOML) tonight and I'm wondering how we gonna approach this. I started in PolyWorlds world generator (for some completely unrelated reason) and stumbled upon `teramath.Region3i::createFromCenterExtents(center, extents)`.

So I wanted to add a similar way to create a `BlockRegion`. Instead of adding more and more constructors or convenience methods I went for a utility class `BlockRegions` (plural form). The implementation for the creator method was simple enough (even simpler than with TeraMath):

```java
public static BlockRegion fromCenterAndExtents(Vector3ic center, Vector3ic extents) {
    Vector3ic min = center.sub(extents, new Vector3i());
    Vector3ic max = center.add(extents, new Vector3i());
    return new BlockRegion(min, max);
}
```

An equivalent implementation is the following:
```java
return new BlockRegion(center, center).addExtents(extents.x(), extents.y(), extents.z());
// when adding BlockRegion::addExtents(Vector3ic extents) this becomes even simpler
return new BlockRegion(center, center).addExtents(extents);
```

This, in turn, made me wonder whether we really need these helper methods, or whether that replacement is simple enough. Or whether we need a different kind of convenience methods, to be able to write something like
```java
BlockRegions.point(center).addExtents(extents);
// ... instead of ...
BlockRegions.fromCenterAndExtents(center, extents);
```

**Comment by pollend** [comment]
maybe BlockRegion could also just accept a single value.

```
new BlockRegion(center).addExtents(extent);
```

**Comment by skaldarnar** [comment]
Yep, I agree that the builder pattern allows for readable code here. I do, however, prefer the static methods with descriptive names over overloaded constructors. Doesn't matter too much though, we agree on the builder-like mutations 👍 

One thing I'm particularly worried about for BlockRegion is that point-like AABBs are **invalid** in JOML - we need to be careful that the semantics work out in the, e.g., for `containsBlock` 

https://github.com/MovingBlocks/Terasology/blob/a829df4c8802441c66078b00cb1f3f9f9ef4b6ad/engine/src/main/java/org/terasology/world/block/BlockRegion.java#L398-L406

I would assume that 

```java
assertTrue(new BlockRegion(center).containsBlock(center))
```

**Comment by pollend** [comment]
that's also a really good point. I think the default behaviour for new BlockRegion(p,p) is also same.
so `new BlockRegion(center).containsBlock(center)` is the same as `new BlockRegion(center,center).containsBlock(center)`

**Comment by skaldarnar** [comment]
We had a chat on Discord on this topic and agree on the following:

- :heavy_check_mark: we agree on using the builder-like methods for mutation to keep things a bit more explicit. instead of having something like `Vectors.copyAndScale(v, 3.14)` we prefer to use `new Vector(v).scale(3.14)`
- :heavy_check_mark: we go for constructors by default, and introduce related helper classes if necessary. when reaching more than 3 or 4 constructor variants we should considered static helper classes (without setting a hard cut anywhere…). the static helper methods should live in an accompanying object following the plural naming scheme (e.g. `BlockRegions` containing helper methods for `BlockRegion`).
