### ISSUE TITLE
"WARNING: Compiling with a JDK not 8 nor 11" warning should print more info about what JDK it's using

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4209]
Someone new to the project was trying to build it from source and they got the `Compiling with a JDK not 8 nor 11` warning, as seen in this log: https://pastebin.com/na70rGh4

but when they do `java -version` at the command line, it reports OpenJDK 11.0.8, which _is_ a JDK 11.

That warning could help by printing more details about which JDK gradle is running under, as it may be using some configuration that has it using a different thing that what the shell resolves `java` as on the command line.

Details it would be useful to have include:

* JDK version number
* other JDK build info (i.e. the part that shows if it's from AdoptOpenJDK or built by another distro)
* the absolute path to the executable it's using

The code involved is here:

https://github.com/MovingBlocks/Terasology/blob/5d87630d6331f240585e9353c7c3a739c7a172ef/build.gradle#L51-L55

**Comment by jSAMUELj** [comment]
Hello! .. Can i work on this?
