### ISSUE TITLE
game tasks should include facade's dependencies on the runtime classpath

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4238]
### What you were trying to do

Add a dependency to facades/PC, i.e. `picocli` in #4157.

### What actually happened

Gradle resolves the dependency and it compiles correctly, but when I go to start the game with `gradlew game` (`:facades:PC:game`), it cannot find the dependency in its classpath.

### How to reproduce

see e.g. the current state of #4157's branch

### Implementation thoughts

There is a lot of duplication between the various JavaExec tasks in facades/PC's gradle file. To make it more maintainable and improve confidence that when we fix this issue, we fix it for _all_ those tasks, it would be helpful to refactor or change the implementation to not require so many duplicated lines in them.

**Comment by DarkWeird** [comment]
@keturn 
we don't have to add modules to the classpath, right?

**Comment by keturn** [comment]
> we don't have to add modules to the classpath, right?

From what I recall of our conversations about this (I can't find an exact line about it at the moment), I believe that is true. Gestalt's module loader does some work independent of the classpath.

However, since we want the `modules/` sub-projects to be built before the facade is run, they're dependencies of the facade project, so gradle's natural approach to java builds _will_ put them on the classpath.

I think one of the things I was trying to find out with the questions I posed in #4157 is

* Must we _exclude_ modules from the classpath?
