### ISSUE TITLE
terasologe crashes when all extensions turned on

### ISSUE THREAD

**Issue by philippelevis** [MovingBlocks/Terasology#4309]
### What you were trying to do
i was trying to turn on every extension

### What actually happened
it crashed
### How to reproduce

* Step 1 start the game
* Step 2create new world and in advacnced game setup turn on every single extension
* Step 3press the "create world" button

### Log details and game version
latest release on 10th of december 2020: release 38

log:
19:53:32.923 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (10721), capping to 1000
19:53:33.023 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
19:53:33.040 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: engine:4.1.0
19:53:33.040 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreAssets:2.2.0
19:53:33.041 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ModuleTestingEnvironment:0.2.3
19:53:33.041 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Inventory:1.4.0
19:53:33.042 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BasicCrafting:1.0.0
19:53:33.045 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BiomesAPI:4.0.1
19:53:33.045 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreWorlds:1.2.1
19:53:33.046 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Health:1.2.0
19:53:33.046 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Hunger:1.1.0
19:53:33.047 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AlterationEffects:1.1.0
19:53:33.047 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Drops:1.1.0
19:53:33.048 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Explosives:1.0.1
19:53:33.048 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Furnishings:1.1.1
19:53:33.048 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreAdvancedAssets:1.2.0
19:53:33.049 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: StructureTemplates:1.0.0
19:53:33.049 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: FlowingLiquids:1.3.0
19:53:33.050 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Fluid:2.0.0
19:53:33.050 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Thirst:1.0.0
19:53:33.050 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ClimateConditions:1.0.1
19:53:33.052 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AnotherWorld:1.0.0
19:53:33.053 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Genome:1.0.0
19:53:33.054 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ItemRendering:1.1.0
19:53:33.055 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CustomOreGen:1.0.0
19:53:33.056 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: OreGeneration:2.0.0
19:53:33.056 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Workstation:1.1.0
19:53:33.056 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: SubstanceMatters:2.0.0
19:53:33.057 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: SimpleFarming:2.1.0
19:53:33.057 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: EdibleFlora:1.0.0
19:53:33.058 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdditionalFruits:1.0.0
19:53:33.058 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: SegmentedPaths:1.0.0
19:53:33.058 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ItemPipes:1.0.0
19:53:33.059 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdditionalItemPipes:1.0.0
19:53:33.059 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Rails:1.0.0
19:53:33.060 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BlockNetwork:1.0.0
19:53:33.060 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MobileBlocks:1.0.0
19:53:33.061 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ModularComputers:1.0.0
19:53:33.061 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Signalling:1.0.0
19:53:33.061 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdditionalRails:1.0.0
19:53:33.062 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdditionalVegetables:1.0.0
19:53:33.062 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdvancedRails:1.0.0
19:53:33.063 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Projectile:1.1.1
19:53:33.063 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WorldlyTooltipAPI:1.0.0
19:53:33.064 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AdventureAssets:1.0.0
19:53:33.064 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: GrowingFlora:1.0.0
19:53:33.065 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: PlantPack:1.1.2
19:53:33.065 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: StructuralResources:2.2.0
19:53:33.065 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AnotherWorldPlants:1.0.0
19:53:33.066 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Durability:1.1.0
19:53:33.066 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: InGameHelpAPI:1.0.0
19:53:33.067 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MultiBlock:1.1.0
19:53:33.067 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MarkovChains:1.5.1
19:53:33.067 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: NameGenerator:1.0.0
19:53:33.068 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Potions:1.3.0
19:53:33.068 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WorkstationCrafting:2.0.0
19:53:33.069 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Alchemy:1.1.0
19:53:33.069 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: AlchemyPlantGenerator:1.0.0
19:53:33.070 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Anatomy:1.0.0
19:53:33.070 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: SoundyGenetics:1.0.0
19:53:33.070 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Apiculture:1.0.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Pathfinding:1.0.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Behaviors:1.1.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BlockDetector:1.3.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: BlockPicker:1.1.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Books:1.1.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Breathing:1.0.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CakeLie:1.0.0
19:53:33.071 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Caves:1.1.0
19:53:33.072 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ChangingBlocks:1.0.1
19:53:33.075 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CheatsForAll:1.0.0
19:53:33.075 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ChiselBlocks:1.0.0
19:53:33.075 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MusicDirector:1.0.0
19:53:33.075 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ChrisVolume1OST:1.0.0
19:53:33.075 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ChrisVolume2OST:1.0.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CommonWorld:1.0.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Fences:1.0.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Cities:1.1.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Climbables:1.0.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Sensors:1.0.0
19:53:33.085 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CombatSystem:1.0.0
19:53:33.087 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Compass:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ComputerMonitors:1.0.1
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Cooking:1.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreRendering:1.0.2
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreSampleGameplay:4.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: DamagingBlocks:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Dialogs:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Economy:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Minimap:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: DynamicCities:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: EdibleSubstance:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: InGameHelp:1.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: PotentialEnergyDevices:1.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Machines:1.2.1
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WildAnimals:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ManualLabor:1.3.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: PhysicalStats:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Equipment:1.2.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Smithing:1.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: EquipmentSmithing:1.1.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: EventualSkills:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Exoplanet:1.0.0
19:53:33.088 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: FlexiblePathfinding:1.0.0
19:53:33.090 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: FunnyBlocks:1.0.0
19:53:33.090 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: GenericRocks:1.0.0
19:53:33.090 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Mawgooey:1.0.0
19:53:33.090 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: GooeyDefence:1.1.1
19:53:33.090 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: GooeysQuests:1.1.1
19:53:33.091 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Valentines:1.0.0
19:53:33.091 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WorldlyTooltip:1.2.0
19:53:33.091 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: GooKeeper:1.1.0
19:53:33.091 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: HjerlHede:1.1.0
19:53:33.091 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: HumanoidCharacters:1.0.0
19:53:33.101 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Inferno:1.0.0
19:53:33.101 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: IRLCorp:1.1.3
19:53:33.101 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ManualLaborEventualSkills:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WorkstationInGameHelp:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: JoshariasSurvival:1.1.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Journal:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Kallisti:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: KComputers:1.0.1
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ParadIce:0.1.0-SNAPSHOT
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Lakes:2.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: LegacyMusic:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: LightAndShadowResources:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: StaticCities:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Tasks:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: LightAndShadow:1.1.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: PolyWorld:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Lost:1.1.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Oreons:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MasterOfOreon:1.1.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Maze:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MedievalCities:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MetalRenegades:1.1.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Minerals:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MineSweeper:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MoreLights:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Spawning:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Portals:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Sample:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Scenario:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Seasons:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ShatteredPlanes:1.0.0
19:53:33.102 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Soils:1.0.0
19:53:33.103 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: SurfaceFacets:1.0.0
19:53:33.103 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WeatherManager:1.0.0
19:53:33.103 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WildAnimalsGenome:1.0.0
19:54:02.895 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IncompatibleClassChangeError: org.terasology.caves.CaveFacetProvider and org.terasology.caves.CaveFacetProvider$CaveFacetProviderConfiguration disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.isTopLevelClass(Unknown Source)
	at java.base/java.lang.Class.getSimpleBinaryName(Unknown Source)
	at java.base/java.lang.Class.getSimpleName0(Unknown Source)
	at java.base/java.lang.Class.getSimpleName(Unknown Source)
	at org.terasology.entitySystem.metadata.MetadataUtil.getComponentClassName(MetadataUtil.java:30)
	at org.terasology.engine.bootstrap.EntitySystemSetupUtil.registerComponents(EntitySystemSetupUtil.java:174)
	at org.terasology.engine.bootstrap.EntitySystemSetupUtil.addEntityManagementRelatedClasses(EntitySystemSetupUtil.java:152)
	at org.terasology.engine.modes.loadProcesses.InitialiseEntitySystem.step(InitialiseEntitySystem.java:40)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:237)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:469)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:432)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:408)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
19:54:02.897 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down 
### Computer details
operating system Linux Mint 19.3 Cinnamon
cinnamon version 4.4.8
linux core 5.4.0-48-generic
CPU AMD Athlon(tm) 64 X2 Dual Core Processor 5200+ × 2
RAM 7.8 gb
Hard drives 479.9 ГБ
GPU NVIDIA Corporation GF119 [GeForce GT 610]

**Comment by jdrueckert** [comment]
Hi @philippelevis :wave: 
Thank you very much for opening this issue.
Crashes when turning on _all_ modules are actually expected as not all modules are compatible.

Theoretically, the AGS (advanced game setup) should mark modules that are incompatible with already activated ones... Can you please confirm, that you didn't see any kind of indication that a module is incompatible (e.g. it being colored red or "greyed out" or something)?

If that's indeed the case, we'll try to reproduce the situation, check whether there's information missing and discuss how to improve the usability of the AGS with respect to displaying incompatibilities between modules :+1:

**Comment by philippelevis** [comment]
Yes, there were some red indicators, but i didnt find out if i can turn
them on.
also a question: can i use the source code to create something?
чт, 10 дек. 2020 г., 8:54 ПП jdrueckert <notifications@github.com>:

**Comment by jdrueckert** [comment]
Okay, we'll try to see if we can improve on the AGS usability. I will close this issue here as Terasology is expected to crash when all modules are activated, but I also created a new issue to track the effort of improving AGS usability to make the effects, risks and incompatibilities a bit clearer: #4312 

As for the source code: Yes, Terasology is license-wise completely free to use. The engine code is present in this repository, the modules can be found in the following org: https://github.com/Terasology
We would like to encourage you to instead of taking the code and doing something on your own with it, to join our community over at [Discord](https://discord.gg/terasology) and contribute as part of our community to improve Terasology 🙂 
You can also have a look at [Gooey's Tour](https://terasology.org/AdventureSite/) to find resources to start digging in.
