### ISSUE TITLE
dev workspace: modules on the java classpath breaks the sandbox

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4375]
Despite my best efforts to find things out _before_ merging build changes (#4343), there are some things that are only coming out in the aftermath.

Excerpts from a recent discussion in [#gestalt](https://discord.com/channels/270264625419911192/714313228271747152/795526922490609676):

>  If the modules are in the main classloader, they're not really modules at all at that point. Just code included in terasology.
[…]
> So for actual release use, module code (and resources) are not on the base classloader, except the engine module or any other built-in module.
> Ideally development runs would reflect this
> partially because it would help detect security related issues
> and partially because some subtle behavior differences from having a slurry of module code in the base classloader

I think two things come from this:

1. Empirically confirm how broken things are. This might be as straightforward as: edit a module so it imports something it shouldn't, run `gradlew game` and _Run TerasologyPC_ with that as a local subproject, see if it succeeds at importing that thing (and maybe invoking a method on it or something).
    I think there _may_ be a possibility that modules still get loaded by the sandboxed loader despite the fact that they would be available to the default loader if it asked for them directly, but that needs research to find out if it's true.
2. Decide if we're willing to compromise on this module security _when running in a dev workspace._ (If there's a vulnerability, it probably applies to all subprojects present in `/modules/` _and_ all their dependencies, whether present as subprojects or fetched as artifacts.)

-- 

keturn's understanding of how this interacts with the security model:

The thing that prevents Terasology Modules from importing code that would give them capabilities they're not supposed to have is the classloader used; when loading the module's class, it handles the requests for the dependencies of that class, and may deny the requests that are not approved.

If the module's class is loaded by the classloader that loads the trusted code (for engine & facade), no such restrictions are applied. If the module's class is on the classpath, it _may_ be loaded by that classloader.

**Comment by keturn** [comment]
In case it's been lost in all the noise: The thing we _gain_ from this compromise is reliable dependency resolution and fast rebuilds for modules while working with them in development.

Gradle and IntelliJ have a lot of optimizations designed around rebuilding dependent parts after changes. I believe the closer we stay to the idea of "a running facade depends on the classes/resources compiled by the module, same as any other java application dependency," the simpler the configuration will be and the more reliably they'll work.

Personally, I would say as long as we aren't compromising the security of our target audience, I'm okay making this compromise in my dev environment when building things from source.

I say that because for pretty much every other project I've worked on, building from source **is** executing arbitrary code. This _includes_ `MovingBlocks/Terasology` (engine, facade, etc). I'm willing to trade away this security property of Terasology modules because it never really occurred to me that it might exist in the first place (and then it took considerable discussion and research for me to believe it exists). And, for the most part, the people with commit access to the modules I'm building also have commit access to engine.

If you plan to be building (or depending on) modules sourced from repositories you do _not_ extend that level of trust to, that's when you'd need to veto having this insecure-mode be the default, and we'd need to come up with other options.

**Comment by skaldarnar** [comment]
What do I need to do as a developer to check on the class-loading aspects after I did some changes (for which I suspect they might cause issues)? How do I build an omega-like zip for my current workspace to test the end-user view of things?

I'm fine with having a less secure dev workspace, as long as we keep the restrictions in place for the shipped game, and as long as we have means to (easily?) detect if some module will be acting up in a release.

**Comment by keturn** [comment]
Cerv mentioned on Discord:

> The [Sample module](https://github.com/Terasology/Sample) actually ships with code meant to test breaking the sandbox, although it has been a while since I've tested if it crashes things appropriately 😁  there are two "crashgameblock" blocks you can place then `e` interact with and they'll trigger code that attempts to do naughty things

That sounds like a good way for us to check the current sandboxness of modules. I think we should test it as
* source subproject vs gradle-filled-dependency-of-other-module
* `gradlew game` vs IntelliJ Run

**Comment by Cervator** [comment]
That could be a simple MTE test as well. Even on simply placing a block that'll trigger an event handler that simply does `System.out.println("Sandbox won't let me do this!");` - assuming we can catch the subsequent crash and count that as a failed test.

**Comment by keturn** [comment]
> as long as we have means to (easily?) detect if some module will be acting up in a release.

Yeah, that's the biggest question right now. I'm okay if it's not part of the tightest feedback loop, because as I understand it you need to make fairly big changes to your code to run in to that (e.g. adding a different dependency), but definitely the sooner the better.

> How do I build an omega-like zip for my current workspace to test the end-user view of things?

I don't think we have a good answer for this at the moment. As I understand it, the bundle-of-modules distributions are built by [Index/distros](https://github.com/Terasology/Index/blob/7ade39080a194834d0cb97bb3877bf8d1a2d77d1/distros/distros.gradle#L27)...

there's a multitude of things we potentially _could_ do to make that easier to do from the dev workspace, but before we get lost in the possibilities of that (in a ticket of its own), I want to check: is there some gradle or groovyw command to do that _right now_ that I've overlooked?

**Comment by Cervator** [comment]
`gradlew distPCZip` was my go to for testing a local Omega workspace -> get zip file -> extract somewhere else -> test.

Or stop before the zip step and test right out of the build dir. Not sure if it works at the moment, haven't tried it for a while.

**Comment by keturn** [comment]
ah, #4347 is the follow-up to #4343 where I'm trying to figure out what to do with those PC facade dist tasks, and I was just coming to the conclusion that it's okay (for the moment) if the behavior of those dist tasks does something weird when there are modules present because the real dist for publication isn't made that way. 😅 

at the moment, that's not guaranteed to get you a zip that includes your module and all its (transitive) dependencies and keeps them off the classpath.

(that might have worked before #4343, except when it didn't due to #4014.)

**Comment by keturn** [comment]
I have lots of lingering questions about our sandbox environment and gestalt-module and classloaders in general, but I believe what we want to do here is to provide a JavaExec option that works like the previous configuration: keep modules off the classpath.

I think that much is straightforward: we set up a Configuration that doesn't have that dependency on `:modules`. (Now I have better appreciation of why previous iterations of this build configuration kept those dependencies on a separate Configuration.)

The other half of the problem is making sure all the module-dependencies are someplace the module loader can find them. I don't think RemoteModuleGatherer, with the way it hooks in to DependencyResolutionListener, is an approach I want to keep. We've seen it doesn't work for all our use cases. And though DependencyResolutionListener _is_ a public Gradle API, it feels like meddling in gradle internals in a way that's not in line with gradle's design as a dependency resolver and build system.

The thing closest to the expected behavior would be to have all the dependencies end up as jar files in `/modules/`.

I'm interested in whether we can give the module loader a custom search path, because I'm a little worried about getting multiple versions of things left in `/modules/` across multiple runs, but I think that's a detail we can work out later.

Long term, because I have an "in for a penny, in for a pound" attitude when it comes to gradle, I think the answer involves changing the module build config so they mark themselves as some kind of "terasology-module" _variant_ and we teach gradle that those shouldn't be included in the runtime classpath, but I don't think that's the most expedient way to fix this regression.

My **current hope** is to do something like this:
- inspect the outputs of `project(":modules")`
- ask gradle to come up with a runtimeClasspath for using them
- make a Copy task that puts those things in `modules/`. Might need to do a little filtering so we really are only copying in modules and not their other allowed runtime java dependencies.

I think that seems like an entirely sensible plan, I just need to look up the gradle methods for the first two steps. Gradle has had a way of throwing wrenches in my sensible plans before; we'll see.

(Open to other suggestions if they have fewer loose wrenches or unknowns.)
