### ISSUE TITLE
Double Sided Block Rendering

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#439]
As I gathered all the information on the json block definition options a stumbled upon the double sided property, and I was wondering how it is supposed to work. 
I think its used for billboard plants atm and tried using it for glass. 

In these screens you can see the result. The green glass has `"doubleSided" : false` and works as expected, culling is done and only the front is visible.
![130209144758087](https://f.cloud.github.com/assets/1448874/142597/f9a25108-7303-11e2-8cb9-0546498fb574.jpg)

The red one uses `"doubleSided" : true` and the faces drawn changes from for every block, somehow depending the previous attached blocks. 
![130209144819887](https://f.cloud.github.com/assets/1448874/142599/2dc00296-7304-11e2-9960-de7fc77ba154.jpg)
The first version is how I expect it to be (all faces drawn),  and these are some other (random) results.
![130209141749613](https://f.cloud.github.com/assets/1448874/142601/4dca943e-7304-11e2-801f-5416f40c2cc1.jpg)
![130209144816353](https://f.cloud.github.com/assets/1448874/142602/4fa60108-7304-11e2-9a78-44ebdb6340d8.jpg)
![130209144803955](https://f.cloud.github.com/assets/1448874/142610/ab5ea388-7304-11e2-9502-f0a56c41c57d.jpg)

Is this a real rendering issue, @begla, or is the double sided option only designed to billboard plants?
##

**Comment by jdrueckert** [comment]
Cannot reproduce this anymore:
![image](https://github.com/user-attachments/assets/e6f8c3a6-6563-49d2-a09e-629375eeebff)
