### ISSUE TITLE
Waving Fooliage Gap

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#440]
Don't know how to call it best, but here's a screeny of what I mean. This can be solved by making the fooliage `translucent`, but I don't know if that's a good fix, though.
![130209230801361](https://f.cloud.github.com/assets/1448874/142623/859d517a-7305-11e2-949c-a36ced725d95.jpg)
##

**Comment by jdrueckert** [comment]
Cannot reproduce this anymore:
![image](https://github.com/user-attachments/assets/377ae681-d5d0-41bb-b979-c8da600e4497)
