### ISSUE TITLE
Space in path to modules on Windows (at least) can cause game crash when running from source

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4407]
Split out from #4392

### What you were trying to do

Run the game (for some sort of testing) from a directory like `D:\Dev\Terasology\Git_WS\Pristine Omega\Terasology` using `gradlew jar game`

Alternatively run from source with an OS username containing a space, meaning there's a space in the path to the default location of the Gradle cache, with a jar file used from there

### What actually happened

💥 

### How to reproduce

* Have a workspace either with a space in its path or use a Gradle cache from a location with a space in the path
* Run the game, such as with `gradlew jar game`

### Log details and game version

One snippet from a run involving the Gradle cache by a user reporting the issue on GitHub:

`java.lang.IllegalArgumentException: Module does not exist at: C:\Users\Naman%20Tayal\.gradle\caches\modules-2\files-2.1\org.terasology.modules\Potions\1.4.0-SNAPSHOT\66b633908549499a1cc563af4574f976c60e4dbe\Potions-1.4.0-SNAPSHOT.jar`

Snippet from me trying in an Omega workspace with a space in the root directory name:

`java.lang.IllegalArgumentException: Module does not exist at: D:\Dev\Terasology\Git_WS\Pristine%20Omega\Terasology\modules\JoshariasSurvival\build\libs\JoshariasSurvival-1.1.0-SNAPSHOT.jar`

### Computer details

Win10 for me, some form of Windows from the Discord user reporting the problem.

**Comment by skaldarnar** [comment]
@keturn FYI, it also breaks on Linux :see_no_evil: 

```
java.lang.IllegalArgumentException: Module does not exist at: /home/skaldarnar/Code/movingblocks/ts%20omega%202/modules/JoshariasSurvival/build/libs/JoshariasSurvival-1.1.0-SNAPSHOT.jar
```
