### ISSUE TITLE
Release internal deps and use non-SNAPSHOTS

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4414]
This issue is just to track what needs new releases due to JOML updates.

- https://github.com/movingblocks/joml-ext (~~v1.0.0~~ v0.1.0)
- https://github.com/movingblocks/TeraNUI (v1.4.0 and v2.1.0)

I think we should aim to not have any snapshot versions in the release of the engine, at least not for our internal libs.

**Comment by skaldarnar** [comment]
To make our lives a bit easier and not jump to the next major version with `joml-ext` we could go for a v0.1.0 release there instead. This would leave enough room to tweak some parts of the semantics (inclusive vs exclusive corners, etc) while only doing a "small bump" to v0.2.0. I think aiming for a v1.0.0 release would be too much for the time frame we are planning for...

@pollend @jdrueckert @Cervator what do you think?

**Comment by jdrueckert** [comment]
Just released `joml-ext 0.1.0`: https://github.com/MovingBlocks/joml-ext/commit/dbe62c1c06f9732bc16984379b1005b91fb3020e

**Comment by jdrueckert** [comment]
Updating the joml-ext version we use in the engine in https://github.com/MovingBlocks/Terasology/pull/4525
