### ISSUE TITLE
engine with HeadlessInput fails to initialise for lack of a BindsSubsystem

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4481]
amongst all the noise on the failing MTE tests, I found this

```
18:01:15.610 [main] ERROR o.t.engine.ComponentSystemManager - Failed to initialise system org.terasology.input.InputSystem@53ed80d3
java.lang.NullPointerException: null
	at org.terasology.input.InputSystem.initialise(InputSystem.java:115)
	at org.terasology.engine.ComponentSystemManager.initialiseSystem(ComponentSystemManager.java:164)
	at org.terasology.engine.ComponentSystemManager.initialise(ComponentSystemManager.java:148)
	at org.terasology.engine.subsystem.headless.mode.StateHeadlessSetup.init(StateHeadlessSetup.java:105)
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:584)
	at org.terasology.engine.TerasologyEngine.changeState(TerasologyEngine.java:567)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createHost(ModuleTestingEnvironment.java:459)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.setup(ModuleTestingEnvironment.java:168)
```

that Null Pointer Exception is https://github.com/MovingBlocks/Terasology/blob/077020fa31aedf48bf2aad186a6a348c5cbc637e/engine/src/main/java/org/terasology/input/InputSystem.java#L113-L116

Unsure how to proceed here. Add a BindsSubsystem to all the engines with an input subsystem? Or is it a bug for one subsystem to have a dependency on another? Or should it gracefully handle `bindsManager` being null?

I also am confused about how the test runner continues to execute the test here instead of abandoning it, that would have made things clearer.

**Comment by keturn** [comment]
oh, well here's the reason it doesn't just stop there:

https://github.com/MovingBlocks/Terasology/blob/077020fa31aedf48bf2aad186a6a348c5cbc637e/engine/src/main/java/org/terasology/engine/ComponentSystemManager.java#L163-L167

I guess I can kinda imagine you might want to not crash to desktop if any subsystem fails, but this needs to be a lot louder. especially for headless systems.

**Comment by keturn** [comment]
oh, except that does mean that's the only subsystem that crashed out, and the rest of MTE's setup code for the engine did run... so maybe it's not actually making MTE tests fail?

shucks, it would have been nice to have found a Reason.

**Comment by keturn** [comment]
and yet, when I try to remove the input subsystem  from MTE entirely, it fails here:

https://github.com/MovingBlocks/Terasology/blob/077020fa31aedf48bf2aad186a6a348c5cbc637e/engine/src/main/java/org/terasology/engine/TerasologyEngine.java#L247-L251

**Comment by DarkWeird** [comment]
There is known problem.
We cannot just delete this from server or headless, because it using via CoreRegistry in several places. 
Really it is not easy to fix it.

**Comment by skaldarnar** [comment]
This also happens locally, and although annoying as it is, it does not seem to make tests fail locally... :thinking:
