### ISSUE TITLE
cleanup joml imports

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#4500]
went through the code and removed the rest of the references to JOMLUtil.

- https://github.com/Terasology/BlockDetector/pull/8
- https://github.com/Terasology/Cities/pull/48
- https://github.com/Terasology/CombatSystem/pull/74
- https://github.com/Terasology/Equipment/pull/132
- https://github.com/Terasology/Explosives/pull/5
- https://github.com/Terasology/SegmentedPaths/pull/17
- https://github.com/Terasology/Lost/pull/35
- https://github.com/Terasology/GooKeeper/pull/43
- https://github.com/Terasology/GrowingFlora/pull/31
- https://github.com/Terasology/LightAndShadow/pull/191
- https://github.com/Terasology/MobileBlocks/pull/7
- https://github.com/Terasology/Rails/pull/75
- https://github.com/Terasology/Health/pull/63
- https://github.com/Terasology/ItemPipes/pull/33
- https://github.com/Terasology/ItemRendering/pull/19

**Comment by skaldarnar** [comment]
All PRs are merged and Omega workspace builds.
