### ISSUE TITLE
Gestalt V7 Migration

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#4509]
# Gestalt v7 Integration
* Changing engine module to package module. ( classpath modules dropped)
 * engine moved in self package (`org.terasology.engine` now)
 * create syntetic package module  for nui (easier then write all in whitelist)
 * Update gestalt to 7.0.5
 * Update gson to 2.8.5
 * Update TeraNui to 2.0.0
 * Update Guava to 29.0-jre
 * Update Reflections to org.terasology:reflections:0.9.12-MB (gestalt build it)
 * Reimplemented Module download (gestalt drop `BaseModule` class)
 * Restore Module loading on gestalt v7
 * Use AutoreloadingAssetManager (seems asset must reload easier now)
 * Replace condition `Module#isSourceModule` to checking Module's files source == `DirectoryFileSource` - must be equal ( affected WorldGeneratorManager)
 * add Gestalt's classes to whitelist
 * remove duplication classes from `org.terasology.input`(`org.terasology.engine.input` now). We have this classes in TeraNUI
 * move `cacheReflections` task on after `classes` task (partial resolve https://github.com/MovingBlocks/Terasology/issues/4126#issuecomment-692232675) (reflections gathering for running from sources now)
 * remove `cleanReflections` after `jar` task
 * renamed `cacheReflections`'s artifact `reflections.cache` to `manifest.json` and serializer changed to Json for using gestaltv7's default values

Relevant PR for reference:
- [Breaking all] Gestalt v7 re-integration (https://github.com/MovingBlocks/Terasology/pull/4144)

**Comment by keturn** [comment]
The big list currently in this issue description is from #4144. There are some things that were in #4144 that could be broken out and done independently, including:

* classpath modules dropped: see #4543
* removing shrinkwrap from engine-tests: reference https://github.com/MovingBlocks/Terasology/pull/4144/commits/eef934f08069b1afd08c5b64f7efc001cdd51448
* update guava: reference https://github.com/MovingBlocks/Terasology/pull/4144/commits/fec847ae3ecbbac09b611b386068e9c28ed356d2
* update gson: straightforward upgrade.
* remove duplication classes from org.terasology.input. We have this classes in TeraNUI: has this been done already?
* move `cacheReflections` task on after classes task: can be done separately.

**Comment by jdrueckert** [comment]
Migration effort done (except for a few follow-ups tracked in https://github.com/orgs/MovingBlocks/projects/20
