### ISSUE TITLE
No ore generation in Josharias Survival

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4523]
**Problem:** With no ores being generated in the world of JS big parts of the tech tree are unavailble, reducing the scope of the game play module drastically. This is a regression compared to previouls (preview) releases.

The ore gen was working in **preview 1123 (20210103)**, so it's likely related to our JOML migration effort. Based on that date and the involved modules, this (most likely) boils down to:

- https://github.com/Terasology/CustomOreGen/compare/93210238ccfd50dde2a6d22776a072db2ac47c11..develop
- https://github.com/Terasology/OreGeneration/compare/1144f6197cc36eed928e02d0ebe38e41f886eb0a..develop

**Comment by skaldarnar** [comment]
Potential fix by @pollend in https://github.com/Terasology/CustomOreGen/pull/13

**Comment by pollend** [comment]
> Potential fix by @pollend in https://github.com/Terasology/CustomOreGen/pull/13

Not really. Min and max positions are suppose to be local to the transform just not sure what the translation did in the old code. Maybe /@4Denthusiast would have a clue.
