### ISSUE TITLE
Improve performance with GraalVM.

### ISSUE THREAD

**Issue by Vuntooz** [MovingBlocks/Terasology#4530]
### What I was trying to do
I have tried to actually play it using weak PC (suits minimal system requirements, two 3.4 Ghz cores, 6 Gb RAM, 2Gb VRAM, HDD, Win7) on lowest settings in any cases. 

### What actually happened
Great stutters according to chunk loading. Even worse than in Minecraft (I understand that MC doesn't have advanced lighting like Terasology does, but still). Some framerate drops according to lighting (without imagianary clouds's shadows). Water shaders slightly affect to FPS.

### How to reproduce
I think using GraalVM may improve performance even on high-end machines, because it allows to transform java bytecode to actual consistent binaries. Because I don't know well architecture of project, it would be difficult to build it myself. So reproducing in this case means comparing of FPS and stutters after successful rebuild of game.

### Log details and game version
Latest stable version (№38).

### Computer details
Everything is disabled (Antiviruses et cetera). Minimal count of non-game processes.

That's my first interaction on Github ever. I've read your contributing guidelines. Excuse me if my issue lacks something.

**Comment by DarkWeird** [comment]
GraalVM(native images) is not silver bullet for performance.

It can improve performance
It can worse performance.
It can just not work.

And we not ready for graalvm yet.
We needs:
Replace most reflection used places (reflection less DI)
Investigate how will works modules with native image (we loads modules(aka mods) in runtime)
Investigate how will works our ECS system
Investigate how will works our assets system(it used java resources. I heard this was issue)
Investigate how will works JNI.

I have in my plan try graalvm at oneday.




Currently we have java with C2 compiler.
It should generate great native code for java bytecode at runtime.(graalvm uses compile phase for aot)





We works with performance now.
@pollend works with graphics(FPS, shaders)

I and @4Denthusiast works with chunk loading performance.



You can try my PR about chunk loading speed. https://github.com/MovingBlocks/Terasology/pull/4502.

**Comment by Zireael07** [comment]
There's also the issue that graalvm doesn't work with some renderers (LWJGL IIRC)...

**Comment by DarkWeird** [comment]
We use lwjgl3 :(
Jni issue?

**Comment by Zireael07** [comment]
Dunno, dropping issue link for reference https://github.com/oracle/graal/issues/304

**Comment by skaldarnar** [comment]
Closing this as "not planned", at least not in the near future.
