### ISSUE TITLE
remove JCenter from all build configurations

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4582]
JCenter is [shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

They will stop accepting new uploads _this month_ (the end of March 2021) and will stop serving downloads entirely in 2022.

So by 2022, we'll want to have removed all the `jcenter()` entries from the repository configurations in our gradle files. (Both `build.gradle.*` and everything in `build-logic`.)

The reason we didn't just do that _immediately_ is because we don't know if all our dependencies are available on other servers yet!

The process for fixing this is something like:

* remove `jcenter` from our configurations
  - replace it with `mavenCentral()` if that config doesn't have it already
* attempt to build. Note which dependencies fail.
* for each one, investigate
  - has that project moved to another server that we need to add to our configuration?
  - have they announced a _plan_ to move, but aren't finished yet?
  - is the project without a maintainer?
    + has it been picked up by a new organization?
    + should we mirror its old releases to our own repository?
    + should we maintain a fork of the project?
    + should we drop the dependency and use something else?

Related reading:
* general documentation on gradle repository configuration: https://docs.gradle.org/current/userguide/declaring_repositories.html
* gradle's instructions on how to migrate your dependencies: https://blog.gradle.org/jcenter-shutdown

**Comment by keturn** [comment]
oh hey, there's some jcenter stuff in groovy too: https://github.com/MovingBlocks/Terasology/blob/1426b6b47363d5b3a080eaf51801c12cb72cd9fb/config/groovy/common.groovy#L6-L7

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace jCenter in all repositories](https://trello.com/c/jMtFGegz/59-replace-jcenter-in-all-repositories)
