### ISSUE TITLE
Water reflects sunlight even if in shadow

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#459]
Next 3d wizardry puzzler! I suspect this one is decidedly low priority ;-)

With or without shadows water will happily reflect sunlight despite the sun being hidden behind hills. Just looks funnier on "Uber" with shadows enabled:

![130316114729710](https://f.cloud.github.com/assets/1063833/267069/d9bfd7be-8e53-11e2-8753-f32942177ceb.png)

Wonder if there's an easy way to use the shadow data to negate reflective sunlight in the same spots?
##

**Comment by jdrueckert** [comment]
Seems to work now:
Sun low with tree and hill casting shadow:
![image](https://github.com/user-attachments/assets/ac9d03c1-ff44-4e3a-8193-e8db38bc4a1e)

Sun high enough for hill and tree to not cast shadow:
![image](https://github.com/user-attachments/assets/e7ef0bd6-5074-4895-89f9-7b8eae9f5e95)
