### ISSUE TITLE
ci: separate stages for unit tests and flaky tests

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4607]
Following #4606, we'll have more than one type of `test` task. We'd like CI to run all the tests. When checking a PR it should require all the well-behaved tests to pass. A failure among the less-reliable tests may mark the build as "unhealthy" but not failed.

If we want to do this for the engine, the place to do it is `Jenkinsfile`.

The Jenkinsfile for modules lives in https://github.com/MovingBlocks/ModuleJteConfig/blob/master/Jenkinsfile

### Open Questions

- [ ] Do we want to do this for engine tests? It does have some `TteTest` cases, but are they flaky enough to demote to lesser importance?

### Things to Watch Out For

- Make sure _all_ the test results are recorded in Jenkins. i.e. splitting them up in to separate tasks doesn't accidentally make it so only the results of one or the other of those tasks are saved.
- People have built tools to do elaborate monitoring and treatment of flaky tests. _**Resist** going down that rabbit hole!_ 🕳  
  We don't want to make it _too_ easy to accept test flakiness too quickly. Save your time for other things, like fixing flaky tests!

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Separate Jenkins test stages](https://trello.com/c/fgorgiQY/53-separate-jenkins-test-stages)

**Comment by keturn** [comment]
you can see what all `check` will run by doing `gradlew check --dry-run`

It looks like `gradlew check --exclude-task test` might work if we want to have a "all the checks _except_ tests" build step without explicitly naming each of those checks.

**Comment by jdrueckert** [comment]
Also, to have the reference here (I need to make answering stuff preferably on GitHub a habit):
since https://github.com/MovingBlocks/Terasology/pull/4611 got merged, we now do have three different gradle tasks:
- `unitTest` running only unit tests
- `integrationTest` running only integration tests (MTE, TTE, etc.)
- `test` running both, unit and integration tests - so basically all tests

**Comment by skaldarnar** [comment]
See also changes done previously in https://github.com/MovingBlocks/ModuleJteConfig/commit/e64657b9d83284a6c272dcce265821a4d5024e16
