### ISSUE TITLE
do not allow modules to import unsafe engine classes

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4639]
The Malicious module detected a regression in #4622 that allows modules to import _any_ class in the `org.terasology.engine` package.

Related: https://github.com/MovingBlocks/gestalt/pull/112

It would help to have a test for this as part of the normal automated test suite that doesn't require manually launching a game and searching the logs.

**Comment by keturn** [comment]
I stashed some work in progress where I was experimenting with this at https://github.com/keturn/Terasology/commit/e95fc8d10da615710aecb49a68b8552eebeba3b8

**Comment by keturn** [comment]
Ah, at least part of why I didn't want to merge that WIP commit as-is is because there are some refactorings in there like `static Module loadAndConfigureEngineModule(…)` that I didn't actually end up making use of.

(because as I wrote tests, it became clear that the tests I was trying to write depended upon the combination of that _and_ stuff from  `setupSandbox` and/or `loadEnvironment`)

and I'm not sure if the stuff I was trying to do with `org.terasology.unittest.stubs` was in a working state

**Comment by jdrueckert** [comment]
Fixed by gestalt#112
