### ISSUE TITLE
audit use of `instanceof DirectoryFileSource`

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4640]
There were a number of places #4622 did:

```diff
-            if (module.isCodeModule()) {
+            if (module.getResources() instanceof DirectoryFileSource) {
```

because `isCodeModule` is not a method in gestalt-v7.

These call sites need to be audited to see if that is a suitable replacement.

* What is it they need to know about the module?
* Does the replacement work in all situations? if module is checked out as source, if it's a jar in cachedModules, if it's in a release bundle, etc.

**Comment by jdrueckert** [comment]
Occurence in [ModuleDownloadListGenerator.java](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/core/module/ModuleDownloadListGenerator.java#L80):
- it tries to find out whether an online version is newer than a local version of a module
- if versions are equal it tries to check if the local module is a source module or a jar
- if it is a source module, the module is not downloaded again

So:
> What is it they need to know about the module?

Whether it's source or jar.

> Does the replacement work in all situations?

No idea, would need to try that out I guess.

**Comment by keturn** [comment]
Ohh, because if you're in a dev workspace and you have sources, you don't want to download a thing that's going to be different from your local sources.

Okay, that makes sense. I am not 100% sure it _works,_ because [mumble mumble], but I understand the use case there.

**Comment by jdrueckert** [comment]
Occurence in [Metrics.java](https://github.com/MovingBlocks/Terasology/blob/78e608c57468210a001a8b84df0fd51f76c5d71d/engine/src/main/java/org/terasology/engine/telemetry/Metrics.java#L64):

- at init time, it tries to fetch the classes implementing metrics from the env
- for every module registered in the module manager it gets the latest version of that module and checks whether it's present as source
- only if it is, it will resolve its dependencies and let the module manager load the environment for the dependency modules it resolved and from there fetch all classes with the `TelemetryCategory` annotation

So: 
> What is it they need to know about the module?

Again, that it's present as source, I guess. My assumption is, that `DependencyResolver` cannot properly resolve dependencies of a jar or `ModuleManager` cannot properly load the environment, although in that case I'd expect it to check the dependencies being present as source :thinking: 
But maybe, I'm missunderstanding, what the following does?
```java
DependencyResolver resolver = new DependencyResolver(moduleManager.getRegistry());
Module module = moduleManager.getRegistry().getLatestModuleVersion(moduleId);
ResolutionResult result = resolver.resolve(moduleId);
```

> Does the replacement work in all situations?

Still no idea, would need to try that out I guess.

**Comment by keturn** [comment]
Hmm, the Metrics use case doesn't make so much sense to me. Why wouldn't it want to use TelemetryCategory from jar modules?

I wonder if in this case the intent in calling `isCodeModule` was to skip asset-only modules, as they won't have annotations to scan?

**Comment by jdrueckert** [comment]
> I wonder if in this case the intent in calling isCodeModule was to skip asset-only modules, as they won't have annotations to scan?

That indeed sounds like a reasonable assumption :+1: 
I wasn't sure if there's any technical blockers to get the annotated classes from jars :woman_shrugging:
And I wasn't aware that `isCodeModule` also had the non-asset notion :bulb:

**Comment by jdrueckert** [comment]
Occurrence in [WorldGeneratorManager.java](https://github.com/MovingBlocks/Terasology/blob/78e608c57468210a001a8b84df0fd51f76c5d71d/engine/src/main/java/org/terasology/engine/world/generator/internal/WorldGeneratorManager.java#L47):
- `WorldGenManager` is refreshed for instance on saving the world gen config
- on refreshing, for every module in the registrythat is present as source code we try to resolve it, load the environment and get all world generators using the `RegisterWorldGenerator.class` annotation to add valid world generators to a list with generator information

Like with the metrics, the intent here might've been to skip asset-only modules as they won't have annotations to scan.

**Comment by keturn** [comment]
I have concerns about that usage of ModuleManager, but I'm trying my best to keep the scope to "feature parity with Terasology-with-gestalt-v5" before going off on _that_ tangent.

The thing with RegisterWorldGenerator sounds like it might actually be a big part of our MTE test failures. Especially in environments like CI module builds that don't have the full module tree checked out, MTE and other dependencies will be jars, not a DirectoryFileSource.

**Comment by jdrueckert** [comment]
> The thing with RegisterWorldGenerator sounds like it might actually be a big part of our MTE test failures. Especially in environments like CI module builds that don't have the full module tree checked out, MTE and other dependencies will be jars, not a DirectoryFileSource.

Do we know whether we can also load an environment (to get annotated types from) based on jars?

**Comment by jdrueckert** [comment]
Occurrence in [InputSettingsScreen.java](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/rendering/nui/layers/mainMenu/inputSettings/InputSettingsScreen.java#L137):

- during init of this screen we want to collect input categories and buttons to bind
- for every module in the registry that is present as source code we try to resolve it, load the environment and get all classes annotated with `InputCategory.class` or `RegisterBindButton.class`

Again it seems that we might use `instanceof DirectoryFileSource` to skip asset-only modules...
Loading a module's environment to run `getTypesAnnotatedWith` seems to be a recurring pattern.
I'm still wondering whether anything is keeping us from doing that on jars... :thinking: 
If not it maybe really only is a way to skip asset-only modules, although it seems a weird way... I would think that a `ModuleManager` should ideally be capable to filter modules it manages based on some categories... Maybe that would be a useful (and more understandable) alternative to add if not present yet?

**Comment by keturn** [comment]
> Do we know whether we can also load an environment (to get annotated types from) based on jars?

I believe we can.

If I'm mistaken about that and we _can't_ get annotations from jars, then that means building `reflections.cache` at compile time is _not_ optional after all, and that would be a thing we need to highlight as a release blocker ASAP.

**Comment by keturn** [comment]
> I would think that a `ModuleManager` should ideally be capable to filter modules it manages based on some categories... Maybe that would be a useful (and more understandable) alternative to add if not present yet?

100% agree with you on this; that's the sort of thing I was thinking in that "trying to restrain self from going on ModuleManager tangent" comment a bit ago.

**Comment by jdrueckert** [comment]
Last occurrence I found of `instanceof DirectoryFileSource` was in `telemetry.TelemetryScreen` and basically is the same stuff that we saw in `telemetry.Metrics`.
The PR cross-referenced above takes care of that.

**Comment by jdrueckert** [comment]
> If I'm mistaken about that and we can't get annotations from jars, then that means building reflections.cache at compile time is not optional after all, and that would be a thing we need to highlight as a release blocker ASAP.

@keturn I believe the fact that your fix for the world generators tested out fine is proof that we are able to get annotations from jars :+1:

**Comment by jdrueckert** [comment]
Now, with the following occurrences being more or less valid:
- ModuleDownloadListGenerator.java
- AbstractEditorScreen.java ( doc & todo in #4697 )

and the following occurrences dealt with:
- Metrics.java
- TelemetryScreen.java
- WorldGeneratorManager.java

this probably only leaves InputSettingsScreen.java to be dealt with, right @keturn ?

Or is there anything else that's part of the definition of done for this issue?
