### ISSUE TITLE
change gradle-gestalt-module to match gestalt 7.1 semantics

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4641]
After https://github.com/MovingBlocks/gestalt/issues/113

we need to update this part of our gradle configuration: https://github.com/MovingBlocks/Terasology/blob/f8684f7c992a4da5aa45018254a66c14c5b7fc65/build-logic/src/main/kotlin/org/terasology/gradology/module_build.kt#L65-L73

fortunately it should be simpler as a result.

**Comment by jdrueckert** [comment]
Done in https://github.com/MovingBlocks/Terasology/pull/4649
