### ISSUE TITLE
Black screen on Ubuntu 18.04 with alpha-20

### ISSUE THREAD

**Issue by Hume2** [MovingBlocks/Terasology#4698]
### What you were trying to do
When I run Terasology from the launcher, it shows a loading screen. After that, a full-sized window appears and it is completely black. I just see a mouse cursor. I hear music but I don't see anything.

I tried the version preview alpha-20+195 (20210519). I tried different versions also. The last working version seems to be release alpha-19+2.

When I manage to hit a button (which I don't see), it makes a sound. I tried to run a world by clicking at the positions where I think the buttons might be. So maybe I launched a world, maybe I did something completely different. And then it crashed.

### What actually happened
Whole the game screen is black. When I (maybe) launched a world, it crashed.

### How to reproduce

* Step 1: Start the launcher
* Step 2: Select version preview alpha-20+195 (20210519)
* Step 3: Wait until the progress bar on the loading screen fills.
* Step 4: A window with black screen appears.

### Log details and game version
[2021-05-21_09-05-10_5.0.0-SNAPSHOT_463 (Google Drive)](https://drive.google.com/drive/folders/12iLtAduGf4eVk_iEqw2gxIocujwapb3h?usp=sharing)

### Computer details
OS: Ubuntu 18.04 64-bit
GLFW version: 3.2
CPU: Intel® Core™ i3-6100U CPU @ 2.30GHz × 4 
GPU: Intel® HD Graphics 520 (SKL GT2)

$ glxinfo | grep version
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 4.60
OpenGL version string: 3.0 Mesa 20.0.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
```

**Comment by skaldarnar** [comment]
[Intel support page](https://www.intel.com/content/www/us/en/support/products/88355/graphics/graphics-for-6th-generation-intel-processors/intel-hd-graphics-520.html) states that the integrated GPU supports OpenGL 4.4. Maybe a driver update is required here?

On the other hand, there are many more exceptions logged in the `Terasology-init.log` which probably need further investigation. 🤔

**Comment by pollend** [comment]
I think @DarkWeird said we needed to flag the version to 3.0 but we're using a whole lot of fixed function pipeline stuff and all of that won't work if you set the profile version to the minimum this way.  the plan was to migrate all the shaders and try to get rid of all the fixed function pipline stuff. I've mostly migrated the shaders but there are a few places that are a bit prickly :( 

https://stackoverflow.com/questions/45015303/how-do-i-utilize-a-different-opengl-profile
