### ISSUE TITLE
Is Terasology support Android 

### ISSUE THREAD

**Issue by sublimegame** [MovingBlocks/Terasology#4769]
Hi all
I just want to know that is this possible for us to build and run Terasology on android device?
Thank you so much!

**Comment by pollend** [comment]
That's going to take a lot of work. Destination sol has been the testbed for developing these features.

We need to better abstract the rendering and migrate in features from gestalt.

**Comment by skaldarnar** [comment]
Hi @sublimegame,

Terasology does currently not run on Android. As mentioned above, this would need a lot of work, and while it might be technically possible, we're just short on people who can put the effort in here. 

The future of Android development seems to go away from plain Java and more towards Kotlin. While this topic comes up frequently, there are no concrete plans to migrate the code.

If anybody plans to work on this, please approach us here or on Discord.
