### ISSUE TITLE
Josharias' Survival In-Game Help "Items" tab crashes Terasology

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/Terasology#4770]
### What you were trying to do
Click on the "Items" tab in the Josharias' Survival in-game help screen.

### What actually happened
Terasology crashed

### How to reproduce

* Start Terasology preview alpha 20+271 (20210615)
* Start Josharias' Survival
* Open the in-game help screen (`P`)
* Click on the "Items" tab

### Log details and game version
Version: preview alpha 20+271 (20210615)
Logs:
```
19:46:21.326 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoSuchMethodError: 'org.terasology.gestalt.assets.ResourceUrn org.terasology.engine.rendering.assets.texture.TextureUtil.getTextureUriForColor(org.terasology.nui.Color)'
    at org.terasology.irlCorp.systems.MechanicalPowerToolClientSystem.drawPowerToolPowerBar(MechanicalPowerToolClientSystem.java:67)
```

**Comment by jdrueckert** [comment]
Discord user `wolfsujiyama` reported this today.

**Comment by jdrueckert** [comment]
For some reason it seems that [`org.terasology.gestalt.assets.ResourceUrn`](https://github.com/MovingBlocks/gestalt/blob/develop/gestalt-asset-core/src/main/java/org/terasology/gestalt/assets/ResourceUrn.java) is not known in [IRLCorp::MechanicalPowerToolClientSystem](https://github.com/Terasology/IRLCorp/blob/develop/src/main/java/org/terasology/irlCorp/systems/MechanicalPowerToolClientSystem.java#L67) or [engine::TextureUtil](https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/rendering/assets/texture/TextureUtil.java#L30) :thinking:

**Comment by jdrueckert** [comment]
Seems this was a mismatch on binary level.
Rebuilding `IRLCorp` and triggering another preview release resolved this.

**Comment by mkienenb** [comment]
Also happens if you use a bucket in Josharias' Survival in 5.1.1.
```
java.lang.NoSuchMethodError: 'org.terasology.gestalt.assets.ResourceUrn org.terasology.engine.rendering.assets.texture.TextureUtil.getTextureUriForColor(org.terasology.nui.Color)'
	at org.terasology.fluid.system.FluidClientSystem.drawFillingBarForFluidContainerItem(FluidClientSystem.java:147)
	at org.terasology.fluid.system.FluidClientSystemMethodAccess.invoke(Unknown Source)
```

**Comment by jdrueckert** [comment]
> Also happens if you use a bucket in Josharias' Survival in 5.1.1.
> 
> ```
> java.lang.NoSuchMethodError: 'org.terasology.gestalt.assets.ResourceUrn org.terasology.engine.rendering.assets.texture.TextureUtil.getTextureUriForColor(org.terasology.nui.Color)'
> 	at org.terasology.fluid.system.FluidClientSystem.drawFillingBarForFluidContainerItem(FluidClientSystem.java:147)
> 	at org.terasology.fluid.system.FluidClientSystemMethodAccess.invoke(Unknown Source)
> ```

Based on the earlier occurrence, I'm guessing the `Fluid` module needed rebuilding :thinking:

**Comment by mkienenb** [comment]
Open a separate issue or just use this one?

**Comment by jdrueckert** [comment]
> Open a separate issue or just use this one?

Good question. Theoretically, re-opening this one would be fine. I don't expect us to do a 5.1.2 to fix that as we still do not really support reproducible builds, so I'd like to target the 5.2.0 milestone. We could adjust the milestone linked on this issue, but maybe then it's better to just create a new one. 

In the end, I don't think it matters much. Reason being that I'd rather see this as an issue that needs verifying on whether it's present in the release candidate we'll do this weekend and if so, re-build the module and check if it's still there (expectation: it won't). Ideally I guess we might want to build all omega modules freshly whenever we release omega - currently afaik we only take the latest releases we find in the artifactory, right @Cervator @keturn ?

**Comment by mkienenb** [comment]
I'll go ahead and open a new one for those very good points.
