### ISSUE TITLE
Billboard items not rendered in inventory

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4775]
**Problem:** Item icons for billboard items (e.g., grass and flowers) are not rendered in the toolbar or inventory. Their texture is missing in the toolbar, but the blocks render fine when held in hand. 

![image](https://user-images.githubusercontent.com/1448874/122459268-05e53300-cfb1-11eb-976c-3b2a7c146f1a.png)

**Comment by pollend** [comment]
resolved with this change: https://github.com/MovingBlocks/Terasology/pull/4827
