### ISSUE TITLE
FacetProvider requirements should be verified

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4924]
For example, BiomeProvider `@Requires` SeaLevelFacet, but code reaches BiomeProvider.process without a SeaLevelFacet provided: https://scans.gradle.com/s/3szw7vgxv4d2o/tests/:modules:DynamicCities:test/org.terasology.dynamicCities.settlements.SettlementEntityManagerTest/placeParcel(SettlementEntityManager,%20ModuleTestingHelper)?top-execution=1

If this had been checked up-front and responded with a clear error message, it would have saved me some time in trying to figure out why my WorldGenerator wasn't working.

@tolziplohu [says](https://discord.com/channels/270264625419911192/702893102481932308/895498118743875616):
> Huh. It looks like the annotations are used for ordering providers but not for verifying that they actually exist. That should actually be pretty easy to detect — just look for empty provider lists for required facets. I guess we just haven't considered that possibility.

**Comment by zhayun3233** [comment]
Hi, I'm Yuna, a CS student looking to make a first contribution, could someone help me get started?

**Comment by Cervator** [comment]
Hi @zhayun3233 - https://discord.gg/terasology is the place for various general support :-)

If you're curious about this topic in particular check out https://github.com/Terasology/TutorialWorldGeneration and our getting started docs in this repo's wiki 👍

**Comment by MrGizmo123** [comment]
Would the WorldBuilder class (org.terasology.engine.world.generation.WorldBuilder) be a good place to perform the check if all required facet providers are available? More specifically in the determineProviderChains function where the other annotations are processed (line 178)

**Comment by MrGizmo123** [comment]
@jdrueckert I agree, as in I think it should fail entirely since its going to crash anyway a few moments later. I think the only time this error will come up is during development of a new world generator and so a prominent error message (after failure) will be most helpful.

**Comment by MrGizmo123** [comment]
An if statement like this should be enough https://github.com/MrGizmo123/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/world/generation/WorldBuilder.java#L230-L233. I'm also not sure how to exit the program properly.
