### ISSUE TITLE
Game screen goes Black

### ISSUE THREAD

**Issue by Ln11211** [MovingBlocks/Terasology#4929]
### What you were trying to do
So I was switching the Window to read the docs/playing.md(basically I paused the game, minimized the window and opened a new window like chrome, etc).
### What actually happened
Once I came back to the game and resumed playing the whole screen went black although I could switch between my tools and blocks. I remember standing on a high tower of blocks, as the screen was black I quit to the main menu and reloaded the game and I was there standing on the same tower of blocks(this means I continued the game where I left although the video wasn't there). I also tried to do this again and this time when the screen went black I tried sprinting and I fell down to death and still, the screen was black...
### How to reproduce

* Open and play the game and then pause the game.
* Now switch to another window by minimizing the game window. You will have to minimize the game window and then switch to the other window, if you directly switch to the other windows(like chrome, etc) using the taskbar, you won't encounter the problem.
* Now come back to the game window and resume the game. You will just see a black screen.
* Alternatively you can minimize the game window and reopen the game window and you will encounter the same problem.

### Log details and game version
Latest develop branch as of Oct 23 rd.
### Computer details
Asus Tuf F-15

**Comment by ujjman** [comment]
also, when the screen goes black and we resize it, the screen goes back to normal again
