### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Ygarr** [MovingBlocks/Terasology#4951]
Just start and run with Static Cities
https://pastebin.com/sUFZQE1g
 java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7)
OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

OS:Manjaro

**Comment by jdrueckert** [comment]
Hi @Ygarr thanks for reporting this.
Can you please give us a bit more information regarding how you started Terasology?
For instance, did you use the launcher or start from source?

**Comment by DarkWeird** [comment]
Guess causes:
1. Using system java 16 (it is possible for old launcher native executables or sources)
2. Using old code ( source at old branch, or terasology package at archlinux)

**Comment by Ygarr** [comment]
Seems using java 11 fixed it
