### ISSUE TITLE
how to start run normal game?

### ISSUE THREAD

**Issue by 2439905184** [MovingBlocks/Terasology#4971]
I am a newer.
![image](https://user-images.githubusercontent.com/29478722/144749478-187fbba5-f690-4505-b612-8e6237e9c764.png)
I downloaded game from github, but I can't start it. I am Chinese ,it seems that I can't download game from launcher ,I got some errors。
![image](https://user-images.githubusercontent.com/29478722/144749543-03d71ed1-9cbf-4d4b-bed0-e3b05e217ea8.png)
I want to change data path,but it seems I can't set that path by my self

**Comment by 2439905184** [comment]
![image](https://user-images.githubusercontent.com/29478722/144749684-268af134-6ad1-4f66-aadd-ee275b5b3138.png)

**Comment by jdrueckert** [comment]
This was resolved in a conversation on Discord. The issue was an incompatible version of Java.
Terasology requires Java 11 now and on Windows, starting from the Launcher is recommended in case you don't want to start from source.
