### ISSUE TITLE
Terasology Crashing on Alt+Tab

### ISSUE THREAD

**Issue by CsyTheArgonaut** [MovingBlocks/Terasology#4974]
https://pastebin.com/P56sEmrY
Sorry for not posting this here, I put it in the pastebin!
It was on Terasology version 5.2.0, started from launcher, gameplay was JoshariasSurvival with no additional modules and I was crashing shortly after hitting Alt+Tab after having spawned but before everything loaded. I was playing in fullscreen mode is thats relevant?

**Comment by jdrueckert** [comment]
Duplicate of https://github.com/MovingBlocks/Terasology/issues/4575
