### ISSUE TITLE
Crash/Bug on trying to generate a world with josharias Survival

### ISSUE THREAD

**Issue by Irgendwer01** [MovingBlocks/Terasology#4977]
### General Info

Terasology Launcher Version: 4.5.0
Terasology Version: 5.2.0
Operating System: Opensuse Leap 15.3
Onboard / Dedicated Graphics: Intel Graphics 3000
Java Version: installed on system: 11, shipped with launcher: 11

### What you were trying to do
Generating a world with josharias Survival

### What actually happened
Crashed

### How to reproduce

1. Select Terasology version 5.4.00
2. Start Terasology
3. Select gameplay josharias Survival
4. Start game
5. See error

### Log details
https://pastebin.com/YGK9aj5a

**Comment by Cervator** [comment]
Getting this updated with a note from Discord: this does _not_ seem to happen with the latest Omega dist from Jenkins at the moment (not yet available by default in the launcher) - https://jenkins.terasology.io/teraorg/job/Terasology/job/Omega/job/develop/418/artifact/distros/omega/build/distributions/TerasologyOmega.zip

So in theory by the time we do the next release / launcher pre-release this issue should be resolved :-)

**Comment by jdrueckert** [comment]
This seems like a sporadic issue I've been experiencing once every while for the past year or so... Not sure, but I _think_ I first saw it at some point after the JOML migration (which resulted in a bunch of out of bounds / off-by-one issues in general)...

@Irgendwer01 were you able to reliably reproduce it or did it only appear sporadically for you, too?

**Comment by skaldarnar** [comment]
I just ran into this with world the following world seed: `ZH09EM8nkPwOc9Fy`

**Comment by Irgendwer01** [comment]
@jdrueckert Sorry for the late response, no I wasn't able to reproduce it, it happened me for a bit of time then it just was away in all versions
