### ISSUE TITLE
When trying to compile the source code for Terasology I get 502 Gateway on gradle sync

### ISSUE THREAD

**Issue by BinaryGears** [MovingBlocks/Terasology#4990]
***2:13 AM	Gradle sync failed: Could not GET 'http://artifactory.terasology.org/artifactory/virtual-repo-live/org/terasology/reflections/0.9.12-MB/reflections-0.9.12-MB.pom'. Received status code 502 from server: Bad Gateway
					Disable Gradle 'offline mode' and sync project (10 s 226 ms)***

The error above is what I am getting when opening Terasology in IntelliJ on Ubuntu; I am running the IDE as root.

**Comment by jdrueckert** [comment]
@BinaryGears Thank you for reporting this - seems our artifactory was down. It should be restarted now, please retry :)

**Comment by BinaryGears** [comment]
Thank you, that fixed it.
