### ISSUE TITLE
Crash while using NUI Screen Editor

### ISSUE THREAD

**Issue by mpildiris** [MovingBlocks/Terasology#4997]
Terasology Launcher Version: 5.2.0 .
Terasology Version: ALPHA-20 .
Operating System: Windows(x64).
Onboard / Dedicated Graphics: Dedicated(rtx nvidia 3070).

1)In the menu before entering the game i tried to open settings
2)I lunched the game and i tried to set BreathingBar to 0 to see if the game responds as well.
3)I tried to saved the progress.
4)I tried load a saved progress game 

1)i tried to open settings and game crashed with a message from -> CrashReporter -> A fatal error occurred(NullPointerException).
2)I tried to set BreathingBar to 0 and game crashed with a message from ->CrashReporter -> A fatal error occurred (Failed to resolve widget BreathingBar in null)
3)Crash reporter gave me a message of a fatal error again with RuntimeException: Saving failed and the game crashed.
4)upload failed message with status->java.io.IOException->server returned HTTP response code:422

![bug1](https://user-images.githubusercontent.com/37209953/154554333-91582e8c-6399-4c4d-ab54-50bbbcc83f99.PNG)
![bug2](https://user-images.githubusercontent.com/37209953/154554341-105787af-cdde-4f04-b85c-65c3be4feaa9.PNG)
![bug3](https://user-images.githubusercontent.com/37209953/154554347-e939dcb4-f42a-4d23-8e7e-97d2faba8c5a.PNG)
![bug4](https://user-images.githubusercontent.com/37209953/154554391-6ec7260e-8bc9-4e63-94de-a8822118ed98.PNG)
![bug5](https://user-images.githubusercontent.com/37209953/154554402-44b12ffc-93e5-4c3c-8d3b-834535482f8b.PNG)
![bug6](https://user-images.githubusercontent.com/37209953/154554412-781b2d6d-a9b2-48ee-9117-f61d95db9dc2.PNG)

Feel free to add any other context about the problem here.
I send 2 extra bugs without pressing any key or mouse move in the starting menu crashed and droped me out of the game.

**Comment by Cervator** [comment]
Thanks for the detailed report! While there's a bit of stuff to unpack in there I wanted to ask if you could please elaborate on " i tried to set BreathingBar to 0" ? Which steps are you taking on which exact screen to do that?

**Comment by mpildiris** [comment]
i go to "extras" ->"NUI Screen Editor" -> i pressed health field and this error showed up(in previews screenshots).Bonus this time another fatal error was presented.(NullPointerException)
![breath](https://user-images.githubusercontent.com/37209953/154595972-e1dc827c-3572-4264-8e3a-83a6ba662387.PNG)
.

**Comment by Cervator** [comment]
Okay, yeah that makes some degree of sense then. Using the NUI editor in-game is really more for developing UI content like new screens or experimenting with layout improvements and such. It isn't really a UI customizer to simply adjust the appearance or placement of things while you play :-)

Still, odds are it has gotten a bit rusty with age and should get some better validation / crash hardening, so this might be a good case to chase down!

**Comment by jdrueckert** [comment]
@mpildiris Hey there, can you copy the full exception from the Terasology-Game.log and post it here, please, so we can see the actual error a bit better? 🙂 

Also, it seems like the log upload to pastebin failed? Is this reproducible for you?
