### ISSUE TITLE
eror wnen i firstly go play

### ISSUE THREAD

**Issue by 51bear** [MovingBlocks/Terasology#5023]

**Comment by jdrueckert** [comment]
Hi @51bear, thanks for the report.
From the logs I take that you selected `GooKeeper` to play.
We are aware that this gameplay mode crashes the game and decided to sunset `GooKeeper` as its content is not worth the effort to fix it.
It will be removed with the next release.

For playing, I'd recommend the JoshariasSurvival or MetalRenegades gameply modes.

I'll close this issue as it's a known problem we decided to not fix.
