### ISSUE TITLE
Crash/Bug on trying to ... Black Screen in game

### ISSUE THREAD

**Issue by MoamenA** [MovingBlocks/Terasology#5057]
### General Info

Terasology Launcher Version: 
Terasology Version: 
Operating System: 
Onboard / Dedicated Graphics: 
Java Version: 

I5 3470
8 giga ram
Intel HD 2500 support Open Gl 4.0

### What actually happened

A clear and concise description of what didn't match your expectations, a.k.a. the crash or malfunction you faced.

### How to reproduce

1. Select Terasology version '...'
1. Start Terasology
1. Select gameplay '...'
1. Add modules '...'
1. Start game
1. Do '...'
1. See error

### Log details

Note, that the crash reporter often provides multiple tabs with different logs.
Please attach (a link to) all of them.

### Workaround

If applicable, describe any workaround you found to avoid the issue

### Additional Infos / Context

Feel free to add any other context about the problem here.
 
Hi There is the problem The Game Give Me black Screen When enter world i Has All the Requirements to lunch game

**Comment by jdrueckert** [comment]
Hi @MoamenA 
Please fill in the template including general info, reproduction steps and log details, otherwise we cannot help you with this.
