### ISSUE TITLE
Harden against unexpected country / language / locale settings - fall back to a default if needed

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#5060]
See #5059 for the full adventure. In short if the user's OS-level locale is set to something our version of Java (I guess? Maybe it was a particularly old Java 11 and some new language code had been issued since?) doesn't know about it can crash the loading of the entire game.

It would present something like the following:

```
20:53:59.666 [main] WARN o.t.e.c.f.c.LocaleConstraint - Locale en_AE should be one of [,nn,ar,bg,kea,nds,zu,am ...... ff,sd,mas,ti,kok,ewo,ms,ccp,br] 
20:53:59.666 [main] ERROR o.t.g.u.r.SimpleClassFactory - Failed to instantiate class: class org.terasology.engine.config.SystemConfig java.lang.reflect.InvocationTargetException: null at ...
```

In this case the user was able to change their OS-level language then the game ran fine. That seems like quite a change to require for a user to load the game though. We could probably just fall back on some variant of English and optionally post a little warning in the main game UI like "Unsupported locale detected on loading, defaulting to plain English" - I think we talked about that as a possibility long ago ("queued" errors/warnings being able to show in the main menu like in an event log of sorts) although I'm not sure what came of it.

**Comment by soloturn** [comment]
tried setting jibberish, and it came up with english. are you sure this still exists? there is nowadays.
```
engine/src/main/java/org/terasology/engine/config/SystemConfig.java:        // Matches unusual locales on Mac OS created from the user's language and location, e.g. en_UA

```
