### ISSUE TITLE
RenderingModuleSettingScreen is not working and giving Java NullPointerException

### ISSUE THREAD

**Issue by NP-chaonay** [MovingBlocks/Terasology#5075]
The description of issue is inside the Log file: https://pastebin.com/LjqkfTm8

**Comment by jdrueckert** [comment]
Hi @NP-chaonay 
please provide additional information related to your environment (OS, Graphics, Terasology version, Java version, etc.) and to how you encountered this issue (Gameplay / Terasology modules selected, steps taken in-game, etc.)

**Comment by NP-chaonay** [comment]
> Hi @NP-chaonay please provide additional information related to your environment (OS, Graphics, Terasology version, Java version, etc.) and to how you encountered this issue (Gameplay / Terasology modules selected, steps taken in-game, etc.)

OS: Windows 22H2 22623.875 (Insider Preview Beta Ch, opt-out is in progress,)
Graphics: Intel Iris Xe Graphic, No dgpu
Terasology Version: stable 5.3.0
Java Version: Seem to using the jre builtin in the downloaded game zip file from official website
CPU: Intel i511300H
Ram 16GB
Launcher setting : MaxGameMemory=8GB; LoggingLevel=ERROR; else leave default.

How to produce this issue:
1) Creating world using default setting
2) advanced mode >> leave default setting >> Universe Setup
3) click add world with default settting >>pregenerate
4) waiting preview
5) Spawn Preview
6) Rendering module config

also I have another issue  related to NullPointerException on OpenAL subsystem and it is because no output devices is enabled in host system (previously enabled on the latest game (at least once) executed) but maybe I will open a new issue then

**Comment by jdrueckert** [comment]
I just followed the reproduction steps reported and can confirm that opening the Rendering Module Config crashes the game.
I'll investigate the issue some more on the weekend.

**Comment by jdrueckert** [comment]
Resolved by #5083
