### ISSUE TITLE
Error when generating the world

### ISSUE THREAD

**Issue by Towdy21** [MovingBlocks/Terasology#5082]
When generating the world, the game crashes to the main screen https://pastebin.com/fVxH1eAJ

**Comment by jdrueckert** [comment]
Hi @Towdy21 
thank you for reporting this issue. From what I see in the logs you posted on pastebin, this is an instance of a not yet resolved sporadic we're seeing every now and then. I'll close this as a duplicate of #5056 
Usually, world generation should succeed on retry.
