### ISSUE TITLE
Remove outdated references to LGTM and optionally suggest alternatives

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#5094]
### Documentation Topic

Once upon a time we implemented Looks Good To Me (LGTM) which was one of the third party code scanning sites that interacted well with GitHub. There are badges in the Readme and even though I helped set it up at this point I honestly don't remember what pieces are involved or if we have any extra info in the docs somewhere :-)

Since then GitHub _itself_ actually acquired the makers of LGTM and embedded the features into GitHub. See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning for some related commentary and links.

I am aware of some of the related GitHub features but have not dug into them much yet. So to get back into the swing of making issues now that I'm "back" (see our Discord) I thought I'd simply write this to leave something easy to look at later, be it for myself or somebody else interested in a super easy issue that could simply be removing the badges from our readme.

There's no need to actually _implement_ any alternatives as part of this issue, but if somebody is curious to write up a little extra comment here on some potential new things / replacements we could look into feel free to add that extra!

**Comment by jdrueckert** [comment]
Removing "needs discussion" label as I believe removing the badges from the readme is a very actionable task. Also adding the "Good First Issue" label to make it more visible for newcomers.

**Comment by Cervator** [comment]
Oh, sure. I tried to use the "doc" issue template and for whatever reason that was a default label :-)

**Comment by jdrueckert** [comment]
> Oh, sure. I tried to use the "doc" issue template and for whatever reason that was a default label :-)

Right, I forgot about that - I think I configured all "request" kind of templates this way as by default I would assume they'd either come from someone community-external in which case we maintainers might want to discuss it first or from someone community-internal who can adjust the labels properly.
