### ISSUE TITLE
Crash while starting

### ISSUE THREAD

**Issue by ghost** [MovingBlocks/Terasology#5103]
### General Info

Terasology Launcher Version: no launcher
Terasology Version: 5.3.0 alpha 23
Operating System: Ubuntu 22.04
Onboard / Dedicated Graphics: RENOIR (renoir, LLVM 15.0.6, DRM 3.47, 5.19.0-45-generic)
Java Version: OpenJDK 11

### What i was trying to do

Start Terasology.

### What actually happened

Many things over different attempts:
- Crashing saying something like: "double-linked list"
- Crashing with [this log](https://github.com/MovingBlocks/Terasology/files/11860514/hs_err_pid7582.log)
- Crashing closing the terminal immediatly and without any log

### How to reproduce

Start Terasology

### Additional Infos / Context

It crashes while initializing module management.

**Comment by Cervator** [comment]
Hey there @Miner34dev - appreciate the report. Could you try to split out the different crashes and include the exact steps you took to provoke them, plus game logging when you do get some? Does not have to be separate issues, just in their own section in your report here. We can't really do much with these details alone, especially when the attempts are jumbled together.

The log you included is from a native Java crash and does not contain the game logging leading up to it, nor do we have any idea what you were trying right before that happened. I did catch this though:

Host: AMD Ryzen 3 5300U with Radeon Graphics, 8 cores, 5G, Ubuntu 22.04.2 LTS

We're currently trying to investigate an issue with Radeon cards, although I thought that might only be on older setups.

**Comment by ghost** [comment]
I just tried to start it executing as a program /Terasology (the shell script) having those results. I 'ill try to start it again to see if i get a more useful log.
Little extra info: my pc is a Lenovo V15 G2 ALC.

**Comment by ghost** [comment]
Wait, why is Terasology starting on OpenJDK-19 Instead of OpenJDK-11?

**Comment by jdrueckert** [comment]
@Miner34dev If you start Terasology via the launcher, it will use the JDK the launcher brings. If you start it directly, e.g. from the zip downloaded from GitHub, then it will the default JDK on your machine.

**Comment by ghost** [comment]
The launcher doesn't work on my computer.
How to make it run on JDK 11 without the launcher? (What to edit in Terasology sh script?)

**Comment by jdrueckert** [comment]
@Miner34dev You don't need to change anything in the Terasology script, as it will simply use your system default. So your system default is what you need to change in order to use JDK 11.
If you don't have a JDK 11 yet, you might need to install it first before you can use it as your system default. We usually suggest https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot to our contributors.

**Comment by ghost** [comment]
Yes! it works!

**Comment by ghost** [comment]
Now closing.
