### ISSUE TITLE
Build from sources failed successfully

### ISSUE THREAD

**Issue by Capewearer** [MovingBlocks/Terasology#5139]
### General Info

Terasology Version: tried 5.2.0 and 5.3.0
Operating System: Windows 10
Onboard / Dedicated Graphics: Intel UHD 620
Java Version: 11

### What you were trying to do
I was trying to build from sources, reading the Contributor Quick Start Page.

### What actually happened

"groovyw module init iota" command doesn't work, causing the bugs. Screenshot shows caused errors. "gradlew game" also doesn't work. Build fails, showing 100 errors (all related to non-existance of net.protobuffer package).

### Screenshots

![screenshot](https://github.com/MovingBlocks/Terasology/assets/145611338/a96606dc-5338-40f3-b30a-13e29bd1079b)

### Additional Infos / Context
I've tried to change Java versions, InteliJ veersions etc. Didn't help. UPD: also tried to run groovyw and gradlew files manually. Also failed.

**Comment by BenjaminAmos** [comment]
Are you using the current `develop` branch?

We've recently upgraded the version of Gradle we use and `groovyw` breaking was an unfortunate side-effect. If you replace the file at `gradle/wrapper/groovy-wrapper.jar` with the one from the latest groovy wrapper release [here](https://github.com/MovingBlocks/groovy-wrapper/releases/tag/v2.2.0) then the `groovyw` commands should start working again.

If you're seeing compilation errors relating to protobuf then you might need to run `gradlew genProto` to generate the protobuf sources. This should have been done automatically but IntelliJ can sometimes circumvent the task that does that.

We're still using Java 11 at the moment for compilation. There are short-term plans to move to using Java 17.

**Comment by Capewearer** [comment]
I have downloaded master branch, but I'll try your proposal to replace Gradle as soon as possible in my time zone (GMT+3). Thanks for proposal.

**Comment by Capewearer** [comment]
Well, you were right about develop branch. It finally worked and launched after "gradlew game" terminal command. Maybe before we shall close that issue, we'll have "Contributor Quick Start" article updated?

**Comment by jdrueckert** [comment]
@Capewearer can you comment on what in particular you'd like to get updated in the "Contributor Quick Start" article?

**Comment by Capewearer** [comment]
It would be good to add the "Troubleshooting" section with list of possible problems with solutions. @BenjaminAmos mentioned "gradlew genProto ", looks like one of possible troubles, known, but hidden for public eyes.

**Comment by jdrueckert** [comment]
@Capewearer I added a section to our troubleshooting docs: https://github.com/MovingBlocks/Terasology/wiki/Troubleshooting-Developer#compile-errors-relating-to-protobuf
They're already linked in the Contributor Quick Start in https://github.com/MovingBlocks/Terasology/wiki/Contributor-Quick-Start#get-help-when-facing-issues

Thank you for reporting this issue and any future issues you might run into 😊
