### ISSUE TITLE
Get "peer not authenticated " error on trying to build the project.

### ISSUE THREAD

**Issue by yili001** [MovingBlocks/Terasology#5159]
### General Info 
Operating System:win10
Java Version: openjdk11

### What you were trying to do

Following the contributor quick start document, I am trying to build the project

### What actually happened
After running command ./gradlew.bat game, it always give the following error(use idea's TerasologyPC run configuration gives same errors too):

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':facades:PC:game'.
> Could not resolve all task dependencies for configuration ':facades:PC:runtimeClasspath'.
   > Could not resolve org.terasology.gestalt:gestalt-asset-core:7.2.0-SNAPSHOT.
     Required by:
         project :facades:PC > project :engine
      > Could not resolve org.terasology.gestalt:gestalt-asset-core:7.2.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://artifactory.terasology.io/artifactory/virtual-repo-live/org/terasology/gestalt/gestalt-asset-core/7.2.0-SNAPSHOT/maven-metadata.x
ml.
            > Could not HEAD 'https://artifactory.terasology.io/artifactory/virtual-repo-live/org/terasology/gestalt/gestalt-asset-core/7.2.0-SNAPSHOT/maven-metadata.xml'.
               > peer not authenticated
      > Could not resolve org.terasology.gestalt:gestalt-asset-core:7.2.0-SNAPSHOT.
         > Unable to load Maven meta-data from https://artifactory.terasology.io/artifactory/terasology-snapshot-local/org/terasology/gestalt/gestalt-asset-core/7.2.0-SNAPSHOT/maven-me
tadata.xml.
            > Could not GET 'https://artifactory.terasology.io/artifactory/terasology-snapshot-local/org/terasology/gestalt/gestalt-asset-core/7.2.0-SNAPSHOT/maven-metadata.xml'. Recei
ved status code 503 from server: Service Unavailable

**Comment by Cervator** [comment]
Hi there @yili001 - that is caused by our Artifactory instance being broken when you tried to build. It seems to be hitting another stretch of crashing once a day or so. I just fixed it so feel free to try again - although it might just be another temporary fix till the next crash.

**Comment by yili001** [comment]
@Cervator Thanks, It works now.
