### ISSUE TITLE
Display active save path in main menu somewhere

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#520]
This one should be easy!

Shiny new PathManager tweaks mean saved files can end up in several different places depending on exact OS (and the optional -homedir command line parameter). As a quick bit of user help I think we should display said path where it makes sense, like the create / load world screens. 

Contributor friendly :-)

Optional bonus: Small button to open (or even change?) said directory in the default directory browsing tool for the OS, if that's easily doable (somewhat have my doubts on this part ...)

**Comment by rzats** [comment]
Closing in favour of #2566.
