### ISSUE TITLE
Clarify whether the pre-built packages run on Apple Silicon

### ISSUE THREAD

**Issue by jernst** [MovingBlocks/Terasology#5213]
... because I can't get it to work, and I notice .dylibs appear to be x86.

**Comment by jdrueckert** [comment]
Hi @jernst,
thanks for the inquiry.
Unfortunately, Apple support is indeed broken for M1/M2 Macs.
This is currently tracked in #5001 / #5055 .

In #5211 @priya4991 recently started fixing parts of it, but it still remains not functional yet.

**Comment by skaldarnar** [comment]
I just got the chance to test out https://github.com/MovingBlocks/JNBullet/pull/16 on an M1 Mac, and I was able to build `libbullet-darwin-aarch64.dylib` for aarch64.
