### ISSUE TITLE
Bug on trying to change display mode to fullscreen : cursor disappears 

### ISSUE THREAD

**Issue by firasmestiri** [MovingBlocks/Terasology#5219]
Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: Windows 10 x64
Onboard / Dedicated Graphics: Nvidia gtx 1650ti
Java Version: Version 8 361

I was trying to change the video settings from windowed to fullscreen

The window changed to fullscreen but I could no longer see the cursor.

### How to reproduce

1. Select Terasology version '.5.3.0'
2. Start Terasology
3. Go to settings
4. Go to video 
5. Go to display mode on the top left (2nd option)
6. Switch to Fullscreen

### Log details

No log details since there was no crash

### Workaround

Since I couldn't see the cursor, I had to guess where it was through the hover highlight on some buttons but then I had to continuously change the position and click in some areas.

### Additional Infos / Context

I reproduced it about 5 times in a row just to check, and then I tried reproducing it after a few minutes of closing the game and it didn't happen again.

**Comment by firasmestiri** [comment]
It seems that the bug was resulted from having the OBS recording software open in parallel

For context I was trying to record another bug I encountered in the game, and after opening OBS the cursor bug started happening but I didn't correlate it at first.

So to reproduce the bug you have to have OBS open in another window (doesn't have to be recording)

Apologies for the oversight

**Comment by jdrueckert** [comment]
Thanks for the bug report @firasmestiri :green_heart: 
That's an interesting one indeed!

Were you able to reproduce it without OBS?

**Comment by firasmestiri** [comment]
you're welcome :)

yes i actually tried to reproduce it, and it seemed to be working fine when OBS wasn't running

**Comment by soloturn** [comment]
there should be a setting in obs to show or hide cursor, isn't it? permit to close @firasmestiri .
