### ISSUE TITLE
Bug on trying to break a block

### ISSUE THREAD

**Issue by Khaled-Dridi** [MovingBlocks/Terasology#5223]
### General Info

Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: 10 x64
Onboard / Dedicated Graphics: Nvidia RTX 2060
Java Version: 17.0.10

### i was breaking sand 

the sand should be destroyed then dropped to me 

### How to reproduce

1. Select Terasology version '5.3.0'
2. Start Terasology
3. make a map 
4. walk until you feel like the FPS is dropping 
5. break a sand block 
6. you will se that the sand block will do the breaking animation and will give you the sand block but in the map you will still see it  

### Log details
No log details since there was no crash

### Screenshots
![image](https://github.com/MovingBlocks/Terasology/assets/95275414/29ad43b0-3bc4-4279-b9a0-42054b003a16)

### Workaround

If applicable, describe any workaround you found to avoid the issue

### Additional Infos / Context

Feel free to add any other context about the problem here.

**Comment by Cervator** [comment]
Heyo - would it be possibly for you to describe which gameplay you were trying out when this happened? JoshariasSurvival?

There actually should be log files, only the crash/issue reporter won't pop up normally unless the game crashes. But alternatively you should be able to just open the game menu then find the reporting utility and logs that way. Or alternatively go right to where the log files are stored on your system - the launcher settings should be able to tell you were that is.

This part is also a bit vague - could you expand on it a bit? Does the game start getting laggy for you pretty fast and consistently, do you need to take any specific actions, can you tell if world generation is struggling to make new chunks near you?

> walk until you feel like the FPS is dropping

**Comment by Khaled-Dridi** [comment]
Hii ok i will try to reproduce the bug and record it

**Comment by soloturn** [comment]
hi @Khaled-Dridi i as well tried to reproduce, but could not. would you be so kind to reopen with more details?

**Comment by Khaled-Dridi** [comment]
> Heyo - would it be possibly for you to describe which gameplay you were trying out when this happened? JoshariasSurvival?
> 
> There actually should be log files, only the crash/issue reporter won't pop up normally unless the game crashes. But alternatively you should be able to just open the game menu then find the reporting utility and logs that way. Or alternatively go right to where the log files are stored on your system - the launcher settings should be able to tell you were that is.
> 
> This part is also a bit vague - could you expand on it a bit? Does the game start getting laggy for you pretty fast and consistently, do you need to take any specific actions, can you tell if world generation is struggling to make new chunks near you?
> 
> > walk until you feel like the FPS is dropping

hii sry i tried to reproduce it many times again but it didn't work, but for more description of the bug when i mine a block it goes into my inventory but when i place it the mechanics is there i can go on top of it and i can brake it again but the textures and shaders don't show up

**Comment by jdrueckert** [comment]
Hi @Khaled-Dridi,
if you cannot reproduce it, then maybe it was a temporary glitch.
Feel free to reopen this if it shows up again for you :slightly_smiling_face:
