### ISSUE TITLE
Inventory management shortcut

### ISSUE THREAD

**Issue by 5archoufa** [MovingBlocks/Terasology#5234]
The inventory could benefit from an "inventory auto-stack" feature. It allows players to quickly consolidate items of the same type in their inventory by double-clicking on an item stack, causing all similar items in the inventory to stack together or on the cursor. This feature helps in managing inventory efficiently, especially when dealing with large amounts of items.

![image](https://github.com/MovingBlocks/Terasology/assets/68157358/fe168af3-91ad-467c-a42e-c3e88275cb24)

**Comment by jdrueckert** [comment]
As this is an inventory-specific issue, I "moved" (unfortunately, GitHub doesn't support cross-org issue move) it to https://github.com/Terasology/Inventory/. Closing this in favor of https://github.com/Terasology/Inventory/issues/53
