### ISSUE TITLE
[macOS Sonoma] Crash "No context is current or a function that is not available in the current context was called"

### ISSUE THREAD

**Issue by a-ivanov** [MovingBlocks/Terasology#5242]
### General Info

Terasology Launcher Version: Launching from IDE
Terasology Version: develop branch (commit 33dabf53cc675c33a2c33c193b7ec4aa1cc0174b)
Operating System: macOS Sonoma 14.4.1
Onboard / Dedicated Graphics: Intel UHD Graphics 630 (x86_64)
Java Version: Liberica JDK 17.0.6

### What you were trying to do

Launched app from IntelliJ Idea with `game (gradle)` configuration and created a new Singleplayer game.

### What actually happened

Game crashed. Tried `TerasologyPC for Mac` configuration with no success. The same commit runs smoothly on Windows 10 though.

### How to reproduce

1. Select Terasology version commit 33dabf53cc675c33a2c33c193b7ec4aa1cc0174b
1. Start Terasology with `game (gradle)` (or `TerasologyPC for Mac`)
1. Select gameplay 'Singleplayer'
1. Add modules 'CoreSampleGameplay'
1. Start game
1. See error

### Log details

```
...
09:33:01.804 [main] INFO  o.t.e.r.dag.RenderTaskListGenerator - ----- OutputToScreenNode
09:33:01.804 [main] INFO  o.t.e.r.dag.RenderTaskListGenerator -                 EnableMaterial: CoreRendering:outputPass
09:33:01.804 [main] INFO  o.t.e.r.dag.RenderTaskListGenerator -         SetInputTextureFromFbo: slot 0, fbo engine:fbo.finalBuffer (fboId: 3), textureType ColorTexture, material CoreRendering:outputPass, parameter 'target'
09:33:01.804 [main] INFO  o.t.e.r.dag.RenderTaskListGenerator - CoreRendering:outputToScreenNode (OutputToScreenNode): process()
FATAL ERROR in native method: Thread[main,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.EXTFramebufferObject.glBindFramebufferEXT(Native Method)
	at org.terasology.engine.rendering.dag.stateChanges.BindFbo.process(BindFbo.java:62)
...
```

**Comment by soloturn** [comment]
could you please try to get a fatal error log, maybe like this:
https://docs.oracle.com/en/java/javase/17/troubleshoot/location-fatal-error-log.html#GUID-6903F4A6-326C-403F-9DF0-475DC50F42F8 ?

**Comment by a-ivanov** [comment]
I would really love to.

Tried -XX:ErrorFile JVM arg with different paths and file names, to no avail. I run `TerasologyPC for Mac` configuration from Idea like 

```
/Users/.../java -Xms256m -Xmx1536m -XstartOnFirstThread -XX:ErrorFile=<relative or absolute path>java_error_another_one%p.log -Djava.awt.headless=true -javaagent:... org.terasology.engine.Terasology --homedir=. --no-crash-report --no-splash
```

No log file is generated. Definitely have permission to write to home dir, process working dir, etc. Checked `/tmp` dir, no logs there. 

Maybe you have more pointers to try.

**Comment by jdrueckert** [comment]
@skaldarnar any ideas here?

**Comment by a-ivanov** [comment]
Fixed the crash.

In `org.terasology.engine.rendering.dag.stateChanges.BindFbo` changed call to `glBindFramebufferEXT` (argument `GL_FRAMEBUFFER_EXT`) with `org.lwjgl.opengl.GL30.glBindFramebuffer` (argument `org.lwjgl.opengl.GL30.GL_FRAMEBUFFER`).

It seems that my graphic driver does not have `glBindFramebufferEXT` implementation or smth.

**Comment by jdrueckert** [comment]
Interesting find @a-ivanov ! Great that you got it working :clap: 
I'm wondering whether this is an issue we see on other MacOS machines, too, and that your fix would also help resolve...
@Cervator @skaldarnar would you be able to check on your MacOS machines, whether you can (1) reproduce the crash and (2) apply the suggested fix to resolve it?

**Comment by skaldarnar** [comment]
Tests out fine on my M1 Mac, and the fix is in line with a TODO comment in that file. 👍 

I've created #5260.
