### ISSUE TITLE
Outdated Documentation and Broken Links

### ISSUE THREAD

**Issue by kierrayoung** [MovingBlocks/Terasology#5247]
Hello! I'm new to the project and was looking through the documentation to get started as a developer. Looking through Codebase-Structure.md, it looks like several of the links to other resources are broken, especially those linking back to forum.movingblocks.net. For example, the IDEA IntelliJ custom set up link is broken.

**Comment by BenjaminAmos** [comment]
External links in the documentation may be a bit broken however I believe the content is still relevant. These need to be fixed but whilst we do that you should be able to use the following substitutions:
 - `*.movingblocks.net` -> `*.terasology.org`
 - `jenkins.movingblocks.net` -> `jenkins.terasology.io`
 
 > For example, the IDEA IntelliJ custom set up link is broken

Which link is this? The custom set-up instructions should be inline with the documentation, so there shouldn't be a broken link at all.

**Comment by jdrueckert** [comment]
@BenjaminAmos Created a fix for this: #5249 
I believe the mentioned intellij link is http://forum.terasology.org/threads/how-to-use-this-forum.33/#post-8778
