### ISSUE TITLE
L&S - Poker chip tree art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#541]
We need block shapes and textures to support the poker chip trees - concept art at http://forum.movingblocks.net/threads/light-and-shadow.762/#post-7537

I imagine the "crown" of these trees to be about 3x3x1 and in theory they could be octagonal with just a simple slope in each "corner" - but maybe we can do better than that :-)

Individual textured blocks would be fitted together by a custom tree generator

Asset target location: https://github.com/MovingBlocks/Terasology/tree/develop/mods/lightAndShadow/assets

**Comment by rzats** [comment]
This issue was moved to Terasology/LightAndShadow#9
