### ISSUE TITLE
L&S - Tree Generator

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#542]
Custom tree generator for new poker trees described in #541 

Closest example class to clone might be org.terasology.world.generator.tree.TreeGeneratorLSystem

Functionality could be as simple as picking between a couple different block variants in the same simple shape. Alternatively we could use some sort of tree blueprint / grammar (to help support other L&S tree types later) but that might be too fancy.

**Comment by rzats** [comment]
This issue was moved to Terasology/LightAndShadow#10
