### ISSUE TITLE
L&S - Red Pawn art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#547]
Need the right files for the Red Pawn in the right places :-)

Based on an oreon miniion we need:

- [x] Animation in .md5anim format
- [ ] Materials file in a .mat file format. I guess this is one of our simple file/asset (text) formats that references the texture png
- [ ] Prefab that ties everything together
- [x] Skeletal mesh in .md5mesh format which I guess is the model itself
- [x] Texture png - this is the UV mapping thing that gives the model its skin

I've left placeholders with minimal content in https://github.com/MovingBlocks/Terasology/tree/develop/mods/lightAndShadow/assets as a simple example - works, too! If left as "oreon" in the prefab's Spawnable a placed "portal" will spawn the creature occasionally.

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/14.
