### ISSUE TITLE
Weird keyboard behavior

### ISSUE THREAD

**Issue by mbrotz** [MovingBlocks/Terasology#551]
Since i am playing around with terasology i've experienced some weirdness in keyboard behavior. Sometimes the return key doesn't work in chat/console, and sometimes i cannot fly when i hit the space bar twice. 

Finally i discovered what causes the return key's malfunction: It's NUM LOCK! With NUM LOCK disabled, the return key is working fine. With NUM LOCK enabled, nothing happens when i hit the return key.

I still don't know what causes the malfunction of the space bar, though...

**Comment by rzats** [comment]
Couldn't replicate this on Win10/Ubuntu VM and it sounds like an OS-specific issue that might have been fixed _looooooooooooooong_ ago. Closing for now - if someone experiences a similar issue in the future it can be handled separately.
