### ISSUE TITLE
L&S - Backgammon tree art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#552]
Another type of tree the L&S tree gen (#542) could place in the world defined by SuperSnark - reference: http://forum.movingblocks.net/attachments/map-png.1021/

Block shapes again, this time maybe very steep slopes going from 2x2 at the bottom to a tip 3-4 blocks up? Plain white or black blocks and trunk in the reverse.

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/15.
