### ISSUE TITLE
L&S - Card Crags (tree) art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#553]
While these are realistically more likely to be a type of boulder from the engine side it would still be the easiest to seed them as trees via #542 

Picture them as large rounded rectangle slabs stacked up against each other like card houses. There's probably a way to pull that off with some nice shapes.

Textures could be plain white / slate gray or possibly full on playing cards? That would be pretty awesome but might make each "card" quite large.

Reference: http://forum.movingblocks.net/attachments/map-png.1021/

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/16.
