### ISSUE TITLE
L&S - Billiard Bluffs (trees) art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#554]
Again easier to think of these as trees as that's an easy way to place them in the world - although these definitely would fit more like boulders in the world :-)

Simple large sphere made out of multiple smaller shaped blocks. Similar to the #541 poker trees, maybe the shapes from there can be used for the billiards too (although we still need the "corner" rounded shapes)

Reference: http://forum.movingblocks.net/attachments/map-png.1021/

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/17.
