### ISSUE TITLE
L&S - Domino piece (tree) art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#555]
Moar weird "tree" shapes!

Reference: http://forum.movingblocks.net/attachments/chessworld2-png.1018/

Might be a smaller differently textured version of the Card Crags (#553). I don't think we really need the grooves / dents in the dominos ...

Edit: I think the textures from here could double as normal blocks so they can be used as roads in "Domino Dominion" - yet the upright ones might need custom thinner shapes? A 2-tall one block thick standing domino would seem really "fat"

Alternatively larger 2x8 standing dominos might work and double as roads.

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/18.
