### ISSUE TITLE
L&S - Carrom Corners decorative blocks

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#556]
Mainly floor decorations (the central "star") - the buildings and outline could probably be done by simple red and black blocks. Speaking of: We need something as simple as full red/black blocks ;-)

Reference: http://forum.movingblocks.net/attachments/map-png.1021/

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/19.
