### ISSUE TITLE
L&S - Pachisi Planes central Tao symbol

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#557]
While we need the plain red/block blocks for the floor (easy) we should have something special in the center, as it might double as the roof of the secret room holding the white wand. Rather than the diamond square on the map (http://forum.movingblocks.net/attachments/map-png.1021/) I propose we shape a large red/black tao on the ground with textured blocks (at least 20x20, maybe bigger?)

It might be doable with straight up square full-color blocks but some diagonal two color blocks might help, if not outright circle pieces (still all in flat blocks, no special shapes needed)

**Comment by Cervator** [comment]
Partial effort (or even fully ready just needing a merge) available at https://github.com/Terasology/LightAndShadowResources/tree/YinYang

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/20.
