### ISSUE TITLE
L&S - Secret room grand Tao 3d decorative animated model

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#558]
I was thinking about something special to put in the secret room with the wind wand and came across something that IMHO would look *awesome* as an animated model floating in the air a few blocks above the white wand:

![3dtao](https://f.cloud.github.com/assets/1063833/652323/5760d7cc-d49f-11e2-9a5a-ff5efe6a2712.gif)

Naturally it would be black/red instead. Maybe a custom model roughtly 3x3x3 in size that is fully animated like the gif?

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/21.
