### ISSUE TITLE
L&S - Banner blocks (think vines)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#559]
Simple chevron type banner blocks you could stack vertically as decorations. Or narrow vertical bands, or something. Easy :-)

Red/black/white combos, probably two versions (one for each side)

Bonus: For the fun of it these could be like vines or ladders - two-dimensional shaped blocks rather than full blocks you could actually climb up. Isn't that always what people in movies do with banners anyway? ;-)

**Comment by skaldarnar** [comment]
Will be available in LaSR soon :wink: 

![terasology-150125212704-1152x720](https://cloud.githubusercontent.com/assets/1448874/5893141/16d205e4-a4d9-11e4-9b6e-8001c4eed121.jpeg)

**Comment by emanuele3d** [comment]
Pretty!

**Comment by Cervator** [comment]
:winner: :D
