### ISSUE TITLE
L&S - "MacGuffin" block for each side (capture the flag style)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#560]
Each side needs a "flag" of some sort in the very center of their base. A "MacGuffin" is some arbitrary object the other side really *REALLY* wants, not necessarily for any obvious reason. This could be as simple as a flag block, a shaped block (a big card symbol for each side?) or something more fanciful.

Ideally it should be a single block, optionally shaped. That allows the player to break the block and pick it up, triggering the quest module @nh-99 is working on

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/22.
