### ISSUE TITLE
L&S - Victory condition quest

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#561]
To go with the MacGuffin in #560 we need an actual "victory quest" which likely is bringing said item back from the enemy base to the home base and placing it in the very inner sanctum next to the home MacGuffin.

If the player picks up the enemy MacGuffin the quest should remain active either until victory *or* the player is killed, in which case the quest should trigger a failure (but not game defeat) condition where the MacGuffin either spawns where the player died or reappears back home.

Could also be traditional CTF where the item drops and any player can pick it back up - if a friendly then the object warps back home immediately.

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/23.
