### ISSUE TITLE
L&S - collection quests

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#563]
Basic starter quests simply consisting of the traditional "go fetch me 10 x!" in this case likely minerals (#562), flowers (#543), or blocks from the assorted "trees"

Completion should be acquiring enough of block x then returning to a location. Reward should be spawning some friendly NPCs (later on we can get fancier and have more of a "tech tree" that could also give bonuses and so on)

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/24.
