### ISSUE TITLE
L&S - Custom ChunkGenerator based on a static heightmap

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#564]
We need a clone of BasicHMTerrainGenerator that reads a different heightmap that'll be used every time for L&S games. Some ideas - not sure which are appropriate for use within this chunk gen:

- [ ] Can we draw biome detail straight from the heightmap and cut the world into the 9 distinct zones making up the world? Reference: http://forum.movingblocks.net/attachments/map-png.1021/
- [ ] Could biomes be made to pick the correct "tree" type for the zone at hand?
- [ ] Could static locations (the castles, villages, and central parchisi board) be placed via the heightmap somehow?

Heightmap should also be fairly small - the L&S world (starting out at least) should be pretty tiny to make it easier to deal with. Maybe investigate how the edges of the world would handle?

I've talked to @mpratt about this in the past so tentatively assigning him. @nymtraveel might also be back in business soon and able to help out :-)

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/25.
