### ISSUE TITLE
L&S - Red Queen art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#569]
Again already almost done by @glasz 

Also: OFF WITH THEIR HEADS!

![offwiththeirheads](https://f.cloud.github.com/assets/1063833/657657/26151cb4-d56c-11e2-94d9-5188b544f797.jpg)
 (glasz edit) model and texture mostly done (texture might be the wrong red, as in not the same red as the other pieces, model needs hands and scepter / tools) skeleton done but might need fixing, walk animation done, needs more anims

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/27.
