### ISSUE TITLE
L&S - Red Knight art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#573]
Concept art in thread, need model etc! Need somebody to volunteer for this one and we'll assign that person to avoid conflicts

http://forum.movingblocks.net/threads/light-and-shadow.762

(glasz edit)
model, texture, skeleton, walk anim done, needs weapons/tools, needs more anims

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/31.
