### ISSUE TITLE
L&S - "Dice" catapult ammo art assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#581]
Pretty straight forward: A block that looks like a 6-sided die, with the appropriate number of dots per side ;-)

(would be hilarious to base damage on the side of the die that hits the target but lets not go crazy ...)

**Comment by Cervator** [comment]
We have a bit about dice blocks now at https://github.com/Terasology/TutorialAssetSystem/wiki/Add-A-Dice - maybe we could add that to LAS/LASR using the assets there - https://github.com/Terasology/LightAndShadowResources/tree/master/assets/textures

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/38.
