### ISSUE TITLE
L&S - Command map

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#583]
This one could be fun and impressive!

We currently have the "Miniaturizer" - mods\core\assets\prefabs\miniaturizer.prefab

It creates a miniature chunk of a selected area (by player tool) shrunk down to about a single block's size.

Rather than allow command & control of creatures via a separate map GUI / overlay you have to pull up (think some of the fancy FPSes that allow that) imagine having an actual "map" of the world, placed on a large table, in the throne room, in front of the commanding king ...

Now modelling the entire world in a mini chunk would be a tall order, but if the world is small enough and we allow the minituarizer to be less granular for its detail level (really half-way between the current mini chunk and the world's backing heightmap) I bet it could be done. Heck we might just need a fancy heightmap showing nicely in-game instead.

The current sort of "holographic" look of a mini chunk might even work in our favor. Some notes:

- [ ] Start by supporting a granularity setting in the current miniaturizer - maybe one mini block per real chunk would be a decent ratio for a world map? L&S world should start small ..
- [ ] Support having the map update (and initially generate) slowly - hardly needs to be real time (slow background task? Could take many minutes to fully initialize) and if one block = one chunk we can probably be smart about when updates happen. Don't really care about small changes either, just when somebody blows the top off a hill or topples a tower
- [ ] Support showing landmark tokens / captions on the map (probably baked into the original heightmap)
- [ ] Support showing structure markers on the map when a player manages to build (and make "official") a tower or other structure
- [ ] Support showing tokens on the map of specific creatures (or squads if that eventually makes more sense) that we care to track (the chess pieces)
- [ ] Support a command interface right on the map in-game, no separate GUI screen necessary. Maybe the edge of the map table has spots for unit types, first click spot to select unit, then click map to issue move/attack order

Crazy, I know! If only GitHub supported rainbow post ratings.

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/39.
