### ISSUE TITLE
L&S - "Class" line-up and effects

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#586]
Like #585 but for the chess piece "Classes" - including graphic detail "cards" to show them and their abilities that we can use for documentation and help in-game. SuperSnark already working on it

Might go something like this - keeping in mind the idea that the player can either spawn as or possess the different chess pieces to adopt a class akin to in FPSes

Pawn = Standard grunt, low death penalty, always free. Could be the only class to later be able to work siege engines? To give them something unique. Maybe the player embodying a pawn enables squad command.
Rook = Tank / "Heavy". Bit more expensive, fair bit more powerful. Slow. Built-in battering ram?
Knight = Mobile and fast. Ideal for side quests / gathering materials for the war effort ;-)
Bishop = Ranged attack (bowman?). I'm amused by the idea of making them Warhammer 40k "tech priests" to handle engineering duties ;-) SuperSnark might be wanting a separate engineer though :D
Queen = Ultimate fighter with both a powerful ranged attack that can help destroy walls/towers and a powerful melee attack probably focused on decapitation ("off with their heads!"). Likely very expensive to play / ultimate attack.
King = Commander. Stays back in the throne room. Might manage #583.
Fool = Total wildcard. Arbitrary, able to fill any role at mediocre strength. Possible role the player starts as?

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/42.
