### ISSUE TITLE
L&S - Tower turret blocks

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#591]
Depends on #590 which itself likely depends on multiplayer, but it is possible we can do the art assets early and at least *pretend* the blocks can shoot arrows in the meantime :-)

Idea is that these turret blocks will be placed by players in towers (possibly with a few initial towers placed in the world on startup) and be the main defense against enemy NPC waves.

The power of the turrets should be able to vary both on quality of materials (upgradeable) and the possible addition of an actual power system (#589)

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/45.
