### ISSUE TITLE
L&S - Extensibility - Maps

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#592]
Add support for custom (user-made) maps, stored in a directory besides the »savegames« in the program data dir. Users should be able to simply drop new height maps into that folder.

- [ ] read in all height map files (*.jpg, *.png, ...) from a folder and display in list when starting a new game
- [ ] show a preview of the selectey map
- [ ] support subfolders and additional information files (e.g. myMap.jpg and myMap.txt)
- [ ] offer (random) procedural maps

Maybe something like this could work for the questing as well, @nh-99?

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/46.
