### ISSUE TITLE
L&S - Very basic growth sim

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#596]
This isn't meant to be a "fancy" growth simulator of any sort, but a simple "check for crops every minute or so then increment the growth stage" to go with the art assets in #580 

Should be fairly straight forward. Could be done with the ES using GrowthComponents attached to the crops and a System checking anything with a growth component once in a while and adding another block of height. Not sure if that would cause too many entities. Or just one per crop type + next gen ES magic in the multiplayer branch to get all fitting blocks in a chunk?

Could also adapt the door / diamond ace for the multi-block approach so the whole thing breaks as once. Or alternatively the billboard check used to make grass "break" if the supporting block is broken. In theory you could possibly harvest only the top of the plant and leave the lower blocks in place?

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/47.
