### ISSUE TITLE
L&S - Player avatar

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#597]
Putting here mainly as a reminder / requirement. Has a few possible solutions

- [ ] @SuperSnark has mentioned working on an "Adventurer" concept that the player could spawn as (would need both the concept + work for new model)
- [ ] @glasz has offered to throw something temporary together
- [ ] We could just use one of the existing L&S pieces like the Red Fool

Either way we'd need to actually attach the player to said model. Player already has a placeholder model in the multiplayer branch.

Could also be nice to support skinning for the "default" player model. This wouldn't affect gameplay with set models like in L&S

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/48.
