### ISSUE TITLE
L&S - Primitive Combat (GelCube style)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#603]
Rather than the "bigger version" over in #590 this is intended as a minimal "combat" system using the super simple technique used for the "danger cubes" at \mods\portals\assets\prefabs\dangerous

The danger cubes if enabled currently (via portals module, spawned by greenportal) will actively hunt down the player and cause damage. That can probably be hacked about a bit to make them damage each other / other gelcubes / applied to L&S mobs.

This would be a temp solution that would work in the develop branch (no portals stuff converted for multiplayer yet). It should theoretically allow the two sides to send waves of symmetrical violence toward each other in perfect balance, until the player disturbs it (with health potions available!)

Maybe something learned from this can be applied to improved combat over time / help (re)implement #590 later. Maybe @MarcinSc will be interested :-)

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/49. Engine tracker should now be L&S-free!
