### ISSUE TITLE
Weirdly hard to see water in low block light conditions?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#656]
Best described with a before/after screenie (all graphic settings default, found cave intersecting river deep underground)

Now you see it:

![terasology pre alpha_2013-07-13_23-13-06](https://f.cloud.github.com/assets/1063833/793728/d1f41b88-ec33-11e2-928e-1ff083c0ee96.png)

Now you don't:

![terasology wiki - edevterasologygitterasology wiki - terasology wiki - _2013-07-13_23-13-17](https://f.cloud.github.com/assets/1063833/793730/dd29f3ec-ec33-11e2-8eea-16043d60cb5e.png)

Guessing the issue relates to the held torch lighting up the surrounding blocks but not the water, yet the _placed_ torch applies to both. Or something like that.
##

**Comment by Cervator** [comment]
Old issue bump! This seems to still be valid today, after a round of lighting tweaks in #2247. Wanted to give some older maybe related issue a retest just to see if they have gone obsolete or not. Nope!

![terasology-160325221446-1152x720](https://cloud.githubusercontent.com/assets/1063833/14057549/c4fd2d8e-f2d9-11e5-9577-ab9ceefebfe5.jpg)

**Comment by 4Denthusiast** [comment]
This is probably because the player-held lights are applied to the opaque geometry with the DeferredPointLightsNode, which is before the ChunksRefractiveReflectiveNode where the water is rendered.

**Comment by jdrueckert** [comment]
Cannot reproduce this anymore:
With placed and held torch:
![image](https://github.com/user-attachments/assets/e110a3f8-81df-46de-855a-786302d07226)

Without placed torch but with held torch:
![image](https://github.com/user-attachments/assets/43c3a856-4780-430a-9d6e-1675599ebcd7)

Without placed and held torch:
![image](https://github.com/user-attachments/assets/142f88ea-4b71-4bff-8be0-49b0bfa8aab3)
