### ISSUE TITLE
Hires icons / one-icon-per-file support

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#657]
We've got some existing icon support in both modules and engine but there is a utility class floating around in modules that binds locations in an icon atlas to names (ModIcons.java). Maybe that really should be an engine level thing / asset support like individual block tiles auto-registering by filename.

Hires support for icons then might also be easier/doable.

**Comment by skaldarnar** [comment]
Items can be created with a simple .prefab and a one-icon-texture file - closing.
