### ISSUE TITLE
Stereo SFX don't drop in volume as distance to player increases

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#663]
Noted by @immortius while testing in multiplayer - stereo sfx won't drop in volume as distance from player increases. We should make sure everything is mono for now.

Music should still be stereo.

We should make this restriction clearer to users of this API. On the one hand, we need documentation that states this limitation in place discoverable by developers. On the other hand, we may want to make this even more obvious by throwing an exception in case the audio system fails to process the sound effect correctly, e.g.,

```java
throw new AudioSubsystemValueError("Tried to assign a direction vector to a multi-channel audio source", sound);
```

**Comment by Cervator** [comment]
minnesotags from IRC was nice enough to look at this, and it looks like only the camera click noise and drink were in stereo.

In addition to mono versions of those two he added a few new sfx.

I put them here for now: https://github.com/MovingBlocks/TeraMisc/commit/1866899a2b2fb393b216381d7022831432980238

I realized I'm not sure we want to keep the sfx in engine long-term, but that it is probably too early to split them out (really need better ways to bundle more modules easily first). Maybe an IotaSfx module for base sounds?

Naturally we could still add more sfx :-)

**Comment by Cervator** [comment]
The stereo/mono location issue may be gone now after #2177 - leaving this open though since the assets are unaffected and still need to be integrated sometime.

**Comment by skaldarnar** [comment]
This is still an issue today :disappointed:

**Comment by skaldarnar** [comment]
I think all existing issues were resolved and we added more documentation to avoid this in the future.
