### ISSUE TITLE
Torch light sums up to quickly.

### ISSUE THREAD

**Issue by mcourteaux** [MovingBlocks/Terasology#667]
When throwing a few torches at the same spot, the light is way too bright. The place is almost entirely white (0xFFFFFF) on the screen. Maybe some kind of asymptotic function should be used to determine the amount of lighting? I'm thinking of something like: 1-e^(-x)
http://fooplot.com/plot/ppv7mmbnes

**Comment by getsmp** [comment]
Confirm that. Same applies to lava source.

**Comment by emanuele3d** [comment]
Lighting is a bit screwed up right now. I might be able to fix it, but I still have to go through a lot of code to understand it all and, more importantly, become agile with it.

**Comment by Cervator** [comment]
Closing as fixed by #2247! Still more tweaking to do in lighting (and shader?) land but light sources no longer go crazy :-)
