### ISSUE TITLE
We got a second sun and not the good kind ;-)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#693]
I've noticed this for a while but wrote it off as another one of the weird shader issues afflicting me. Turns out @immortius gets it too, yet not the shader issues.

A little dim sun hangs out right by the horizon line mostly visible at night (next to the moon-sun in the following screenie:)

![sneakysun](https://f.cloud.github.com/assets/1063833/1223292/62dbc49e-2716-11e3-9d87-c33c9a4aecca.png)

Investigated a bit and it is introduced by https://github.com/MovingBlocks/Terasology/commit/d872bf701f59bcc02411846a00fb1f93aa5aaacd

This wasn't the way I was hoping for multiple celestials :D
##

**Comment by emanuele3d** [comment]
Ok, just had a look at this one. It is really just a texture issue: a bright orange blurry streak needs to be painted out of the texture. Unfortunately it is a humble but artistic task, which is not exactly my cup of tea. I just tried to delegate to pruteanu. If that doesn't work I'll ask in the Art and Media forum. Anybody proficient with a paint program won't need much time to fix it, I just do not have that kind of proficiency having spent most of my career in 3D programs such as Maya and Softimage. Paradoxically it might have been quicker for me to fix if it was a shader or programming problem. =)

**Comment by Cervator** [comment]
Closing as fixed by #2871 at long last :-)
