### ISSUE TITLE
Switching out of Terasology makes mouse unusable on Linux

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#699]
Switching out (alt+tab) out of Terasology on Linux is still bugged. I can't use mouse after that (it doesn't seem to generate any system events, like click, etc), so in order to continue using computer I have to run terminal using keyboard only and pkill java.
##

**Comment by pollend** [comment]
using a new version of lwjgl 3 so not sure if this is still applicable.
