### ISSUE TITLE
Human friendly player identity for multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#705]
Currently clients are identified with a certificate helping the server keep track of who's who. That doesn't help the actual player in-game very much though!

In the game menu a player should be able to enter their name, which would then be sent to the server along with their certificate. Server keeps track and disallows duplicate names on different certs (maybe need a way later to clean obsolete certs if a player loses theirs but want the name back)

Player name should also be used with the say command in the console and probably hovered over their character model.

Bonus: Throw in a random monkey head color on new player creation

- [x] Name entry in GUI
- [x] Name associated with cert
- [x] Name conflict resolution on server
- [x] Name used in console chat
- [x] Name used in-world on/above player model
- [x] Monkey monkey monkey

**Comment by Cervator** [comment]
@flo - would you say this is complete other than the floating name in-game? Though I could swear somebody had that mostly done at one point, in relation with tooltips (@Josharias comes to mind for some reason)

The name associated with cert thing is what I'm thinking works now

Related:  #1433

**Comment by flo** [comment]
http://forum.terasology.org/threads/worldly-tooltip.1092/

**Comment by Cervator** [comment]
Ah-hah, yes, that's what I was vaguely remembering. Anything other than free time get in the way of finishing it? It looks so close to complete.

**Comment by msteiger** [comment]
Update: The player name now defaults to `System.getProperty("user.name")`.

@flo great to hear. Do you think that could be used for other world entities such as NPCs and town names, too?

**Comment by flo** [comment]
@msteiger: yes that was the idea. I am currently in the IRC chat and have a question about the PolyWorld. It would be cool if you could come.

**Comment by Cervator** [comment]
Closing as fully completed some time ago, woo.
