### ISSUE TITLE
Automated game doc intro within source code?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#72]
I'm wondering if we could come up with a good way to use a central location under source control to define the main "game help" section for what keys do what and such, then automate the update of related game info in the GitHub description, a wiki page for game doc, and any other place that makes sense.

While this doesn't necessarily mean also implementing a game help screen in-game whatever format should be readily usable for said help screen be it for application or applet

This could be particularly helpful during the early stages on identifying which tool is which - or we could just attach a description string to each Tool and do an on-hover?
##

**Comment by jellysnake** [comment]
Closing as the broad idea has been spun into a few different issues and features
