### ISSUE TITLE
Module Overhaul - Adventure

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#725]
What time is it? Adventure time!

This module is by @MrBarsack who I hope can review it for use with the multiplayer/restructure changes real quick. Code is pretty minimal but does deal with changing blocks.

Also would be great with any other fun new blocks added :-)

New home: https://github.com/Terasology/Adventure
Jenkins: http://jenkins.movingblocks.net/job/Adventure

Command to fetch: 

`gradlew fetchModuleAdventure`
##

**Comment by skaldarnar** [comment]
We want to overhaul all the modules, no need to keep track of this one specifically here.
