### ISSUE TITLE
Module Overhaul - Crafting

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#728]
This module is another big one to convert for the new multiplayer/structure changes. It involves involves a fair amount of GUI stuff that could involve #720 and is a novel yet complex beast :-)

There are other related pending issues like #481 and #509 and lots of discussion in the forum

Original author is @small-jeeper - hoping he can take a look at bringing the base functional version up to speed. Ideally that would include related functional changes but I think it would be nice just to have working as-is too

New home: https://github.com/Terasology/Crafting
Jenkins: http://jenkins.movingblocks.net/job/Crafting

Command to fetch:

`gradlew fetchModuleCrafting`
##

**Comment by jdrueckert** [comment]
Closing this as the module has been archived by now (https://github.com/Terasology-Archived/Crafting) and is subject to a rewrite - if at all.
