### ISSUE TITLE
Module Overhaul - DynamicBlocks

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#729]
This module was originally done by @pencilcheck and later used in part by @small-jeeper to help start on an outright minecart module if I remember correctly.

It is fairly small, code-wise, not sure how much work it would be to dust it off real quick - hopefully not too much if @pencilcheck would be up for taking a look :-)

Alternatively if @small-jeeper can commit his nice minecart module working in the new structure maybe that entirely eclipses this? I know you're both around, come say hi :D

New home: https://github.com/Terasology/DynamicBlocks
Jenkins: http://jenkins.movingblocks.net/job/DynamicBlocks

Command to fetch:

`gradlew fetchModuleDynamicBlocks`
##

**Comment by skaldarnar** [comment]
We want to overhaul all the modules, no need to keep track of this one specifically here.
