### ISSUE TITLE
Module Overhaul - GrammarSystem

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#730]
This one is for @skaldarnar since it is his system and he is still very much active with it - even starting a new-style structure repo elsewhere playing with the grammar fun :-)

https://github.com/skaldarnar/PAG

I know sdab from the forum was also active on specifications in the wiki, but not sure if we've got him on GitHub

I figure we need to update and enhance this one both for the multiplayer/structure changes as well as for the batched lighting when actually placing grammar-based structures in the world (using the batched approach rather than the existing  crushing lag block-by-block approach)

New home: https://github.com/Terasology/GrammarSystem
Jenkins: http://jenkins.movingblocks.net/job/GrammarSystem

Command to fetch:

`gradlew fetchModuleGrammarSystem`
##

**Comment by jdrueckert** [comment]
Closing this as the module was archived by now (https://github.com/Terasology-Archived/GrammarSystem) and is subject for a complete rewrite.
