### ISSUE TITLE
Module Overhaul - Portals

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#736]
Another one for meeee - unless somebody else wants it :-)

Portals needs to be updated to work in multiplayer, since the spawning should only be triggered server side, not on every client independently.

The creatures in this module should be able to take advantage of the new pathfinding / jobs soon - if it takes long enough to get around to this that would probably be included here.

New home: https://github.com/Terasology/Portals
Jenkins: http://jenkins.movingblocks.net/job/Portals

Command to fetch:

`gradlew fetchModulePortals`
##

**Comment by skaldarnar** [comment]
We want to overhaul all the modules, no need to keep track of this one specifically here.
