### ISSUE TITLE
L&S - "Gray" flora art asset

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#748]
Idea to go with the "card suit color" flora blocks - an "unclaimed" version of the suit flowers that the player could tag with a tool of some sort to turn into flowers following their side, yielding some sort of benefit like territory claim / regeneration for nearby friendly.

Edit: There are existing faction-specific versions at https://github.com/Terasology/LightAndShadowResources/tree/master/assets/blockTiles/flora

**Comment by rzats** [comment]
Moved to https://github.com/Terasology/LightAndShadow/issues/43.
