### ISSUE TITLE
Player hand / held tool is translucent in some circumstances

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#764]
This is a quirky one, predates the big #760 PR after it was noticed some more, may even date back to #665 which I'm going to close now in favor of this.

Screenie:

![terasology-131127220024](https://f.cloud.github.com/assets/1063833/1637504/2d511768-57ed-11e3-8005-8f16b70d8d47.png)

Now for the quirky part: This seems to consistently happen on the *first* time you start a game ever in one particular game data directory. But I fell off a mountain by accident, respawned .... and my hand/tools were then completely solid again. Went to main menu, started a branch new world, and hand/tool were *still* solid

Started with a brand new dir and hand/tools were translucent again. This time dying or starting a new game didn't make it solid.

All settings default with latest develop branch as I submit this

Weird!

**Comment by emanuele3d** [comment]
This seems to be a FrameBuffer related issue and might have been fixed by my latest PR, introducing the FrameBuffersManager. Can you check?

**Comment by Cervator** [comment]
I haven't seen this for ages now. Yeah it is likely fixed, will close as such :-)
