### ISSUE TITLE
Module Overhaul - Fences

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#796]
Not sure how I missed this one - but ~~fences currently aren't auto-adjusting their shape and~~ the gate has gone missing. I think it used to work before the great convergence but now the Fences module only has a few blocks in it, no gate, and no dynamic action.

- [x] automatic **shape adjustments**.
		`FenceSystem` that allowed them to adjust: https://github.com/MovingBlocks/Terasology/pull/427/files
- [ ] Bring back **gates** (https://github.com/Terasology/Fences/issues/2)
		PR that included gates: https://github.com/MovingBlocks/Terasology/pull/446/files

**Comment by ArihantJoshi** [comment]
Is someone still working on this??
Can I work on it?

**Comment by Masolria** [comment]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by jdrueckert** [comment]
Superseded by https://github.com/Terasology/Fences/issues/2
