### ISSUE TITLE
Miniaturizer seems broken

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#798]
Just noticed it isn't highlighting blocks or shrinking anything at all. Probably broke during the great convergence or when we extracted a pile of stuff to the Core module

It needs more work anyway and there are related concepts like #583 that could be nice to work into an overhaul. Also still _really_ want that dynamically created normal block from a miniaturized selection ;-)
##

**Comment by skaldarnar** [comment]
The miniaturizer was removed a long time ago, last traces in #1582. Closing as outdated.
