### ISSUE TITLE
add description of engine:checkStyleMain to gradlew tasks output

### ISSUE THREAD

**Issue by mkienenb** [MovingBlocks/Terasology#823]
I couldn't figure out the way to do this, so no patch, but if possible, we should add engine:checkStyleMain as an option from gradlew tasks.

Glancing at the source, it looks like it should be done with a description="" setting for the checkStyleMain tasks, but I couldn't find that task (and maybe I'm completely wrong anyway).

I'm guessing this is because checkStyleMain is a checkstyle plugin task and not a Terasology one, but I guess we could make something that calls checkStyleMain?   checkstyle, all lowercase, would seem like an obvious choice.
##

**Comment by jdrueckert** [comment]
checkstyle and pmd tasks by default are added to the "Other Tasks" group which is not shown in the output of `gradlew tasks`, only in the output of `gradlew tasks --all`. #5261 adds checkstyle and pmd tasks to the "verification" group instead, so they show up next to the spotbugs tasks. With this, their task description is also visible:
```
Verification tasks
------------------
check - Runs all checks.
checkstyleJmh - Run Checkstyle analysis for jmh classes
checkstyleMain - Run Checkstyle analysis for main classes
checkstyleTest - Run Checkstyle analysis for test classes
integrationTest - Runs integration tests (slow) tagged with 'MteTest' or 'TteTest', exclude tests tagged 'flaky'.
integrationTestFlaky - Runs integration tests tagged with 'flaky' and either 'MteTest' or 'TteTest'.
pmdJmh - Run PMD analysis for jmh classes
pmdMain - Run PMD analysis for main classes
pmdTest - Run PMD analysis for test classes
sonar - Analyzes project ':engine' and its subprojects with Sonar.
sonarqube - Analyzes project ':engine' and its subprojects with Sonar. This task is deprecated. Use 'sonar' instead.
spotbugsJmh - Run SpotBugs analysis for the source set 'jmh'
spotbugsMain - Run SpotBugs analysis for the source set 'main'
spotbugsTest - Run SpotBugs analysis for the source set 'test'
test - Runs the test suite.
testDist
testDistForLauncher - Validates locations in distForLauncher.
testDistZip - Validates locations in distZip.
unitTest - Runs unit tests (fast)
```

Merging #5261 will close this issue
