### ISSUE TITLE
Self Generating Structure (Castle)

### ISSUE THREAD

**Issue by SuperSnark** [MovingBlocks/Terasology#857]
We need a self generating structure that the player "creates" by placing a blueprint on a section of land and will slowly build itself over time until the blueprint is complete.

The speed at which the structure generates itself should be variable based on the number of player assigned resources.  For example, if a player assigns at least one pawn to the structure, it will initiate the building process.  The more pawns assigned, the faster the structure will generate.

The structure should be built of standard Terasology bricks and be destroyable by the opposing player and his minions.

If the structure is destroyed to some degree, it should be able to repair itself, based on blocks missing and the blueprint, assuming at least one pawn is actively assigned to the building.
##

**Comment by skaldarnar** [comment]
With [`Teraology/StructureTemplates`](https://github.com/Terasology/StructureTemplates) we now have a good mechanism for defining and spawning structures via blue-print. For a first implementation, the required blocks could be determined from the template and player's resources stored in a specific chest could function as building resources. 
Later, pawns could be assigned to buildings jobs with some behavior tree specification. 

Pinging @CptCrispyCrunchy as the building process by pawns/oreons might be of interest for the dynamic cities project. Potential reuse ahead.

**Comment by jdrueckert** [comment]
With [Terasology/StructureTemplates](https://github.com/Terasology/StructureTemplates) and the oreons in Master Of Oreon building buildings I'd say we technically got everything that this issue wanted, so I'm closing this as complete.
