### ISSUE TITLE
Modding/Plugin API

### ISSUE THREAD

**Issue by calclavia** [MovingBlocks/Terasology#862]
Just found this game and the graphics look amazing. It'll be great if a plugin API is provided for people to write plugins for this game similar how Minecraft mods. I would love to write potential mods for it and would definitely help make the modding API if the team is to it. :)
##

**Comment by orubel** [comment]
Well Groovy is actually a Java extension whereas Scala attempts to rewrite Java.

For example, you can take any Java class, change the extension to '.groovy' and it will compile. You can do the same with Scala because of the incompatibilities with Java.

**Comment by Cervator** [comment]
Ohai @orubel! Slightly dated issue here (2.5 years woo!), we probably could close it now. Our engine is in pretty good shape and exposes a bunch of stuff via API for our modules.

Additionally we've tested both Scala and Kotlin support for developing modules :-) Groovy would work too, for sure, just hasn't been done.

**Comment by skaldarnar** [comment]
Closing as we have a pretty solid modding API and Alpha 1.0 release which should help with staying compatible with mod interface for some time.
