### ISSUE TITLE
GelCube overhaul [$10]

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#884]
I've pulled the GelCube stuff out of portals, as they weren't actually working - they relied on some old rendering hacks unique just for them

Not sure how much is needed to get them working again. I moved all the code and assets to:

https://github.com/Terasology/GelCubes

There's still one portal back in Portals that'll spawn them if this module is enabled (which last I checked would crash stuff, wee!)

**Comment by Cervator** [comment]
Adding a bounty to this - not having our poor @GooeyHub mascot working in-game after this long is a tragedy! :-)

Shouldn't be particularly involved, being that Gooey is a *cube* - not the most complex creature model ever.

- [ ] Create a new model-based gelatinous cube (can review the deer in [WildAnimals](https://github.com/Terasology/GelCubes) for inspiration)
- [ ] Allow them to be dynamically colored somehow (which is really all the old version did, but hard coded to a set of colors) without hard coded color definitions or textures
- [ ] Support some level of translucency so you can see through the model (old approach at some point had an outer cube and an inner cube)
- [ ] "Animate" the cube by having it expand and contract during movement (is that even an animation? Dynamic resizing?)
- [ ] Hook up the existing squishy SFX (probably about the oldest sounds we have!)
- [ ] Add a behavior beyond the "stray" option the deer has, such as moving toward a player who is near the cube, squishing up against the player

Bonus: Create some sort of generic texture to give a faint idea of surface features. At minimal some gradients to mess with the translucency, at best a few with vague facial features of different "natures" - happy Gooey, angry Gooey, etc, as per our mascot graphics ;-)

Pinging @SuperSnark for lulz.

**Comment by skaldarnar** [comment]
Crossreference: http://forum.terasology.org/threads/gooeys-quests.1461

**Comment by Cervator** [comment]
@flo do you think we should consider this covered by Gooey's Quests? The more "primitive" gelatinous cubes may still have some value, especially if they could be imbued with extras like transparency or carrying a block internally (via #77) ?

Or if nothing else maybe hook the squishy noises up to GQ sometime for movement :-)

Let me know if you think this is worth keeping open, otherwise we can close it and you can claim the grand $10 prize, woo! Don't spend it all at once, or do by just rolling it on to some other issue, your pick :-)

**Comment by flo** [comment]
I think we should consider it covered. I suggest you put the 10 $ back into the pool and use it for something more important.

**Comment by Cervator** [comment]
Closing as completed via GooeysQuests :-)
