### ISSUE TITLE
Torches too bright in Sunlight

### ISSUE THREAD

**Issue by Wolfgange3311999** [MovingBlocks/Terasology#899]
(I hope this is the right place)
Torches are blinding when held in your hand in sunlight, especially with sand. There should be a maximum brightness for light.
Ex:
![torch](https://f.cloud.github.com/assets/5875019/2084459/361197f8-8e23-11e3-8c30-61a17ee8b17b.png)

**Comment by Cervator** [comment]
Closing as fixed by #2247! Still more tweaking to do in lighting (and shader?) land but light sources no longer go crazy :-)

**Comment by HybridDog** [comment]
Have you seen that yet?
http://freespace.virgin.net/hugo.elias/graphics/x_posure.htm

**Comment by Cervator** [comment]
Hi @HybridDog - personally no, since I'm not a 3d wizard, I just merge and test things :-)

It might be useful for one of the wizards like @pollend working on lighting though, thanks!
