### ISSUE TITLE
Highlight video: Throughout the Ages

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#932]
We need somebody to do a nice highlight video of @MarcinSc's WoodAndStone module series - it is getting pretty fancy and although the journal talks you through it we could use a video to demo it real quick :-)

@skaldarnar was circling this a while back but unsure if enough time! Any takers?
##

**Comment by smsunarto** [comment]
@Cervator this super old issue should be good to close i guess

**Comment by skaldarnar** [comment]
We need more highlight videos, but rather for the more recent stuff 😉
