### ISSUE TITLE
Agent-based simulation of land usage

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#944]
In order to define and place high-level structures in generated worlds, different usage areas must be identified. Different areas are preferable for one type of land usage or another.

Using the ContourTracer, different terrain features can be explicitly referenced (e.g. polygon shapes of lakes, forests, deserts, etc). 

Based on a set of environment-aware agents, the usage of these areas can be simulated.
As a result, farms would be settled in grassland areas while fishing lodges are placed at the shore.

On a different level, the location of entire settlements could be derived based on some simulation of optimality constraints.

**Comment by Cervator** [comment]
Closing as completed by GSOC 2016 and released as part of Alpha 4!

@CptCrispyCrunchy @msteiger and others if you can think of follow-up issues to submit here or in one of the relevant module repos please do! Especially if we can get some bite-sized easy issues going to help new contributors to get started :)
