### ISSUE TITLE
Charcoal Pit no longer displays smoke particles when burning

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#958]
Charcoal Pit was rendering smoke using particle system, but it stopped working. Maybe it was affected by OpenGL changes @begla has made?

We have confirmed that the particles are being generated correctly, and the renderParticle(Particle particle, float light) is called correctly.

**Comment by Cervator** [comment]
Closing as obsolete. The instructions above are outdated and I'm not sure the current charcoal oven even works. We also know smoke particles work elsewhere.
