### ISSUE TITLE
Console does not recognize first key press

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#964]
As the title says, I have to press the first key twice after opening the console.

**Comment by Cervator** [comment]
Bump - with #2082 merged the console key is now *both* the grave key and F1. So using the console via F1 avoids the dead key and as a bonus you can open and close the console with the same key :-)

The console issue was the only place (I think) where we encountered the dead key drawback and with any solutions sounding rather quirky I'm going to mark this as resolved - if anybody feels it still worth a fix eventually feel free to re-open!
