### ISSUE TITLE
Changing graphic settings in-game results in odd behavior like models or blocks going all black or white

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#966]
Starting the game on *Nice* or *Epic* will work fine, models are lit and you can see the textures.
![terasology-140216132849-1152x700](https://f.cloud.github.com/assets/1448874/2180221/51292c7c-9706-11e3-9058-f4c755480efd.png)
Changing to *Insane* or *Uber* will result in black models. 
![terasology-140216132909-1152x700](https://f.cloud.github.com/assets/1448874/2180222/54e238ea-9706-11e3-80b0-b5fba0a6df77.png)
Switching the seetings back does not solve the problem, models will stay black.

**Comment by emanuele3d** [comment]
Just checking, is this still an issue?

**Comment by Cervator** [comment]
Yep. I still get all-white dropped objects after having changed settings in-game.

**Comment by emanuele3d** [comment]
Please reassign it to me for the time being. One day I might be able to fix this.

**Comment by Translator5** [comment]
Terasology Alpha 64
Linux Mint 17-3
Java JDK 8
Installed using the launcher

![terasology-160320010345-1920x1080](https://cloud.githubusercontent.com/assets/9306861/13908572/8e86436c-ef05-11e5-9e95-6838b66be891.png)

**Comment by Cervator** [comment]
Closing as complete, huzzah!
